### ISSUE TITLE
Only model_0/1/2/3 gameobjects are visible on FPV

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1044]
I am curious if there is a reason behind only rendering 4 meshes on first person view? Maybe there is some workaround without editing/merging models?

**Comment by Alex-Well** [comment]
I also noticed this problem. Also in the first person view the item is displayed without any changes that occurred to him in the game. For example, if it is Night Vision Goggles and the player turns them on, then the activated GameObject is visible only from a third party. (I once made glasses with an energy protective field activated by pressing a key, but because of this flaw it was not visible from the first person.)

**Comment by SDGNelson** [comment]
For the next update I'll adjust that to remove the 4 mesh limit, as I don't see any reason to limit it. (that code is ancient) Ideally it would just modify the layer of all renderers, but I suspect there are some weird cases with the current items we wouldn't want to do that.

As for NVG effects not visible in first person, likely because only shirts are made visible in first person. Not much solace but 4.0 does draw all clothes in first person.
