### ISSUE TITLE
Nelson, please fix CollisionEventHook! 

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1045]
Please forgive me for re-writing about this error! I know that Nelson is very busy with other more important corrections and additions to the game, and other people show much more patience than me ...
The question of the fate of **CollisionEventHook** has been haunting me for several months. Initially, I received an unclear answer about his fate, and then I decided to spend time and recorded a video confirming my words, but a month has passed since then, but I still have not received an answer.
Once again, I apologize for being impatient and setting myself a high priority for this problem, but many don’t even realize how much the **CollisionEventHook** fix can improve the game. This is very important for me and I hope that Nelson will read it and see the video proof of my words.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/984#issuecomment-519687781

**Comment by SDGNelson** [comment]
Apologies for the haunting. I sympathize with how you're feeling - you're really pushing the game's modding support to its limits which is awesome, and I wish that 4.0's mod support was available since you'll be able to do so much more with it and the Blueprint systems.

Right now the CollisionEventHook events all work server-side and can be used by plugins, but are only triggered for the local player client-side as you mention. Ideally they would trigger for all players client-side, but doing so would require changes to player collision which I'm hesitant to make because they have far-reaching implications.

The robust solution is to replicate from the server when these events are happening, but there are a variety of netcode features which need work before that can happen e.g. network addresses for random components like this. I'm planning to do some netcode cleanup and revamps in the coming months which will help a variety of modding features like this and custom UIs.

**Comment by Alex-Well** [comment]
I will definitely wait for these changes!

**Comment by SDGNelson** [comment]
Referencing future netcode work: #1233
