### ISSUE TITLE
bayonet and butcher knife not working

### ISSUE THREAD

**Issue by aman7** [SmartlyDressedGames/Unturned-3.x-Community#1055]
you cannot equip butcher knife, and if you attach bayonet to your gun, bayonet doesnt work at all, and also cannot equip your gun next time.

**Comment by SDGNelson** [comment]
Thanks for the report! Patch for this is now in the process of compile / upload.
It was happening for items with invalid LOD groups due to the viewmodel changes, and unfortunately none of the affected items were ones I had tested with. (Happened to musket, knife, bayonet, etc.) Usually I test changes like this with the original core set of items IDs < 50.

**Comment by aman7** [comment]
just found dragonfang have the same issue.

**Comment by Johnanater** [comment]
Well, there was just another update. Oof

**Comment by Spebby** [comment]
This has now been fixed.

**Comment by SDGNelson** [comment]
To clarify: the patch fixed it for the items mentioned in my comment, as well as other affected items e.g. the dragonfang. (There was only one patch.)
