### ISSUE TITLE
Play is Always loading on Queue Position:#

### ISSUE THREAD

**Issue by HanaForward** [SmartlyDressedGames/Unturned-3.x-Community#1070]
I found that the communication between the server and the client is repeated.
Server : 00 01 04 00 00 00 12 65 b0 00 00 00 00 00 00 00 00 00
Client  : 00 01 04 00 00 00 16 64 01 00 b1 00 00 00 ff ff ff ff 00 00 00 11 2f 69 78 c2 a5 cc 81 43 6d e6 32 c1 00 00 5c 43 00 00 b4 42 
No error output

**Comment by SDGNelson** [comment]
Interesting, thank you for the record! I'll try matching up how the game is interpreting these soon and report back - probably next week.

**Comment by SDGNelson** [comment]
Kicking myself for forgetting to follow up on this immediately when it was posted...

Assuming that the posted sequences of bytes were the repeating portions, it's odd because neither of them make sense lining up with the game's packet headers. Especially if the player was in the queue. It makes me wonder if they might be headers Steam uses which would explain why they repeat. 

Do you remember any other details about this? Or was there any way to reproduce the stuck queue?

**Comment by SDGNelson** [comment]
I made a few potential small fixes, and also a fix for an endianness issue that might affect this.

**Comment by HanaForward** [comment]
thinks @SDGNelson

**Comment by HanaForward** [comment]
I think it may be related to the player network, because only some players will

**Comment by SDGNelson** [comment]
Fingers crossed! I'm hopeful we'll see some improvements in this coming update. I'll remove the "next update" label purely for tracking purposes, but the issue will be left open for following up after the update.

**Comment by SDGNelson** [comment]
It has been a long time, but from emails I believe this has been resolved earlier this year by the change from SteamNetworking to SteamNetworkingSockets. For whatever reason some players were dropped after authentication with SteamNetworking.
