### ISSUE TITLE
Bunch of new "hacks" that can get through battleye

### ISSUE THREAD

**Issue by FleshyPig** [SmartlyDressedGames/Unturned-3.x-Community#109]
i dont know what else to say it's getting difficult to play on public servers..

**Comment by yegac1337** [comment]
BattlEye only SIGS dll's and blocks injection methods into the game. Chances are Nelson himself wont be able to fix it. This would be up to BE upgrading their system or investing in FairFight.
`FairFight ® is a non-invasive, customizable, Server Side Anti Cheat engine using agnostic technology that operates in real time.`

**Comment by yegac1337** [comment]
FairFight can detect aimbots, No-Recoil, No-Spread and more.

**Comment by Trojaner25** [comment]
Time to get back observatory

**Comment by Trojaner25** [comment]
@yegac1337 you should be banned. You are selling hacks for other games.

**Comment by yegac1337** [comment]
I did not realise suggesting stuff to make a game better would get me banned. Its a step forward into stopping cheaters.

**Comment by Trojaner25** [comment]
stopping cheaters like you?

**Comment by yegac1337** [comment]
Ah yes, I understand. I suppose I can report shit without testing and seeing if it works. Makes sense. Anyways I love when stuff starts because I make a suggestion of FairFight.

**Comment by xdlewisdx** [comment]
"Testing" you are selling cheats, one of the developers and sellers of THANKING cheat, lol and you say you are only testing

**Comment by Trojaner25** [comment]
Its a shame that he got the white beret @SDGNelson

**Comment by xdlewisdx** [comment]
Indeed, seems to use it as power here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/26 xD

**Comment by N1GHTPATROL** [comment]
I agree, while the anti-cheat does an o.k. job against free hacks, many new hack clients such as Thanking and CryEye which have no problem getting past BattlEye. Seeing how /spy worked for a good 8 months or more before any developer decided to do something against it, maybe something new would do the trick, at least until 4.0 is released.

**Comment by yegac1337** [comment]
Thank you @N1GHTPATROL. I've suggested to NSTM to tell Nelson about it. Atleast now Nelson can read it here.

**Comment by Kr4ken-9** [comment]
I don't understand, BattlEye bans all chiters?

**Comment by snowball7275** [comment]
yes chiters are bad but batleye bans them

**Comment by NSTM9** [comment]
On the 24th of March, Update 3.18.4.0 came out. Written at the bottom of it, it read out: "Updated BattleEye". This update was due to a bypass in which we found, that involved Discord's overlay system, which could be edited such that the cheat .dll is masked under Discord's. We were able to find and confirm this information by testing.

Furthermore, there is currently _no solid evidence_ of yegac currently using/distributing/developing any cheats. The current standing ban in which he has is due to cheat-testing by idling in a server. In the method in which cheats are tested by us, they are:
1. Left idling in server.
2. Used on private server to test capabilities, such that we can structure ideas that could fix the problems without BE, so that fixes are permanent. 

Yegac brought up the idea of Fairfight from testing, and I already have suggested the addition of Fairfight directly to Nelson.

You can't just wait for a problem to arise to be fixed. It's better that cheats are taken, tested and fixed before they become worse.

Not everyone comes from the same history. You should judge based on the present, not by their past. What one might state about another is false, whether it be slander or confusion.

**Comment by xdlewisdx** [comment]
Sure he sells cheats, i can give you an invite to there Discord called THANKING (https://discord.gg/Q6thztS), they sell the cheat for 35$ Discord has already taken down 1 of there THANKING discord servers due to a report and ToS violation so there isn't much proof anymore, but here's what I've got so far, pretty obvious hes helping them with the cheat and advertising it in his linked accounts

https://i.imgur.com/8IKiHfw.png
https://i.imgur.com/l6SDPl1.png
https://i.imgur.com/CAfTdW9.png

**Comment by yegac1337** [comment]
Once again this is already known I'm in the discord, Where does it state I'm a developer or sell it. First photo is obviously a meme, If you were to look at my profile I made it to my own. Second is me just saying to watch his livestream as he was livestreaming himself coding it. And obviously the 3rd one was a meme I made based off of #103 Not to mention you did no research again into your information.
![image](https://user-images.githubusercontent.com/32919508/33540391-bcd6b17e-d87f-11e7-82d9-c40bede47cbd.png)
More invalid information. This is not the place to discuss it.

**Comment by yegac1337** [comment]
Please keep the invalid conversations and opinions off of here. The definition I would put for you two is
![image](https://user-images.githubusercontent.com/32919508/33540507-569feee2-d880-11e7-8c87-dc613dd8c4a8.png)

**Comment by snowball7275** [comment]
hi

**Comment by Trojaner25** [comment]
so again apparently someone thinks I'm xdlewsidx @yegac1337

**Comment by Trojaner25** [comment]
Why dont you show your white beret here to prove that you do not sell hacks? And to stop the conversation?

**Comment by MoltonMontro** [comment]
http://unturned.wikia.com/wiki/White_Hat

Assuming his inventory is also public, you could look there. http://steamcommunity.com/id/imls/inventory/#304930

**Comment by Trojaner25** [comment]
since when did @MoltonMontro became yegac

**Comment by SDGNelson** [comment]
If you find a new cheat that hasn't been detected yet you can forward it through the BattlEye website, or if sent to me I investigate as well and directly forward to them. Right now all the cheat developers for Unturned are little kids so it shouldn't be a problem blacklisting their stuff.

**Comment by AtiLion** [comment]
@SDGNelson You just roasted yourself with that comment. You are claiming that little kids are managing to bypass all your and battleye's security. Cheers xD

**Comment by zoomy500** [comment]
a little unprofessional, calling all cheat developers little kids?
sven has previously stated that he has forwarded the cheat to battleye, although nothing has resulted of it. I would gladly work with you to fix issues if you were more communicable.

**Comment by justboughtmarmalade** [comment]
@Torubloo = meme lol.
ik this is old but this guy never gets old
