### ISSUE TITLE
Bug: Replace & Unplace using different magazines too early

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1132]
A bug that makes a gun use a different magazine before it was even replaced. Applies to all guns with replace & unplace, noticeable in 3rd person.

**Comment by SDGNelson** [comment]
I think I misunderstood this report: my first impression was that there was a bug with the model activation and deactivation timing. Re-reading I think it means that the new item's model is immediately used, rather than being swapped out once the old item's model is removed?

For example: a 30 bullet magazine is on the gun. Then the player attaches a 100 bullet drum. The drum becomes immediately visible rather than changing models partway through.

Unfortunately this is a dumb limitation of some earlier decisions in 3.0, and is unlikely to be fixed. Thankfully 4.0 does properly animate this - in the current versions you can see the magazine swap when your character reaches down to grab the new one from their ammo pouch.
