### ISSUE TITLE
Suggestion: Option for guns to restrict attachments as opposed to access

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1136]
Title says all: an option for guns to restrict attachments as oppossed to access. Makes it so that you can restrict one or few attachments to a gun.

Demonstration on how it could work:

Attachment_Caliber_Restrictions 2
Attachment_Caliber_Restriction_0 296
Attachment_Caliber_Restriction_1 1007

**Comment by SDGNelson** [comment]
Would make sense to do as part of this: #1064

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
