### ISSUE TITLE
Does Shader graph work in unturned  ? "lightweight pipeline unity"

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#1177]
i didn't test yet but i need to know if we can use shader graph in unturned i hope yes
i'm remaking my project
![does](https://user-images.githubusercontent.com/40163506/67672135-90f65d00-f977-11e9-8512-b8ebf91dd756.JPG)

**Comment by Trojaner** [comment]
It depends if Nelson is using a scriptable render pipeline, which is likely not the case since it would break all workshop shaders

**Comment by SDGNelson** [comment]
My first thought was yes because I assumed they are translated into HLSL, but it looks like Trojaner is right that we would need to switch to using a SRP. I haven't looked into it yet, but it would be nice to use the SRP if we can do it without breaking existing assets - primarily in order to strip the featureset down to what Unturned actually uses.
