### ISSUE TITLE
Flanker and Burned zombies

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1178]
Hello, I noticed an error with zombies on the server. The fact is that the zombie burner and flanker hit the player at a greater distance than ordinary zombies.

**Comment by SDGNelson** [comment]
I'm sorry to say it might be placebo (though I don't think that's the correct word here), as all the zombie types share the same attack ranges. Mega zombies have an attack range of 2 meters, whereas non-mega zombies have 1 meter range. These values are halved on dedicated servers in order to hopefully make hits feel fairer with the delay.
