### ISSUE TITLE
Timed Conditions

### ISSUE THREAD

**Issue by Vulby** [SmartlyDressedGames/Unturned-3.x-Community#120]
> Timed Flag
>-
>How it would be used:
>
>1.
>`Condition_#_Type Flag_Timed_Short`
>`Condition_#_Time` //Time set in hours ingame hours
>`Condition_#_ID: Similar to normal IDs, flag ID on the player to check.`
>`Condition_#_Value: Target value for the flag, 16-bit integer meaning the range [-32768, 32767].`
>`Condition_#_Allow_Unset: Pass condition if the player doesn't have this flag yet.`
> 
> 2.
>`Condition_#_Type Flag_Timed_Bool`
>`Condition_#_Time` //Time set in hours ingame hours
>`Condition_#_ID: Similar to normal IDs, flag ID on the player to check.`
>`Condition_#_Value: Target value for the flag "True" or "False".`
>`Condition_#_Allow_Unset: Pass condition if the player doesn't have this flag yet.`

>  Timed quest
>-
>How it would be used:
>
>1.
>`Condition_#_Type Quest_Timed`
>`Condition_#_Time` //Time set in hours ingame hours
>`Condition_#_ID: Quest ID to check for.`
>`Condition_#_Status: "Active" has the quest, "Ready" can complete, "Completed" already finished`
>
>2.
>`Type: Quest`
>`ID: Number in this range [0, 65535].`
>`Conditions: Refer to conditions section. Available for turn-in when met.`
>`Rewards: Refer to rewards section. Granted when turned-in to NPC/a condition resets it.`

**Comment by SDGNelson** [comment]
Could you explain how this would be used? i.e. I'm not sure I understand the difference you intend between Quest_Timed, Flag_Timed_Bool and Flag_Timed_Short.

I can imagine the use of a condition checking the time of day e.g. one condition to check it's after 2 PM and another before 6 PM so that you can only do the action between those hours, but that doesn't seem to be what you mean.
