### ISSUE TITLE
Server loading auto downloaded workshop after plugins

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#122]
It would be helpful if the server were to download and load workshop content before plugins load. This causes various plugins such as uEssentials' kits to remove modded items because they do not exist when the plugin is loaded. This also breaks any workshop-dependent plugins which are on auto-download.

**Comment by Trojaner25** [comment]
This is actually not an Unturned issue as Unturned does not load the plugins, but RocketMod does. 

The plugins load before workshop and level on purpose. This issue needs to be fixed on the affected plugins as they can know when workshop has been downloaded. This can not be fixed by RocketMod as some plugins depend on being loaded that early.

**Comment by SDGNelson** [comment]
Looks like Trojaner cleared this up.
