### ISSUE TITLE
Shooting at close range

### ISSUE THREAD

**Issue by ANY892** [SmartlyDressedGames/Unturned-3.x-Community#1223]
So ive played this game for over 5 years now and never had this issue.
when you shoot at close range like 0 to about 7 or 8 meters in 3rd person the shots dont hit they just go threw whatever is there and it really annoying maybe its some kind of glitch/bug or am i the only one who has this issue?
Edit: mostly happens when shooting down on zombies doesnt happen in prone!

**Comment by SDGNelson** [comment]
Is the third-person crosshair over the enemy? In 3P the bullets shoot diagonally toward wherever the center of the screen hits in the world (otherwise it would not be possible to aim in 3P).

**Comment by SDGNelson** [comment]
Feel free to comment and I will re-open.

**Comment by ANY892** [comment]
i shot at a wall so there was no way the bullets could have missed i have about 3k hours in this game so i knew about diagonally shooting

**Comment by SDGNelson** [comment]
Here's a screenshot of the 3rd-person aiming at close range:

https://i.imgur.com/hBahvpl.png

My shots there were hitting the zombie, even though the character is facing a completely different direction. It's down to the 3P camera placement. In 4.0 I intend to have a tighter 3P camera in order to reduce this effect.

Is that how you're shooting, or if you shoot like that does it work how you'd expect?

**Comment by SDGNelson** [comment]
Again feel free to comment and I will re-open. Sorry if I'm misunderstanding your question. If you post an image it might help.

**Comment by ANY892** [comment]
it happens at longer ranges too idk why i am just gonna go and verify my files incase thats the problem

**Comment by SDGNelson** [comment]
Hopefully, but if it's still an issue if you post an image or a video if it happening that might help narrow it down!
