### ISSUE TITLE
[FEATURE REQUEST] blindfold

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#1243]
Adding the ability to blindfold someone via plugins, I checked the code some time ago and it was not possible unless the item was added to the inventory slot.

**Comment by baranmod** [comment]
Full screen black UI effect could be a workaround

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
