### ISSUE TITLE
[Feature Request] Dynamic Images in UI and Magazine Ammo Capacity Lift?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1246]
Hey Nelson, I have a few feature requests that I'd like to bring to your attention if possible.

I was wondering if by chance in the near future you'd be willing to invest some time into allowing dynamic images inside of UI's which enables the use of item images i.e. if someone wants to buy an item from a Shop UI the items modded or vanilla would automatically load on to it from a shop database, and the same goes towards killfeed and kit integration via UI.

Also, if possible could we have a lift on the magazine ammo restrictions set in place being at 255, perhaps have something available in workshop dat files to go past 255 for Futuristic & PVP Server Ennvironments on Unturned? 

Thanks for considering!

**Comment by SDGNelson** [comment]
In the slightly longer term by goal is to allow full server-side control of UIs like that: #1233 

The 255 limit is due to unsigned 8-bit integers for item quantities, and unfortunately that limit is prevalent through a huge amount of code, so it's unlikely to be changed. For what it's worth 4.0 raises the limit to an unsigned 16-bit integer.

Not exactly great news for you... 😞
