### ISSUE TITLE
Bug with in-game group limiting

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1248]
There is some bug with in-game groups. If group member count is limited, some players still know a way how to bypass it. Its somehow related to promoting team members to "admins" of a team. Didn't test myself yet, but will do and give more details if needed.

**Comment by SDGNelson** [comment]
I'll take a look at this for the next update and see if any exploits pop out.

**Comment by SDGNelson** [comment]
Promoting and demoting members only affects the rank, so I don't see how it could be abused to bypass the member limit. If you do test and find some details that would be much appreciated!

**Comment by baranmod** [comment]
Got an explanation from one player who did that:

1. Create the group (max team members i.e. set to 4)
2. Invite 4 people
3. Promote every member to admin
4. Delete the group
5. Then they can invite as many people as they like because it glitches at 2/4

Not sure if it exactly works as described but will have some free time later today - will test it

**Comment by SDGNelson** [comment]
Thanks for the explanation! Hmm deleting the group should kick everyone, I'll check that.

**Comment by SDGNelson** [comment]
Thanks for the report! This should be fixed in the next update. There were two oversights related to group deletion:

1. Deleting player could be removed before other players were removed preventing deletion from finishing.
2. Group still kept a valid ID so it could be rejoined.

Deletion has been moved into GroupManager.deleteGroup, and a couple related aspects were tidied up.
