### ISSUE TITLE
Server Memory Usage Issues - Assets and Serialized Files

### ISSUE THREAD

**Issue by InterstellarGamer** [SmartlyDressedGames/Unturned-3.x-Community#1252]
Server console is flooded with messages such as:

```
Unloading 1 Unused Serialized files (Serialized files now loaded: 2)

Unloading 2 unused Assets to reduce memory usage. Loaded Objects now: 2095.
Total: 5.366700 ms (FindLiveObjects: 0.389800 ms CreateObjectMapping: 0.068300 ms MarkObjects: 4.891600 ms  DeleteObjects: 0.016500 ms)
```

The server doesn't crash, and the log files don't report anything related to the issue. 
I've tried on two different machines with fresh installations, with and without Rocket, with the same messages spoiling the console.

Machine #1: PowerEdge R510
CPU: (2x) Intel Xeon X5670 (2.93GHz)
RAM: 16 GB
OS: Windows Server 2019 (x64)

Machine #2: Gaming Rig
CPU: i5-4440 (3.1GHz)
GPU: AMD Radeon R9 200 / HD 7900
RAM: 16 GB
OS: Windows 10 Pro (x64)

_Also just a side note, the server automatically loads france.masterbundle even if the server is set on a different map. I'm guessing this might be intentional but just wanted to let it be known._

**Comment by SDGNelson** [comment]
That should only be happening during startup: it's related to Resources.UnloadUnusedAssets which is called to (ideally) reduce RAM usage when dealing with many individual asset bundles. It should not be happening while the server is actually running - is it?

Re France: you're right that it's "intentional"-ish because the server doesn't know whether the map uses assets from France, but that map will be moved to the Workshop soon so it won't need to be loaded by default anymore.

**Comment by InterstellarGamer** [comment]
Yes, the message only occurs on startup. I'd suggest that it were to only appear in the log (or not at all). Anyways, thanks for the clarification on that.

**Comment by SDGNelson** [comment]
Ideally yes they would just be in the log, but Unity writes them to stdout.
