### ISSUE TITLE
Ability for Barrel durability to be a non-integer

### ISSUE THREAD

**Issue by NSTM9** [SmartlyDressedGames/Unturned-3.x-Community#1304]
If a barrel's durability is set to a non-integer (i.e. 1.33, 0.66, 0.5), the barrel no longer has durability, and will not break.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
