### ISSUE TITLE
More suggested modding additions

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1305]
Some more modding additions:
- Allow other attachments to change gunfire sound when loaded. If a suppressor is attached, it is prioritized instead.
- Allow different attachment placement configuration on a different gun. e.g, a certain gun can have holos placed backmost but scopes are placed forward but vice versa for another gun. (Works especially when we have access to all vanilla attachments. Not sure if it should be .dat or Unity-related)
- A variation of the Makeshift Muzzle's damage .dat config for all attachments that resembles what guns and melee use. e.g:

> Player_Damage 36
> Player_Leg_Multiplier 0.6
> Player_Arm_Multiplier 0.6
> Player_Spine_Multiplier 0.8
> Player_Skull_Multiplier 1.1

- 2 reload variations & sounds that play depending if ammo is empty or not (I might have said this before)
- Player stamina damage for weapons & consumables
- Player oxygen damage for weapons & consumables

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
