### ISSUE TITLE
Option for trains to continue moving to the nearest node after a player exits.

### ISSUE THREAD

**Issue by Islam988** [SmartlyDressedGames/Unturned-3.x-Community#1308]

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
