### ISSUE TITLE
[FEATURE REQUEST] Reset_On_Quit [True/False] Config Option

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1331]
Would reset a player's location, skills, experience, reputation & items upon logging out of a server. Useful for Deathmatch maps.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
