### ISSUE TITLE
[FEATURE REQUEST] More Durability & Jamming options

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1332]
Durability_Effect_Damage [True/False] - Would either allow or disallow duribility to effect damage, true by default.
Can_Jam_Without_Durability [True/False] - Would cause weapons to jam regardless of durability.
Override_Difficulty_Durability [True/False] - Would cause the weapon to ignore the server's difficulty and still cause a weapon to degrade.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
