### ISSUE TITLE
Airdrop Bug

### ISSUE THREAD

**Issue by Rupm1r** [SmartlyDressedGames/Unturned-3.x-Community#1341]
Please fix this terrible bug, watch a video.

https://www.youtube.com/watch?v=M6gmdPFYlMU

https://www.youtube.com/watch?v=MjgpzuDJqs4

https://www.youtube.com/watch?v=M3GwtR-0fNQ

**Comment by SDGNelson** [comment]
Thanks for the report! It should not be too exploitable because the server will discard shots from inside the box. One straightforward option would be to kill anyone inside the airdrop once it lands (squished), but that makes it less moddable for the future. I'll probably do that for the meantime though.
