### ISSUE TITLE
Editor won't load.

### ISSUE THREAD

**Issue by INeedHelp225** [SmartlyDressedGames/Unturned-3.x-Community#1348]
Earlier today I worked on my editor map of 3 months.
Just in case it is related, on Christmas day I had added Washington materials and details for the map.
Today I used the devkit to make paint foreign materials with the selection tool and foliage window, along with the type browser. I used it to paint the scorched grass and stone assets for a deadzone.
I decided to also use some river gravel assets to put rocks on the sides of the river, and used some to put in a quarry area of the map to replicate the cool mine look in the Germany limestone quarry location. 
Proud with my work I saved the devkit, and exited to the main screen to work on the map in the main editor again. I joined the editor and waited, and it did not load. I left it to load for an hour or so, and came back to find it not loading, rather being stuck with the bar permanently pointing right fully.
I then began to spend an hour researching for solutions to the problem, using the deletion of the flag files trick. I copied the map and used the trick, but alas it did not work. I tried deleting all nodes, putting new flags in, everything that could in theory make sense. 
I cherish this map and have spent too many hours making it for it to be corrupted due to my callousness in the devkit. 
Is there any other solution, like a fix, or is my map toast?

**Comment by SDGNelson** [comment]
Could you email the Client.log or map files to me please? I'll take a look and get it sorted out - it should be possible to recover. I also always recommend keeping backups or version control just in case!

**Comment by INeedHelp225** [comment]
Is it possible to google drive it to you? Pasting/moving the map file will not work here or in the regular email.

**Comment by INeedHelp225** [comment]
I've sent you the google drive of the map

**Comment by SDGNelson** [comment]
Thanks for the file. It looks like there are two problems:

1. Multiple landscapes in the level (as opposed to multiple tiles)
2. Multiple foliage systems in the level (as opposed to multiple tiles)

I'll get those fixed up for the next update so that they don't get stuck. For my future reference the problems are at:

`Landscape.cs:778`
`FoliageSystem.cs:570`

Unfortunately there isn't a great workaround in the meantime. I took a look in the `Level.hierarchy` file and it appears to be water, hole volumes, landscape and foliage. One option would be to delete that file which would revert to the pre-devkit adjustments, but that post-devkit work would be lost. There are more than 16 hole volumes in the level however which is not supported (on GPU those are a fixed size array). You could also keep a copy of the current `Level.hierarchy` to compare how much would be lost if deleted.

**Comment by INeedHelp225** [comment]
Thank you so much! I'll be editing those files as soon as possible! Thanks again, have a great day!
