### ISSUE TITLE
Add Skill rewards

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1360]
### It would make it possible to make quests or interactive object which will increase our skills without us being able to do it ourselves.

**Comment by SDGNelson** [comment]
Interesting idea. It makes sense to add.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
