### ISSUE TITLE
Map bug with unknown cause

### ISSUE THREAD

**Issue by Skogen787** [SmartlyDressedGames/Unturned-3.x-Community#1362]
Ok, so i made a map, i uploaded it, then i updated it, after i updated it, everything is okay in singleplayer, but on a server, anything i have added/moved doesnt appear for anyone else than me, and the things that are there for me are extremly buggy, like i can walk through certain walls and phase through floors and roads, i dont know if this is a problem with some of the files in my map folder, it shouldent, something to do with the game, the server or if it somehow hasn't been updated properly, help solving this issue would be greatly appreciated

**Comment by PandahutMiku** [comment]
Having the workshop map installed and the actual map installed under Root Unturned/Maps can cause issues like this from my experience. Double-check to make sure it's not installed in both locations. I usually rename the map under Unturned/Maps to something else to prevent conflicts.

**Comment by joeymisfit** [comment]
Could also be due to the fact that he may have added modded items into the game. Since he said people are phasing through buildings, if that's the case whatever workshops that were used would have to be added to the server so that client-side can grab the workshops as they load in.

**Comment by PandahutMiku** [comment]
> Could also be due to the fact that he may have added modded items into the game. Since he said people are phasing through buildings, if that's the case whatever workshops that were used would have to be added to the server so that client-side can grab the workshops as they load in.

My bad, can't read apparently. Important to make sure you're not using curated map content with or content from mods you have installed without adding them to the server as well. The server is enforcing movement in his case though, as he says he can walk through, phase through things and it's 'extremely buggy'. I'd bet he updated the map on his side without actually pushing to workshop or just has duplicate as mentioned above, and since the server has a different version of the map, it's enforcing movement based on it's copy.

**Comment by SDGNelson** [comment]
PandahutMiku is right that it would be due to having two conflicting versions of the same map installed - the local version may have been the one updated with new objects that other players don't see yet.
