### ISSUE TITLE
(Request) Different firerates for different firemodes.

### ISSUE THREAD

**Issue by NSTM9** [SmartlyDressedGames/Unturned-3.x-Community#1372]
For example, a gun that fires faster on Bursts, but slower in full auto. This could provide more robustness to weaponry that might have both actions, as currently using automatic would be the most preferred firemode if both auto and burst are provided at the same rate. (ex. Empire)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
