### ISSUE TITLE
(Request) Gold character specific skins

### ISSUE THREAD

**Issue by NSTM9** [SmartlyDressedGames/Unturned-3.x-Community#1373]
Options to apply skins to a single gold character, or all characters at once. Allows for each character to have more customization, i.e. perhaps having a character that equips fancier skins for PVE, while another character equips camouflage skins for PVP, etc.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
