### ISSUE TITLE
(Request) Damage volumes for DevKit

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1374]
Volumes which can be used to set N damage per N second. Also could be enable features like oxygen, fire, acid etc. damage.

**Comment by Spebby** [comment]
#1220

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
