### ISSUE TITLE
(Request) Separate inventory cosmetic disabling

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1379]
Sometimes good to disable only top or hat, not all cosmetic. Nice idea to make something like pannel which opens when you press "Disable Cosmetic" in menu. Hold Shift to disable all cosmetics.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
