### ISSUE TITLE
(Request) Disabling other UI in map config

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1380]
Ability to disable UI when watching on player (nickname, etc.); stats icons UI (bleeding, radiation, etc,); notifications UI (enter/farewell when entering safezone/deadzone, gasmask stats); vehicle UI; 

All this can be done in map config and set by true/false

**Comment by Paradox304** [comment]
I'm pretty sure the UI when you watch a player can be disabled already.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
