### ISSUE TITLE
Volume Hole messed up after update

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1385]
Basically can't go through volume holes anymore after recent update

**Comment by SDGNelson** [comment]
Thanks for the report! I'll fix this in a patch this evening. (rather than immediately in case other bugs are reported)

This update changed movement to do an overlap sweep to double-check whether Unity's built-in character movement went through a wall with overlap resolution disabled. The benefit of this is it fixes many exploits related to pushing yourself through walls with vehicles. Unfortunately the sweep isn't ignoring the ground while inside a hole volume at the moment, so I'll update it to correct that.
