### ISSUE TITLE
Movement issues at max height

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#1386]
In relation to #1385 
At max height, if you are clipping through the skybox/top of the map, you cannot move. I'm not sure how you want to go about addressing this, but this wasn't an issue before.

https://www.youtube.com/watch?v=9F6Tk20g4JU&feature=youtu.be

**Comment by SDGNelson** [comment]
Hmmm this is a less straightforward case. You're right that it's because of the movement changes. It's not ideal to ignore the border collision because it's used in other places like fences and special buildings. 

I assume that it works normally if a little bit further below the max height? In that case this might be a "won't fix", as there's not much reason to be 1km above the map.

**Comment by PandahutMiku** [comment]
> Hmmm this is a less straightforward case. You're right that it's because of the movement changes. It's not ideal to ignore the border collision because it's used in other places like fences and special buildings.
> 
> I assume that it works normally if a little bit further below the max height? In that case this might be a "won't fix", as there's not much reason to be 1km above the map.

Yea It's perfectly fine if you're not headbutting the max height. Just brought it up because before you could stand up with no issue and a player complained, probably shouldn't be building so high, to begin with.

**Comment by SDGNelson** [comment]
Thanks for the confirmation. I'll also double-check with some of the other "clip" volumes to ensure there's no stuck cases.
