### ISSUE TITLE
(Request) Hide weapons with .dat option.

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1390]
Options in the .dat file of a vest or clothing to be able to hide the weapons in the 1/2/ALL slots. This would prevent glitches with weapons and vests.
Example:
Hideslot 1
Hideslot 2
Hideslot All

**Comment by JackReagan** [comment]
Please Nelson add this !

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
