### ISSUE TITLE
Console input not working

### ISSUE THREAD

**Issue by Raxul257** [SmartlyDressedGames/Unturned-3.x-Community#1400]
I created vanilla server by following [docs tutorial](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md), but I can't execute any command from console. Everything else works.

The same happened when I were using manually compiled rocket, but it didn't when I used its latest release from Github and that's because it was uploaded in November, but files inside zip were modified in June, before rocket's input handling was removed.

OS: Ubuntu 18.04

**Comment by Raxul257** [comment]
My custom handler fixed it, but vanilla handler still doesn't seem to work

**Comment by SDGNelson** [comment]
Good timing Raxul257! It sounds like you've done quite a bit of technical digging, and I'm impressed you made your own IO handler for it. Attached is the final re-build of RocketMod that will be included going forward: [Rocket.Unturned.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4131364/Rocket.Unturned.zip)

Due to Rocket's built-in console code conflicting with Unturned's the default is disabled, but can be enabled with the "-ThreadedConsole" command-line option. It sounds like yours might have made some improvements however, in which case I'm happy to listen if you'd like to share.

The game's built-in implementation is in the ThreadedConsoleInputOutput class which waits for `Console.KeyAvailable` before calling the blocking `Console.ReadLine` on another thread. It uses ConcurrentQueue to pass inputs and outputs from the game thread.

**Comment by Raxul257** [comment]
"-ThreadedConsole" argument solves this issue. It would be nice if you include information about it in [docs tutorial](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md).

You can see my IO handler [here](https://github.com/Raxul257/UnturnedConsoleModule/blob/master/src/CommandInputOutput.cs). It's based on ThreadedConsoleInputOutput.

**Comment by SDGNelson** [comment]
Ah, okay. With the proper final build of RocketMod in the next update it should become safe to make "-ThreadedConsole" the default again. I probably won't do it this Friday because it will take hosts some time to transition, but perhaps next Friday.
