### ISSUE TITLE
Servers with fake player count

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#1406]
I see an increasing amount of servers with fake player counts in the server list.

I suggest that such servers should be blocked from joining after comparing it to the real player count in the server details window (e.g. if the difference is > 5 then dont allow join). But afaik people also fake the server details count by not ending the players steamworks session. Don't know how to detect that one...

**Comment by SDGNelson** [comment]
Agreed that it's annoying. Steam automatically determines the advertised player count from the player sessions, so you're right that hosts are not ending them when they should be. It might require something manual like outright banning them with the `MasterServerBlacklist.txt` regex

**Comment by Ankumo** [comment]
Why is that even should be annoying? Why do you even need to restrict servers to show up if it has over 24 players limit? I don't get it, and i think the rest of the community will not understand that too. It's like you're just making decisions on your own when it must be a player's choice. You think a new player will read all the patchnotes to see that he can edit some whatever file to be able to see all the servers which he can play? Really? We are doing this, because of this useless feature that should be given to players like a simple warning, even if there'd be some perfomance hits to a client and we're just letting them know that there's some cool servers around (especially RP) which needs a much more players to have fun.

Sorry i had to answer with some sharp retort maybe, but i really don't get it
