### ISSUE TITLE
Map issue with upgrading foliage in DevKit

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1428]
Devkit has Foliage Upgrade Wizard to make good and quality materials and details from Devkit on old maps, made in legacy editor. After selecting materials in tiles map don't save and then don't load. I used this guide because didn't find anything better:
 https://www.youtube.com/watch?v=gs59TsEZue4&feature=youtu.be

**Comment by SDGNelson** [comment]
For the most part that video seems accurate. During the upgrade process the materials can be assigned in the Ground Upgrade Wizard to automatically paint them.

Are your tiles being created, or is it doing nothing?

**Comment by NoThreat** [comment]
> For the most part that video seems accurate. During the upgrade process the materials can be assigned in the Ground Upgrade Wizard to automatically paint them.
> 
> Are your tiles being created, or is it doing nothing?

Tiles were created. But I don't know how to assign materials in Upgrade Wizard itself. No instructions for this. 

Also this issue has my friend. On every created map.

**Comment by NoThreat** [comment]
>During the upgrade process the materials can be assigned in the Ground Upgrade Wizard to automatically paint them.

Ok I did it. Same thing. I really believe something is wrong with game in this aspect. Please check it.

**Comment by SDGNelson** [comment]
I'll give it a try on one of the older maps

**Comment by SDGNelson** [comment]
To try it I used the tool to convert the Tutorial map's older terrain. It converted and saved/loaded without incident.

Since you mention foliage I wonder if you are also placing a foliage system into the level? The upgrade tool does not convert the "details" to foliage, and there is actually a bug fixed in the next version related to newly placed foliage. If you only upgrade the landscape it should work.
