### ISSUE TITLE
Please Remove/Limit SetBotPlayerCount

### ISSUE THREAD

**Issue by Torubloo** [SmartlyDressedGames/Unturned-3.x-Community#143]
This is something that can be used for good things, but more often then not it is abused I am done getting messages asking how to do this and seeing these servers faking their player count to try bait people to join and get more players, please remove this or limit it somehow

complete cancer

**Comment by aviadmini** [comment]
I agree it's cancer, but you can't simply remove it since it's in Steamworks library. Unless you're willing to modify it 

Setting bot player count has some awful side effects (e.g. not showing up in Rocket/Vanilla server lists, only Any).

I'm not sure how to limit it also. One way I think might wris to remove server from master list when bot player count is >1

**Comment by Trojaner25** [comment]
Servers which have BotPlayerCount > 1 already do not show up if "Plugins" is not set to "ANY" on the server list.

**Comment by SDGNelson** [comment]
The next update will hide responses with >1 bot players so we'll see how well that works, though it might interfere with player count filtering on the masterserver when initially making the request.
