### ISSUE TITLE
[FEATURE REQUEST] Clothing Skill/Stat Boost

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1436]
Clothing could specify a skill or stat to be boosted when wearing. Would allow for a "higher skill level" than normally available with Max Skills. Amount of additional levels should be specifiable, would default to 1.

Ex.

Skill_Boost Diving 2
Skill_Boost Warmblooded
Movement_Speed_Multiplier 1.2

**Comment by erik7302** [comment]
I would also like also a method to increase the ability over the limit (for plugins), in a way that doesn't affect the /maxskills command (plugin)

**Comment by Spebby** [comment]
Partly added in 3.21.31.0

**Comment by Spebby** [comment]
idk why i closed this it, movement speed was the only modifier added.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
