### ISSUE TITLE
(Request) Disable "Esc" dialogue closing 

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1443]
Sometimes it will be good to probit player use Esc button to exit from NPC dialogues. Similar feature has "Custom NPC" mod from Minecraft, and it's very useful there. Why not to add something like this in Unturned?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
