### ISSUE TITLE
Barricade problems on the server

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#1448]
Please watch the video to make sure. When a player picks up a barricade, he gets a completely different one. This only happens in this region of the map. Last wipe was ~two months ago.
The console does not work on my hosting properly, so I use rocket logs, but there are no errors.

https://www.youtube.com/watch?v=OFJAS8IxH_I

**Comment by SDGNelson** [comment]
This is almost definitely related to this issue: #1249 

Based on the logs shared and the checks I put in place I think the remaining cause(s) are _probably_ due to plugins making unsafe calls from other threads. In the past update I put game thread exceptions in a few places and already plugins have been hitting them and being fixed, so it bears seeing if there is a good place to put a similar check for barricades.
