### ISSUE TITLE
[FEATURE REQUEST] Vehicle "Turbo"

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1452]
Option for Fuel & Electricity
Functions similarly to the "speed boost" on the Bicycle. Would add a button to the vehicle panel in the inventory that says "Boost". Would automatically be assigned to the player's sprint button.

Maps like Easter Island and some unreleased maps have some pretty janky solutions to get a similar effect.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
