### ISSUE TITLE
In-game Groups

### ISSUE THREAD

**Issue by Keyword65d** [SmartlyDressedGames/Unturned-3.x-Community#1456]
Hi, I am in the progress of making a plugin but after making an in-game group that a player joins they get automatically kicked if they rejoin the server.
This, of course, does not happen when a group is made by a player but then done with the plugin it kicks them for some reason.
I would like to know if there is a setting that I am missing or something I need to set to true or false.

**Comment by SDGNelson** [comment]
My guess is that you are setting their Steam group ID? Probably what is happening is the check with the Steam backend to ensure they are members of the Steam group is failing because the group doesn't exist.

It looks like there isn't a nice way to assign them to a group server-side at the moment aside from messing with the PlayerQuests RPCs to create a fake invite and accept it. I will add helper functions for creating groups and force-assigning players to groups though.

**Comment by Keyword65d** [comment]
I use GroupManager.getOrAddGroup for creating the group and to assign it.

Player.Player.quests.channel.send("tellSetGroup", ESteamCall.ALL, ESteamPacket.UPDATE_RELIABLE_BUFFER, new object[]
            {
                groupInfo.groupID,
                0
            });
            GroupManager.sendGroupInfo(groupInfo);
