### ISSUE TITLE
More gamemode win conditions.

### ISSUE THREAD

**Issue by Islam988** [SmartlyDressedGames/Unturned-3.x-Community#1467]
Certain conditions to trigger an arena reset would be nice, especially since custom gamemodes only really apply to the name. Players_Killed, Experience_Level, Reputation, Time_Survived, and NPC_Interacted are just a few examples that would allow mappers to create new and interesting gamemodes.

**Comment by SDGNelson** [comment]
It would be nice to support more gamemode customization. The custom label was added because of maps like Dango which otherwise showed up as survival mode.

Your proposal is that the NPC conditions could be evaluated per-player for the game mode, and when a player fulfills the conditions it triggers the end of arena "player X won"? It's an interesting idea. I guess the built-in arena functionality would need to be turned off as well?

**Comment by Islam988** [comment]
Yeah exactly, I hope its something that could work because it would open up a lot more possibilities than what we have now.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
