### ISSUE TITLE
base64 network transmission image support

### ISSUE THREAD

**Issue by Nacho-Neko** [SmartlyDressedGames/Unturned-3.x-Community#1474]
Approximate method：
sendUIEffect();
sendUIEffectImagebase64();
add cache picture use md5 for sendUIEffectImageURL
url - byte[]  use sqlite   Delete regularly
If allowed I can create relevant code

**Comment by SDGNelson** [comment]
What sort of image is it? i.e. Why does it need to be sent dynamically through the game rather than the existing methods?

**Comment by HanaForward** [comment]
Using urls will have higher latency.
If base64 is allowed, it is possible to implement self-drawn pictures and display them to players。

**Comment by GazziFX** [comment]
Why base64? You can send byte arrays (Faster and less size). Spy image encodes with JPEG and sends in bytes

**Comment by GazziFX** [comment]
Image data should be sended in several packets because netcode have only 65535 bytes buffer or you can create new byte array for each send/recieve

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
