### ISSUE TITLE
Add Player.look.isSpectating

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#1487]
Please add 'PlayerLook.isSpectating' this return a bool to check is the player have the "F7" Enabled

**Comment by erik7302** [comment]
also a event when the player toggles it.

**Comment by rube200** [comment]
That would be great, I’ve been looking for something like that but I’m pretty sure it’s not yet possible

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
