### ISSUE TITLE
(Feature Request) Add more damage types and hallucination effects for magazine asset.

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1493]
Weapon asset has tags, which would be useful for magazine asset or at least add an override function to these tags for magazines.
Im making a sort of dartgun with different darts, and I want to make it so that some darts deal Virus damage and give you hallucinations, while others either heal you or give you the energy.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
