### ISSUE TITLE
Domain IP

### ISSUE THREAD

**Issue by andrewbroken** [SmartlyDressedGames/Unturned-3.x-Community#1502]
Make it possible to create domain IPs (as in minecraft), so that when changing hosting, the IP does not disappear

**Comment by erik7302** [comment]
if this get added i wont be free(i think) also u hav free services like No-Ip to hav a static ip where u can select a free domain or pay for a custom one.

**Comment by Trojaner** [comment]
I think this isn't possible as steamworks saves IPs not domains

**Comment by SDGNelson** [comment]
The game does DNS lookups, so if you own a domain you can create an 'A' record pointing at your server regardless of hosting provider.

**Comment by Trojaner** [comment]
@SDGNelson I think he means saving servers with domain, not IP

**Comment by SDGNelson** [comment]
Ah I see. Thanks for the clarification @Trojaner. It is an interesting suggestion. Trojaner's comment about Steam saving IPv4 addresses is correct. If reworking this menu I would save the domain name in a game format rather than only using the Steam system. On the bright side I will keep this in mind to-do in 4.0!

**Comment by SDGNelson** [comment]
This *might* work in the next update because support for [GSLTs](https://github.com/SmartlyDressedGames/U3-Docs/blob/master/GameServerLoginTokens.md) has been added, and apparently one benefit of them is it *might* favorite the server ID rather than the IP.
