### ISSUE TITLE
[FEATURE REQUEST] Crafting Blacklist Config Option

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1508]
Would prevent certain items from being crafted on a map.
Would be useful for maps that want to rebalance certain overpowered items (such as dressings), but don't want to replace cloth/metal in its entirety. 

Ex. 
```
"Item_Blacklist"
{
95,
394,
476,
1104,
1105,
}
```

**Comment by DerpyHoowes** [comment]
I would rather make it so that you can blacklist certain blueprients of items, instead of items themselves and make it as a server ability, not just map.

Ex:

"Blueprint_Blacklist"
Item_ID: 76
Blueprint_Index 0

So Blueprint_0 of Blowtorch is now blacklisted on the server/map, but Blueprint_1 is still available.

**Comment by educatalan02** [comment]
This can be made with plugins.

**Comment by Spebby** [comment]
I suggested this primarily for use on Curated/Featured maps, not a specific map that would be run on only 1 server. Plugins aren't a viable option here.

**Comment by Spebby** [comment]
Nelson added an issue addressing this exact thing 19 days ago, I didn't notice it, and I'm assuming he didn't notice this request.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1549
