### ISSUE TITLE
Make PlayerUI_* inside map Config.json override-able via Plugin

### ISSUE THREAD

**Issue by Tortellio** [SmartlyDressedGames/Unturned-3.x-Community#1512]

**Comment by DiFFoZ** [comment]
#1242

**Comment by NathanDontGotDis** [comment]
I know this was supposed to be or was planned to be added from that other post DiFFoZ referenced in January. I'm hoping that it could be worked on or released eventually. Really cool feature looking forward to it.

**Comment by SDGNelson** [comment]
Eventually definitely. Lots of requests on this to-do tracker though so it can be hard to prioritize them 😞

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
