### ISSUE TITLE
Variable for NPCs

### ISSUE THREAD

**Issue by julien040** [SmartlyDressedGames/Unturned-3.x-Community#1515]
When we write NPC, we could add Variable like {{price_jacket}} (or something like that).
And on the server's config.json, add a special category like 
````json
"NPC_Variable" : {
"price_jacket": 5,
"price_apple":10
}
````
I don't know if it's possible.
Have a good day!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
