### ISSUE TITLE
Placing claim flags (and other barricades/structures) inside of other objects

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1520]
Currently, the client does calculations to see if it's able to place something, and so you cannot place down a claim flag and then a wall, but if you place down both at the same time those checks are bypassed, and the server itself doesn't seem to check, so you can place down claim flags inside of walls and objects.
![3236d26a69a4](https://user-images.githubusercontent.com/17209937/76822892-cd244000-67e8-11ea-8ef7-c10c87cdd3e1.gif)
It looks like you could fix this by making the server do the same check as the clients for space, or possibly by making the client do the space check at the end of the placement animation as well if the server check would be hard to implement.

**Comment by SDGNelson** [comment]
Interesting point. The server does a check for objects of the same type being placed together at the same time, but this needs a physics check. IIRC the client does also check at the end of the animation, but may not have been notified of the claim flag yet. Not sure how to deal with this but will think about it...

**Comment by PandahutMiku** [comment]
> Interesting point. The server does a check for objects of the same type being placed together at the same time, but this needs a physics check. IIRC the client does also check at the end of the animation, but may not have been notified of the claim flag yet. Not sure how we will deal with this yet but will think about it...

I could be entirely wrong, but I don't think the client checks twice, checkSpace() in usuablebarricade is only called by check() which is only called in tick() for highlightertool and startPrimary(). 

If you want just the client to do the work, you could add onto the BuildingRequestManager to have it wait for a few ticks and ask the clients to re-verify space via an RPC if they're placing too close. You could do that just for "high risk" barricades such as claim flags or sentries. A less iffy solution could be to have the client have its own upgraded BuildingRequestManager to know the locations of other placements and have checkSpace simulate the placements, both at the end and start of the animation.

**Comment by PandahutMiku** [comment]
Just a minor update, per #1527, it would be nice if you expanded the collision for them a bit in order to prevent placing inside of objects. You don't even need two people or anything fancy for this, you can just straight up place claim flags inside of some barricades. Hopefully, that is at least easier to fix than two people placing, and from what I've seen, it is the main source for abuse as you can efficiently lay down a ton of claim flags and easily put down pillars on top of them. 
![Unturned_GQ3nrGyV21](https://user-images.githubusercontent.com/17209937/80269790-d2df3200-8680-11ea-9509-821aa3351058.png)


![Unturned_kkiefRa0GG](https://user-images.githubusercontent.com/17209937/80269738-4fbddc00-8680-11ea-9af7-27159543d091.png)
![Unturned_dyL0nywYh9](https://user-images.githubusercontent.com/17209937/80269739-52b8cc80-8680-11ea-917f-a3d8311e3551.png)

**Comment by SDGNelson** [comment]
This was not addressed yet, but also adding that players have reported putting ceilings inside floors for reinforcement. https://www.youtube.com/watch?v=PvA21PJf8KY

**Comment by SDGNelson** [comment]
This should finally be fixed in tomorrow's update! 🥳
