### ISSUE TITLE
Other damage types for magazines and throwables to work as explosion damage

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1524]
There are virus, bone breaking, hallucination etc damage types for guns right now. It would be awesome if these types could work for magazines and throwables as an explosion damage (i.e. grenade break bones for all players in its explosion range). Also, maybe for attachments?

On top of that, maybe Projectile_Damage_Multiplier; Projectile_Blast_Radius_Multiplier; Projectile_Launch_Force_Multiplier could work for attachments too?

**Comment by iBowie** [comment]
#1493

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
