### ISSUE TITLE
Linux server console not working

### ISSUE THREAD

**Issue by TLingC** [SmartlyDressedGames/Unturned-3.x-Community#1530]
Linux server console not working, set up according to [https://wiki.smartlydressedgames.com/wiki/Linux_dedicated_server](https://wiki.smartlydressedgames.com/wiki/Linux_dedicated_server), with RocketMod installed from the `Extras` folder.

**Comment by SDGNelson** [comment]
Despite being on the official wiki I'm not sure how correct that documentation is. I'll have to check with Molt about that one. As a starting point the official docs are here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/ServerHosting.md

I have checked relatively recently and running the `./ServerHelper.sh` script with the `-ThreadedConsole` argument on Ubuntu was working for me. Now that the patched RocketMod is included in the game the ThreadedConsole argument should become the default soon.

**Comment by TLingC** [comment]
Thank you, I just tested and it just works perfectly.
By the way, is `secureserver` been replaced by `InternetServer` and `LanServer`?

**Comment by SDGNelson** [comment]
Glad to hear that!

`InternetServer` is an alias for `SecureServer` and will be the the recommended launch option, but `SecureServer` will stick around because it has a long history.

Under the hood there are three ways to initialize the Steam Server API: Secure (VAC enabled), Insecure (VAC disabled), and LAN. Originally the command-line arguments directly mapped to these flags.

**Comment by MoltonMontro** [comment]
Hey, @TLingC! As stated at the top of the page, that documentation has largely been community-updated. Unfortunately, it's most likely been inaccurate every since the dedicated server app was released, and RMod was deprecated.

However, I'm in the process of improving the page so that it more closely references our official documentation (located on the U3-Docs repo, as Nelson linked). Thanks for bringing this up!

**Comment by TLingC** [comment]
thank you.
