### ISSUE TITLE
Add a LOD to the Boulder

### ISSUE THREAD

**Issue by MonsterGeeks** [SmartlyDressedGames/Unturned-3.x-Community#1531]
Please add a LOD or dispawn the boulders when we are away. That makes the maps bug

**Comment by SDGNelson** [comment]
Can you elaborate about the bug please?

**Comment by MonsterGeeks** [comment]
Is it possible to make it disappear like some objects ? Because all the boulders on the map load or have it on the map.

**Comment by FalkenJr** [comment]
Boulders don't seem to have proper LODs (it looks like they use the same model at every distance) so it might be beneficial for performance on maps with lots of boulders to work on that a bit

As for boulders not disappearing, that's most likely just your landmark settings being on medium or above, set them to low if you don't want boulders to appear

**Comment by SDGNelson** [comment]
FalkenJr is right. LODs for the boulders are problematic because their geometry is simple in the first place, and are often rotated so the model can be seen from every direction. At one point there was an in-game static batching feature to reduce draw calls, but the tradeoffs were not worth it. In the future it might be worth reimplimenting in which case triangles inside the terrain could be culled.
