### ISSUE TITLE
Tank turret turning speed.

### ISSUE THREAD

**Issue by 0AlexSashka0** [SmartlyDressedGames/Unturned-3.x-Community#1537]
Hello. I want to make a mode of tank battles, if there are already many ideas for implementation, but the tower’s turning speed is not enough for realism. I would be glad to see a similar implementation on your part. Ideally, make speed in two planes, namely turning the tower and raising / lowering the muzzle.

P.S. Immediately I want to apologize for my English.

**Comment by Alex-Well** [comment]
I support, only my colleague did not express himself clearly. We would like to see additional settings of the transport config allowing you to set the turret rotation speed and the vertical lift speed of the turret barrel.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
