### ISSUE TITLE
[FEATURE] Ability to change oxygen

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#1539]
Add the ability to change oxygen through the plugin, please!

```CSharp
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void clientModifyOxygen(CSteamID senderId, sbyte delta)
{
      simulatedModifyOxygen(delta);
}

public void serverModifyOxygen(float delta)
{
      if (delta == 0) return;
      short delta1 = Math.roundAndClampToShort(delta);
      simulatedModifyOxygen(delta1);
      if (channel.isOwner) return;
      channel.send("clientModifyOxygen", ESteamCall.OWNER, ESteamPacket.UPDATE_RELIABLE_BUFFER, delta1);
}
```

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
