### ISSUE TITLE
[FEATURE REQUEST] Object/Resource player damage options

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1544]
Ex. Damage_Player_Melee 10 (Potentially also a Fists flag for only fists)
(Would damage the player who attacked the object/resource with their melee weapon, or fists)
Damage_Player_Range 10
(Would damage the player who attacked the object/resource with a ranged weapon)
Damage_Player_Other 10
(Would damage the player who attacked the object/resource with any other kind of weapon (Grenades, traps))

i mainly want this so a player can be damaged when attacking cactuses and glass, though this would have other uses.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
