### ISSUE TITLE
Feature Suggestion: Support custom poses for NPCs

### ISSUE THREAD

**Issue by tankirules** [SmartlyDressedGames/Unturned-3.x-Community#1564]

**Comment by SDGNelson** [comment]
Would definitely be a nice feature to have. 👍

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
