### ISSUE TITLE
[FEATURE REQUEST] MORE VEHICLE EVENTS

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#1572]
Dear Nelson,

Is it possible for you to add more events into the Vehicle mod hooks. Eg, OnSirenOn, OnSirenOff, OnHeadlightsOn, OnHeadlightsOff. The purpose is to add animations to vehicles. Even better if you can make it playing animation when moving for Event like OnVehicleMovement Animation starts playing or something. Would be very interesting to see walker/animal 'vehicles'. 

Thank you for your time and hope to hear from you soon :D

**Comment by FabianWongJingLin** [comment]
Dear Nelson,

Any updates about this? Could you also make one event for when the vehicle first spawned in, so we could make it like an airdrop.

Thank you for your time and hope to hear from you soon :D

**Comment by Creeper258YT** [comment]
Would be a pretty cool feature honestly, I think if there was a setting in the Config (the singleplayer settings...) to disable vehicle spawing, it would be nice as you can disable Items and Zombies but not vehicles.

**Comment by FabianWongJingLin** [comment]
@SDGNelson Sorry to ping you, but is this possible?

**Comment by SDGNelson** [comment]
Definitely possible and makes sense to do. Probably not in a patch but whenever the next proper update is

**Comment by FabianWongJingLin** [comment]
Thank you so much :D

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
