### ISSUE TITLE
[Feature Request] Add effects to reward types

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1598]
Useful for effects such as jukebox music (see #1461) or effects playing on quest completion
Can use spawnpoints to define where the effect is played, defaults to NPC position when not set

Perhaps add ability for effect to be played serverside instead of clientside? 
IE Reward_#_Type Global_Effect/Local_Effect

**Comment by SDGNelson** [comment]
Opens a lot of interesting possibilities. Cool idea 👍 though no planned to-do date yet

**Comment by SDGNelson** [comment]
I forget if I mentioned it to you directly, but there is a component `EffectSpawner` which can do this from UnityEvents now. Still agree that an NPC trigger should be added too.

**Comment by dzonyloker** [comment]
Is this feature still planned?
For now, we need to place object next to NPC to trigger a sound effect.

**Comment by SDGNelson** [comment]
@dzonyloker Note that opening an issue does not mean something is planned. Since the reward handler does have any scene context this would only be able to spawn effects at location markers for the meantime. One thing on my to-do list however is a Unity Event component which subscribes to the Event NPC reward type, that could be used to trigger EffectSpawner which would provide a bit more flexibility.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
