### ISSUE TITLE
Melee Item Question

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#1599]
Hello!
Is there a way to repeat the animation when I press the click?

I mean to repeat only animation and not sound.

**Comment by SDGNelson** [comment]
Not at the moment. What do you have in mind?

**Comment by educatalan02** [comment]
My mind is to make a Desfibrilator but If I add **repeated** the sound is literally trash.
The animation looks good but the sound not really.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
