### ISSUE TITLE
Hackers can bypass SPY

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#1605]
I found that Unturned hackers can no longer watch with SPY. They can call the game and bypass SPY directly, which can make the SPY screen normal and can show that it is being spy.

**Comment by PandahutMiku** [comment]
This has been around/done for a very long time and there's probably little Nelson could do about it, because at the end of the day you have no other option then to ask the client directly for the screenshot. Most hacks just disable all ui elements on spy much like Harmony is used by plugins to patch methods. I guess nelson could randomize the spy method names/parameters but it wouldn't work for long. Hacks already spoof and randomize hwid too.

**Comment by SDGNelson** [comment]
PandahutMiku is correct that anything sent by the client is inherently spoofable.
