### ISSUE TITLE
Status update to Root Override progress

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1625]
A few months ago, I have been told that this system exists & I plan to use it to its full potential.

I did some testing with the Root_#_Override but it seems to have a few side effects, unless I'm doing something wrong. It would sometimes get rid of the spawn or not make it work at all.

How to exactly make it work & is it functional to date?

**Comment by SDGNelson** [comment]
It should be working fully. It has been supported since the spawn assets feature was added. The _Override flag was added later however. If you check the Client.log file after assets have loaded there may be some warnings about missing spawn table references that could indicate the issue, otherwise if there is a bug in the game we can track it down.

There are two expected cases:

1. Extending vanilla spawn tables e.g. inserting custom items into vanilla maps:
```
Roots 1
Root_0_Spawn_ID # of a vanilla spawn table
Root_0_Spawn_Weight value as if it were a normal entry in the vanilla table
```

2. Replacing vanilla spawn tables with a custom spawn table:
```
Roots 1
Root_0_Spawn_ID # of a vanilla spawn table
Root_0_Override (if present then the vanilla table is replaced entirely)
```

**Comment by OneManOperative** [comment]
Did some testing & it now works, thank you, Nelson. I will proceed to close this issue myself to save you the troubles.
