### ISSUE TITLE
Can't play on Hawaii

### ISSUE THREAD

**Issue by Creeper258YT** [SmartlyDressedGames/Unturned-3.x-Community#1626]
So, I deleted Hawaii and Hawaii Assets files multiple times, did nothing. I verified the game files, did nothing. I looked for errors in the Error Logs, nothing again. I have no idea what's wrong.

I tried to join a server using Hawaii : 
![image](https://user-images.githubusercontent.com/38672451/79644096-b02ab600-8174-11ea-914d-f39d8aefd5b4.png)
I tried to play it in Singleplayer, it couldn't load it.

If you are wondering, I download Nelson one.

[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4497083/Client.log)
[UnityDebug_Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4497088/UnityDebug_Client_Prev.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4497089/Client_Prev.log)

**Comment by SDGNelson** [comment]
In singleplayer the map shows up in the list, but gets stuck partway through the loading process? If you can upload the Client.log file from after trying to load into singleplayer it may provide some further details. (Client.log files in original post appear to be multiplayer.)

It may also be worth trying the Steam "Verify Integrity of Game Files" because that will also validate workshop items.

**Comment by Spebby** [comment]
There's also a chance the server is running a modified version of Hawaii, or a workshop reupload, instead of the official version.
