### ISSUE TITLE
"Stuck on Queue Pos. 1"

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#163]
Many people are complaining about the new update causing their game to bug out with the infamous "Stuck on Queue Position One". In case Nelson hasn't heard of this, it is affecting many people and currently the majority of servers are under 5-8 players.

**Comment by Trankvil** [comment]
my server have also problem queue position number one. restart server problem is dont missing

**Comment by baranmod** [comment]
And apparently it mostly happens on Washington/PEI maps and workshop maps based on those two. No problems on Russia, Greece

**Comment by Hawkyou72** [comment]
Same thing is happening to my server, no one can join. Maybe its the new update?

**Comment by N1GHTPATROL** [comment]
It is the new update, and as of now 90% of servers are bricked, and this update has been live for about 7 hours.

**Comment by Hawkyou72** [comment]
Lets just hope Nelson fixes this quickly

**Comment by Torubloo** [comment]
@N1GHTPATROL i might of found the problem, can you punch? and does it log you joining? if so turn on debug and it should say loading lighting next to the FPS?

**Comment by Hawkyou72** [comment]
Yes I can punch @N1GHTPATROL , can you go into more detail

**Comment by ishuto** [comment]
My server has the same issue as well. I attempted to reinstall Unturned twice, and making a vanilla server (no mods or workshop) but this error is still on. SOMETIMES it lets me in but mostly I get stuck on queue position number 1 and it lets me punch and hear my environment. My friends have issues joining to my server because of the same reason so I need to wait for a fix.

**Comment by ghostpro228** [comment]
Plz fix bug

**Comment by Torubloo** [comment]
This seems to be similar to the Max_Packets_Per_Second bug but i don't think it is that, this bug seems to only happen to certain maps, with debug on you can see it says "Lighting", mouse is stuck in the middle of the screen, it's like if you were ingame but the ui didn't close.

People can even hear each other and talk to each other, they can also see you punching and spinning around, you can't walk though

Will post more if i find out more, for people who are just saying "it doesn't work" and not contributing/giving more info on this bug please do not comment in the first place, it just creates spam.

@SDGNelson

**Comment by SDGNelson** [comment]
Sorry for the delay - it took a while for me to replicate it. Turns out the differences between UE4 and Unity are getting to me (I made a dumb mistake). Preparing a patch now.
