### ISSUE TITLE
[FEATURE REQUEST] Mo' sound options

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1630]
Unity Side
"Unscope": plays when the player gets out of ADS
"Shooting_Addative": plays louder the longer you shoot

Unturned has been working towards reducing the amount of redundant sounds in the CoreMasterbundle, and by extension, curated content. It would be nice if some additional options were added. 
"UseAudioClip" : Gas cans, handcuffs and cable ties, handcuff keys, flashlight, tools, and all throwables currently do not have an Audio Clip option for using them.
"BangAudioClip" : flashbang sound (While on the topic, it would be nice if the flashbang's duration and trigger time weren't hardcoded)
"SmokeAudioClip" : ditto but for smoke
"CastAudioClip": Fishing :)
"ReelAudioClip": ditto
"TugAudioClip": ditto ditto
"ToggleAudioClip" : sound for things like Laser Pointer, Headlamp & Nightvision (these are also not able to be overwritten anyways)

In terms of these audio clip redirects there are probably more worth adding, but these are the ones that stick out to me.

**Comment by OneManOperative** [comment]
Sound when ADS'ing is already in the game. Getting out of ADS doesn't have sounds though.

**Comment by Spebby** [comment]
partly added in 3.22.15.0

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
