### ISSUE TITLE
[FEATURE REQUEST] Fuel Calibers 

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1637]
Would allow for tiers of Fuel. 
Vehicles would be able to specify their Fuel Caliber they use; 
Ex. Vehicle_Fuel_Caliber _ID_ Defaults to 1, or Vanilla.

Objects that have fuel reserves would be able to specify their Fuel Caliber.
Ex. Object_Fuel_Caliber _ID_ Defaults to 1, or Vanilla.

Items that have fuel reserves can specify their Fuel Caliber.
Ex. Item_Fuel_Caliber _ID_ Defaults to 1, or Vanilla. 

Barricades that have fuel reserves would be able to specify their Fuel Caliber.
Ex. Barricade_Fuel_Calider _ID_ Defaults to 1, or Vanilla.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
