### ISSUE TITLE
[FEATURE] "Mixed" type of Item in Workshop

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1640]
In most cases you do mod not only with Shirt or Barricade. It's very hard to choose. Why not to add "Mixed"? Last addition of "Custom Game" for map was really helpful.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
