### ISSUE TITLE
Ghost vehicles and players

### ISSUE THREAD

**Issue by Raxul257** [SmartlyDressedGames/Unturned-3.x-Community#1642]
Two days ago I opened up my server which almost all the time has 70+ players online and I found a strange bug. From time to time I can find copies of players and vehicles (mainly), which appear at random places. Sometimes other players can see them and sometimes they can't. I didn't find any errors in server and client logs. I guess it's related to amount of players.

**Comment by CyberAndrii** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/693

**Comment by SDGNelson** [comment]
If it is the issue CyberAndrii mentions then it might be cleared up in the next update because the game will take stricter measures to prevent plugins from corrupting the network data.

Otherwise it is quite probably related to the player count. (as a point of reference the vanilla game supports only up to 24 players)

**Comment by CatzMR** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1616
