### ISSUE TITLE
[FEATURE REQUEST] Vehicle Towing Restriction

### ISSUE THREAD

**Issue by K-Raptor** [SmartlyDressedGames/Unturned-3.x-Community#1649]
I was wondering if we could get a configuration inside the vehicle's .dat file that would restrict a vehicle from being towed? So something along the lines like "**Towing_Disabled**" or so. That way lets say a modded skycrane can't tow large vehicles such as tanks, large ships, or another skycrane in that case. Just an extra restriction would be nice for modding.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
