### ISSUE TITLE
NPC and Zombies

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1659]
Hello! I want to offer several innovations:

NPC:
- Setting markers on the map with an active quest.
- Navigation visit gives out certain conditions for NPCs

Zombie:
- editing the attack range of each type of zombie
- the ability to wear zombie mesh clothes

Sorry for my English.

**Comment by sam9612** [comment]
Agree that zombie clothing system need more functions so that cloth emission, metallic, 3d shirts can be applied.

**Comment by FalkenJr** [comment]
May also be beneficial to improve emission/metallic textures on players/zombies, as only one instance of each can exist at one time
(ie. only the shirt's emission texture is applied when both shirt and pants have emission textures bundled with them, potential conflict due to names?)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
