### ISSUE TITLE
[Feature]InfiniteReserves/Magazines

### ISSUE THREAD

**Issue by erik7302** [SmartlyDressedGames/Unturned-3.x-Community#1671]
Unlike InfiniteAmmo this let the gun reload/fill without having another mag on the inventory, also plays the sound.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
