### ISSUE TITLE
Navigation issues 

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1673]
When I put a new navigation on the map and put the spawn of zombies, then in a single game they will not spawn.

- Bake Navigation button pressed
- Spawn zombies 0.85
- Navigation number 30
- Old navigation works fine

Previously, everything was installed without problems. If necessary, I can send a video.

**Comment by SDGNelson** [comment]
Are the white/purple bounds overlapping any other navmesh areas? Only one navmesh is active per client at a time.

**Comment by SvyatoslavOrlov** [comment]
Other navigation do not touch the main one.

**Comment by SDGNelson** [comment]
The main one? If they are smaller overlapping a main navmesh that will also not work. None of them should be touching at all.

**Comment by SvyatoslavOrlov** [comment]
https://youtu.be/WcA3BPqjKvs

**Comment by SDGNelson** [comment]
Odd, alright: would it be possible to send me the map file please? I will try loading it up and see what might be happening.

**Comment by SvyatoslavOrlov** [comment]
Google Drive https://drive.google.com/open?id=1wUOGYHoQhFd5c-ZQVvl7lOgME-Bq6Zmd

**Comment by SDGNelson** [comment]
Thanks for the files. It seems the problem is that some of the navmeshes are not baked yet. If you bake them all it should load properly. In the next update I have made a change so that it will continue loading regardless of some not being baked, and was able to add a new navmesh to your map with zombies spawning in it.
