### ISSUE TITLE
[FEATURE REQUEST] Stereo Station Availability Area

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1682]
Addition to the Ambience/Effect volume that makes a specific station available once the volume has been entered. Useful for secret messages.

While on the topic of Stereos, locking stations to a map is also something that'd be appreciated. That way map specific easter eggs can't be played on a completely unrelated map.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
