### ISSUE TITLE
[FEATURE REQUEST] New bayonet options

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1688]
Currently the bayonet items cant be customized. Firt of all I think we need default options like Damage just like the normal melee weapons. Secondly, I would like to see the ability to make bayonet stab cost some energy, just like the powerful attack with the melee weapon. Of course the amount of energy consumed for this action must be set in the asset. It would be also nice to see settings like Bleeding chance and different types of damage for bayonet. Custom animation and sound are also important things. Right now the game applies default stab sound and animation to any modded bayonet, and I would like to see an option to make custom sound and animation. It could be made, so that if the modder doesnt make his own animation, the game applies the default one, but if he makes one and adds it to the prefab and some special tag to the asset (Has_Stab_Animation) it applies the custom animation to it.

**Comment by Alex-Well** [comment]
Supporting, it will be very useful for modding!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
