### ISSUE TITLE
More text symbols for Interact and Conditions localisation

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1691]
Good thing you can do your own localisation for whatever objects or NPCs, but amount of it is very limited. Maybe you will change it to fit a bit more?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
