### ISSUE TITLE
[FEATURE REQUEST] Changing the rendering of items

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1692]
Hello Nelson, will it be possible to add an option for rendering items in the first person as if it were in the third person. At the moment, the image of the weapon in the hands is superimposed on top of the image of the scene so that the gun barrel does not pass visually through objects on the stage. However, because of this, it is difficult to determine the real distance.
If you added a line that disables this method of rendering from the first person, then we could make melee weapons that could be thrown.

**Comment by SDGNelson** [comment]
Eventually I intend to merge the first and third person views, but no ETA

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
