### ISSUE TITLE
Mesh Replacement | More types of clothes

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1698]
Nice thing you can replace player mesh using clothes. I didn't find way to use this as another type of clothes, like vests or masks, for example. Is there any possible way to do this?

 Maybe I miss something or game just don't have such option?

**Comment by SDGNelson** [comment]
The body mesh can only be replaced once at a time, so shirts were chosen to do it. What do you have in mind? i.e. what happens if a vest and mask that both want to replace the character mesh are equipped.

**Comment by NoThreat** [comment]
I want to replace mesh only once, but using not only Shirt type of clothing. Is this possible?

**Comment by SDGNelson** [comment]
Why an item other than a shirt? The shirt was picked because the texture is not needed if the mesh was replaced, though it could have been the shirt or pants.

**Comment by NoThreat** [comment]
I wanted to do something interesting using item because player could change shirt and model was able to pick player's material displaying current shirt player was wearing. Right now it works with pants, but be good to work with shirt. 

(Sorry for English)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
