### ISSUE TITLE
Wall glitching, back to 2017

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1715]
[![](http://img.youtube.com/vi/DHjbIGfP9JA/0.jpg)](http://www.youtube.com/watch?v=DHjbIGfP9JA"")

**Comment by SDGNelson** [comment]
Thanks for the report: giving it a try myself it seems to happen when the camera hits the ceiling above and gets pushed into the wall instead of down. Off the top of my head it should not be doing that (obviously) but I will figure it out for a .2 patch later this weekend. (unless there is a critical bug, best to avoid too many patches)

**Comment by SDGNelson** [comment]
Should be fixed in the .2 patch Monday!
