### ISSUE TITLE
Add configuration to disable ServerTextChatMessenger

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#1724]
- Allow_Use_Command_ServerTextChatMessenger ( default false )
- Allow_Chat_ServerTextChatMessenger ( default true )

Can you add this in the config, because it can be some issue with security? For example using the commands `/admin`, `/kill`, `/night`, `/shutdown` etc... 

And add some of the logging when mods use `ServerTextChatMessenger`.
( path in hierarchy? + message )

If this is not be added then I create a plugin that blocking all `ServerTextChatMessenger` feature.
OR make blacklist of commands whats can't be executed with this hook
```
                public void SendTextChatMessage(string text)
		{
			if (Provider.isServer && Provider.configData.Server.Allow_Chat_ServerTextChatMessenger)
			{
				ChatManager.serverSendMessage(text, this.DefaultColor, null, null, EChatMode.SAY, this.IconURL, this.UseRichTextFormatting);
			}
		}

		public void ExecuteTextChatCommand(string command)
		{
			if(Provider.configData.Server.Allow_Use_Command_ServerTextChatMessenger)
			{
				Commander.execute(CSteamID.Nil, command);
			}
			CommandWindow.Log($"ServerTextChatMessenger => {command}");
		}
```

**Comment by Alex-Well** [comment]
I protest! Thanks to this script, the creators of mods can protect them from a steal! Server administrators who steal other people's mod packs are now more careful about mods. This will force them to use only their own mods.

**Comment by GazziFX** [comment]
Maybe simple script for protection
```c#
class Protection
{
  public UnityEvent Detected;
  public string TargetIP;
  void Start() 
  {
    if (ip.ToString() ! = TargetIP) 
       Detected.Invoke();
  }
}
```
It can be cracked on server but harder to crack on client

**Comment by DiFFoZ** [comment]
> I protest! Thanks to this script, the creators of mods can protect them from a steal! Server administrators who steal other people's mod packs are now more careful about mods. This will force them to use only their own mods.

In the menu workshop submit has the label `AllowedIPs`. This can protect your mod. But if u find your mod in modpack then u can use DMCA.

**Comment by Alex-Well** [comment]
> Maybe simple script for protection
> 
> ```cs
> class Protection
> {
>   public UnityEvent Detected;
>   public UnityEvent Legit;
>   public string TargetIP;
>   void Start() 
>   {
>     (ip.ToString() ! = TargetIP ? Detected : Legit).Invoke();
>   }
> }
> ```
> 
> It can be cracked on server but harder to crack on client
> Usage: Disable GameObject by default and restore with legit event

This is useful, but then you still need to call some kind of server function of type **/shutdown** so that they could not use the mod that you did for your server!

**Comment by GazziFX** [comment]
@Alex-Well shutdown command can be bypassed with plugins, but on client you can just disable Renderrer and mod will be useless

**Comment by Alex-Well** [comment]
> @Alex-Well shutdown command can be bypassed with plugins, but on client you can just disable Renderrer and mod will be useless

An interesting option, but it will not be correct to remove such features as interaction with the server from modders. Unturned, on the contrary, strives for progress, and the more opportunities content creators have, the more interesting gameplay you can implement!

**Comment by NoThreat** [comment]
Just remove using any commands ok

**Comment by SDGNelson** [comment]
Your suggestions make sense. The client requests log the message and hierarchy path, so I will do the same for the server requests. I will also add the options to enable/disable them.

(Sunday or Monday patch)

**Comment by Trojaner** [comment]
I dont even get why this guy has downvotes, he actually has a point

**Comment by Alex-Well** [comment]
> I dont even get why this guy has downvotes, he actually has a point

We with modders came up with how to protect the mods from theft. Adding a command of type / shutdown to the mod could turn off a server that uses our mod without permission. However, some were afraid of this and suggested introducing these restrictions. I believe this may be a good system for protecting mods, but now it will not be effective since the server will be able to block commands from mods by default.
Perhaps Nelson will make an alternative?

**Comment by PandahutMiku** [comment]
> > I dont even get why this guy has downvotes, he actually has a point
> 
> We with modders came up with how to protect the mods from theft. Adding a command of type / shutdown to the mod could turn off a server that uses our mod without permission. However, some were afraid of this and suggested introducing these restrictions. I believe this may be a good system for protecting mods, but now it will not be effective since the server will be able to block commands from mods by default.
> Perhaps Nelson will make an alternative?

Some of your messages are slightly difficult to understand, so apologies if I get something wrong.

From what I do understand from your messages though, you're saying the ability for mods to execute commands is a deterrent from other servers to steal mods as they could update them and abuse the fact they can send commands? If so, that's kind of a silly reason to protest this. If people start fighting people stealing their mods by exploiting this functionality, I think there's another issue at hand then that.

>Adding a command of type / shutdown to the mod could turn off a server that uses our mod without permission

I don't think you understand how someone would steal your mod in the first place. You can use the IP whitelist/blacklist functionality to stop people directly from using the mod. Otherwise people would download the mod itself, and upload it under their own account to steal it. Meaning, to turn off a server that uses your own mod without permission, you would have to have that same functionality inside of the mod already being active in the version you uploaded. (Meaning if your own server was using the mod -- clients would constantly be trying /shutdown)

> but now it will not be effective since the server will be able to block commands from mods by default.

I don't think Nelson said anywhere if it would be by default that Mods would be blocked from sending commands. In my opinion, though, it should be the default. The case where mods send commands is very rare and not very likely. It should be required for servers to explicitly enable such functionality. I really doubt any mod using this functionality is going to have issues just because it's not on by default.
 
One compromise would be to let mods send messages on the behalf of players by default (though configurable) but not send commands by default.

But honestly, you're talking about such a minor component which use cases are already very rare.

**Comment by Alex-Well** [comment]
> > > I dont even get why this guy has downvotes, he actually has a point
> > 
> > 
> > We with modders came up with how to protect the mods from theft. Adding a command of type / shutdown to the mod could turn off a server that uses our mod without permission. However, some were afraid of this and suggested introducing these restrictions. I believe this may be a good system for protecting mods, but now it will not be effective since the server will be able to block commands from mods by default.
> > Perhaps Nelson will make an alternative?
> 
> Some of your messages are slightly difficult to understand, so apologies if I get something wrong.
> 
> From what I do understand from your messages though, you're saying the ability for mods to execute commands is a deterrent from other servers to steal mods as they could update them and abuse the fact they can send commands? If so, that's kind of a silly reason to protest this. If people start fighting people stealing their mods by exploiting this functionality, I think there's another issue at hand then that.
> 
> > Adding a command of type / shutdown to the mod could turn off a server that uses our mod without permission
> 
> I don't think you understand how someone would steal your mod in the first place. You can use the IP whitelist/blacklist functionality to stop people directly from using the mod. Otherwise people would download the mod itself, and upload it under their own account to steal it. Meaning, to turn off a server that uses your own mod without permission, you would have to have that same functionality inside of the mod already being active in the version you uploaded. (Meaning if your own server was using the mod -- clients would constantly be trying /shutdown) (I don't think there's any way you could use a mod to check the server name or IP inside of a modhook but correct me If I'm wrong)
> 
> > but now it will not be effective since the server will be able to block commands from mods by default.
> 
> I don't think Nelson said anywhere if it would be by default that Mods would be blocked from sending commands. In my opinion, though, it should be the default. The case where mods send commands is very rare and not very likely. It should be required for servers to explicitly enable such functionality. I really doubt any mod using this functionality is going to have issues just because it's not on by default.
> 
> One compromise would be to let mods send messages on the behalf of players by default (though configurable) but not send commands by default.
> 
> But honestly, you're talking about such a minor component which use cases are already very rare.

Yes, you are probably right that a small number of modders became the use of this opportunity in this way .. Probably I will have to implement protection in another way. You can use more advanced methods of struggle, but they are more harmful than if it was a simple shutdown of the server via / shutdown.

**Comment by SDGNelson** [comment]
This was not indented as some sort of DRM malware... I am disappointed.

In the .2 patch on Monday:
- Per-server settings have been added to the config file. Messages and commands from Unity Events are disabled by default. The settings are in the `UnityEvents` section as `Allow_Server_Messages`, `Allow_Server_Commands`, `Allow_Client_Messages` and `Allow_Client_Commands`.
- All usage of Unity Event messages and commands are logged on client and server.
- `ServerTextChatMessenger` command execution is routed through `Commander.execute_UnityEvent` rather than `Commander.execute`.
- `Commander.onCheckUnityEventPermissions` has been added for fine-grained control over which commands can be used by `ServerTextChatMessenger`.
- `ChatManager.onCheckUnityEventPermissions` has been added for fine-grained control over which commands can be used by `ClientTextChatMessenger`.

**Comment by Alex-Well** [comment]
> This was not indented as some sort of DRM malware... I am disappointed.
> 
> In the .2 patch on Monday:
> 
> * Per-server settings have been added to the config file. Messages and commands from Unity Events are disabled by default. The settings are in the `UnityEvents` section as `Allow_Server_Messages`, `Allow_Server_Commands`, `Allow_Client_Messages` and `Allow_Client_Commands`.
> * All usage of Unity Event messages and commands are logged on client and server.
> * `ServerTextChatMessenger` command execution is routed through `Commander.execute_UnityEvent` rather than `Commander.execute`.
> * `Commander.onCheckUnityEventPermissions` has been added for fine-grained control over which commands can be used by `ServerTextChatMessenger`.
> * `ChatManager.onCheckUnityEventPermissions` has been added for fine-grained control over which commands can be used by `ClientTextChatMessenger`.

@SDGNelson I hope you’re doing the right thing, but I’ll still show why I upheld the opposite opinion! I present to you the mod protection system!
https://www.youtube.com/watch?v=4xlrM0yAFw8
