### ISSUE TITLE
Nelson blocked only less dangerous vulnerabilities!

### ISSUE THREAD

**Issue by Alex-Well** [SmartlyDressedGames/Unturned-3.x-Community#1734]
(I apologize if I expressed myself unclearly somewhere!)

Hello Nelson. I am a modder who has always sought to develop modding in Unturned. You recently added a useful modding tool like **ClientTextChatMessenger** and **ServerTextChatMessenger**. However, the encoders were afraid that the mods could send commands on behalf of the server as **/shutdown** and suggested that you enter the restrictions included by default. Yes, your fears are true and at the same time in vain. Mods could crash the server long before the appearance of these scripts, but there were still no cases when the mod purposefully damaged the server. I am annoyed by the fact that with the new restrictions you have banned only minor threats such as for example chat text or prescribing the **/teleport** command, and the ability to really harm the servers is still in the game. Moreover, you can harm the server not only by turning it off, but also by killing for example all the players on the map. This video will confirm my words, my mod is still able to turn off the server at my command, but now the administrator will not receive a message with information for what reason the server was shutdown. (Awesome vulnerability fix)
https://youtu.be/gX60DevJW0w
I know many ways to make a server unplayable if my mod is on it. However, no other modder has ever used this evil. I don’t understand why you introduced these restrictions. I just wanted to make a mod that allows teleporting and that it would not be dependent on server settings. How am I supposed to be now? Asking people to enable an option that supposedly makes their server vulnerable now?
If we talk about vulnerability, then plugins are much more dangerous than mods. What prevents a person selling a plug-in from inserting into it a stiller that will steal all other plugins from the server or give out administrator rights? Why do modelers limit and prevent teams and logic elements from using in their mods? After all, administrators have the right to choose which plug-in or mod to install on the server, and the threat may be there and there.
I just want more opportunities for modding so that it is more independent, however, you restrict some options by default.
Nelson, the task of modders is not to harm, but rather create content for the game, why introduce server restrictions!
Please make at least the **Allow_Client_Messages** and **Allow_Client_Commands** options enabled by default. I was going to send a message to the chat using the trigger when the flashlight was turned on, which would then activate the teleport built into the flashlight and at the same time cause an error in the console to block messages for other clients using another script. Those. turn messages into chat as some local commands only for certain mod items and this would not require any action from plugins, administrators. My mod would work by default.
Although I have a much more suitable alternative, I recently offered another very useful modding tool.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1697
You wrote that there may be problems with its implementation, but it seems the commentators below have refuted your concerns.
I also propose adding more different scripts for modding and allowing sending messages for **ClientTextChatMessenger** by default, and for **ServerTextChatMessenger** to disable it.
I believe such a compromise will be appropriate.

**Comment by Letomaniy** [comment]
bullshit

**Comment by SDGNelson** [comment]
Well, for starters, as soon as the update released you immediately used the new feature to do exactly what everyone was afraid of.

If I had not included any options to enable/disable this feature then plugins would have done it by injecting code likely to cause bugs, so better to get ahead of them by having an official option.

There are no restrictions in singleplayer so usage of the text chat messengers will work out of the box, but if a server owner wants to install them on their server they will need to know to enable them.

**Comment by PandahutMiku** [comment]
> (I apologize if I expressed myself unclearly somewhere!)
> 
> Hello Nelson. I am a modder who has always sought to develop modding in Unturned. You recently added a useful modding tool like **ClientTextChatMessenger** and **ServerTextChatMessenger**. However, the encoders were afraid that the mods could send commands on behalf of the server as **/shutdown** and suggested that you enter the restrictions included by default. Yes, your fears are true and at the same time in vain. Mods could crash the server long before the appearance of these scripts, but there were still no cases when the mod purposefully damaged the server. I am annoyed by the fact that with the new restrictions you have banned only minor threats such as for example chat text or prescribing the **/teleport** command, and the ability to really harm the servers is still in the game. Moreover, you can harm the server not only by turning it off, but also by killing for example all the players on the map. This video will confirm my words, my mod is still able to turn off the server at my command, but now the administrator will not receive a message with information for what reason the server was shutdown. (Awesome vulnerability fix)
> https://youtu.be/gX60DevJW0w
> I know many ways to make a server unplayable if my mod is on it. However, no other modder has ever used this evil. I don’t understand why you introduced these restrictions. I just wanted to make a mod that allows teleporting and that it would not be dependent on server settings. How am I supposed to be now? Asking people to enable an option that supposedly makes their server vulnerable now?
> If we talk about vulnerability, then plugins are much more dangerous than mods. What prevents a person selling a plug-in from inserting into it a stiller that will steal all other plugins from the server or give out administrator rights? Why do modelers limit and prevent teams and logic elements from using in their mods? After all, administrators have the right to choose which plug-in or mod to install on the server, and the threat may be there and there.
> I just want more opportunities for modding so that it is more independent, however, you restrict some options by default.
> Nelson, the task of modders is not to harm, but rather create content for the game, why introduce server restrictions!
> Please make at least the **Allow_Client_Messages** and **Allow_Client_Commands** options enabled by default. I was going to send a message to the chat using the trigger when the flashlight was turned on, which would then activate the teleport built into the flashlight and at the same time cause an error in the console to block messages for other clients using another script. Those. turn messages into chat as some local commands only for certain mod items and this would not require any action from plugins, administrators. My mod would work by default.
> Although I have a much more suitable alternative, I recently offered another very useful modding tool.
> #1697
> You wrote that there may be problems with its implementation, but it seems the commentators below have refuted your concerns.
> I also propose adding more different scripts for modding and allowing sending messages for **ClientTextChatMessenger** by default, and for **ServerTextChatMessenger** to disable it.
> I believe such a compromise will be appropriate.



The issue with the mods sending messages goes further than just locking the server/shutting it down. You could easily make a mod admin yourself or some ID on every server and do other much more malicious things then crashing the server. 

You're still talking about a very niche feature. If your mod uses it to teleport people or say stuff in chat, you just have to include a few words in your description of your mod "This mod sends messages on behalf of user for <x, y> functionality. You must enable this in the config by setting Allow_Client_Messages to true". That is not going to deter people any more than having your mod teleport people/say stuff on the behalf of users would in the first place.

The argument about plugins being able to do more damage is null. People already know this to be true, and are skeptical about plugins and more careful with them. People wouldn't think something downloaded off the steam workshop could cause such damage, which is why it's important to restrict them.

You care a lot about such something which has such a niche use case, which doesn't help when you already stated your intent was to try to use it to shutdown the server as some sort of DRM protection. As I said above, the need to set the config options is not going to deter anyone from downloading mods that use them. People would be deterred by the fact your plugin uses them in the first place when such a thing is borderline unnecessary and has very little practical use case.

Fundamentally your argument seems to be "we can already shut down the server with other stuff/do worse and plugins can also do worse" but as I said above, this doesn't really work out. People are much less skeptical of mods on the workshop vs plugins from third parties, and these mods using commands could do a lot worse then shut down your server. They could easily use the mod to ban people they don't like, admin themselves, etc.


> Nelson, the task of modders is not to harm, but rather create content for the game, why introduce server restrictions!

Very ironic you say this after saying you want to use this feature to shut down servers stealing your content, and trying to argue that modders can already do worse.

**Comment by SDGNelson** [comment]
Nicely worded @PandahutMiku, I completely agree with you.
For the mentioned teleport usage in OP: it would make more sense to use the mod-exposed teleport functionality anyway rather than commands. The command aspect of this is only useful for features that are not mod-exposed yet, like changing the weather.

**Comment by Alex-Well** [comment]
Can you then change the message processing method from ClienTextChatMesseger so that messages are read by the server but not sent to clients? In my mods, the communication mode of mods through chat was implemented, now it does not work by default. This will not affect security in any way since these are ordinary text messages and they will not be shown only when you turn on options.

**Comment by SDGNelson** [comment]
> Can you then change the message processing method from ClienTextChatMesseger so that messages are read by the server but not sent to clients? In my mods, the communication mode of mods through chat was implemented, now it does not work by default. This will not affect security in any way since these are ordinary text messages and they will not be shown only when you turn on options.

Can you clarify what you mean or are trying to do please?

**Comment by Alex-Well** [comment]
When a player writes a chat message, the server checks and then sends it to clients. This is used, for example, to create text filters that do not display messages with curses. I suggest blocking messages from ClientTextChatMasseger in this place, so that messages activate TextChatEventHook, but do not show to users. In such a not so convenient way, I can implement communication in mods, for example, Item with Vehicle.
I understand that this sounds strange, but I doubt that you will have much time to write a universal UnityEvent.

**Comment by Alex-Well** [comment]
@SDGNelson The vulnerability through which I caused the shutdown of the server on the video is in the Exit() method

**Comment by Bradler26** [comment]
My 2 cents.

I agree with what @PandahutMiku says about just adding a line in your mod description telling owners to enable that feature. I'm pretty sure that 90% of owners will at least read the first few lines of the description before adding a mod to the server. 

My idea is that maybe Nelson could add a warning message like he has for mods that use the wrong Unity version. The warning simply states that "X mod requires Allow_Client_Messages enabled in order to work correctly".
This way your fear of people not realising they need Allow_Client_Messages enabled is somewhat removed and us server owners don't need to worry about every workshop we download. 

I don't know how hard it would be to implement but if it is easy enough I think it would be the best workaround.
