### ISSUE TITLE
New event for BarricadeManager.destroyBarricade and StructureManager.destroyStructure

### ISSUE THREAD

**Issue by Pustalorc** [SmartlyDressedGames/Unturned-3.x-Community#1737]
Currently `BarricadeManager.destroyBarricade` and `StructureManager.destroyStructure` don't raise any events when called. It would be nice to have them raise an event as to help plugins that track barricades + structures constantly know when a buildable has been destroyed (yes, I will be calling both Barricades + Structures buildables, as that is easier).

For example, I've been working on a plugin called BaseClustering, and currently it constantly takes ~5 seconds to work through `BarricadeManager.regions` and `StructureManager.regions` to build a list of all of that data on a large map with 45K buildables. This damages performance, as if I were another plugin and wanted to find a specific item in the map, I would be adding the 5 second penalty of processing through all that data + however long it takes to find the item.
On BaseClustering however, I pre-process the data and then allow myself as well as other plugins to get all the buildable data as a list, which takes a couple milliseconds at worst.

Having these events would help plugins like this track when other plugins (Like WreckingBall, Decay, or any other plugin that destroys buildables) completely get rid of a buildable from the map.

**Comment by joeymisfit** [comment]
+1

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
