### ISSUE TITLE
Feature Request: Event For UI Toggle

### ISSUE THREAD

**Issue by Bradler26** [SmartlyDressedGames/Unturned-3.x-Community#1742]
I have recently started fiddling around with more UIs lately and one thing that makes a UI seem odd is when it doesn't act the same way as default UIs. 

If possible could an event be made that plugins can hook onto to see when certain UIs are toggled on/off. This would make other UIs that servers use a lot better looking when the client opens their inventory, hits ESC or dies the UI will despawn the same way the default health UI despawns.

If it is easy enough to add it would be a great feature to add. Thanks :)

**Comment by Bradler26** [comment]
Hey.

Is there a plan to add this for any of the upcoming updates?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
