### ISSUE TITLE
Add an option to make traps group friendly

### ISSUE THREAD

**Issue by Paradox304** [SmartlyDressedGames/Unturned-3.x-Community#1745]
It would be so good if there was an option to make traps be group-friendly, as in my server we have custom traps and teams so team members usually step on the traps and die.

**Comment by SDGNelson** [comment]
Re-opening, request makes sense, albeit no immediate plan to add

**Comment by Paradox304** [comment]
I made a plugin that does it, so I closed it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
