### ISSUE TITLE
Add option to place a video or photos when mods are loading in a server

### ISSUE THREAD

**Issue by EKISDE** [SmartlyDressedGames/Unturned-3.x-Community#1747]
Option on server config for place videos or photos when you are joining a server with mods.

Thanks for read

**Comment by Alex-Well** [comment]
Images during the download are taken from the folder with the map. Do you want to make them taken from the Internet?

**Comment by Trojaner** [comment]
He prob means having a custom loading screen like in gmod

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
