### ISSUE TITLE
is there new issue in shooting system?(a lot headshots, not dying) 

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#1756]
Hello,
recently we heard few players complain about shooting a lot bullets, but the other player doesn't die!
a player managed to get a video (many headshots!): 
https://cdn.discordapp.com/attachments/612059834396966942/714245840683925585/unturned_putins_is_great_2020.05.24_17h44_cutted.mp4
all the time I thought detecting bullets hits is done on shooter-server side, and victim can't affect it, that's why we don't see infinite health cheats.
so, could anyone explain whats going on, in this video, and similar cases? it is new game issue?
thank you

**Comment by SDGNelson** [comment]
You are right that infinite health cheats are **NOT** possible.

There might be a bug, but I have not seen this reported following the update. Have any other hosts seen issues with bullets being ignored?

**Comment by rube200** [comment]
I asked about it to awedy:
![Screen1](https://user-images.githubusercontent.com/20555316/82814142-6e391200-9e8e-11ea-95ab-a14bbc9260c9.png)
![Screen2](https://user-images.githubusercontent.com/20555316/82814151-76914d00-9e8e-11ea-9678-79fae5b3e5dc.png)

**Comment by Paradox304** [comment]
Same thing happening on my server as well. I'll ask some players to get some proof of it.

**Comment by Paradox304** [comment]
He is correct, it might be a latency problem.

**Comment by AstatineSC** [comment]
Same thing is happening on my server, It might be a latency problem as well.

**Comment by archie426** [comment]
@SDGNelson Maybe because of the new raycastinfousage enum? Can't really think what else could have caused it. I doubt everyone here is having latency problems

**Comment by SDGNelson** [comment]
The multiple reports do raise my suspicions. Latency-wise it is also odd that the client would see the other player shooting them, but not have dealt any damage.

archie426 is right that it could be related to the new getInput usage parameter. Taking a look over the relevant code nothing jumps out at me, but I will take another look with fresh eyes later. If anyone is using custom "anti cheat" plugins that read/write the inputs queue then it would be problematic if they don't set the usage value.

**Comment by Paradox304** [comment]
Not the case here.

**Comment by nanashi88** [comment]
actually idk what is"read/write the inputs queue", but if you refer to player.input, then our module doesn't touch it

**Comment by archie426** [comment]
If they didn't set the usage value wouldn't they then just get a missing method exception because the signature is different though?

**Comment by SDGNelson** [comment]
I mean that if the plugin dequeues the inputs and then queues modified ones the usage flag might be unset. The getInput method without a usage parameter was marked obsolete, but can still be called (returns null).

**Comment by sacarusan3** [comment]
It cant be realted to latency, since both player had 30 and 60-70 ms. If it was latency and the guy with the viper was not actually where juno (the player that recorded the video) was seeing him, it should affect to juno as well: when the viper guy kills juno, all his loot should have been pulled to where server detected he got killed at. The same goes with the viper guy's loot when he dies. But in the video you can clearly see that juno dies and does drop all the loot right where he was standing, meaning he got killed in that position and also the viper guy drops the loot exactly where he was being seen in the video, when the apc road kills him. Here is an example of what should happen when it is a latency issue: https://youtu.be/Go4Okv-6OFA

Here in this video you can see the guy being killed next to the metal door, but the frame he dies his screen freezes for 2 frames i believe, and his loot/dead body gets pulled back to where server detected he died, which is next to the pillar. This happened to me too one time: i was moving and heared a grizzly shot, my screen froze for 2 seconds and then, i saw my self dead with my loot being pulled to where i was one second before my screen froze. That guy had probably a really high ping or spike right in that moment he shot me.

**Comment by archie426** [comment]
Ahhhh ok

**Comment by Johnanater** [comment]
I get reports about this all the time, but I'm pretty sure it's due to lag/people raging. ¯\_(ツ)_/¯

**Comment by SDGNelson** [comment]
Closing because this was a while ago without further reports, but feel free to comment and I will re-open. After the netcode rewrites mentioned in the 2021 blog post I have been thinking about reworking the input networking and character movement to help with issues like this.
