### ISSUE TITLE
[Request] Please add method for loading image for player before showing him ui.

### ISSUE THREAD

**Issue by Cubody** [SmartlyDressedGames/Unturned-3.x-Community#1768]
Hello, Nelson! Can you add possible to load images to player before he will get UI with these images. Some method like EffectManager.LoadURLImage(up.CSteamID, "url") if it's possible =)

**Comment by SDGNelson** [comment]
To cache them ahead of time? Would be a straightforward addition, but is the load time really that noticeable?

**Comment by Greenorine** [comment]
Well, if you want to load some icons in UI, it'll take some time. For me it's 0.1-0.4s, for another man. For someone else who has a worse Internet connection, longer. I tried to make 1s before showing UI, but some players don't get the image quickly.

**Comment by Greenorine** [comment]
So will this be added?

**Comment by Trojaner** [comment]
I don't see how this could be helpful in any way to be honest

**Comment by Greenorine** [comment]
> I don't see how this could be helpful in any way to be honest

Well, for example: I have an UI that shows to player some images. I need to start this UI for player fastly without any loadings, so that his eyes were comfortable and he got the information instantly.

Also it can be usable for UIs that using pagination. I can send image of button ot image of "nothing" to currently button "next" or "prev". This way I can protect player from trying to press button "next" if he's on last page.

**Comment by Trojaner** [comment]
Even with EffectManager.LoadURLImage you can not know when the image has been loaded, defeating the purpose of it's addition.

> Also it can be usable for UIs that using pagination. I can send image "button" or image of "nothing" to currently button "next" or "prev"(UI image). This way I can protect player from trying to press button "next" if he's on last page and it wouldn't be laggy =)

Don't download the image from the internet and include in the workshop mod instead?

**Comment by Greenorine** [comment]
> Even with EffectManager.LoadURLImage you can not know when the image has been loaded, defeating the purpose of it's addition.
> 
> > Also it can be usable for UIs that using pagination. I can send image "button" or image of "nothing" to currently button "next" or "prev"(UI image). This way I can protect player from trying to press button "next" if he's on last page and it wouldn't be laggy =)
> 
> Don't download the image from the internet and include in the workshop mod instead?

I want to use this method on player connected, he'll have time to download, I think.
And about workshop. I want to change image in real time, it depends on the player's action.

**Comment by Greenorine** [comment]
@SDGNelson well, can it be added?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
