### ISSUE TITLE
[QUEST FEATURE]

### ISSUE THREAD

**Issue by SvyatoslavOrlov** [SmartlyDressedGames/Unturned-3.x-Community#1772]
Add the ability to prohibit the abandonment of the quest

**Comment by SDGNelson** [comment]
Makes sense - would be useful for the vanilla boss battle quests as well

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by Ongjming** [comment]
Sorry to leave this message asking: Anyone has any clue as to what state the said quest is in if it was started midway then abandoned?
For quest conditions there are (None, Active, Ready, Completed)
Thought it would be None again since it got abandoned, but dialogue wise it is still broken (Players can no longer get back that said quest, even with dialogue option giving that quest with condition of having that quest as None)
