### ISSUE TITLE
Serverside barricade/structure salvaging

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#1773]
Hey,

Right now the barricade and structure salvaging time is countdown client-side, so it can be easily cheated. I think salvage time should be measured server side along client. 
I also need my plugin to detect when player starts salvaging specific barricade, so that's why I'm asking for it :)

Thanks

**Comment by rube200** [comment]
Nelson, if you keep it in client-side remember to add an event when the player stops the salvage in the middle as well.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
