### ISSUE TITLE
Aiming animation problem

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1775]
So I made custom animations for my gun item, and they all work, but the sights are misplaced from the screen center for some reason. When I applied vanilla schofield animations to it, sights became normal again. So, I suppose, something is wrong with Aim_Start and Aim_Stop animations, but I dont really know what exactly. I thought that camera basically snaps to the Sight prefab location when you aim, and animation doesnt affect it, but as it turns out, it does. So, what should I do to my aiming animation to fix it?

Also the Sight prefab coordinates are ok, and have zero X coordinate 

On the image you can see how much the sights are misplaced compared to vanilla schofield.

![20200529235625_1](https://user-images.githubusercontent.com/59206749/83325257-943a2a00-a273-11ea-9e77-71186a47d9a7.jpg)

**Comment by SDGNelson** [comment]
Off the top of my head it is probably related to the rotation of the sights while aimed-in. In 3 only the view position (not rotation) is aligned. One option in Blender might be to constrain the gun model and blend the constraint in/out with the aim animation, but it has been a while since I animated in Blender.

**Comment by DerpyHoowes** [comment]
Uhh, guess I will experiment with the rotation a bit. Thank you
