### ISSUE TITLE
Option to load prefab from another source

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1779]
I suggest introducing an option that allows you to load a prefab for one item from another. For example, this would be useful for loading Projectile not from Item, but from Magazine. Thus, it would be possible to create weapons firing shells of various physical and visual properties. If there is no way to make this option universal for all types of items in the game, then just make an option like Load_Prefab_Projectile for Magazine.

I also ask you to pay attention to this issue. https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1750
I understand that maybe not all ideas will be implemented, but some may well be easily implemented and very useful. (Especially AnimationEventHook, the script of which we ourselves have written, and you just have to add it to the game)

**Comment by SDGNelson** [comment]
Eventually, but no ETA

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
