### ISSUE TITLE
(Request) Option to disable teleportation checks on rocketmod

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#1788]
With an update of <del>rocketmod</del> LDM to the latest version, I noticed that most of teleport commands on all plugins started acting weirdly (commands refuse to teleport randomly. I.e. /home command might work in most cases and in some - it won't teleport player on bed even if player didn't do anything with his bedroll).

So, maybe its possible to add an option to rocket config to disable these checks which prevent successful teleportations

**Comment by SDGNelson** [comment]
Ideally the individual plugins would be updated to use the various `Player.teleport` functions rather than Rocket's `UnturnedPlayer.teleport` so that they can properly consider teleport checks.

The reason LDM originally changed `UnturnedPlayer.teleport` was that players could prone underneath an object and have their friend TPA to them to get inside the object. (because Rocket's teleport bypassed any checks) There were a lot of ways to abuse this on servers with TPA

In the latest version of LDM (included in 3.20.5) the /home command matches the vanilla respawn behavior - prior to that it was actually teleporting players inside their bed.
