### ISSUE TITLE
[FEATURE REQUEST] Add storage and bedroll functionality to objects

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1791]
- Define respawn position using devkit spawnpoints, ex.`Respawn SafezoneBedRespawn_0`
- Alternatively set position using empty gameobject, keeps everything inside the object prefab
 
- Serverside item storage like chests, open to any players
- Potential for per-player storage? Wouldn't be good for performance and file size though
- Could open the door for airdrop style looting systems using spawn tables

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
