### ISSUE TITLE
Vehicle Icons

### ISSUE THREAD

**Issue by NoThreat** [SmartlyDressedGames/Unturned-3.x-Community#1793]
Items has icons. It's really nice. You can watch items in inventory or NPC's vendor. Sometime ago vehicles had icons and even F1 supports it (econ offroader skins in extras). But if you do icons in Unity, like items, there will be nothing. Neither in workshop F1, nor vendor. 

How about reviving this feature? It could be useful in vendor.

**Comment by SDGNelson** [comment]
Would make sense to have icons for vehicle vendors, though it is unused in vanilla for now. The mean thing is that vehicles have not been setup for icons yet. Ideally I would like to refactor some of the icon  features soon anyway.

**Comment by NoThreat** [comment]
So good. Will wait it from you.

**Comment by educatalan02** [comment]
It could be good, since I already tried to get Vehicle Icons, but it looks like its not working properly.

**Comment by educatalan02** [comment]
Is there any ETA on here? @SDGNelson

**Comment by SDGNelson** [comment]
No ETA - it is low priority for the meantime. I would like to rework the icon system at some point to automatically determine the bounds and outline them, so it might happen then.

**Comment by educatalan02** [comment]
Okay

**Comment by TeemoCell** [comment]
Is there any ETA on here? @SDGNelson :D

**Comment by Pepenas** [comment]
Would really need this not gonna lie

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
