### ISSUE TITLE
[FEATURE REQUEST] Waypoints as a reward type

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1799]
Quest markers for NPC creators using the group waypoint functionality, IE. Getting the Word Out quest marking each of the Russia police departments on your map/compass

- Disappears when quest isn't tracked or when quest is abandoned
- Waypoints follow flag rules (ex. flag_bool set to 1, waypoint disappears)
- Define waypoint color and text in .dats?
- Change icon to make it more distinct from player waypoints?

**Comment by SDGNelson** [comment]
I can imagine it being useful. Right now the lack of markers for quests is intended as an old-school sort of thing. Support for multiple markers would also need to be added.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
