### ISSUE TITLE
How to disable Acid gun player-damage in PVE server? 

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#1806]
PVE. Acid gun (id: 9021 in Belgium or 6698 in Easter Island) cause player-to-player damage. I cann't find any config to disable it. And the damage does not called by `DamageTool.damagePlayerRequested`.

**Comment by SDGNelson** [comment]
Interesting case. At the moment that damage against players cannot be disabled because it uses (what was considered) a workaround to spawn zombie acid from a weapon.

After giving it some thought, despite this being originally a mod hack, there needs to be better official support for it considering it has been used on the curated maps. For the next update I will put something in place to respect the PvP settings.

**Comment by warren39** [comment]
Thanks for help! I look forward to the next update.

**Comment by SDGNelson** [comment]
Thanks for reporting this. In the next update any "temperature" damage caused by players via projectiles, grenades, and bullets is disabled on PvE servers. Environmental "temperature" damage like zombie acid spit still applies on PvE servers.
