### ISSUE TITLE
possible bug with workshop items

### ISSUE THREAD

**Issue by Old-Faithful** [SmartlyDressedGames/Unturned-3.x-Community#1817]
<img width="409" alt="what" src="https://user-images.githubusercontent.com/66855829/84557250-85786a80-ad7d-11ea-9712-009819b46f44.png">

this is when i try to go into [iLL]: Plastic Warfare.  i used to get "server was not authorized by the creators of 7 workshop item(s) to use their content" but i managed to fix it by uninstalling and reinstalling once. i tried going into the server a few days ago after being inactive but now this message shows up. i asked their discord and got help but the problem hasn't changed.

what i've done to try fix this: 
-uninstalled and reinstalled the game.
-verified integrity of game files: verified with no hiccups.
-Delete this folder: 304930 located:  C:\Program Files (x86)\Steam\steamapps\workshop\content\304930
-deleted the individual files in /304930
-went into game and clicked the + to subscribe
-unsubscribed then restarted.

one thing i noticed: it manages to download and subscribe P2 Beta, P3 Beta and MedicalSystem UI.

**Comment by SDGNelson** [comment]
The simplest answer is perhaps: are you sure the server IS authorized?

**Comment by Old-Faithful** [comment]
> The simplest answer is perhaps: are you sure the server IS authorized?

i just asked them about this. "by authorized, you mean the mods, right? in that case, every mod should be able to be used on the server. since this happens to certain people. "

**Comment by Trojaner** [comment]
Maybe the server changed IP but your mods aren't updated yet?

**Comment by Old-Faithful** [comment]
> Maybe the server changed IP but your mods aren't updated yet?

they said they'll try to re-upload all the packs when they get time. i'll get back to you when they do.

**Comment by Old-Faithful** [comment]
ok. they've updated the mods again. seems like it's confirmed that server side, nothing is wrong. now, it's this again. i really think there's something wrong.
<img width="537" alt="Untitled" src="https://user-images.githubusercontent.com/66855829/84588828-a379c400-ae7e-11ea-8a13-92c1660d5a67.png">

**Comment by TH3AL3X** [comment]
Are you sure, your IP server is whitelisted correctly without domain, i mean
**not this IP: eu.darknesscommunity.club**
**this IP: 78.46.226.129**

**Comment by Old-Faithful** [comment]
i don't know much about whitelisting but those two IPs aren't even related to what i'm reporting about. those two servers go to [EU] DARKNESS [SEMIVANILLA|TPA|X5LOOT|KEEPSKILLS]. the server that i'm having problems with is [iLL]:Plastic Warfare|Military|PW4|28slots. its IP is 78.46.226.129, port 27032. it's a fully custom server for all out war.

**Comment by TH3AL3X** [comment]
Its a example...

**Comment by Old-Faithful** [comment]
> Its a example...
> I mean try to add the IP without domain, and ports

oooh, i get it. so, you want me to go to connect and type the IP. this server doesn't have a domain name to put in. the very first time i found this server, i used connect, typed the IP and port. now, i just find it in my favourite servers. 
i tried the way you suggested. here's what happened.
<img width="384" alt="Untitled" src="https://user-images.githubusercontent.com/66855829/84611085-dff60000-af10-11ea-8ae3-ce68433bd9ec.png">

**Comment by TH3AL3X** [comment]
I don't know if this could be true, but could it be because you have a mod inside a pack that requires authorization? idk call me idiot

**Comment by SDGNelson** [comment]
Can you attach the Client.log file from the Unturned/Logs directory please?
There should be a line like "Server's allowed IP for Workshop downloads: ", so we can see if the client is determining the server's IP incorrectly.
There should also be lines explaining why the client thinks each item is unauthorized.

**Comment by Old-Faithful** [comment]
here it is. 
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4783564/Client.log)
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/4783565/Client_Prev.log)

**Comment by SDGNelson** [comment]
Thanks. Here's the workshop-related section:

[2020-06-15 14:01:48] Server's allowed IP for Workshop downloads: 162.254.193.102
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P6_M_Beta
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P4
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P5
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P1_Beta
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P2_Beta
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for P3_Beta
[2020-06-15 14:01:48] Server is not authorized in the IP whitelist for iLL Standalone

Is 162.254.193.102 the IP of the server you were trying to join?

**Comment by rkrause4** [comment]
Hi,

I'm the server owner to the server he is trying to join. I figured I'd chime in to give some more details towards the server side to help out. 

Our IP is **104.192.227.58** our mods are whitelisted to that IP as well. The format that we are using is *104.192.227.58,73.111.126.177* when we upload our mods via Steam.

We talked to our hosting service and they said they do not recognize this IP: **162.254.193.102** in their network. When I join the server my mods download correctly and our authorized. My log outputs the following:

[2020-06-15 19:19:37] Server's allowed IP for Workshop downloads: 104.192.227.58

**Comment by PandahutMiku** [comment]
162.254.193.102 is the IP of a Valve Relay Server. It seems that when players fall back to using a relay due to NAT Punching issues or whatever, it's checking the IP of the Valve Relay Server for mod ipwhitelist instead of the actual Server's IP. These issues are really annoying and it is often that trying to get an IP of a player using  SteamGameServerNetworking.GetP2PSessionState will say the player is not using a relay and give back the relay server's IP, even though they are using a relay. Might be related to this issue

**Comment by SDGNelson** [comment]
Thanks rkrause4 and Miku for the details. I think you are right that it must be getting the relay's IP instead. That is worrying if there is a delay before GetP2PSessionState returns the actual remote IP rather than the relay IP... to be safe I will change any usage of those to treat the relay flag as "unable to get IP", and perhaps add a delay before GetP2PSessionState.

**Comment by tankirules** [comment]
I believe i am having this issue too, randomly some people cannot join due to the unauthorized bug and it is really frustrating because the server _is authorized_ and many people _are on_ but some just cannot join

**Comment by SDGNelson** [comment]
In the next update all vanilla usage of `GetP2PSessionState` checks that `m_bUsingRelay` is zero. Most usage has also been routed through a helper `getIPv4Address` instead. I will remove the "next patch" label for now, and we will see how it goes.

**Comment by SDGNelson** [comment]
Have you guys heard any reports about this following the update? So far I did get one email about workshop restrictions which I presume is related.

**Comment by rkrause4** [comment]
I have heard of at least one person having this issue with our mods/server. He was able to resolve it, by doing a few things such as; restarting Unturned, uninstalling and unsubscribing to mods, and possibly a restart of his computer. I'm not sure what one of those actually fixed it for him. Nor was I able to get his logs to see any more details about it.

The issue seems to be not as frequent as it was before. That is of course only by the number of complaints in our Discord about it.

**Comment by SDGNelson** [comment]
The issue seems to be not as frequent as it was before. That is of course only by the number of complaints in our Discord about it.
> Thanks, that is somewhat reassuring.

Since Miku mentioned a delay it might be that for most players m_bUsingRelay is correct after initial connection, and that for the remaining players experiencing it the m_bUsingRelay field is not correct yet. It seems awfully messy to introduce an artificial delay though...

Long-term the new Steam network APIs do not expose any address info, so a different identifier may be needed anyway.

**Comment by Old-Faithful** [comment]
'ello. i hate to bring bad news but it's still this.
<img width="461" alt="updated oof" src="https://user-images.githubusercontent.com/66855829/87535425-96edc300-c6eb-11ea-825e-dff0fc8fdc44.png">

i tried uninstalling and reinstalling. got this message after reinstalling. not too sure what to do right now.

**Comment by SDGNelson** [comment]
For the meantime we might just have to disable the client-side restriction validation unfortunately.

**Comment by SDGNelson** [comment]
Recently this was re-enabled to use the advertised IPv4 address which is not perfect, but I would still like to revisit the feature at some point.
