### ISSUE TITLE
Feature Request: Ignore Armor for guns or magazines

### ISSUE THREAD

**Issue by Renaxon** [SmartlyDressedGames/Unturned-3.x-Community#1831]
Line added to guns/mag dat files where they would ignore certain amount of armor, for example you'd add something like 'Ignore_Armor 0.5' to a magazine and if someone had 0.5 armor on body part it'd effectively do 0.75 amount of damage.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
