### ISSUE TITLE
request add an option to change the seconds for place a barricade

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1837]
I think it is a good idea for the PvP, since this allows the player to cover himself in a barricade that he has place it instantly, since the unturned animation is very slow, or it would be a good idea to add a new skill for this ...

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
