### ISSUE TITLE
[Feature Request] Conditions in NPC

### ISSUE THREAD

**Issue by MrObi123** [SmartlyDressedGames/Unturned-3.x-Community#1842]
Dialogues can have conditions, but there should be a way so you can still see the dialogue even if you don't meet the requirements of the conditions. But there's a lock symbol on the dialogue so you can't press it.
'
Response_0_Requirements 1
Response_0_Requirement_Type Item
Response_0_Requirement_ID 67
Response_0_Requirement_Amount 1
'

Also an OR function for conditions could be cool, you need to have this OR this.

You can use items now in the vendors, maybe add a way so you can pay in dialogues. You can kinda already do this, but not like how the vendors work. Then "bus" NPCs easier to make, so you can pay to travel in different ways.
'
Response_0_Cost #
Response_0_Currency caf6bf006edb431a82e5b99e9eb2f47c
'

These features would open up a lot of cool ideas.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
