### ISSUE TITLE
[FEATURE REQUEST] Timed Explosive

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1843]
Placed barricade would automatically explode after a set amount of time, without need for a detonator, though with another .dat option, a detonator could be used to detonate early. By default set to true, but can be set to false in order to prevent early detonations. 
Explosion_Timer _Value_
Use_Detonator _True/False_

**Comment by DerpyHoowes** [comment]
You can do it by applying Grenade.cs script to the barricade

**Comment by Spebby** [comment]
> You can do it by applying Grenade.cs script to the barricade

Tested, not very useable. The moment the outline for placing the barricade appears, the barricade instantly explodes. It hasn't even been placed yet, you're still holding it, and it explodes.

**Comment by DerpyHoowes** [comment]
Because you applied the script to the Barricade prefab. You should apply it only to the Clip and it will work fine.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
