### ISSUE TITLE
Action Rocket not heard from long distances (& suggestion to making more options to create projectile ammo)

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1845]
I tested guns with Action Rocket awhile back & it turns out that they are heard from shorter distances from other Actions like Trigger & Pump.

And for the suggestion, if this doesn't exist yet, make it so that individual damage numbers work on projectile ammo. This can work by having the same sample from the special ammo in military magazines work for projectiles too. I'm currently limited to multipliers so having this can make it so that I make rocket ammo that deals more damage to vehicles but less to players.

And also give the option to use a different projectile depending on the ammo so that modders can make ammo that with custom projectiles that have different hitboxes & such.

**Comment by Alex-Well** [comment]
I suggested to Nelson to add an option to load a prefab from another type of object. Well, or just make it for the magazines. That would be helpful.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/1779

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
