### ISSUE TITLE
Parameter Request Proof_Acid

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#1846]
It would be useful to have the Proof_Acid parameter for clothes, working just like Proof_Fire.
It would also be useful to add support for such parameters as Proof_Radiation, Proof_Water, Proof_Explosion, with any type of clothing. At the moment, these parameters belong only to a certain class of objects in the game.

**Comment by FANYPLAYRU** [comment]
I think that Nelson likes to remove more than add, so it is worth hoping that Proof_Fire will not be removed in the next patches or updates.

**Comment by SDGNelson** [comment]
Makes sense to add, but no ETA

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
