### ISSUE TITLE
Courtesy from JmTheWolf: Dead players blocking build

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1853]
A player of the name, JmTheWolf, has discovered that dead players who haven't respawned yet prevent other players from building in that area.

**Comment by SDGNelson** [comment]
Interesting catch. This is because dead players are recycled when they respawn, and their disabled corpse is kept at their death location until then. The query has to check for triggers so disabling that is not an option, aside from maybe teleporting them I'm not sure about a workaround for the next update.
