### ISSUE TITLE
Community thing: Endorse OpenMod

### ISSUE THREAD

**Issue by archie426** [SmartlyDressedGames/Unturned-3.x-Community#1856]
Yeah what it says on the tin. Include in Extras in the game files. Reasons are already pretty apparent

**Comment by SDGNelson** [comment]
> Reasons are already pretty apparent

Perhaps not to me. Why?

**Comment by Trojaner** [comment]
@archie426 OpenMod has not even officially released, you are a bit too early

@SDGNelson OpenMod is the successor of RocketMod and is backwards compatible through a wrapper plugin.
https://github.com/openmod/openmod
https://openmod.github.io/openmod-docs/

**Comment by archie426** [comment]
Yeah but I'm thinking in advance lol. Main reasons is because you yourself are not keen keeping RocketMod maintained which is preventing a lot of improvements. That wasn't the reason that OpenMod was created, but it is certainly a benefit that comes from it. It does this at the time as providing compatibility for old plugins, which is perfect for this scenario.

If you compare the two sources then you will actually notice the difference and see why this is almost essential. Accepting contributions to LDM wouldn't really help because the main point is the entire project just needs to be rewritten.

If you endorsed it, it would help a lot of server owners be coaxed in to changing, which would be extremely beneficial. Also I don't really see why Rocket should be there and open mod not. 

This isn't supposed to be a rant, sorry if it sounds like one lol.

**Comment by SDGNelson** [comment]
@Trojaner continuing the goals of RM5?

From my point of view, ideally any improvements I work on are made to the base game rather than individual plugin frameworks. For example I intend to add RCON support to Unturned and Unturned II directly, rather than to Rocket.

Maintenance-wise I don't really have the choice - I need to continue maintaining Rocket because many servers depend on it. The LDM fork is included in the game files to help encourage hosts to upgrade because it fixes important issues that they might not care about.

If server hosts find OpenMod useful and many of them transition over to it then I am open to including it in the official docs, ensuring future compatibility, necessary API changes, etc.

**Comment by Trojaner** [comment]
@SDGNelson exactly! OpenMod is the improved successor of RM5.

With the OpenMod.Rocket.Unturned plugin, which is based on the LDM fork, it guarantees backwards compatibility to RocketMod plugins.

I hope OpenMod will be accepted by many server hosters due the rich features it has, which should make managing servers much easier and consistent across different games. Thanks for considering adding it to the official docs if it becomes popular enough.

**Comment by archie426** [comment]
@SDGNelson It's not really about improvements to the base game and functionality. That all works fine. It's more command registration, eventing and stuff like that really. If you endorsed this then I believe people would stop using LDM/Rocket, even if they don't use any OpenMod plugins, it is one less person you have to maintain for.

Frameworks like this are here to extend command functionality to the game as well as other stuff, which is why OpenMod hasn't actually wrapped anything from the game.
