### ISSUE TITLE
SUGGESTION: Change Legendary rarities colour from pink to gold

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1859]
Currently, the Legendary rarity and Epic rarity look very similar, making Legendary's colour gold should help to differentiate at a glance. Plus a lot of games use gold to represent the Legendary rarity.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
