### ISSUE TITLE
[SUGGESTION] Breaking changes

### ISSUE THREAD

**Issue by ennerperez** [SmartlyDressedGames/Unturned-3.x-Community#1875]
Hello @SDGNelson,

I see that you love to damage the game with certain frequency, it would not be advisable to simply delete it from steam and end it?

I tell you, cuz I see that the QA for updates is very low quality, in any case:

1. You can notify in some way when updates are coming so that developers and server owners can plan the migration and be attentive ALL day, to your post update updates. (It's what you do every time)

2. You can request any member of this community to do the tests before launching an update and I assure you that with pleasure many of us would lend their equipment and servers for it.

/ ** / _If you need help, only have to ask for it._

**You and only you are killing this game and probably the next one.**

**Comment by PandahutMiku** [comment]
Nelson does use Github Issues marked as PSA to notify people of breaking changes:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues?q=is%3Aopen+is%3Aissue+label%3APSA
If you're talking about the Rocketmod forcing you to a new version, it was stating that when you booted up the server for weeks that a newer version of Rocketmod would be required sometime in the future. This stuff is also noted in the patch notes.


There is also a Preview Branch of Unturned Nelson pushes updates to first. If you want, you could setup a server to auto update to it every time it gets released and run tests/whatever you wish to do.
https://steamdb.info/app/304930/history/

**Comment by ennerperez** [comment]
> Nelson does use Github Issues marked as PSA to notify people of breaking changes:
> https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues?q=is%3Aopen+is%3Aissue+label%3APSA
> If you're talking about the Rocketmod forcing you to a new version, it was stating that when you booted up the server for weeks that a newer version of Rocketmod would be required sometime in the future. This stuff is also noted in the patch notes sometimes. (If you're talking about the rocketmod changes you just complained about, literally nothing is stopping you from forking Rocket and making any changes you want, it's all open-source)
> 
> There is also a Preview Branch of Unturned Nelson pushes updates to first. If you want, you could setup a server to auto update to it every time it gets released and run tests/whatever you wish to do.
> https://steamdb.info/app/304930/history/

The issue that worries me when I see my users leave the server for compatibility reasons.

Thank you for your suggestions, I will take them into consideration. I'll already devise a strategy to mitigate this in the future and minimize my self-annoyance.

**Comment by SDGNelson** [comment]
Thanks @PandahutMiku for nicely summarizing everything!

Any major updates are usually scheduled for Friday mornings (PST), and if there are important patches they will come out shortly thereafter. In the past it seemed best to keep an auto-update mechanism external to the server because clients can still find servers with a matching version, but I have been considering building in an update detector that could be subclassed by plugins or simply run a .bat/.sh script.

Testing-wise there will unfortunately always be issues that slip through the cracks. MoltonMontro, danaby2, Renaxon and myself had all been testing this version for the last week or so while putting in the finishing touches, and even then three bugs snuck through. https://steamcommunity.com/app/304930/discussions/0/2638497042767432172/ Over the years a degree of automated testing has been introduced, but I would like to improve it.

**Comment by TH3AL3X** [comment]
Anyway, I think this system works very well, in this way an entire community can help Nelson to solve errors and for that Nelson created the github, but I think what ennerperez trying to tell you is that he's a bit unprofessional the way you do.
