### ISSUE TITLE
[FEATURE REQUEST] NPC Vendors Buy/Sell All

### ISSUE THREAD

**Issue by WW-TC** [SmartlyDressedGames/Unturned-3.x-Community#1879]
I think being able to have a buy all or sell all option to NPCs should be interresting, like the ones with crafting. Would be good for buying large quantities of items or selling large quantities without having to click the sell button hundreds of times. Thanks!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
