### ISSUE TITLE
Repeated appeal to Nelson on optimization

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#1886]
Repeated appeal to Nelson on optimization

I apologize for my translation, I write the text with the help of a translator

Greetings to all. First of all, I want to thank Nelson for the latest updates and no small effort in optimizing the game.

I am writing you requests from several major projects (servers). I would like to mention a few very important issues:

1) Adding spawn grids for animals, as well as for zombies. Due to the lack of grids, animals can be compared absolutely at any point on the map, where there are players and they can appear.
2) Adding player downloads. We have been asked to do this more than once. After all, when the server has more than 48 players, the fps and ping disappear. I think it is possible to correct the primary testing players for chankovye. Add a slider or in Config.json setting for player visibility or disabling them altogether. An example of this is minecraft and GTA.
3) Loading objects and mods into the player's memory, you need to fix this moment somehow, since the longer the player plays on the server, the faster its resources (PC) are clogged and fps drawdowns begin
4) Problem with the build of the camera, it is also possible to add it to Config.json parameters for restrictions on the map (Restrictions will depend on the number of chunks)

Русский текст, возможно кто-то сможет донести мои мысли доходчивее:

Повторное обращение к Нельсону по оптимизации
Извиняюсь за свой перевод, пишу текст с помощью переводчика

Приветствую всех. В первую очередь хочу поблагодарить Нельсона за последние обновления и не малый труд в оптимизации игры.

Пишу вам обращения от нескольких крупных проектов(серверов), хотелось бы упомянуть несколько очень важных проблем:

1) Добавления сеток спавна для животных, так как и у зомби. Из-за отсутствия сеток, животные могут спавнится абсолютно на любой точке карты, там где есть игроки они и могут появляться и продолжить свое бесконтрольное похождение по карте.
2) Добавления прогрузки игроков. Уже не раз просили об этом. Ведь когда на сервере больше 48 игроков, фпс и пинг пропадают. Мне кажется это можно исправить прогрузкой игроков по чанково. Добавить ползунок или же в Config.json настройку на видимость игроков или же вовсе их отключения. Пример тому майнкрафт и гта.
3) Загрузка объектов и модов в память игрока, необходимо исправить как-то этот момент, так как чем дольше играет игрок на сервере, тем быстрее его ресурсы (ПК), забиваются и начинаются просадки фпс
4) Проблема с постройкама, также воозможно добавить в Config.json параметры по ограничению на карту (Ограничения будут зависить от количества чанков)

**Comment by TH3AL3X** [comment]
Hopefully ... I already made a post and nelson do not worry about this topic, since it is a dead game and he is making a new one,Every day I receive messages from hundreds of users complaining of lag, I try my best to change the decay time, etc ... but nothing is always the same, it's a shame, since my server is decreasing in volume of people because of this https://unturned-servers.net/server/217270/

**Comment by SDGNelson** [comment]
1. Can you clarify about "animals can be compared absolutely" please? If I understand correctly it sounds like you are asking for some sort of spatial data structure (e.g. quadtree) for animals.

2. Yes, ideally this will happen after some netcode reworks. It would be tricky to implement as-is because there is no mechanism for RPCs missed when the player does not exist client-side, and the players are tightly coupled with the list of connected clients.

3. Mods are loaded into memory before connecting as you mention, but this would not cause gradually declining fps. It sounds like something may be leaking while playing in that case. This sort of issue is difficult to track down, but if you know a way to replicate or it happens passively while connected I could run in debug mode while idling on the server.

4. Can you clarify this please?

**Comment by DiFFoZ** [comment]
1. Add navmesh for animals like for zombies. Due to missing navmesh animal can spawns everywhere point on the map, where
has players animal can be spawned and continue walks/living on the map.

2. Add distance to seeing players. When on the server more than 48 players FPS is lower and ping is higher. I think it can be fixed with loading players by chunk. Add a slider or add to `Config.json` settings visibility players. For example in games Minecraft or GTA.

3. Loading objects and mods into memory player need to be fixed when as player longer playing on the server then its PC resources are clogged ( memory ) and starting freezes.

4. Problem with buildings also maybe add to `Config.json` settings to restriction buildings on the map ( Restrictions it will depend on numbers of chunks )

**Comment by strongunturned** [comment]
@SDGNelson 1) Animals spawn anywhere, they do not have a point on which they will walk, they appear where there are players, you need to add animals navigation, as well as zombies

2) This would help greatly in optimization

**Comment by strongunturned** [comment]
@SDGNelson также хотелось обратить внимание еще на один критический баг. Карту можно взламывать на сервере и ставить своих НПС, при этом сервер пускает игрока на карту, не говоря о том что он взломал карту и изменил её под себя. Чем критичен этот баг? С помощь этой проблемы, игроки могут ломать экономику сервера, устанавливая ванильных нпс к себе на карту и уже на сервере покупать запрещенные предметы и тд. Необходимо запретить игрока заходить на сервер с измененными НПС, картой и так далее. 

Переводчик: 

I also wanted to pay attention to another critical bug. The map can be hacked on the server and put their own NPCs, while the server lets the player on the map, not to mention that he hacked the map and changed it for himself. What is critical about this bug? With the help of this problem, players can break the economy of the server, installing vanilla NPCs to their map and already on the server to buy prohibited items, and so on. You must prohibit the player from accessing the server with changed NPCs, maps, and so on.

**Comment by strongunturned** [comment]
Прощу обратись на это внимание Нельсон, очень прощу об этом, ведь данные баги убивают сервера и оптимизацию, пожалуйста прислушайтесь к моим словам. С любовью ваш игрок.

Переводчик:

Please pay attention to this, Nelson, please do, because these bugs kill the server and optimization, please listen to my words. With love, your player.

**Comment by DiFFoZ** [comment]
> The map can be hacked on the server and put their own NPCs

Yea, it's can be hacked but server validates if NPC is too far from the server-side ( about 200m ) then server ignores a request.
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/916 also some time ago reports about that

**Comment by strongunturned** [comment]
@SDGNelson https://youtu.be/oF59QLmcR48 демонстрация бага

**Comment by strongunturned** [comment]
@DiFFoZ держи в курсе :)

**Comment by strongunturned** [comment]
Русский текст:

Это все что наболело за последние года, я понимаю что вы заняты новым продуктом, но прощу исправить и эти моменты с оптимизацией и багами мод серверов. Спасибо вам большое, желаю вам успехов и терпения. С любовью к любимой игре и Нельсону *сердечко*

Переводчик: 

This is all that has hurt over the past year, I understand that you are busy with a new product, but I will forgive you to fix these moments with optimization and bugs mod servers.Thank you very much, success and patience. With love to your favorite game and Nelson!

**Comment by DiFFoZ** [comment]
Вот =D @strongunturned 
![image](https://user-images.githubusercontent.com/48765566/87852180-e4f00a00-c929-11ea-978b-2878632b1b0d.png)
![image](https://user-images.githubusercontent.com/48765566/87852185-ef120880-c929-11ea-9c84-f02b646dcb06.png)

**Comment by strongunturned** [comment]
@DiFFoZ Я не про это, посмотри видео, ты все поймешь.

**Comment by SDGNelson** [comment]
Locally clients can see an NPC they placed, but any progress with it will not be accepted by the server. All NPC progress is server authoritative and cannot be cheated by the client.

**Comment by strongunturned** [comment]
@SDGNelson Но как вы видите на видео, мы можем ставить абсолютно любых НПС, и торговать с ними на абсолютно любом сервере, этот баг работает на всех мод картах. Карту можно редактировать и ставить НПС, при этом сервер пускает игрока на сервер с измененной картой и ванильными НПС. 

Перевод:

But as you can see in the video, we can put absolutely any NPCs, and trade with them on absolutely any server, this bug works on all mod maps. The map can be edited and put NPCs, while the server lets the player on the server with the changed map and vanilla NPCs.

**Comment by educatalan02** [comment]
Example: If you manually edit a NPC from Russia Map, and you keep the GUID. Upload it to Workshop and download it. The client will keep the Workshop NPC instead of the Official NPC from the map.
PD: You can arruine the economy of the server with this, since you can put to sell sticks for 5000000 EXP

**Comment by strongunturned** [comment]
@educatalan02 так и есть, необходимо срочно это исправить

**Comment by SDGNelson** [comment]
Ah, sorry, you are correct that the vendor can be opened near server NPCs, but only if the vendor asset exists in the server files as well. It is not possible for clients to change the XP amounts or the vendor items, so it is not really exploitable in the meantime. I will open a private issue to add a server check ensuring the vendor is accessible through the current NPC.

**Comment by strongunturned** [comment]
@SDGNelson спасибо вам большое, также подумайте пожалуйста над оптимизацией прогрузки игроков.

**Comment by SDGNelson** [comment]
Regarding the lag it will be the main goal for 2021: https://blog.smartlydressedgames.com/unturned-in-2021/
