### ISSUE TITLE
[FEATURE REQUEST] Object Language support

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1889]
Objects have support for multiple prefabs for different languages. Sort of like Russian.dat/Portuguese.dat files for Notes/Items/NPCs. Could be used to swap out names of buildings, textures or sounds.
Ex. 
Object_Russian.prefab

**Comment by FlodotelitoKifo** [comment]
this would be a great addition, though how would this work with material palettes?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
