### ISSUE TITLE
launcher weapon projectile timer

### ISSUE THREAD

**Issue by azzaholic** [SmartlyDressedGames/Unturned-3.x-Community#1897]
give a projectile timer for launcher weapons to allow for non-impact style weapons. e.g bouncing grenades, ricochet weapons.

**Comment by Spebby** [comment]
this may have been added? consider closing

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
