### ISSUE TITLE
Make projectile weapons use different projectiles depending on the magazine loaded

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1899]
The title says it, but in case if I should say it again, projectile weapons like launchers should really use different projectile prefabs depending on the magazine used so that different ammo can be fired from them in order to make the launchers fire projectiles with different models & trail effects.

And please make projectiles support different explosion effects. Currently, from my tests months ago, launchers only use the effects it was given from its own .dat file but not from the magazine that is loaded into the gun. And if I remove the explosion effect from the launcher's .dat file but the magazine has it, the gun doesn't fire projectiles.

**Comment by kotyaraaa** [comment]
it would be a cool feature!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
