### ISSUE TITLE
Decay timer for vehicles

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#1900]
Similar to bases, if owner is not online for a while then unlock or destroy

**Comment by Ongjming** [comment]
Found this while searching related text, just wanted to add on something.
For vehicles that are in safezone areas (Like the sea regions around the Liberator/on the Liberator itself), there is currently a setting for the server to define a time limit before it auto unlocks.
However, this does not clear/destroy the vehicle. Whatever vehicle that is there that doesn't sink, yet is non drivable (Like erm a flipped APC), it will be there for quite some time. (I might be wrong about this since that vehicle was there only for around 1 week)

This decay timer could potentially help remove such stuck vehicles automatically from the map :D
