### ISSUE TITLE
[FEATURE REQUEST] Melee Explosion Options

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1902]
- Explosion_Damage <Value>
- Explosion_Damage_Host <Value> 
(Amount of damage the player swinging the weapon takes, to make these weapons viable for PvP, without instantly killing the player using them)
- Explosion_Durability <Value>
- Explosion_Amount <Value> 
(Defaults to infinite, but can be set to a lower value for one time uses)

Would create an explosion per melee swing.

(Split from Mega Request to allow for easier tracking of status)

**Comment by Ankumo** [comment]
For... what? Btw you're able to do that already but with some workarounds

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
