### ISSUE TITLE
[FEATURE REQUEST] Multiple Horde Beacon Drop Tables

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1906]
- Different Drop Tables per Navmesh for Horde Beacon. 

Would incentivize Horde Beacons at more risky locations, as they would give better loot. While easier location gives worse loot.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
