### ISSUE TITLE
[FEATURE REQUEST] Some new modhook ideas

### ISSUE THREAD

**Issue by Lin-Ain** [SmartlyDressedGames/Unturned-3.x-Community#1910]
1st. **Hit Modhook**. When the target is hit by hands/melee/ballistic guns, it can execute some events.
2nd. **Damage colllider Modhook**. When the target enters the object with IsTrigger Collider, it will suffer stable damage per second. Damage can be divided into mutiple kinds (players/zombies/animals/vehicles and more).
3rd. **Spawn modhook**. Which can be active by other modhooks or components. When active, an item or vehicle will spawn. ID should be written in this modhook.
4th. **Follower modhook**. Gameobjects with this modhook will follow the nearest target. Target can be set to players/zombies/vehicles/animals.

**Comment by Alex-Well** [comment]
This will definitely be useful, however Nelson will need to do the client / server sync for some ModHooks to work.
It would also be useful to add the previously proposed Animation EventHook to trigger events on items when the player plays a specific animation. More details here #1697

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
