### ISSUE TITLE
[Feature Request] Option to enable specific hairs with hats

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#1911]
Something like this will enable hairs that modder would consider compatible with their hat

Hairs 3
Hair_0 0
Hair_1 2
Hair_2 10

**Comment by SDGNelson** [comment]
Hmm interesting idea.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
