### ISSUE TITLE
[Feature request] Vehicle Owner and Friends

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1918]
Only vehicle **Owner** and **Friends** can place **stuff** on the vehicle, A lot of people troll putting things on vehicles, and this should work as a claim flag where it doesn't allow you to build on the vehicle because you are not from the same group.

**Comment by GazziFX** [comment]
Can be solved with plugin

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
