### ISSUE TITLE
[FEATURE REQUEST] Ability to blindfold/handcuff player through NPC interaction 

### ISSUE THREAD

**Issue by azzaholic** [SmartlyDressedGames/Unturned-3.x-Community#1924]
Issue for California Bait and switch quest where the player is kidnapped and imprisoned by bandits.

**Comment by Spebby** [comment]
Need to make sure that if player is wearing glasses they don't get deleted, and are instead placed into the inventory. And also need to make sure nothing gets deleted from the inventory if the inventory is full.

**Comment by DrDallas1** [comment]
This could be circumvented with a bit of clever UI work.

**Comment by Spebby** [comment]
While true, this is for curated content.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
