### ISSUE TITLE
Issue with Allow_Per_Character_Saves in Config.json

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#1928]
Hey @SDGNelson I'm not sure if it's been reported yet but all character inventories wipe including the main character that has joined the game when enabling the option.

**Comment by PandahutMiku** [comment]
> Hey @SDGNelson I'm not sure if it's been reported yet but all character inventories wipe including the main character that has joined the game when enabling the option.

We use this on quite a few of our servers with zero issues. Just keep in mind  if you enable it without wiping some players are going to be confused as it's going to force them to one slot regardless of the one they were using before. I would bet cookies that you are having issues with it because of an Avi plugin (I think Avi offers exactly this in plugin form)

Btw, I assume you mean when disabling this option and not when enabling it, right? Otherwise, this is enabled by default.

**Comment by joeymisfit** [comment]
The customer enabled it and it wiped all characters inventory, including the one slot. So they disabled it when they first got the server. I also just double checked the account and they don't have Avi installed.

**Comment by SDGNelson** [comment]
Closing, but feel free to comment and I will re-open. (IIRC the follow up was in email or something and it was fine)
