### ISSUE TITLE
Keep_On_Death suggestion

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#1930]
Should_Drop_On_Death works, but item just vanishes on death and doesn't stay in player's inventory. How about adding another option like `Keep_On_Death` with true/false? Server config allows only configure multiplier of dropped items, but what if I want to make exact items not droppable after death?

**Comment by educatalan02** [comment]
You can use a simple plugin made exactly for that

**Comment by Spebby** [comment]
> You can use a simple plugin made exactly for that

Plugins aren't the answer to everything. Not everyone wants to play with plug-ins, and not every server hoster wants to have plugins installed.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
