### ISSUE TITLE
Small suggestion: making the bayonet melee data usable for all other attachments

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#1937]
Just a small suggestion about making the melee data found in the bayonet item usable for other attachments instead of just the tactical. It's for making something like a bayonet knife attached to an AR barrel, or a wonky magazine bayonet like this.
![image](https://user-images.githubusercontent.com/48363842/90006834-b8ba7580-dcaa-11ea-90ee-7dd145968655.png)

I don't really need anims with this, as long as the melee data can be used on other attachments it should be fine.

**Comment by OneManOperative** [comment]
And also may be an option to not let guns use dexterity's reloading speed perk or use a certain amount of it. I wanna make stronger weapons but at a downside of the dexterity skill not helping them in the reload speed department.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
