### ISSUE TITLE
[Feature request] Add ESP for see lockers, wardrobes, beds behind the walls for admins

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1938]
The admins have a function to see the players behind the walls as if it were an ESP, It would be very helpful to put a function to see behind the walls the lockers, since this would serve to know if it is necessary to destroy a raided base or if it is a floor base.

![image](https://user-images.githubusercontent.com/13141042/90008192-42167b80-dc9c-11ea-950b-af100bcdf461.png)

**Comment by Johnanater** [comment]
This would be a great feature for preventing the accidental removal of floor bases

**Comment by MrPiliadis** [comment]
Yeah that would be great I also had some problems.

**Comment by GazziFX** [comment]
Why not use freecam or make a plugin that spawns visible through walls effect?

**Comment by TH3AL3X** [comment]
> Why not use freecam or make a plugin that spawns visible through walls effect?

Brain dead ?

**Comment by nanashi88** [comment]
at our server we have excluded destroying storage objects from wreck command.
this will minimize damage. but ofc it should be avioded from begining to wreck active base.

we use decay system based on claimed beds. and sice we have started to use this system, admins doesn't need to go around clean the map anymore.
--------------------------------------------------------------

@GazziFX you are confusing me. since you are interested in this game, and contributing by replying here, then:

could you stop ruining this game by your UndeadHacks?!
the previous two moths were so peaceful, and we started to be more creative and focus on other stuff other than running after cheaters.
but now thanks to you, cheaters are back.
don't you think it is enough after all this years?!
does the dirty few bucks you gain from it worth the sadness you cause the other people?!
if keep staying stubborn I am sure you will get a fair payback of the same type in your life, and mark my wards!

**Comment by GazziFX** [comment]
@nanashi88 Im not ruining this game, I made server-sided anticheat and now focused on client-side

**Comment by nanashi88** [comment]
@GazziFX cheats ruin games and ruin fun
and it causes kind of phobia among Unturned community!! 
players were keep reporting cheats , even though cheats were down!! (during previous 2 months)

I don't get the logic from doing cheat and anti-cheat! 
is this the same logic of anti-virus companies that spread viruses?! is money the only logic from behind this?! even if it was dirty money?! or it is to prove self?! you have proved yourself long enugh
 
you said your server side AC doesn't detect all kind of cheats, for example ESP and Silent aim!!
anyway, plz publish your server-side AC source code for free.
also it would be perfect if it contains UndeadHacks users DB ( and keep updating it XD) 

sorry, what is client-side?! client-side AC?! interesting !! but this could end with Battleye ban , isn't it?
but also this not gonna solve issues like ESP .... 

--------------------------------------
Terror sorry for taking this thread out of the main topic.
but I guess you understand my feelings since you have spent huge effort developing DAC

**Comment by GazziFX** [comment]
@nanashi88 I think you talking to the wrong person, Im not doing any hacks, Im just plugin developer.

> also it would be perfect if it contains UndeadHacks users DB

What you wnat to do with this DB if it doesn't contains any SteamID

> client-side AC?! interesting !! but this could end with Battleye ban , isn't it?

It will be used without BE turned on, its for servers with client modules for more possibilities

**Comment by TH3AL3X** [comment]
> at our server we have excluded destroying storage objects from wreck command.
> 
> this will minimize damage. but ofc it should be avioded from begining to wreck active base.
> 
> 
> 
> we use decay system based on claimed beds. and since we have started to use this system, admins doesn't need to go around clean the map anymore. (the advantage of claimed beds over claim falgs that beds get destroyed at raids)
> 
> 
> 
> --------------------------------------------------------------
> 
> 
> 
> @GazziFX you are confusing me. since you are interested in this game, and contributing by replying here, then:
> 
> 
> 
> could you stop ruining this game by your UndeadHacks?!
> 
> the previous two moths were so peaceful, and we started to be more creative and focus on other stuff other than running after cheaters.
> 
> but now thanks to you, cheaters are back.
> 
> don't you think it is enough after all this years?!
> 
> does the dirty few bucks you gain from it worth the sadness you cause the other people?!
> 
> if keep staying stubborn I am sure you will get a fair payback of the same type in your life, and mark my wards!
> 
> 

I have a plugin too for decay and one made by me, it remove all plates and campfire and other stuff every 5 hours, but we still have lag problems, due is x5loot and is easy to do a base

**Comment by nanashi88** [comment]
@TH3AL3X yeah, this decay doesn't solve lag spikes issue. it just to keep the map clean.
lag spikes is due to huge bases. (when there are huge amount of buildables per the new 5 regions that get loaded when crossing from region to another)

----------------------------------------
> I think you talking to the wrong person, Im not doing any hacks, Im just plugin developer.
@GazziFX either you have Schizophrenia or that you feel shame about it, so trying to hide it!!
![image](https://user-images.githubusercontent.com/59157332/94236166-70cb7700-ff15-11ea-8df2-af234402aabb.png)
this screenshot just so others trust me.
but I have more SOLID proofs that you are the same person!!
I am a cheat hunter for long time already, and all the time dealing with solid proofs only. no point in lying!

since you feel shame about developing cheats, then just stop it.  
you have good skills, you will be able to gain clean money from other projects!

**Comment by TH3AL3X** [comment]
> @TH3AL3X yeah, this decay doesn't solve lag spikes issue. it just to keep the map clean.
> 
> lag spikes is due to huge bases. (when there are huge amount of buildables per the new 5 regions that get loaded when crossing from region to another)
> 
> 
> 
> ----------------------------------------
> 
> > I think you talking to the wrong person, Im not doing any hacks, Im just plugin developer.
> 
> 
> 
> @GazziFX either you have Schizophrenia or that you feel shame about it, so trying to hide it!!
> 
> ![image](https://user-images.githubusercontent.com/59157332/94236166-70cb7700-ff15-11ea-8df2-af234402aabb.png)
> 
> this screenshot just so others trust me.
> 
> but I have more SOLID proofs that you are the same person!!
> 
> I am a cheat hunter for long time already, and all the time dealing with solid proofs only. no point in lying!
> 
> 
> 
> since you feel shame about developing cheats, then just stop it.  
> 
> you have good skills, you will be able to gain clean money from other projects!

And then BattlEye doesn't ban those guys, I got banned by no reasons, and now I'm not able to play if I don't pay a spoofer, and need to do everything without BattlEye server...

**Comment by rube200** [comment]
You sus

**Comment by TH3AL3X** [comment]
> You sus

Uh

**Comment by GazziFX** [comment]
> when there are huge amount of buildables per the new 5 regions that get loaded when crossing from region to another

Try to smoother this lags to several frames using coroutine that is call yield return null; (alias for yield return new WaitForEndOfFrame();) per X objects, IDK if its requires client-side changes

**Comment by fahrettinenes** [comment]
If this is done, the wallhack cheats will be made easier.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
