### ISSUE TITLE
Chat Colors

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#194]
A chat line can only have one color at the moment.
I suggest adding a feature which allows multiple colors per chat line.
This can be done with simple HTML,  BBCodes, Unity's own formatting, etc

Example from Minecraft:
![](http://minecraft.mmoaddons.com/img/minecraft-improved-chat-screenshot-1.jpg)

**Comment by N1GHTPATROL** [comment]
I think at this point Nelson would have to re-do the entire chat system, because it's just generally a mess in its current state. I think something like Rust (Also uses Unity of course) does the best job with chat. Colors, even formatting such as bold and different font sizes would be amazing and unlock a lot of features.

![image](https://user-images.githubusercontent.com/7349712/35296470-20d16ff6-004a-11e8-8b8e-65b6ee6345fe.png)

**Comment by SurvivorCDG** [comment]
I think that the chat has long been time to update. It is necessary to add the ability to adjust the count of lines and length of messages.

**Comment by SDGNelson** [comment]
Unity has very nice rich text built-in, however at one point I disabled it for chat messages because players were abusing it e.g. large text, fake admin messages. One option would be to allow it for server -> client chats, as well as a config option to enable rich text for client -> server chats.

**Comment by Trojaner25** [comment]
Thats what I thought.
Players should not be able to use this by default, but maybe with external plugins or config options (e.g. admin can use it but players can not).

**Comment by N1GHTPATROL** [comment]
+1 I would like to see any form of formatting by server end be built into the game.
