### ISSUE TITLE
[New function] Make the mute button for mute X people of the chat

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#1940]
I've been having extreme toxicity problems on my server, and the mute button only works by voice, could it be possible to mute the person in the chat as well?

**Comment by SDGNelson** [comment]
Now that we can have layered UI elements (uGUI only) I am thinking about adding a dropdown to the player mute menu with options to mute text chat and adjust volume gain per-player.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
