### ISSUE TITLE
[QOL] HUD Element for weapon Durability

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1946]
would be very useful for most players, many don't realize a gun is at 0% until hours after it reaches that percentage. Would hopefully help players figure out when they need to repair their weaponry.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
