### ISSUE TITLE
[Feature Request] Specific Seat Modhook

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1958]
So currently we have a VehicleEventHook which works when players interact with driver's seat. It would be nice to see the same feature but for passenger seats too. With it many things would be possible, the first thing that comes to mind is tank commander hatch. So when the player seats at the special seat, intended for tank commander to look around and when he seats there, a hatch also opens.

![main-qimg-13f38d0c2c2f189127912183cb7e848e](https://user-images.githubusercontent.com/59206749/91645238-1d682500-ea4c-11ea-9838-5d8d078f48e2.jpg)

**Comment by SDGNelson** [comment]
Hmm I guess this has been re-requested as #2280. Lots of feature requests to do! For this one in particular I am undecided between per-seat components with events vs expanding the root event hook. Not that it really matters. Will probably do at some point.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
