### ISSUE TITLE
[Linux] Random crashes with huge logs full of errors

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#1961]
For a while my Unturned has been crashing after about 10-30 minutes of gameplay. I checked Player.log and it was spamming errors until it crashed and was 5 million lines long! I tried uninstalling workshop mods, but it still persisted.

It's the same thing being spammed over and over again, here's the end of the log file: https://pastebin.com/bd4M9B0W

Hopefully this can be fixed. :)

**Comment by SDGNelson** [comment]
I got an email similar to this a few weeks back and it turned out to be related to some specific post-processing features. If you disable all post-processing and maybe turn one or two on at a time it should hopefully be stable. The 2018.4 post processing package is behind by a bit, so hopefully this will be sorted out when we update to 2019.4.

**Comment by Johnanater** [comment]
Looks like the spam and crash are caused by turning on Screen Space Reflection, thanks!

**Comment by SDGNelson** [comment]
Glad to hear that you were able to work around it for the moment!
