### ISSUE TITLE
Lifesteal property

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#1969]
when adding this property to a weapon, it'll be able to heal you a percentage of the damage dealt when used in a zombie or player. (i.e. if the lifesteal percentage value of a gun is .15, then 15% of the damage dealt by that weapon would heal the player).

**Comment by rube200** [comment]
this can be easly made using a plugin

**Comment by Spebby** [comment]
> this can be easily made using a plugin

Terrible response, not everyone who makes modded content has a server, and if it's curated content, then plug-ins are a no-go.

**Comment by rube200** [comment]
> > this can be easily made using a plugin
> 
> Terrible response, not everyone who makes modded content has a server, and if it's curated content, then plug-ins are a no-go.

1st is not a 'terrible response'
2nd I don't have a server
3rd U can contribute with free/paid plugins.
4th u never mentioned about curated content

**Comment by Spebby** [comment]
> 4th u never mentioned about curated content

You can usually assume that most people who know about this site are aware that plug-ins exist, if you see this type of request, usually it's for Curated content.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
