### ISSUE TITLE
[Minor] Vehicle Hook Event

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#1976]
It would be nice if we had an event when a skycrane hooks a vehicle with an option to cancel it.

Something like InteractableVehicle.OnVehicleHook(InteractableVehicle caller, InteractableVehicle Target, ref bool ShouldAllow)

Thanks

**Comment by Alex-Well** [comment]
+ Unity Event Hook for Mods!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
