### ISSUE TITLE
[Feature Request] Optional Hook radius for vehicles with magnets

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#1990]
So currently the Hook radius is hardcoded to 3, which isn't enough in any sense. Sure, you can fit 7-8 dirtbikes in it, but when it comes to normal size vehicles like cars or even medium-large like planes, it can only fit one. Can we have one of the following ways to increase it: 1) By increasing the scale of Hook prefab 2) By adding a collider to the Hook prefab, which would be the Hook workspace, instead of a sphere 3) Adding a string like Hook_Radius_Override x to the asset

**Comment by SDGNelson** [comment]
Yeah makes sense, ideally there should be some ability to specify multiple shapes

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
