### ISSUE TITLE
[FEATURE REQUEST] Stereo songs enabling based on quest conditions

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#1992]
If a specific quest had a soundtrack, it'd be nice if the player could gain access to the song after the quest is completed. Prevents soundtrack spoils before the quest is completed, and to reward the player with the ability to listen to the song again. 

Also useful if a specific track (maybe a SOS request?) is only available during a quest

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
