### ISSUE TITLE
Fuel consumption depending on speed

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2039]
Nice thing that now I can change recoil and not only depending on player's pose. How about to add fuel consumption depending on speed option for vehicles? If my vehicle stay and don't move, fuel will be consuming very low. If vehicle accelerate, fuel will be consuming faster. I hope, this is possible to add in future updates maybe?

**Comment by educatalan02** [comment]
Same way it would be really good if we can change max speed for vehicles serverside using plugins

**Comment by TH3AL3X** [comment]
> Same way it would be really good if we can change max speed for vehicles serverside using plugins

aight, the speed thing is a good idea

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
