### ISSUE TITLE
Audio Source only works in 3rd person on items

### ISSUE THREAD

**Issue by Volsuin** [SmartlyDressedGames/Unturned-3.x-Community#204]
Title. 

After testing it out, it seems the Audio Source component only works on items when you are in third person, and the sound plays every time you swap perspectives. Any chance on a fix to get it to also work in first?

**Comment by SDGNelson** [comment]
Sorry, I read this earlier but didn't comment. The first person viewmodel is actually at the origin point (0, 0, 0) to avoid floating point accuracy issues when wandering the far reaches of maps, so you wouldn't be within range of it. Audio sources on items aren't currently a priority feature.

**Comment by Ongjming** [comment]
Sorry to necro this thread, but it is the only topic I found talking about unity's audio source.
I was wondering, since for item modding, almost every item/structure/buildables/etc need to have the audio named "use", probably within its folder; then would it be possible (on the current timeframe since it had been 2 years+) for multiple items to have this audio source component then pointing to that one "Use" audio file?
I am not that good at modding stuff, fumbling as I go along, but I thought it would be a good way to save file size if multiple item that uses the same sound can have just 1 audio clip there instead of multiple copies of it, one in each item folder.

**Comment by SDGNelson** [comment]
@Ongjming: good timing, I have been working on consolidating those audio clips recently. For example barricades have a "PlacementAudioClip" property now and consumeables have a "ConsumeAudioClip" property. Open a separate issue if you have further questions about that however.
