### ISSUE TITLE
Allow projectile weapons to take custom explosions from ammo giving custom explosions

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2044]
In the core game, military fragmentation mags allow ballistic weapons to fire explosive rounds. But it doesn't work if you apply the same data to projectile weapons, which limits the possibilities of making custom explosive ammo for them.

This should really be a feature if it is possible to implement it to Unturned. It would be really helpful to be very creative & make unique ammo like acid or fire rockets & similar ideas.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
