### ISSUE TITLE
Ctrl + F Auto Storage

### ISSUE THREAD

**Issue by aladairmaxwell** [SmartlyDressedGames/Unturned-3.x-Community#2072]
If you press Ctrl + F on storage with item inside, it will auto equip. But why not to do opposite effect, and add ability to press Ctrl + F on empty storage and automatically put item in hands inside the storage?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
