### ISSUE TITLE
Workshop issues

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2078]
Will try to explain by this scenario:

Player subscribes to server-A workshop which contains an item (lets say its gun) with ID-12345. Then, player goes to server-B which uses a workshop mod which contains a barricade with same ID (12345). Priority goes to a subscribed workshop, not the workshop which is used on the server player is connecting to. And because of that, player gets an error "Your files are missing a custom barricade asset (12345) this server is using"

Is it possible for this to be solved somehow? I mean, it might also solve issues where player sees different items/barricades than they actually are. For example, if some server uses tiny barricade and another server uses same id for doors, if player subscribes to that workshop containing tiny barricade, on another server he will see that instead of door which kind of makes it a legit wall hack. Even though, I am sure there is no easy solution for that, but this issue is pretty annoying and it takes a lot of time to explain for average player how to unsubscribe all workshops (because most of them subscribing to everything they can)

**Comment by PandahutMiku** [comment]
I believe this extends to every type of item/workshop that works off IDs, although I can only confirm that is true for dialogues.
Like if you join Server-A with Unturnov 1.0, and then Server-B with Unturnov 1.5, those dialogue IDs are overlapping a bit and will result in seeing the wrong or outdated NPC text. 

I suggested in the past to not load any workshop on game startup, and when you join a server, fully load all its workshops, and fully unload on exit. Only when entering a singleplayer/map editor should it load the client's downloaded workshop. This would help loading speeds and hopefully fix these issues but is probably not as easy as it sounds.

On a related point, if a mod (say, Nordic Armory) updates, the server restarts to update but the client doesn't, the client cannot equip any of the guns until they restart themselves. Figured I would throw this in there since it's a related topic and an annoying re-occurring issue.

**Comment by educatalan02** [comment]
> I believe this extends to every type of item/workshop that works off IDs, although I can only confirm that is true for dialogues.
> Like if you join Server-A with Unturnov 1.0, and then Server-B with Unturnov 1.5, those dialogue IDs are overlapping a bit and will result in seeing the wrong or outdated NPC text.
> 
> I suggested in the past to not load any workshop on game startup, and when you join a server, fully load all its workshops, and fully unload on exit. Only when entering a singleplayer/map editor should it load the client's downloaded workshop. This would help loading speeds and hopefully fix these issues but is probably not as easy as it sounds.

I suggested it too some time ago, because it's annoying for new players.

**Comment by SDGNelson** [comment]
The ideal long term solution would be to completely convert to UUIDs, but that will not happen anytime soon.

In the near term I have been thinking about a workaround like you guys are describing. The game would still load assets the same way, but would group them by source (e.g. workshop file id, local package). Then the ID to asset mapping could be refreshed per-server to ensure only the assets used by the server are considered. In singleplayer and editor it would still have to use everything. This would basically be a change to `Assets.find`, but that code is used in so many places that there is a lot to look over.

**Comment by SDGNelson** [comment]
In good news: this is finally implemented in the next update!
