### ISSUE TITLE
[Feature Request] Addition of tire/wheel HP value

### ISSUE THREAD

**Issue by JackSenaviev** [SmartlyDressedGames/Unturned-3.x-Community#2089]
eg. HP under the "Vehicle" damage subcategory (individual value for tire though, not the same value as the whole vehicle),
basically the same system as with whole vehicle HP/tree/zombie/etc. the system, but put in a child part of the asset this time (tire in this case)

Tire HP set to 500 = 5 hits to destroy from a weapon which deals 100HP per hit to a vehicle

This would potentially be a better alternative than having 1-shot tires which can be currently destroyed with the simplest items like a wooden bat,
this would probably bring a better in-game experience, both vanilla and modding wise.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by JackSenaviev** [comment]
It is okay, man, I do understand. Thank you for the response, nonetheless
