### ISSUE TITLE
askClearEffectByKey

### ISSUE THREAD

**Issue by SingleThreadedWorld** [SmartlyDressedGames/Unturned-3.x-Community#2098]
It would be nice if we had this optional method to clear an effect by the Key of the effect instead of only by the ID of the effect. It would be a great extra tool.

**Comment by SDGNelson** [comment]
Makes sense, however you can achieve the same thing for the meantime by passing an ID of 0. It destroys the effect (if any) associated with the key without spawning a new one.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
