### ISSUE TITLE
Inventory HUD is not scaled properly

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2123]
Before:
![before](https://user-images.githubusercontent.com/31174978/101195122-c7c19b00-3680-11eb-9518-dce2ca87242d.png)
After:
![after](https://user-images.githubusercontent.com/31174978/101195143-ce501280-3680-11eb-82bb-57a8493d8ee0.png)

**Comment by SDGNelson** [comment]
Assuming you are referring to the item header bars: this was an intentional change. I am open to feedback on this if players would prefer it to match the scroll width again.

**Comment by Nox39** [comment]
liked better this new way, smaller resolutions looks smoother.

**Comment by DerpyHoowes** [comment]
![изображение](https://user-images.githubusercontent.com/59206749/101205397-9e077480-367e-11eb-899a-960747318ed6.png)
Chat now becomes gold if you have a gold account (I guess it was intended so and this feature could probably be in the game before the update, but I personally had my chat color same as the one set in options, instead of gold one, and it was far better) yet the cursoir uses color set in options.

Scrolling bars turn white when held, instead of turning green (or any color that you specified in the Interface Background Color setting).
![изображение](https://user-images.githubusercontent.com/59206749/101206632-731e2000-3680-11eb-8481-9ed60fb27067.png)


Speaking of header bars, old ones were better. New header bars leave a huge blank space between inventory and scrolling bar. Even if the scrolling bar will be moved next to the inventory slots (which isn't even possible, as I assume, because there are modded clothing items with way more slots lenght than the header bars length), there will be an annoying blank space between scroller bar and Nearby items iventory. I see absolutely no reason for such a change and agree with BowieD.

Also shading on the FPS counter and map names is very annoying, since all the other text has no shading. Also this shading seems to overlap the letters in some spots
![изображение](https://user-images.githubusercontent.com/59206749/101206276-f68b4180-367f-11eb-8281-003828ac7600.png)

Overall the changes seem really forced and ureasonable, especially the font change. Unturned was totally fine with Arial, the new font looks very bad. This title makes my eyes bleed.

![изображение](https://user-images.githubusercontent.com/59206749/101206497-41a55480-3680-11eb-9cfd-ce12e65e8528.png)

**Comment by iBowie** [comment]
Most certainly that looks straight up bad
![image](https://user-images.githubusercontent.com/31174978/101206793-74a41400-3691-11eb-84de-82a6da56820e.png)

**Comment by SDGNelson** [comment]
After re-investigating there were two reasons for this change in the refactor:
1. In order for scrollwheel input to be handled by the list there needs to be an invisible panel behind the grid empty space, but this blocked the item drop.
2. With IMGUI my scaling logic used the view width, whereas with uGUI the actual content size is used which means wide inventories cannot scroll on wide screens if it uses the scroll view width.

For the .2 patch tomorrow morning I will restore the old alignment. This will prevent the horizontal inventory scrollbar from being used, but that is a rare case. There will be an invisible button to catch the item drops when not clicking on grids.

@DerpyHoowes the chat box was gold before, but I am reconsidering some of the gold elements of the UI in favor of prefs. Now the scrollbar handles use the "foreground" color giving you more control than before. The font change is the IMGUI default vs uGUI default, but I do want to experiment with making it sharper.

**Comment by SDGNelson** [comment]
Best of both worlds should be restored in the next update. #2203
