### ISSUE TITLE
Oxygen is even more harder to see

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#2126]
![image](https://user-images.githubusercontent.com/31174978/101195557-6817bf80-3681-11eb-8aba-c1c76dff2f6e.png)
No shadows and white text over white bar is not visible at all

**Comment by SDGNelson** [comment]
I did experiment with a different shadow or color for it, but felt the existing appearance was better. In my opinion it is not a big deal because you only need to read it when the oxygen is actually decreasing at which point it is easier to read, but I am open to feedback if players want it to be changed.

**Comment by SDGNelson** [comment]
For the patch tomorrow I darkened the bar slightly to make it easier to read
