### ISSUE TITLE
UI for players/structures health/name disappeared

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2135]
On top of that, can't interact with lockers etc.
What I mean: 
![image](https://user-images.githubusercontent.com/14231707/101198433-216b9a80-366c-11eb-83d1-020af76db254.png)

Also, can't open doors. Not sure if its some plugin conflict?

**Comment by baranmod** [comment]
And can't take items from ground

**Comment by baranmod** [comment]
![image](https://user-images.githubusercontent.com/14231707/101198629-6bed1700-366c-11eb-9ed1-72d7b884ae2c.png)

**Comment by SDGNelson** [comment]
Can you send over your Client.log file please? I wonder if something broke with EPluginWidgetFlags.ShowInteractWithEnemy

**Comment by baranmod** [comment]
This spamming in client.log:
```
[2020-12-04 20:02:07] NullReferenceException
[2020-12-04 20:02:07] UnityEngine.Transform.get_parentInternal () (at <f15e66ec8bac455da00fc30eb5e18d09>:0)
UnityEngine.Transform.get_parent () (at <f15e66ec8bac455da00fc30eb5e18d09>:0)
SDG.Unturned.GlazierBase_uGUI.RemoveChild (SDG.Unturned.ISleekElement child) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerUI.hint (UnityEngine.Transform transform, SDG.Unturned.EPlayerMessage message, System.String text, UnityEngine.Color color, System.Object[] objects) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerInteract.Update () (at <9d9d689f237446c29d18b969b9b82c89>:0)
```

**Comment by SDGNelson** [comment]
Thanks for the stack trace, will investigate.

**Comment by kotyk7** [comment]
Can confirm that bug on my modded server.

**Comment by baranmod** [comment]
there is one more exception (related):
```
[2020-12-04 20:08:17] NullReferenceException: Object reference not set to an instance of an object
[2020-12-04 20:08:17] SDG.Unturned.GlazierBase_uGUI.set_isVisible (System.Boolean value) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.SleekWrapper.set_isVisible (System.Boolean value) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerUI.hint (UnityEngine.Transform transform, SDG.Unturned.EPlayerMessage message, System.String text, UnityEngine.Color color, System.Object[] objects) (at <9d9d689f237446c29d18b969b9b82c89>:0)
SDG.Unturned.PlayerInteract.Update () (at <9d9d689f237446c29d18b969b9b82c89>:0)
```

**Comment by TH3AL3X** [comment]
Please Nelson, before doing an update, check if things are ok and if necessary, do a beta version for testing, do not do this anymore because the only thing you get is that the community goes to ruin ...

**Comment by iBowie** [comment]
There WAS a beta

**Comment by TH3AL3X** [comment]
> There WAS a beta

Ye but he need to wait until people report bugs...

**Comment by PandahutMiku** [comment]
This seems to just happen when you load into a server twice (maybe because of loading assets twice, or something?)
I was able to get it to happen repeatedly by just doing that.
Here's my client logs, if they help.
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5644826/Client_Prev.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5644827/Client.log)

**Comment by SDGNelson** [comment]
Fairly confident that the problem here was some global IMGUI state not cleaned up after viewing the player hint that would break after re-joining. Will be fixed in the .1 patch which is now building/uploading

@TH3AL3X it was in beta for over a month. There were quite a few bug reports and feedback, but these issues that did slip through would have been hard to find without more players.

**Comment by SDGNelson** [comment]
Closing because there have been no further reports of this after the .1 patch, but feel free to comment and I will re-open
