### ISSUE TITLE
Admin Edit broken?

### ISSUE THREAD

**Issue by Gsechs** [SmartlyDressedGames/Unturned-3.x-Community#2152]
F6 doesn't seem to be working post update for me. Specifically I can connect select items. Oddly working on some servers but not others. Anyone else experiencing this?

**Comment by SDGNelson** [comment]
Is this on the .1 patch? If you can attach your Client.log the next time after it doesn't work I can take a look

**Comment by Gsechs** [comment]
Yes, on the .1

Will do.

**Comment by LuisDavid1198** [comment]
i have the same problem f6 dont work in my server

**Comment by Matias2Lo2Faro** [comment]
I have the same problem the admin editor isn't working at my server

**Comment by Leandrozz** [comment]
The admin editor is not actually working uhm, it would be a really nice and gentle action if u decide to fix your game Nelson.

**Comment by SDGNelson** [comment]
Again, if anyone can attach a Client.log file when it does not work then I will take a look. When I tested in .0, .1, and .2 patches it worked fine in singleplayer and multiplayer.

**Comment by LuisDavid1198** [comment]
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/5647879/Client.log)

**Comment by LuisDavid1198** [comment]
The F6 stopped working after the fisrt update on my server, but if i use the same mods on singleplayer it works completely fine

**Comment by SDGNelson** [comment]
Thanks for attaching the log LuisDavid1198! Interestingly there do not appear to be errors related to the admin editor.

Since there are no errors we will have to narrow down manually. In order to clarify:

What is the exact issue? e.g. Are you unable to select items? Do they not move?

Does it happen only with specific items? e.g. A specific mod pack? If so I can install the mod pack to try and reproduce it.

**Comment by LuisDavid1198** [comment]
https://pastebin.com/KUanvQ9e

Im unable to select items at all
Here are the list of mods

**Comment by LuisDavid1198** [comment]
On my server (with the modpack) the admin editor doesn't work but on singleplayer it works completely fine,

**Comment by SDGNelson** [comment]
Woah, that is a huge list of mods. In that case could you temporarily give my account (steamid 76561198036822957) admin please, and send the server IP:port? If so, I will connect in debug mode and see if I can reproduce it on your server.

**Comment by LuisDavid1198** [comment]
okey
195.206.165.251:27015
Password: 119822

**Comment by SDGNelson** [comment]
Thank you! The problem (at least in your case) is effect asset 65091 which I believe is a money HUD. This thing: https://i.imgur.com/ZfqnKkF.png
It's actually a fullscreen image of a small box, rather than a small box. There's literally this 1920x1080 sprite blocking input: https://i.imgur.com/i7SaVKR.png

The plugin creator should replace the fullscreen image with a box that represents the actual size, or disable it from blocking input.

**Comment by LuisDavid1198** [comment]
thanks for all

**Comment by SDGNelson** [comment]
Feel free to comment and I will re-open.
