### ISSUE TITLE
Sudden disconnect 

### ISSUE THREAD

**Issue by Nox39** [SmartlyDressedGames/Unturned-3.x-Community#2201]
Since the last update many people are getting dced from my servers and my friends servers as well, errors vary between battle eye(wich two days ago gave me the first bluescreen-forcedshutdown when i tried to close the game),lost connection, missing connection.
At first i tought it was some kids ddos'ing the server and then i tried to swap the VPS provider. After that i build a brand new server and asked my friend to connect ( a new VPS provider, new ip ports, brandnew vanilla server straight from steamcmd.download) and just 1min after my friend connected he got DCed again, and then i tried to call the rest of my server, in wich some people played normal and some got kicked/dced from time to time (many times two got dced/kicked together). Mind that all the test were made privately so no ddoser could know we were testing.
Idk if it is a reccuring error but i could notice it more often after these last updates.

**Comment by Johnanater** [comment]
I have also received reports of players disconnecting with BattlEye messages.

**Comment by PandahutMiku** [comment]
A few days ago there were a number of players complaining about Battleye: Query timeout kicks, but I assumed it was just a service issue with Battleye itself. Would be helpful if you included the client.log(s)/server logs and/or exact kick reasons

**Comment by PandahutMiku** [comment]
I've got a few of the Query timeout kicks since then, I think it's something to do with battleye itself.
https://forums.funcom.com/t/kicked-by-battleye-query-port/150117/29
One of the devs in that thread for Conan exiles said
`We’re aware of this. It seems there’s been a change in the BattlEye master server IP in the last 24h.
We’re looking into how to resolve this issue.`
9 Days ago, and that thread became very inactive after that. Odd.

```[2020-12-10 23:00:46] BattlEye client message: Server computed GUID: 197a19fb6940c7bc41ce7b145dca4532
[2020-12-10 23:04:14] Kicked from server. Reason: 'BattlEye: Query Timeout'
[2020-12-10 23:04:14] Shutting down BattlEye client
[2020-12-10 23:04:14] BattlEye client shutdown result: True
[2020-12-10 23:04:14] Client disconnect from 500104403 result: True
[2020-12-10 23:04:14] Cancelled auth ticket
[2020-12-10 23:04:14] Returning to main menu
[2020-12-10 23:04:14] Disconnected
[2020-12-10 23:04:19] Refreshing Steam inventory
[2020-12-10 23:04:19] Applying graphics settings (loaded menu)
[2020-12-10 23:04:19] Applied graphics settings
[2020-12-10 23:04:19] Featured Workshop 1186318457 [10/20/2020 12:12:01 AM, 11/1/2020 11:59:59 PM]
[2020-12-10 23:04:20] You were kicked from this server because: BattlEye: Query Timeout`

**Comment by joeymisfit** [comment]
I've noticed this as well, when it happens there's usually about 10 or so players that get kicked with the same error each time. A quick fix for this is to use _-NetTransport=SteamNetworking_ until it gets figured out, as it's ruining the play experience on the game for players and streamers alike, not to mention for us server owners, we lose money in the long run due to issues like this.

**Comment by PandahutMiku** [comment]
> I've noticed this as well, when it happens there's usually about 10 or so players that get kicked with the same error each time. A quick fix for this is to use _-NetTransport=SteamNetworking_ until it gets figured out, as it's ruining the play experience on the game for players and streamers alike, not to mention for us server owners, we lose money in the long run due to issues like this.

Interesting, I've never seen kick waves like that. Just happens to once unlikely noob once every so often. I would imagine based on the error details that switching back to old networking would not fix this, maybe placebo?

**Comment by joeymisfit** [comment]
No idea, but it can get a wee-bit frustrating at times. 😋 This forum post also references [Issue 2205 - You have lost your place in queue.](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2205)

**Comment by SDGNelson** [comment]
Sorry for my delay. This passed under my radar while resolving all the UI stuff. I will ask BattlEye about this today.

This would be unrelated to #2205, and I agree with Miku that changing to old networking is almost certainly placebo.

**Comment by SDGNelson** [comment]
BattlEye replied that there was a misconfiguration when they moved servers, but that it should be resolved by now.

If anyone is still seeing the Query Timeout kick let me know and I will notify them.

**Comment by joeymisfit** [comment]
> Sorry for my delay. This passed under my radar while resolving all the UI stuff. I will ask BattlEye about this today.
> 
> 
> 
> This would be unrelated to #2205, and I agree with Miku that changing to old networking is almost certainly placebo.

That's interesting, since I also help with a hosting company for unturned, we use tcadmin and the dsa, some customers that don't have the startup argument added have complained about not being able to join their servers due to a lost place in queue or the usual authentication error. I had tested the theory on a new node I had purchased by running an unturned server without the argument and it threw the authentication error, once I added it and restarted, people were able to join. As for the battleye query timeout, that seems to go away after using the startup argument which is odd, since you said it's placebo.

**Comment by PandahutMiku** [comment]
> BattlEye replied that there was a misconfiguration when they moved servers, but that it should be resolved by now.
> 
> If anyone is still seeing the Query Timeout kick let me know and I will notify them.

Thanks for your quick response on this, can you clarify what you mean by "Resolved by now"?

The last time I had the issue myself was only yesterday

`[2020-12-10 23:04:14] Kicked from server. Reason: 'BattlEye: Query Timeout'
[2020-12-10 23:04:14] Shutting down BattlEye client
[2020-12-10 23:04:14] BattlEye client shutdown result: True
[2020-12-10 23:04:14] Client disconnect from 500104403 result: True
[2020-12-10 23:04:14] Cancelled auth ticket
[2020-12-10 23:04:14] Returning to main menu
[2020-12-10 23:04:14] Disconnected
[2020-12-10 23:04:19] Refreshing Steam inventory
[2020-12-10 23:04:19] Applying graphics settings (loaded menu)
[2020-12-10 23:04:19] Applied graphics settings
[2020-12-10 23:04:19] Featured Workshop 1186318457 [10/20/2020 12:12:01 AM, 11/1/2020 11:59:59 PM]
[2020-12-10 23:04:20] You were kicked from this server because: BattlEye: Query Timeout``

I can see it happening today as well

`[2020-12-11 12:35:24] BattlEye Kick 76561198147364305 Reason: Query Timeout`


Is Query Timeout referring to the client failing to connect to the master server, or the client failing to connect to the actual server's battleye module?

**Comment by SDGNelson** [comment]
@PandahutMiku his exact wording was:

>  It seems there was a misconfiguration after we moved servers, this should be resolved now.

Unsure about timezone - was that kick last night, or after my earlier comment? I believe the timeout is the client and/or gameserver timing out while connecting to the BattlEye master server, not the connection between the client and gameserver.

@joeymisfit It is odd that the Steam authentication is being slow to respond. Maybe too many people playing Cyberpunk! I am extremely confident that changing the networking is placebo based on the log in the other thread. For the next update I will add some separate messages for the different types of queue timeout to clarify this, and see about adding separate timeout durations for the different backend services (Steam auth, Steam econ, Steam groups).

**Comment by PandahutMiku** [comment]
> @PandahutMiku his exact wording was:
> 
> > It seems there was a misconfiguration after we moved servers, this should be resolved now.
> 
> Unsure about timezone - was that kick last night, or after my earlier comment? I believe the timeout is the client and/or gameserver timing out while connecting to the BattlEye master server, not the connection between the client and gameserver.
> 
> @joeymisfit It is odd that the Steam authentication is being slow to respond. Maybe too many people playing Cyberpunk! I am extremely confident that changing the networking is placebo based on the log in the other thread. For the next update I will add some separate messages for the different types of queue timeout to clarify this, and see about adding separate timeout durations for the different backend services (Steam auth, Steam econ, Steam groups).

The kick time was in UTC, i.e about 7 hours ago, before your comment. So far, no other query timeouts after the update, even on a server with 40 players on it. Hopefully, it's fixed then. I Will update if it happens again.

**Comment by Nox39** [comment]
> > @PandahutMiku his exact wording was:
> > > It seems there was a misconfiguration after we moved servers, this should be resolved now.
> > 
> > 
> > Unsure about timezone - was that kick last night, or after my earlier comment? I believe the timeout is the client and/or gameserver timing out while connecting to the BattlEye master server, not the connection between the client and gameserver.
> > @joeymisfit It is odd that the Steam authentication is being slow to respond. Maybe too many people playing Cyberpunk! I am extremely confident that changing the networking is placebo based on the log in the other thread. For the next update I will add some separate messages for the different types of queue timeout to clarify this, and see about adding separate timeout durations for the different backend services (Steam auth, Steam econ, Steam groups).
> 
> The kick time was in UTC, i.e about 7 hours ago, before your comment. So far, no other query timeouts after the update, even on a server with 40 players on it. Hopefully, it's fixed then. I Will update if it happens again.

Same on all my servers, no one complaining about timeouts.

**Comment by SDGNelson** [comment]
Great! :)
