### ISSUE TITLE
Cant leave game

### ISSUE THREAD

**Issue by Tairiku-Ookami** [SmartlyDressedGames/Unturned-3.x-Community#2223]
![image](https://user-images.githubusercontent.com/75531507/102014223-8ed99400-3d1a-11eb-8f63-74b4b2098cc3.png)
Button is greyed out

**Comment by SDGNelson** [comment]
Lol! Thanks for the report. The button enabled/disables must not be getting reset properly when leaving the pool

**Comment by SDGNelson** [comment]
The enabled/disabled was being reset properly from the pool, so something in the UI was still using the button after it was released. Hopefully it has been fixed, but I have added a bunch of logging to catch any remaining cases of this. Closing because it is the same underlying problem as the other issue.
