### ISSUE TITLE
Battery_ID Feature

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2239]
Similar to the Tire_ID feature which identifies a specific tire to be used with a vehicle, but instead Battery_ID to to allow for special vehicle batteries to be selected and block usage of the vanilla vehicle battery.

**Comment by iBowie** [comment]
If Nelson won't add this - you can use my plugin that is called "BowieD.Unturned.AssetExpander". You can find it in my repos.

**Comment by SDGNelson** [comment]
Makes sense to add, but no ETA.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
