### ISSUE TITLE
OpErAtIoN HeAlTh

### ISSUE THREAD

**Issue by SuccNelson** [SmartlyDressedGames/Unturned-3.x-Community#227]
Dear Nelson,

As the title says, maybe you should start an OPERATION HEALTH on Unturned, where you just focus on improving the game experience and actually allowing it to live more over the years. I understand that you may be busy with 4.0, but if you are going to kill yet another Unturned version, you should simply just delete it entirely instead of leaving it around for people to use and complain.

Anyways, the OPERATION HEALTH for Unturned hopefully would last 3 months (unless you somehow fix everything in 3 weeks), where you would focus on the following:

- Improving RAM/CPU usage for both client and server.
- Optimise code, make Steam-Calls more reliable, use [Obsolete] attribute instead of replacing an entire method or property.
- Fix bugs posted by the community that are well known, even if the solution is ugly (unless you have time to figure out a clean way)
- Be more active and open to the community. Basically: JOIN your own community.
- Don't make anything new until you are done fixing every main and dangerous bug to the game's health (This is very crucial, because if you keep adding new stuff, you keep adding bugs, which kicks the HEALTH status of the game back and triggers people).
- Make releases first testable by a group of trusted people or in the other upload thing with steam, don't upload directly and then do a hot-fix because you forgot something, this is annoying to basically everyone. (Specially since you can't test on everything and you don't have time for that with your 1 week schedule, which brings me to the next point)
- Reduce update frequency to every 2 weeks or monthly, an update every week is too demanding for work, specially if you also have side projects like 4.0 or university stuff.

To resume:
Just fix the game, and manage the time for it better. At this rate, the game is being considered dying, which in a way is true, since every update, mostly everyone just knows there's a bug you've made and didn't notice, and they hunt it down as soon as they can, and they always find it.

Regards,
SUCC

**Comment by ChubbyQuokka** [comment]
Despite the joke-like name of the title, I do believe he/she brings up many great points.

**Comment by Trojaner25** [comment]
>Make releases first testable by a group of trusted people or in the other upload thing with steam, don't upload directly and then do a hot-fix because you forgot something, this is annoying to basically everyone. (Specially since you can't test on everything and you don't have time for that with your 1 week schedule, which brings me to the next point)

He does this already.

**Comment by SuccNelson** [comment]
> > Make releases first testable by a group of trusted people or in the other upload thing with steam, don't upload directly and then do a hot-fix because you forgot something, this is annoying to basically everyone. (Specially since you can't test on everything and you don't have time for that with your 1 week schedule, which brings me to the next point)
>
> He does this already since some weeks.
>
> > Improving RAM/CPU usage for both client and server.
>
> He said that he won't make this, since it is not worth it for Unturned 3.

Oh rip, well, he could still do the rest of things... or if he doesn't... well I don't know then if he doesn't... Since I bet it's already been considered to make the game open source or all other things, but I've seen the community module and I think that could be a good way to improve the game, but it should be done fast or mainstream somehow... But hey, thanks for the reply and info Trojaner.

**Comment by Trojaner25** [comment]
I agree on all points by the way, but I do not have any hope regarding any changes.

**Comment by fr34kyn01535** [comment]
Both, making cpu and memory usage better and 'code optimisation' are things that won't happen because they don't render an issue. Beside the fact that code optimisation is a bogus wish (like what do you want to have it optimised it for) memory usage is tied to the use of assets and cpu of code architecture. Unturned 3s internals will not really change as Nelson is aiming for the improved version Unturned 4, where all concerns people had in 3 flow in and make it better. You can't expect Nelson to make methods obsolete because there is no officials modding, and no need for it.

I personally agree with having a public pre release instead of testing new releases by throwing them on the publicity but I am sure we see this for Unturned 4.

Unturned 3 is obviously not Nelsons focus right now but game breaking bugs (which should rarely occur with the amount of feature added) are fixed as soon as they are appearing on our radar. The best you can do here is to report them properly in a well documented and repeatable manner.

Regarding your nickname and the title of this issue I should have closed the issue immediately, please move this discussions to the forum next time and make sure to choose a proper nickname there.
