### ISSUE TITLE
[QUESTION] Mass replace assets on a map?

### ISSUE THREAD

**Issue by FalkenJr** [SmartlyDressedGames/Unturned-3.x-Community#2275]
IE: replacing a concerning amount of Russia boulders with a custom boulder asset without having to manually Ctrl+B and Ctrl+N for several months straight

**Comment by SDGNelson** [comment]
Fair request. I think did something similar when working on Germany as a temporary hack, so I will make a note to do something along these lines soon™

**Comment by SDGNelson** [comment]
This has been partially added for tomorrow's update. You can create a "EditorAssetRedirectors.txt" file in the game folder. Lines starting with # or // are treated as comments, otherwise lines should contain two GUIDs separated by ->

For example as a little test I replaced the fire station with a factory on PEI:
fbc6a34ebb67439c967d924bbe0486d1 -> aacff43cfe73463ea55cbbd8e8fede45
