### ISSUE TITLE
Clothing Degradation Control

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2288]
When creating something like Power Armor any amount of protection is almost irrelevant because it very quickly drops to small amounts of protection at the same rate as things many times less protective. Two things that would solve this issue in the most straightforward way would be something like

Degrade_Rate n (Defaults to 1, n representing multiplier on the rate of armor decay)

or

Armor_Minimum n (Defaults to 0, n representing level of protection at 0%)

I think features like these are definitely something that unturned would greatly benefit from, and would allow for more bulky, high value clothing to be introduced in a balanced way without forcing the player to constantly be repairing to keep the armor anywhere close to max protection.

**Comment by SDGNelson** [comment]
Fair point, there should be some an to control that. No ETA though

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
