### ISSUE TITLE
[Feature Request] Secondary turret for vehicles

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2298]
We already have turrets for drivers and passangers of the vehicles, and require the gun item to work. So, as I assume, it just makes the player equip the gun item when seating in a specific seat. And so why cant we have secondary and primary turrets? Just 2 guns for two item slots when using vehicle turret. Switching between them would be done by pressing 1 and 2 keys (or any other keys that player specified in the control settings). I dont think its something that cant be done, and it would really improve the combat vehicles in the game, for example allowing planes to not only have the machinegun weaponry, but also bombs or rockets.

**Comment by clbt404** [comment]
That would be super cool.

**Comment by SDGNelson** [comment]
You are correct that it works by equipping an invisible gun item. Unfortunately it is a bit hacked-together, so multiple weapons per seat would require a fair bit of work to clean up. Ideally could be added at some point, but not a priority.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
