### ISSUE TITLE
[Feature Request] Armor_Bypass

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2306]
A line of code specified in a gun or magazine such as [Armor_Bypass True/False] that ignores armor value when dealing damage to an enemy. Defaults to false.

Possibly also a line such as [Can_Be_Bypassed True/False] to clothing that denotes what can or cannot be bypassed with a gun possessing armor bypass capabilities. Defaults to false.

**Comment by SDGNelson** [comment]
I feel like this is a tricky issue because then someone else will ask for a weapon setting that bypasses the per-armor can_be_bypassed setting, so on and so forth. Similar armor balancing problem to sort out in 4. Could simply have armor tiers, but ideally mods can insert armor/damage into the armor tier stack.

**Comment by Dumfoozler** [comment]
I suppose, maybe a setting where it can be 
Has_Bypass _True/False_
Bypass_Level _n_

Can_Be_Bypassed _True/False_
Bypass_Level _n_

Reason I in particular want it is to implement Fallout's intended counters to power armor, such as an electrical gun that deals roughly equal damage to Power Armor and Unarmored.

**Comment by Ongjming** [comment]
One application this could have could be for the blowtorch repairing vehicles for vehicle set with 0 multiplier armor. Currently 0 armor vehicles could not take damage but it also could not receive repairs from the blow torch.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
