### ISSUE TITLE
Unturned is messed up, please do something about it.

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#233]
I don't care what it takes. 

Unturned's player base is dropping off really fast, and if 4.0 isn't released any time soon then it's going to die miserably. I'm only making this post because of something that pissed me off far more than all my other reasons. This:

![unturnedram](https://user-images.githubusercontent.com/7349712/37125902-85895f12-223c-11e8-8dbb-fc2c95ac738e.PNG)
![gtaram](https://user-images.githubusercontent.com/7349712/37125904-87e67c0e-223c-11e8-95c8-6050086abae9.PNG)

Unturned literally used twice the RAM as GTA 5 fully modded with Redux and other post-processing mods. And gets better frames, too. There's a major problem here, and I'm not even going to get into how the steam overlay is broken. I'm starting to think less and less that it is battleye because it works on some systems, me included. Makes me think there's something that can be done to fix it, that you're too lazy to go and figure out.

I don't care if you have to fix 3.0 or just release 4.0 sooner, I really don't. I'll be honest here, monthly devblogs of a game we can't even play isn't going to be enough for me or 95% of the population. I want to stop hearing from literally everyone how they can't run one of the most basic "popular" games on steam. Just look at the charts, then do some math. http://steamcharts.com/app/304930#6m

**Comment by MoltonMontro** [comment]
The data provided by SteamCharts follows trends consistent with other games, particularly in the same sandbox-y survival genre.

Part of the reason 4 exists is because of the reason you're making this post. Many optimizations that would've been liked for Unturned 3 are not possible without rewriting the core infrastructure.

4 is currently in the progress of trying to get a basic "beta" of sorts out. Nelson is working on 4 everyday, trying to finish polishing out relevant features/sub-features, fix bugs, and further optimize the game.

Although Nelson has not been working on Unturned 3 much himself lately (with some exceptions), there are several curated and timed curated projects in the work. It should be relatively safe to expect stuff coming from 4 _and_ Unturned 3 in the coming weeks as Nelson tidies up 4 for an early preview, and one of the curated map teams tidies up for their notable Unturned update.

Personally, with the above in mind, I am not as concerned.

**Comment by SDGNelson** [comment]
My guess is that you have a lot of workshop content installed. I loaded up Russia which used approximately 1GB of RAM: https://i.imgur.com/6LX79wB.jpg

Unfortunately one of the core decisions made early in 3's development was to preload all of the game's content which results in that high RAM usage which lots of modded content installed. Preloading has its pros and cons, but this is a definite con, and is one of the areas I'm aiming for big improvements with in 4 by streaming as much in/out as possible.

BattlEye sent over a progress update a day ago saying that they're close to fixing it, but that it's tricky to allow the Steam overlay without introducing other security issues. I'm not sure if it's still the case but last I checked Unturned is the only non-native game using BattlEye so it's a bit of a special case.
