### ISSUE TITLE
Modding idea to allow magazines to only damage invulnerable vehicles (optionally buildables)

### ISSUE THREAD

**Issue by LawToTheSap** [SmartlyDressedGames/Unturned-3.x-Community#2333]
I like to see this feature in the future wherein a magazine with a corresponding invulnerable ID can give ammunition to damage invulnerable vehicles with a matching invulnerable ID. It would be cool to see certain guns have special ammo to damage special vehicles like Grizzly AP ammo to damage an attack heli or a rocket launcher with those long rockets to damage a tank. Maybe buildables too, but I want it for the vehicles first :)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
