### ISSUE TITLE
Auto reconnect on shutdown

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#2335]
This is a rather small QoL enhancement request. 

When a server shutdowns, the game should try to auto reconnect automatically. Alternatively a "Reconnect" button would work as well.

Use cases:
Servers often need to restart and lose many players when that happens. It would also make it easier for the players to quickly reconnect instead of having to search for the server again.

**Comment by WCPistolPete** [comment]
We have "Confirm" when the player gets disconnected. "Reconnect" next to it would be awesome.

**Comment by SDGNelson** [comment]
Good point. Until the server finishes restarting they would get the "retrying #" message, but there could be a different message for that case. Maybe shutdown should have an option to enable/disable the reconnect button.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
