### ISSUE TITLE
Low-Ram players

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2350]
As of the past few weeks, around ~3 players have reported that they can no longer play unturned due to crashing on loading skin assets. All of these people had 4gb of ram and said it worked fine in the past and deleting the core.masterbundle (lol) actually let their game load, albeit in a pretty broken state without any cosmetic textures/etc.  I'm not sure what you could do specifically, but maybe adding back -AggressiveGC command-line tool would be helpful, at least something we could try to suggest to these people. If I recall correctly, you added it to try to help someone with 2gb of ram join, and it didn't fix their case, but it might help these. All these people reported in the past they could play Unturned 3.0 fine, but not now.

(To note as well, tried the suggestion of deleting workshop folder, and the only thing in their logs was just [Loading core.master bundle async](https://i.imgur.com/8g5hOh6.png), no errors or anything).

**Comment by SDGNelson** [comment]
Uh oh... this coming week I will see about a bandaid fix by looking for any assets that can be removed from the core asset bundle.

The -AggressiveGC option is still available and might be worth a try, but I am not too hopeful. It was added because of a Unity forum post suggesting that some texture creation errors during asset loading with low RAM could be mitigated by forcing garbage collection frequently.

Later this year it (should?) help once the barricade/structure assets can be async loaded on demand rather than at startup, but that is at least several months away. Unfortunately I do not think there is anything else that is an easy candidate for async loading for a quick fix.

**Comment by SDGNelson** [comment]
Yesterday I put together a simple tool to find assets with the same hash in the asset bundles, and have prioritized a list of files to gradually work on consolidating to save memory. This cannot easily be done in bulk because most of the game asset types load assets by relative path, so over the coming months I will gradually add support for loading assets by path within the bundle - i.e. currently I intend to do a little bit of work on this each week.
