### ISSUE TITLE
Teleport back glitch

### ISSUE THREAD

**Issue by Openrome** [SmartlyDressedGames/Unturned-3.x-Community#2352]
So to do this you need a car and to die. So have you car infront of you so you can hop in then as you hit 0 hp like you can easily do with bleed, hunger, thirst, zombie damage. You press your key to get in your car and die at the same time. So when you hit button to hop out of a car  it will spawn you underneath the car location and you will underneath the map. 

( hey nelson when will you fix the accidentally punch glitch when you go into your inventory or out and you click on something at the same time?)

**Comment by SDGNelson** [comment]
Hmm... I am skeptical because all of the related code (entering vehicle, exiting vehicle, kicking player out of vehicle upon death) test whether the player is dead or not, and I was unable to reproduce what you described. And is it respawning you under the map, or does it respawn you properly back at a spawn point?

Regarding the punch after exiting inventory: are you using the old IMGUI option? If there are steps to reproduce it with the newer uGUI inventory then I will definitely fix it.

**Comment by Openrome** [comment]
I will try to get a video of me doing it and okay

**Comment by SDGNelson** [comment]
It looks like this might be a singleplayer-only issue, but I will check into it. L1ght sent in this video: https://www.youtube.com/watch?v=j5Gaj-LZ6I4

**Comment by SDGNelson** [comment]
Sorry for my original skepticism. I _think_ this is probably fixed for tomorrow's update, but whether I missed a nuance remains to be seen.

**Comment by Openrome** [comment]
It can happen on multiplayer but when it happened to me i was on a  pure vanilla sever
