### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Cubody** [SmartlyDressedGames/Unturned-3.x-Community#2366]
Now it's possible to make your own HUD and disable vanila one - it's good. But is it possible for you, Nelson, to make same possibility for chat and checking enter and escape keys? This will make it possible to create own chat system.

**Comment by SDGNelson** [comment]
What would your custom chat do differently?

**Comment by Greenorine** [comment]
Anither look and more chars possible.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
