### ISSUE TITLE
More user-friendly error messages

### ISSUE THREAD

**Issue by D-AIRY** [SmartlyDressedGames/Unturned-3.x-Community#237]
It needs to add more useful information when an exception occurs. For example, the file name and line number with parse error.

**Comment by Trojaner25** [comment]
mono does not support this.

**Comment by D-AIRY** [comment]
The code should know which file currently used, if exception happens - possible to print that filename to console.

**Comment by Trojaner25** [comment]
Which files do you mean? Source code files or files like .dat?

**Comment by D-AIRY** [comment]
The second

**Comment by Trojaner25** [comment]
Nevermind in that case.

**Comment by SDGNelson** [comment]
The .dats work by building a dictionary of string to string pairs, which makes it tricky to do error checking for the assets because there's not really any structure beyond e.g. "does the .dat contain an ID?" It's definitely a problem, however, and I've learned from it for 4: manual file editing is bad ux and won't be a thing, and all of the asset classes have an overriden method to check for mis-configurations with some easy macros like ASSET_CHECK_SOFT_PTR_MEMBER(MyMesh).
