### ISSUE TITLE
I cant join any server please help

### ISSUE THREAD

**Issue by reduxtr** [SmartlyDressedGames/Unturned-3.x-Community#2370]
so something just deleted my unturned and i just installed it again and joined a server but it keep kicks me from the server and saying "Your files are missing a custom barricade asset (47269) this server is using." please help me to fix this

**Comment by SDGNelson** [comment]
There is a workaround planned to prevent this from happening in the next few months, but in the meantime the reason is that subscribed workshop files are conflicting with the server's workshop files. If you unsubscribe from your workshop files and then join the server it will have the same set of files.
