### ISSUE TITLE
[Feature Request] Disable zombie spawning

### ISSUE THREAD

**Issue by muertoof** [SmartlyDressedGames/Unturned-3.x-Community#2377]
It would be nice if the current Unturned API provided the ability to disable zombie spawning in certain navigation. Also, it would be great if the ZombieRegion passed any parameters of the position, center for example. If it is possible of course

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
