### ISSUE TITLE
[Feature Request] Single Bullet Reloading

### ISSUE THREAD

**Issue by NSTM9** [SmartlyDressedGames/Unturned-3.x-Community#2390]
Like back in 2.0, where shotguns and such were reloaded one shell at a time - could be a line that allows for that (i.e. Use_Single_Reload), which could also be implemented for some bolt action rifles. May require looking into the spaghetti for magazines though.

or as danaby puts it
![image](https://user-images.githubusercontent.com/33303448/107131737-07c61980-688e-11eb-893f-f2fbf832ac88.png)

**Comment by SDGNelson** [comment]
Yeah, I agree it would be nice to have again.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
