### ISSUE TITLE
Workshop Upload Progress

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2391]
Could you please add some kind of loading bar or indication of upload progress for workshop items? Because currently when you upload a mod all of the info fields just empty and the screen just sits like for like 5-10 minutes or whenever the mod is uploaded. It would be nice to see the progress or at least one of those spinning circle things so people know its at least working.
![image](https://user-images.githubusercontent.com/75531507/107131884-39e07700-68a0-11eb-879d-0d1fe8d75eb3.png)

**Comment by SDGNelson** [comment]
I agree it would be nice to have. The workshop upload menu sucks in general right now.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
