### ISSUE TITLE
Requesting destructible objects to support NPC rewards

### ISSUE THREAD

**Issue by MrGoBi** [SmartlyDressedGames/Unturned-3.x-Community#2393]
![11111111111](https://user-images.githubusercontent.com/46658857/107160444-ebfe6880-699e-11eb-9afe-b7023edffc14.png)

I need the object to no longer be displayed after the player destroys it.
It's just that if you use a "take" interaction, for example, it will work:
![222222222](https://user-images.githubusercontent.com/46658857/107160530-73e47280-699f-11eb-9657-1e14132d966a.png)

**Comment by SDGNelson** [comment]
Interesting idea. It was not designed that way, but it could make sense. Complicated by the fact destruction may involve multiple players or no players.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
