### ISSUE TITLE
Requesting safezone generator to prevent object respawns

### ISSUE THREAD

**Issue by Real-DJ-Lucky** [SmartlyDressedGames/Unturned-3.x-Community#2411]
Is it possible for you to make the safezone generator also prevent the spawning of map destructibles such as the broken glass bits or random books?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
