### ISSUE TITLE
Typing Bug

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2417]
Here is the step typing bug happens. Not sure this only happens to Korean.
1. Type English or Korean on sign or chat
2. Ctrl+A to select all text
3. While all texts are highlighted(selected), type Korean(if Enlgish was typed in step 1, change to Korean) straight in
4. After this, typing in both language doesn't work
Only way to solve was reconnect server or single player. I have tested with few players and all of the player reported same issues

**Comment by SDGNelson** [comment]
Unfortunately this would be a bug with the Unity text input, and so outside the game's control. There are a few known issues with the input fields, and a few of them are supposedly fixed in future versions of TMP, so hopefully they will be backported to Unity LTS. Hopefully by the end of the year the game should experimentally support Unity's new-new UI system "UIElements" which ought to work better.
