### ISSUE TITLE
Suggestion to make a refined version of the Invulnerable tag to only allow certain damage

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2443]
Make an improved version of the invulnerable tag for vehicles, structures and barricades to only be damaged by certain entities. This may include gunfire, projectiles, throwable explosions, melee & zombie damages preferably.

This change targets modders who want to further make complex damage systems in regards to what vehicle, structure or barricade will allow or nullify damage.

**Comment by ZoliWorks** [comment]
So far we have this for **vehicles**, but an expansion would be welcome

**Invulnerable**: Makes vehicle immune to all weapons (but not explosives) without the Invulnerable property.

**Explosions_Invulnerable**: Makes the vehicle immune to explosions.

**Environment_Invulnerable**: Makes the vehicle immune to zombies, animals, and thrown mega zombie boulders.

**Bumper_Invulnerable**: Makes vehicle invulnerable to collisions to damages caused by collisions with other objects.

**Tires_Invulnerable**: Makes tires Invulnerable.

**Child_Explosion_Armor_Multiplier**: Multiplies explosion damage dealt to people in the vehicle by provided number.

**Comment by OneManOperative** [comment]
While the current invulnerability tags already exist, it does need to extend to caliber tags to set entities to be vulnerable to certain damages incoming from those select-few caliber values.

In short, the invulnerable tags need an expansion like you said.

**Comment by SDGNelson** [comment]
Yeah, the current system is not great. It is relatively low priority to rework (compared to network stuff for example), but I can definitely see it happening. In particular to unify damage across all entities with shared rules for damage multipliers, armor, damage types, etc. Maybe I will write up a proposal for comments, but if you want to write up a suggestion as well it may be a useful input.

**Comment by OneManOperative** [comment]
>write up a suggestion as well it may be a useful input

Well, this issue revolves around making sure invulnerability is flexible to all incoming damage.

Taking Squad as an inspiration from this, it would be nice if invulnerability had a new option to accept IDs, or as stated previously, a modified version of the caliber ID system. Not only this makes it really simple, but it's a very versatile value that it makes it so that vehicle and buildable entities only receive damage if the IDs match. E.g, take 42069 as the Tandem damage ID. If the projectile and a tank vehicle match, the tank will allow the projectile to deal damage to it and nothing else. This can be mainly be on guns of both ballistic and projectile systems, but optionally, it would be nice to see this on barricades that deal damage too; or basically for anything that deals damage, even explosives from throwables to mod bombs made to damage certain structures or vehicles.

The invulnerability ID in .dat file form could look like:
`Invulnerable_ID 42069`

Another option to go for is to add an intermediate invulnerability value to bridge between low and high caliber invulnerability. However compared to the first suggestion, I can only see minor use of this because it only caters to bringing minor effects.

My 3rd suggestion is an extension to the first invulnerability ID system, wherein it multiplies damage to the entity if it takes damage from the corresponding ID. This is identical to the Child_Explosion_Damage_Multiplier; albeit compatible for buildables and vehicles if damage from source has the matching ID.

There are many more ideas in the back of my head that I can see to be very beneficial for modders, but I didn't want to be overloading ideas or getting carried away right on the Getgo. So I'll leave it to 3 suggestions and bring them up monthly or when it's needed.

I hope this message is understandable. I wouldn't mind if these can't really get out there, but that's it from my end about what more I could suggest for the mean time.

**Comment by OneManOperative** [comment]
Also sorry if I reply to this issue again after almost a week, I wanted to add on the Invulnerable ID suggestion that, if it were to be worked on, I hope it can support multiple IDs.

That's all, I hope this is the final thing I can add to it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
