### ISSUE TITLE
Steamcmd serevr: Lost connection with host or steam networks

### ISSUE THREAD

**Issue by zisuf** [SmartlyDressedGames/Unturned-3.x-Community#2449]
Im trying to create a small server for me and my friend through SteamCMD and every time I try to join the it goes to the loading screen for a moment then says, "Lost connection with host or Steam networks". Everything loads perfectly fine in the SteamCMD and all the commands and map are successful. But when I try to join it just tells me "lost connection with host or steam servers". and this error message pops up in SteamCMD:

src\steamnetworkingsockets\clientlib\steamnetworkingsockets_connections.cpp (2473) : Assertion Failed: [#1331488911 UDP steamid:76561198306578309@10.0.0.239:64147] problem (4003) %s, but connection already dead (0 4003 Cert is not authorized for appid 1110390, only 304930)

I have already forwarded the port and worked with the fire wall and nothings working. When I was looking for solutions on youtube and google it looked like many other people were experiencing this problem

**Comment by SDGNelson** [comment]
Hmm "Cert is not authorized for appid 1110390, only 304930" is weird because 1110390 is the Dedicated Server, and 304930 is Unturned. There was a similar case where someone was logging into steamcmd using a steam account, rather than login anonymous, and then forgetting to log back into Steam. Are you using login anonymous (recommended)?

**Comment by zisuf** [comment]
Apologies but, how do I know if I used login anonymous? I dont really have the best memory

**Comment by SDGNelson** [comment]
Before running "app_update" in steamcmd using "login" with a Steam account or anonymous is needed.

**Comment by zisuf** [comment]
Oh that, well in that case yes I am using login anonymous. Thank you for clarifying

**Comment by SDGNelson** [comment]
Sorry, I am not sure what else to suggest then... Maybe validate the server install? https://developer.valvesoftware.com/wiki/SteamCMD#Validate

**Comment by Anomalyyyy** [comment]
I have been having this problem since my friends and I started getting back into Unturned. Everyone can get to the server preview that shows the map, population, mods, etc. but no one can actually connect to the server. After sitting in the loading screen for a few seconds red text in the top left shows up: "Server not responded in: Xs Automatically disconnecting in: XXs." After a few seconds of this we're kicked back out to the main menu with the message "Lost connection to host or Steam network."

I have tried:
1. Updating Unturned
2. Verifying Unturned file integrity
3. Reinstalling Unturned
4. Updating SteamCMD
5. Reinstalling SteamCMD
6. app_update both 111039 and 304930 in SteamCMD
7. app_update validate both 1110390 and 304930 in SteamCMD
8. Connecting via public IP (this works for no one)
9. Connecting via "localhost" (this works for me as the host but not my friends)
10. Connecting via IPv4 (this works for me as the host but not my friends)
11. Double checking that 27015-27017 are port forwarded with UDP protocol
12. Double checking that my firewall is not prohibiting connection
13. Praying to the Steam network gods
14. Praying to Nelson himself
15. Crying

While the last three weren't terribly effective, I have exhausted my knowledge of the game and SteamCMD to fix this problem to no avail. If there is anything I could or need to do to solve this problem I would greatly appreciate knowing. Thank you.

**Comment by SDGNelson** [comment]
@Anomalyyyy sorry for the pain! This error has only happened to me a handful of times and it was always from temporarily losing connection to Steam, so I still do not have a great suggestion if it is happening consistently, but it might be worth:
1. Add "-LogSteamNetworkingSockets=7" without quotes to friend's command line and your server command line
2. After friend tries to connect please ask your friend to send Client.log from Unturned/Logs folder
3. Send that Client.log and Server_ (id) .log from U3DS/Logs to me
4. Remove -LogSteamNetworkingSockets=7 from command line because it probably significantly impacts performance

**Comment by Anomalyyyy** [comment]
When you say command line, do you mean the in-game console or specific .exe property files in the Unturned folder?

**Comment by SDGNelson** [comment]
For the client:

1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-LogSteamNetworkingSockets=7" without quotes

For the dedicated server you can add it to your launch script *after* ServerHelper.bat but *before* +InternetServer

**Comment by Anomalyyyy** [comment]
Here you are.
[Server_MyServer.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8746102/Server_MyServer.log)
[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8746103/Client.log)

**Comment by SDGNelson** [comment]
Thanks for the logs, but sadly there do not seem to be any useful errors. :(

On the server side everything seems to be working properly, and no mention of any connection attempts from the client.

Nowadays I think old steam networking might internally use new steam networking because the developer mentioned plans to do that, but it **might** be worth trying enabling the old networking by adding this to the server command line:

`-NetTransport=SteamNetworking -BypassEnableOldSteamNetworking`

**Comment by Anomalyyyy** [comment]
It worked! What's funny is that there was a Steam update and in the patch notes it mentioned some kind of client connectivity. I wasn't sure if the update or your solution was the real fix so we tried both. We were all able to connect to a server using the Old Steam Network bypass and we were not able to connect to a server that didn't.

**Comment by SDGNelson** [comment]
Awesome, glad to hear you were able to use the workaround for the meantime! Hopefully this gets resolved in the newer networking sooner or later.

**Comment by nExysYT** [comment]
So, i use 25046 port. And i need to have forwarded 25047 port?
Please answer

**Comment by LaurentMrl** [comment]
Hey i'm wondering where should i put the -NetTransport=SteamNetworking -BypassEnableOldSteamNetworking ?
Or where can i find "the server command line" ?

**Comment by SDGNelson** [comment]
@LaurentMrl if you created a script to launch your server (this is the recommended way) then the command-line is any text between ServerHelper.bat/ServerHelper.sh and +InternetServer. For example `ServerHelper.sh -NetTransport=SteamNetworking -BypassEnableOldSteamNetworking +InternetServer/MyServer`
