### ISSUE TITLE
Plugin error with the new update

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#2459]
Multiple plugins giving out similar errors after the latest update;

```
[3/5/2021 12:34:15 PM] [Error] An error occured while executing cv []: System.TypeLoadException: Could not resolve type with token 01000040 (from typeref, class/assembly SDG.Unturned.ConsoleInput, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
  at Arechi.CallVote.Voting.Vote (Rocket.API.IRocketPlayer player) [0x00156] in <82b8b8d4d3ba4d13980b77a18a1c5057>:0 
  at Arechi.CallVote.Command.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x0007e] in <82b8b8d4d3ba4d13980b77a18a1c5057>:0 
  at Rocket.Core.Commands.RocketCommandManager+RegisteredRocketCommand.Execute (Rocket.API.IRocketPlayer caller, System.String[] command) [0x00000] in <d60abb45450649579e1e8db675144e04>:0 
  at Rocket.Core.Commands.RocketCommandManager.Execute (Rocket.API.IRocketPlayer player, System.String command) [0x00176] in <d60abb45450649579e1e8db675144e04>:0 
```

**Comment by PandahutMiku** [comment]
We've had no issues but it seems any plugin that was dependent on the ConsoleInput classes are erroring because it was removed in this update.

Also some people who updated their Rocket/hooked onto the OnGestureChanged_Global Event have some errors because it was changed to include the Gesture itself, but that one can be solved by just upgrading rocket it seems.

**Comment by SDGNelson** [comment]
The old old old ConsoleInput and ConsoleOutput classes been marked obsolete empty stubs for multiple years now, I wonder how the plugin was referencing them. i.e. they did not do anything at all so what could the code have been doing...

I did decide to break OnGestureChanged_Global because it was useless without the parameter, and anyone affected would have already updated Rocket last week so it could be safely assumed they would update this week.

**Comment by Buldozeris** [comment]
From what i know, it broke call vote plugin and tebex payments plugin

**Comment by nanashi88** [comment]
I see at the Error message "Arechi" name.
Arechi is a known and active developer. you could try make contact with him, maybe he gonna fix it ...
https://github.com/Arechii
also you could get his discord from his github page.

**Comment by AdamDN** [comment]
> I see at the Error message "Arechi" name.
> Arechi is a known and active developer. you could try make contact with him, maybe he gonna fix it ...
> https://github.com/Arechii
> also you could get his discord from his github page.

I'm sure he will fix his issue, but there's other plugins which have the same issue which have been long abandoned.

**Comment by Arechii** [comment]
I'm impressed it took 4 years to break CallVote's early versions haha. @AdamDN on my CallVote repo you can find releases of the rewrite I did a while back. Those should not be affected by the update. 😏

**Comment by AdamDN** [comment]
> I'm impressed it took 4 years to break CallVote's early versions haha. @AdamDN on my CallVote repo you can find releases of the rewrite I did a while back. Those should not be affected by the update. 😏

Didn't mean to call you out haha, there was multiple plugins with the error - yours just looked the cleanest to copy paste 😜

**Comment by TH3AL3X** [comment]
I'm going to upload the old cvote full fixed soon to my repository

**Comment by TH3AL3X** [comment]
> I'm impressed it took 4 years to break CallVote's early versions haha. @AdamDN on my CallVote repo you can find releases of the rewrite I did a while back. Those should not be affected by the update. 😏

I have the old version plugin, and it took me to update it like 2 times only
