### ISSUE TITLE
Teleport / move player without reset player camera rotation

### ISSUE THREAD

**Issue by Game4Freak** [SmartlyDressedGames/Unturned-3.x-Community#2469]
Currently when a player is teleported his camera rotation is reset. I used RPCs to be able to move a player without this happening. Because this way will no longer work in the future, it would be nice if you could add a way to move / teleport a player without resetting their camera.

**Comment by SDGNelson** [comment]
Out of curiosity I wonder in what context you are using that, i.e. why keep their view pitch?

**Comment by Game4Freak** [comment]
I got some plugins where a player can drag another player. Example: A handcuffed player can be dragged by another one.
When using the default teleport it gets really weird for the player because his view pitch resets all the time.

**Comment by SDGNelson** [comment]
Interesting, makes sense. I intend to rewrite some of the player input and movement code after these netcode rewrites, so then would be a good time to add this.

**Comment by surv0013** [comment]
It would also be great to be able to change the camera rotation. It is desirable along two axes, and not as when teleporting only along one (X).

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
