### ISSUE TITLE
Warn about RPC usages

### ISSUE THREAD

**Issue by Trojaner** [SmartlyDressedGames/Unturned-3.x-Community#2471]
Please add big red errors when plugins use channel.send so developers and users will be notified about this. You could analyze the stacktrace to check if its called from Unturned / RocketMod itself or if called from a plugin.

Idea is inspired from ShimmyMySherbets RPCDetector plugin, but it would be better if this was built-in so it reaches more users.
https://github.com/ShimmyMySherbet/UnturnedRPCDetector/blob/master/RPCDetector.Rocket/Core/RPCDetectorCore.cs#L93

**Comment by SDGNelson** [comment]
Good idea. I will add this after converting over all the built-in RPCs - lots of work 😵 

In the next update all of the SteamChannel closeRead/closeWrite related methods have been marked obsolete and changed into stubs. These "chunk" RPCs and voice RPC would have been breaking things if called by plugins, so they are the only ones I am breaking backwards compatibility for.

All of the "SteamCall" methods which used checkOwner, checkServer, or had CSteamID first parameter have been marked obsolete, but call their replacement method in case they were being called directly by plugins. Plugins should please not call the replacements directly however because they are still a WIP.

Send by name will continue to work for the foreseeable future, but once some of the RPCs get moved into other classes for deferral those RPCs will not be supported anymore. For example methods like "tellStereoTrack" will need to have their execution deferred if the barricade is async loading.
