### ISSUE TITLE
Kicked from server: weather DefaultSnow file mismatch

### ISSUE THREAD

**Issue by WCPistolPete** [SmartlyDressedGames/Unturned-3.x-Community#2474]
Affected map: Yukon.

![20210313155955_1](https://user-images.githubusercontent.com/53093137/111044374-2a5fcb00-8416-11eb-86b5-fa8a329c4e7b.jpg)

[Client_03-13-2021_15-51-00.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6135582/Client_03-13-2021_15-51-00.log)

**Comment by SDGNelson** [comment]
Maybe a silly question, but have you modified that file?

**Comment by joeymisfit** [comment]
Right after the update came out yesterday, I had gotten informed from a few people that when they join their servers it says, "You were kicked from this server because: weather DefaultRain file mismatch" and their players weren't able to join either. As a fix they had to delete the rain assets file and restart their servers.

**Comment by SDGNelson** [comment]
@joeymisfit deleting the rain asset from the server would prevent it from raining on that map. The files have not changed since the weather update two weeks ago, but maybe verify game files to ensure they are correct?

**Comment by WCPistolPete** [comment]
Issue began with the 6 March update.

**Comment by WCPistolPete** [comment]
Verifying client-side game files did not help. Although you said there were no changes to the rain or snow files since 6 March, something happened with server-side linux files that is causing the error.

**Comment by JustOneMoreBlock** [comment]
This has been fixed by removing `Config.json` and allowing it to create a new one.

I've created a diff checker between New vs. Old.

https://www.diffchecker.com/pzDjrE9u

I mainly disabled snow.

```
      "Snow_Frequency_Min": 0.0,
      "Snow_Frequency_Max": 0.0,
      "Snow_Duration_Min": 0.0,
      "Snow_Duration_Max": 0.0,
```

**Comment by WCPistolPete** [comment]
Typing any Rocketmod command that alters the weather will also throw the error. Again only since the 13 March update.

**Comment by SDGNelson** [comment]
Actually based on your comment about Rocketmod custom command I wonder if it is enabling the weather on the server, but not replicating to clients? (i.e. if it is an older command) In that case the client would think there is no weather and sending an empty hash. One way to test if that is the problem would be by using the built-in weather command and seeing if the kick happens.

**Comment by WCPistolPete** [comment]
The result is the same. Change config.json or use rocketmod -- mismatch and kick. Either the client does not get the new information or a "no weather" hash sends an error. Result? mismatch and empty server.

**Comment by SDGNelson** [comment]
What do you mean about use rocketmod?

**Comment by SDGNelson** [comment]
In today's update I included the client/server hashes in that kick message. If my suspicion is correct the client hash will be zero.

**Comment by SDGNelson** [comment]
Following up: WCPistolPete sent an email with a screenshot that the client hash was indeed zero. But the reason was different than what I had guessed:

Based on JustOneMoreBlock's comment I thought the interval and duration had been disabled in response to this issue and assumed that was preventing it without much more consideration, but actually their server has always had interval and duration set to zero. It is reasonable to expect the game would disable weather in that case, but actually the server is starting and stopping blizzards every single tick. To be honest I am surprised this has not caused other problems in the past.

Adding to this problem, there is an edge case that if the weather changed between when the server requested the hash and the client replied the hash would not match - which is the case with the weather changing every tick.

For this week's update I will fix setting those values to zero so that they disable the weather, and fix the edge case when the weather has changed between sending and receiving the hash.

**Comment by SDGNelson** [comment]
I assume you have not run into this since last Friday's update? Closing, but feel free to comment and I will re-open.
