### ISSUE TITLE
[Feature Request] Burglarly Doorly Domiciliary

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#2491]
Yeah the name is not catchy as "stealy wheely automobiley" but in essence would be a tool to force open Metal Doors.

And or Lockers / Vaults / Metal Library / all the other Locked Barricade class item.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by Lion4K** [comment]
Yeah, after 2 years I've kinda figured you wouldn't add it.
That's OK.
But thanks for reply anyway.
