### ISSUE TITLE
[Feature Request] Chance, and Time to use the "stealy wheely automobiley"

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#2492]
A server side option to set the needed time to unlock a car using the stealy wheely automobiley and also chance of not working out and breaking the tool.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
