### ISSUE TITLE
Add custom sounds without having to upload in the workshop and without using the EffectManager

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2495]
Add an event that allows you to add sounds that are in the directory of your server, without having to upload anything to the workshop, be it all server side.
It is a good idea for servers that do not want mods but want sounds when you kill a player, It could be implemented even in unturned radio and in this way not forcing X audios to be downloaded...

Sorry for my england, please don't judge me with this post

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
