### ISSUE TITLE
[Feature Request] A method to Fast store items on a container.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#2498]
We need a method to store items more rapidly, or automatically, like a Minecraft Hopper, or a Conveyor Belt, or maybe just a button on the storage GUI that you can click and let the items being transfer automatically because its annoying, really annoying to click each item individually.

To get the items from the container we just salvage the container and spam F, but to store them, Man.

**Comment by aviadmini** [comment]
Quality of life changes 👍

**Comment by Lion4K** [comment]
> Quality of life changes 👍

Looking back now I don't know if you're being sarcastic or not, since you banned me from your discord for wanting to buy plugins without static IP    ¯\_(ツ)_/¯

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
