### ISSUE TITLE
Remove_Head

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2502]
Similar to the mesh replacement and applying to helmets, specifically to help with some rounder helmets from having to be massive to prevent the corners and looking like bobbleheads on the player mesh, basically just makes the head invisible in the same way that custom mesh would.

**Comment by SDGNelson** [comment]
Since the head and body are part of the same mesh this would either need to be part of the body shader, or a separate mesh. In the meantime the best option would be a mesh replacement item as you mentioned.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
