### ISSUE TITLE
Server not working with ZeroTier One

### ISSUE THREAD

**Issue by ItzPeto** [SmartlyDressedGames/Unturned-3.x-Community#2506]
Hi there! I have a problem with connecting my Unturned server to the ZeroTier network

Every time i bind the IP (that i got assigned by ZeroTier) to the server the console starts spamming this just before the level loads.

```
Waiting for Steam servers...
Failed to connect to Steam servers because k_EResultNoConnection, still retrying
```

This was happening even with the +Lanserver option
Also I tried binding my local IP to the server which worked and I could join the server without any problems.
When binding to 0.0.0.0 it does not bind to the ZeroTier network.

**Comment by SDGNelson** [comment]
Sorry, but that is outside the scope of the support here. Would recommend contacting ZeroTier support for that.

**Comment by maciejisnotavailable** [comment]
I am still having this issue. It isn't an issue with ZeroTier because I have the same issue when using Hamachi. The issue only appears when binding the server to a port, and when I attempt to set an online server without binding to a port, and I set GSLT correctly, and set everything up perfectly, nobody can directly connect to me, nobody can connect in the "Friends" tab, and the only way to connect to the server is through LAN. I have forwarded ports on my router and I know that they are forwarded correctly on the internal firewall because I can connect to other devices on the same network. I spent a few hours teaching my friend how to set up the server on their device, on a different operating system, and they also had the same issue. I will provide logs when necessary.
