### ISSUE TITLE
[Feature Request] Sticky Grenade Improvement

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#2513]
Dear Nelson,

Hello, is it possible for you to parent the grenade upon collision to any object? Or can you make a hook such that upon collision with an object, the collided object get parented to that object that it collides with?

Also, I have a suggestion to make. Is it possible for you to add a raycast infront of a fast-moving projectile for secondary detection of impact as the rigidbody collision isnt very reliable?

Thank you for your time and have a nice day!

Yours Sincerely,
SMD

**Comment by SDGNelson** [comment]
Ideally yes, it would attach to the hit object. In the past this was not possible because the game had no way to globally identify a transform between systems, but it will become possible after this next RPC update because everything can be assigned a NetId. No ETA on the stickies using it however. Players on moving vehicles will probably be the first attachment-related use. Sweep-based CCD (game default) for projectiles is essentially raycast projectiles, but I might also add a weapon option for game-managed physics queries as well eventually.
