### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Buldozeris** [SmartlyDressedGames/Unturned-3.x-Community#2522]
Would be nice to have option to disable weapons/clothing skins in server config file. I dont see problem with weapon skins, but clothing skins for survival or pvp server is bad idea. You cant see what armor player is wearing because of those skins. And it ruins experience on pvp/survival server. I know it can be done by plugin, but those plugins break all the time.

**Comment by Jdance-Media** [comment]
I have been needing this for a long time. I run a FPS shooter mode in Unturned and skins have always been an issue for me.
If we can get this feature sometime in 2021 that would be great.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
