### ISSUE TITLE
Plugins 

### ISSUE THREAD

**Issue by Mathwie** [SmartlyDressedGames/Unturned-3.x-Community#2530]
Can u add events :
PlayerQuests.onSellToVendorRequested(Player player, ushort id, byte index, ref bool shoudAllow)
PlayerQuests.onBuyFromVendorRequested(Player player, ushort id, byte index, ref bool shoudAllow)
LevelManager.onToggleBinaryStateRequested(InteractableObject object, Player player, ref bool shoudAllow)
or how to replace them

**Comment by aviadmini** [comment]
All toggleables could use such event (if not yet there)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
