### ISSUE TITLE
Empty stub methods after RPC Rework & LDM causing out of sync skills

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#2537]
Probably poor title, never good at those.

With the rework, there is a number of methods left as empty stubs.

For example, AskSkills, TellSkills,  tellScreenshotDestination, tellScreenshotRelay, tellClothing, askEquipment. (If needed I can find more I'm sure, just found a few obvious ones for now).

Kind of confused on why you left them empty, I think it would be more desirable to just remove them and have the command/plugin error out instead of just seemingly working and doing nothing.   Unless you just forgot to update them to redirect to new methods..?

On a related topic, there is a billion old methods you left for plugin compatibility like EffectManager.sendUIEffect, etc. Do you plan to change the netcode more in the future and it would be smartest for us to keep using the marked obsolete csteamid methods for compatability, or do you want us to grab the ITransportConnection from the Steamplayer ourselves and use the newer methods? A lot of Unturned devs are kind of confused about that right now, especially newer devs when it's marked they are using an obsolete method and they have no idea what an ITransportConnection is.

There is further confusion especially regarding some methods marked obsolete, such as askSkills, which doesn't work at all. Other ones marked obsolete, like sendUIEffect work fine. The addition of obsolete messages like "Use the new method using ITransportConnection instead of CSteamID" would serve as really helpful guidance for plugin developers.

Lastly, LDM's UnturnedPlayer has a method to change the skills of a player (UnturnedPlayer.SetSkillLevel) that is using [askSkills](https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/blob/c4fdf0cbb75c7e645a3b98bd57c1873714114d3f/Rocket.Unturned/Player/UnturnedPlayer.cs#L595), which is now a stub method that does nothing. This is resulting in the skills the server has becoming out of sync with the client. If some people have been reporting more rubberbanding after the new netcode update, that seems to be why, since the player's stamina skill is being changed server-side without informing the client. 

I assume it should just be player.skills.ServerSetSkillLevel now?

Thanks! and sorry for the wordiness of this

**Comment by SDGNelson** [comment]
Hey Miku,

Good point: it is confusing having some obsolete methods that still work (albeit slower) vs obsolete methods that do nothing. 

My hope was that anyone developing modern plugins would see the obsoletion and update not to use those methods regardless of whether they still did something for backwards compatibility.

Any methods which become stubs were converted to the directly use NetPakReader / NetPakWriter rather than RPCs, or in the case of once-per-connection RPCs completely changed to send initial state rather than by request, so there was not a good way to handle compatibility.

ServerSetSkillLevel is the intended replacement yes. I was really hesitant modifying that Rocket method because someone may be relying on an unintended side effect like OnPlayerDeath, but I suppose considering askSkills is a stub modifying it would be better. askSkills was only intended to be called once and would have been resending the entire skills list on modification.

**Comment by PandahutMiku** [comment]
> Hey Miku,
> 
> Good point: it is confusing having some obsolete methods that still work (albeit slower) vs obsolete methods that do nothing.
> 
> My hope was that anyone developing modern plugins would see the obsoletion and update not to use those methods regardless of whether they still did something for backwards compatibility.
> 
> Any methods which become stubs were converted to the directly use NetPakReader / NetPakWriter rather than RPCs, or in the case of once-per-connection RPCs completely changed to send initial state rather than by request, so there was not a good way to handle compatibility.
> 
> ServerSetSkillLevel is the intended replacement yes. I was really hesitant modifying that Rocket method because someone may be relying on an unintended side effect like OnPlayerDeath, but I suppose considering askSkills is a stub modifying it would be better. askSkills was only intended to be called once and would have been resending the entire skills list on modification.

Thanks for your quick reply

My main concern with the obsolete methods and ITransportConnection was just that earlier you mentioned that some of that networking stuff still isn't set in stone yet and may be changed in the future. Is it safe for plugins to grab ITransportConnection from SteamPlayer and use it in the new methods, or do you plan on anything that stuff more in the future?


About [LDM's SetSkillLevel](https://github.com/SmartlyDressedGames/Legally-Distinct-Missile/blob/c4fdf0cbb75c7e645a3b98bd57c1873714114d3f/Rocket.Unturned/Player/UnturnedPlayer.cs#L592), the way it is right now is that it will set the skill on the server but not replicate it to the client since the askSkills method is stub/empty. So if you use UnturnedPlayer.SetSkillLevel to reduce or increase someone's stamina skills, they will rubberband around, or if you use it for anything else, the client just won't ever be told. The only incompatibility I could imagine is that if a plugin was using the method and instantly checking if it properly changed, but it looks like the new method does change it instantly like before. Regardless I think it would be better to fix it than keep it in a completely broken state that causes other issues with rubberbanding unless you know something I don't or are talking about something else. Sorry If I repeated myself a bit, but I probably wasn't clear about it before.

Thanks for your time

**Comment by SDGNelson** [comment]
It should be safe to grab ITransportConnection from SteamPlayer yes - I do not foresee that ever changing. The implementation of ITransportConnection could change because there is no reason for plugins to be manually using the transport layer directly, but the usage of ITransportConnection as an opaque connection identifier will not change.

For this Friday update I will change `UnturnedPlayer.SetSkillLevel` to call `ServerSetSkillLevel` as you mention. 👍
