### ISSUE TITLE
Magazine_Empty

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2540]
Small request to add a parameter to magazines to specify a model to show up when at x0 ammunition. This would allow for clips and magazines with visible bullets or casings to show off if empty on a visual level.

**Comment by DerpyHoowes** [comment]
Perhaps specific models for different ammo count properties with some basic logic would also make up a nice addition to the game. Like, enabling some model if ammo count is less than 15, or equal to 30, or whatever - just the same logic operations as the ones that we currently have for NPC conditions.

**Comment by Dumfoozler** [comment]
I was also thinking that would be cool, maybe specifying in dat files at a certain ammo count to use a Model_0, Model_1, Model_2, or something similar.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
