### ISSUE TITLE
Option for the siren to turn off with a vehicle engine

### ISSUE THREAD

**Issue by IsaiahHarvi** [SmartlyDressedGames/Unturned-3.x-Community#2546]
There isn't an option for the siren of applicable vehicles to turn off with their engines.

**Comment by DerpyHoowes** [comment]
You can make it yourself. Attach an Activation Event Hook to the sirens and make it turn on some form of ballast which wont allow the vehicle to move, or perhaps turn off the back Tires and turn off the same tires but outside of the Tires hierarchy, so that there are no original tires to make the vehicle move, but the placeholder tires dont allow it to just fall on the ground (not sure if this works as I imagine it, but still worth trying I guess. If this doesnt work ballast is still an option).

**Comment by Jdance-Media** [comment]
Zoliworks made it so you have to or you cannot move your helicopter. You also have to wait for the engine to start.

**Comment by ZoliWorks** [comment]
I assume you want the sirens to stop flashing when the engine of the vehicle is off (which happens automatically when the driver exits the vehicle)? 

If you're making custom vehicles, you can straight up add a "Vehicle Event Hook" to the Vehicle prefab and "On Driver Removed" make it disable the Sirens gameobject. (gameobject->enabled & un-check)
