### ISSUE TITLE
"Phantom" item bug

### ISSUE THREAD

**Issue by FunkyWaffles** [SmartlyDressedGames/Unturned-3.x-Community#2547]
People are experiencing a old bug more frequently after the recent update (3.21.14.0), this bug will make the item still appear in your inventory and other items can fill in the space of the item giving a "phantom" like appearance.
Images: https://imgur.com/a/XH1SD6g

**Comment by SDGNelson** [comment]
There do seem to be a spike in reports of this yesterday and this morning. Nothing related to the inventory implementation changed in the update though. I wonder do you have any plugins patching the inventory? 😕

**Comment by Ongjming** [comment]
This issue came out immediately after the latest update, best explained by https://steamcommunity.com/app/304930/discussions/9/3163190952005843458/ (TootsyBowl, Steam)

It happens in Singleplayer mode as well as in Server.

**Comment by Dumfoozler** [comment]
Can verify this is happening in every mode for every type of item. It was happening with vanilla items on my testing map earlier.

**Comment by SDGNelson** [comment]
Sorry for the big delay on this. It should be fixed in the .1 patch released now.

Not as an excuse for my mistake, but to clarify why this slipped through: I was so focused on netcode related bugs that when trying to reproduce the reports yesterday I was trying different combinations of the network-related item interactions, and even thought it might be a plugin related to the item netcode changes from last week. In retrospect this was obviously a really dumb bug on my behalf.
