### ISSUE TITLE
[BUG REPORT] Pressing "R" makes decals flash.

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2549]
Very strange, not sure why or how it is happening but in all worlds I've tried pressing R to reload makes the world flash for a frame.

https://user-images.githubusercontent.com/76188059/114315638-cf30ff00-9acd-11eb-8c9e-1de42c2bf492.mp4

**Comment by SDGNelson** [comment]
It seems that this is probably related to #2421 when updating the attachments, but obviously that should not happen when not using a night vision scope. Will check into it.

**Comment by SDGNelson** [comment]
Spent some time today digging into this, but no closer to figuring it out. Happens when toggling flashlights as well. Sigh. Will continue tomorrow.

**Comment by SDGNelson** [comment]
The item state update (reload, toggle flashlights, etc) was causing an item icon recapture. Since all rendering has to share the same scene and lighting parameters, and icons captured at night should look the same as during the day, the icon capture temporarily sets ambient light to white. Decal rendering was getting this wrong ambient light value similar to the other issue. I experimented with a bunch of workarounds, but ended up having to put together a messy hack for decal ambient light. For the next update this and the night vision dual-render scope decal should be fixed. It will get properly cleaned up once we can update to URP or HDRP.
