### ISSUE TITLE
[Feature request] Event for when an admin toggles their Spectator mode (Shift F7) in PlayerLook.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#2553]
Also, the ability to cancel it would be nice.

**Comment by TH3AL3X** [comment]
I think is possible to do it without a event, and forcing "first person" when he toggle the "orbiting"

**Comment by DanielWillett** [comment]
> 
> 
> I think is possible to do it without a event, and forcing "first person" when he toggle the "orbiting"

I looked through a lot of the code for the special F_ commands in PlayerLook and they all appear to be client-side. I may be wrong but it looks that way. The only server-side thing is a variable that says they're allowed to use the commands, which can be set through the server. Theres no way as far as I know to detect when they actually activate it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
