### ISSUE TITLE
[UI] Support for clientside conversion of metric/imperial units 

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2560]
I'd like to suggest adding a way for clientside units conversion similar to the way UI effects replace hotkeys (e.g. `<plugin_0/>`) with clientside values (in`EffectManager.formatPluginHotkeysIntoText`).

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
