### ISSUE TITLE
Apply Storage Properties to Object

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2562]
Allow for objects to have the barricade storage properties, to allow for local world objects to act as interactable storages that cannot be damaged or salvaged whatsoever, and be placed from within the editor

**Comment by Jdance-Media** [comment]
This is a feature that has been requested/needed for the past year or so. Objects should be able to work as interactables.
I would also be nice if we could get other interactable features such as generators for objects.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
