### ISSUE TITLE
Group name/id above player name in spectate cam

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2564]
Would it be possible to implement this feature into game? It could be possible to turn it on/off in server's config file. The main point of this feature is easier monitoring of cross-teaming (currently its a bit of a mess to check groups in players list). It could look something like this (if it is steam group then it would show steam group name and if it is in-game group - it would show id of the group):
![image](https://user-images.githubusercontent.com/14231707/115413323-bdea9f80-a1fd-11eb-9962-da36eee280d8.png)

**Comment by SDGNelson** [comment]
Neat idea. It would be nice to add more spectating tools.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
