### ISSUE TITLE
Map editor's incorrect work

### ISSUE THREAD

**Issue by Raptor-UA** [SmartlyDressedGames/Unturned-3.x-Community#2568]
![IMG_20210423_155217](https://user-images.githubusercontent.com/81715836/115875350-cc2efa80-a44d-11eb-84ee-af69e0f82044.jpg)

**Comment by SDGNelson** [comment]
Is the terrain outside the map border not getting updated? I wonder if baking it might not have been handled when the skybox and in-border terrain were merged and replaced with the tiled terrain. Unfortunately this particular case is unlikely to be fixed because the devkit terrain tools will be merged back into the regular editor.
