### ISSUE TITLE
Laser colors.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2583]
I am pretty sure you cannot change the laser color at all.

**Comment by Ongjming** [comment]
Not sure about the Tactical Laser itself, but you can make a modded rangefinder with Light components which you can change its size radius and coloration. So when you toggled the range finder on, it can act as light or laser or both if you want. Making the laser work like the one in game probably need a bit of fine tuning the light beam....

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
