### ISSUE TITLE
[Feature Request] EPluginWidgetFlags

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2590]
```CSharp
enum EPluginWidgetFlags
{
    ShowVoiceIcon,
    ShowVehicleMeters,   //Complete
    ShowInteract,   //Complete (Only Enemy Interact)
    ShowGasmask,
    ShowWeaponMeters,   //Complete
    ShowTrackedQuest,
    ShowHotkeyBar
}
```

Complete: `2.5f/7`

**Comment by Greenorine** [comment]
EPluginWidgetFlags.ShowChat

**Comment by fahrettinenes** [comment]
@SDGNelson

**Comment by 01-Feli** [comment]
he is already receiving notification for each comment @fahrettinenes

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
