### ISSUE TITLE
RocketMod Support Item

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#26]

**Comment by yegac1337** [comment]
Remove sven from RocketMod and hand the project off to someone else.

**Comment by RainOfPain125** [comment]
Pave a way for adding a kind of permissions.xml and plugin support for Vanilla Unturned so Sven is no longer a needed asset in the development of Unturned

**Comment by SDGNelson** [comment]
[Here's a response I posted which covers my opinion of Sven](https://forum.smartlydressedgames.com/t/my-ban-appeal/1353/43?u=sdgnelson)

**Comment by RainOfPain125** [comment]
The only way to solve problems is by talking. Sven seems to be very
childish and has blocked me on twitter, and has banned me from the
"official" Unturned Discord. Just because you don't like someone doesn't
mean you shouldn't talk to them and resolve conflicts

**Comment by FredMods** [comment]
Keep drama elsewhere, please.

**Comment by yegac1337** [comment]
In all honesty if he would of just apologised to Ed this would of never happened, He can't say anything as you yourself Nelson involve yourself with cheaters in one way or another. I'm dropping out of this as I think its just stupid and immature but I do think an apology is needed to Ed.

**Comment by xdlewisdx** [comment]
Apology for what? banning a person associated with cheats? that's like saying if i go make a website where people can sell cheats i shouldn't be banned? of course I should it's making it easier for someone to get cheats, it doesn't matter if he JUST managed Dyno hes making the discord a easier place to sell cheats, you know the funnest part is he lied about knowing it was a cheat discord and is STILL IN IT MODERATING AND MANAGING and you guys are still saying we should apologise

and you know what? even if he didn't know which he did, he still went and attacked Sven and still is attacking Sven, and just for that he would have been banned from the Discord.

**Comment by RainOfPain125** [comment]
I'm banned and I didn't attack Sven. It's not unusual for Sven to abuse -
but this time Sven needs to man up and apologize for his radical and
unevessary actions agaibst ItzEd

**Comment by xdlewisdx** [comment]
Nothing for him to apologize for, He banned someone associated with cheats period end of discussion I'm not going to waste my time on this anymore oh and @RainOfPain125 just letting you know you aren't even banned

**Comment by yegac1337** [comment]
You are wasting your time, Nelson associates himself with me as I help with BattlEye. Anyways useless conversation as Sven is dense.

**Comment by xdlewisdx** [comment]
I'm pretty sure Nelson wouldn't associate himself with someone's who first repo is private cheats for H1Z1 so stop bsing

**Comment by yegac1337** [comment]
Not posting anymore here as its not for this. I also don't have time to argue with you as I'm working on a project atm. 
![image](https://user-images.githubusercontent.com/32919508/32202297-efb67af4-bd98-11e7-8c8d-bf4cd86f369e.png)

**Comment by xdlewisdx** [comment]
Wow, one last comment i can't help myself, this is so sad Nelson should definitely look into removing that because of the fact you seem to be into cheating very much, half steam friends list creates cheats many bans on profile and you seems to use/abuse the fact that somehow you got that beret as if it makes you have power and because you have it i should just listen to anything you say

**Comment by yegac1337** [comment]
Well, You wan't to be immature and keep this going so lets keep it going. Yes I'm into cheating and Developing, I code. I tinker. I help get stuff patched. You are already wrong with my friends list as I'm 90% sure its basically all Unturned Youtubers such as Hayden, Union and RoboKast. I never really "abused my beret." Never said you should of listened to me or anything related to that. Half of the memes made on my twitter are months old and are quite obviously memes, half of which had nothing to do with Nelson or Sven at all. Just because I cheat doesn't mean anything, Where does knowledge to work on stuff like this come from. Out of thin air? Obviously not. Once again I do not have time to deal with you and this is not the place. If you wan't to continue this add me on steam and keep it off of the issue section. This has nothing to do with issues. 

Also the Sven thing blew over, Half the memes aren't mine are were reposted from UnturnedCreators discord. If you do want to continue this please keep it off of here and add me on steam or add me on discord. @mystifying

**Comment by yegac1337** [comment]
Also not going to say I disagree with all of your points, Yes I am very public about cheating but I do help out with the community on Unturned. You do have valid points, You have some completely irrelevant points. Anyways once again the bottom of my last post.

**Comment by Trojaner25** [comment]
This is so sad...

**Comment by xdlewisdx** [comment]
btw @RainOfPain125 Sven didn't even ban you xD
