### ISSUE TITLE
Custom Mesh Compatibility with Zombies

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2603]
Whenever custom mesh is put onto zombies, it uses the default zombie model and the mesh is nowhere to be seen. I understand this is because the zombie model and player model are different. Can the functionality to override their mesh with the custom mesh shirts be implemented for zombies and mega zombies?

**Comment by SDGNelson** [comment]
I would like to merge the player and zombie appearance features, but no ETA sorry.

**Comment by surv0013** [comment]
@SDGNelson Sorry to interfere, but it would be nice if the server did not send the clothing indices from the zombie spawn point to the client, but the clothing ID, then a plugin could be made that would spawn zombies with custom clothing.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
