### ISSUE TITLE
[Feature Request] auto kick idle players

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#2611]
Hey,

it would be nice if you could add option to auto kick idle players after xx minutes.
also players who have died but haven't respawned.

Greetigs

**Comment by SDGNelson** [comment]
I agree that would be a useful feature. There are some improvements I would like to play to the input netcode, so it would make sense to add as part of that.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
