### ISSUE TITLE
[Feature Request] Allow build in locations bool

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#2613]
Many servers disallow building in locations because its easy way to block items respawns.
Maps like Elver or Kuwait already have no-build zones.

Would be nice to have config option Allow_build_in_locations bool.

This will help many servers by reducing the effort of running around the map and destroying those structures.
Also many players will avoid server bans for breaking rules.

Hordebeacon should bypass this limit.

**Comment by GazziFX** [comment]
It can be easily implemented by plugins, I know one

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
