### ISSUE TITLE
[Feature Request] Add NPC conditions and rewards to Barricade

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#2620]
I see that the blueprint has added this function, can barricade also add it?It is better to turn on the function of NPC UI.

**Comment by SDGNelson** [comment]
Eventually I would like to add support for the dialogue through non-NPC entities like props and barricades.

**Comment by prank0011** [comment]
> 最后，我想通过像道具和路障这样的非NPC实体来增加对对话的支持。

Will it be added in the form of mod hooks? In this way, animals can also open NPC dialog boxes.

**Comment by prank0011** [comment]
> Eventually I would like to add support for the dialogue through non-NPC entities like props and barricades.

Will it be added in the form of mod hooks? In this way, animals can also open NPC dialog boxes.

**Comment by SDGNelson** [comment]
Perhaps, it depends how broadly the NetId improvements have been done at the time.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
