### ISSUE TITLE
[Feature Request] Better animation support

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2632]
Right now in Unturned, there are no alternative reloads instead it's the reload animation and a charge animation, so animating like a H&K Slap is impossible or making a bolt action sniper rifle be correctly reloaded instead of *visually* discharging 1 round. I wish only for dry reloads that's really it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
