### ISSUE TITLE
Request: Timer on detonatable explosives

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2635]
Unless the code cannot be easily updated on the spot to do so, there should also be an option to put a timer to detonatable barricades like demolition charges. The purpose of this is to create timed explosives that have duration per second before detonation. I hope that the code to this can also be easy to implement to the game. Perhaps add sound to it so that there can be an audio cue option.

**Comment by Spebby** [comment]
#1843

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
