### ISSUE TITLE
feature request, no timer countdown when server is not responding

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2642]
waiting 10 seconds to exit each time when server stops responding over and over every 10 or 15 minutes is pretty aids

**Comment by SDGNelson** [comment]
Are you saying you want the client to immediately disconnect in that case? It sounds like the underlying issue of the server not responding every 10 or 15 minutes should be resolved instead. There are lots of reasons that could be happening. If it only happens to you then it is likely a problem with your connection to the host, but if it happens to all players on the server then it could be a performance problem on the server or a problem with the host's network.

**Comment by 01-Feli** [comment]
> 
> 
> waiting 10 seconds to exit each time when server stops responding over and over every 10 or 15 minutes is pretty aids

If it happens to all the plugins be sure you dont have any plugin installed that uses thread.sleep or something like that, probably it can be a plugin with a timer that you set up in the config every 10 or 15 minutes

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
