### ISSUE TITLE
Request for clothing items to support disabling Allow_Manual_Drop

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#2643]
At the moment, this config function is not working in full force.
When there is room for the clothes in the inventory, they are not removed, but when the inventory is full, the clothes simply fall to the ground.
Or add a new feature that prevents you from taking off your clothes by hand.

**Comment by SDGNelson** [comment]
When Allow_Manual_Drop is disabled on the clothing item? I guess preventing changing clothes if any of the items would be dropped? This would be a reasonable change, but off the top of my head there are a few features that would make this tricky to quickly fix.

**Comment by PARTOVIY** [comment]
Yes, when the function is disabled on clothes, then the clothes are not removed from the character when there is space in the inventory, as soon as there is no space in the inventory, then it is removed and falls to the floor.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
