### ISSUE TITLE
[Feature Request] Numbered Limbs on Animals

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2648]
Hello!

Currently, animals are only able to have hitboxes on Left Back, Right_Back, Spine, Left_Front, Right_Front, and Skull, as they have to correspond to the games predetermined names to calculate damage properly

I am simple asking for either the ability to mark down what bones should take what kind of damage, or simply to allow Right_Front_0, Right_Front_1, etc for having multiple legs or jointed limbs. The animations are already there and the bone names can exist, the only issue is to be able to apply hitboxes to them.

I beg for your help with this issue, as I want to create more fluid and motionable animals and to do that I will either have to have massive and unrealistic hitboxes, or be able to incorporate more than just the 6 hitboxes allow you. If you would be able to help out with this it would be a great service both to me and to all of the people trying to design animals.

Thank you,
- Dumfoozle

**Comment by SDGNelson** [comment]
It would definitely make sense. It is a very old system wherein the hitbox id is an enum with those 6 entries. Using other bone names should work fine in the meantime, but they would use the body damage multipliers.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
