### ISSUE TITLE
Suggestion: Option to change binocular reticle in Unity

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#2655]
I'm pretty sure this is hardcoded, but I bet it is also easy to implement to the game wherein creating a binocular item can have a different reticle when in use. Good for modders to create binoculars with more creative visuals upon using them.

**Comment by SDGNelson** [comment]
You are correct that it is hardcoded at the moment. Would make sense to move into a modable option.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
