### ISSUE TITLE
[Feature Request] "offline raid" on-off setting

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#2673]
Hey,

it would be nice if you could add option to enable/disable "offline raid".
ofc there should be an option like : "can raid xxx minutes after logoff" (to avoid abuse)

Greetings

**Comment by SDGNelson** [comment]
Like disable damage against the base if nobody from the owner / group is online? I agree it could be a useful option, particularly with an optional damage multiplier.

**Comment by nanashi88** [comment]
yes.
damage multiplier also great idea
also timer is important to prevent abuse
for example: "can raid 15 minutes after logoff"
to prevent abuse of imediate disconnect to prevent raid

**Comment by GazziFX** [comment]
Can be implemented by yourself

**Comment by Jdance-Media** [comment]
This feature can be implemented via a plugin but it should be built in, so that way server owners can enable and disable it quick when they want to and the feature can be easily used.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
