### ISSUE TITLE
Add a hot button to throw a grenade

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#2677]
Greetings, Nelson.

Please tell me if you can make a hotkey (for example:) so that the player gets the first grenade that comes across, the ring opens and it rushes in the direction where the player is looking. If yes, please tell me what the terms are. I, like many players, would like to see this feature. Thank you.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
