### ISSUE TITLE
Dedicated Server Executable Name Should Be Different [Change Request]

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#2696]
Hello, I've been messing with the dedicated server app recently because I need to test my plugins and such, but there is a big issue with it. Steam thinks that the dedicated server is actually the main game running, so I cannot launch Unturned from Steam to get on the server. To spare people from having to deal with this annoyance I personally think it would be best to change the name of the dedicated server executable that way Steam isn't some idiot and gets confused.

**Comment by GazziFX** [comment]
Steam isn't confused but BattlEye does, it doesn't close until you close server and Steam checks that Unutrned_BE.exe is still running. For me solution was very easy **just launch Unturned without BattlEye**

**Comment by SDGNelson** [comment]
Interesting point Jdance-Media and thanks for suggesting workaround GazziFX. Currently Unity names the headless Windows executable the same as the project name. It might be changeable since it only appears to be used for the executable and _Data folder names. Since there is a workaround I would be hesitant to rename these things however considering it would undoubtedly break other peoples' code/tools.
