### ISSUE TITLE
Custom weather settings on the map

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#2699]
I created my own custom weather, but now I have a question. What should I write in Config.json so that this weather would accidentally turn on on my map?
In general, I need:
- Make my weather appear on the map randomly
- Set the time and frequency for it

Also, if it is possible to add my weather to the map, is it possible to make several weather modes?
Let's say if I make two types of weather, can I insert them into the map, as well as adjust their frequency, etc.

I have seen separate settings on different sites, but I need specifics and an example.

Thank you in advance

**Comment by JorelDecker** [comment]
@SDGNelson Help pls

**Comment by SDGNelson** [comment]
Configuring weather for the map is detailed here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelAsset.md
It is possible to have weather in specific areas yes by configuring the weather mask in the ambiance volumes. More details in the weather doc: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/WeatherAsset.md

I would recommend looking at Bundles/Assets/Levels/PEI.asset for an example because it has rain and lightning storms.

**Comment by JorelDecker** [comment]
> Configuring weather for the map is detailed here: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/LevelAsset.md
> It is possible to have weather in specific areas yes by configuring the weather mask in the ambiance volumes. More details in the weather doc: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/WeatherAsset.md
> 
> I would recommend looking at Bundles/Assets/Levels/PEI.asset for an example because it has rain and lightning storms.

Understood, thank you very much. But it's not clear yet, you can write how to configure the weather in a certain place. I ask you very much with an example

**Comment by JorelDecker** [comment]
@SDGNelson  Help pls x2

**Comment by iBowie** [comment]
> I would recommend looking at Bundles/Assets/Levels/PEI.asset for an example

Nelson told there IS an example

**Comment by JorelDecker** [comment]
> > Я бы порекомендовал посмотреть на Bundles/Assets/Levels/PEI.asset для примера
> 
> Нельсон сказал, что есть пример

There is no example for a specific site

**Comment by JorelDecker** [comment]
@SDGNelson Help pls x3

**Comment by SDGNelson** [comment]
Please stop sending duplicate notifications, and there was no need to email me reminding me to look at this. I catch up on all my emails and GitHub issues every day.

France would be a good example of weather in specific locations because it has Snow only in the mountain regions. The ambiance volumes on France have their Weather_Mask set to overlap with the DefaultSnow Weather_Mask.

**Comment by JorelDecker** [comment]
> Please stop sending duplicate notifications, and there was no need to email me reminding me to look at this. I catch up on all my emails and GitHub issues every day.
> 
> France would be a good example of weather in specific locations because it has Snow only in the mountain regions. The ambiance volumes on France have their Weather_Mask set to overlap with the DefaultSnow Weather_Mask.

Sorry, but in the level.hierachy of France, I did not find a Weather mask

**Comment by SDGNelson** [comment]
It may not have been re-saved after the update, but if you open France in the level editor you can see how they are setup.
