### ISSUE TITLE
Trap Damage, Include the trap's owner as the damage causer

### ISSUE THREAD

**Issue by ghost** [SmartlyDressedGames/Unturned-3.x-Community#2700]
Right now when Traps damage players, the damage is counted as from CSteamId.Nil and not from as the owner of the trap. It would be nice if eventually traps passed the owner of the trap with the damage, so players would know who's trap killed them, and plugins could selectively stop or log trap damage with owner details. 

I understand if this is something you don't want to do until you clean up the barricade owner stuff, as this would likely mean having another special barricade that tracks the owner in two places.

**Comment by SDGNelson** [comment]
As you correctly guessed, the trap code does not currently know the owner. But it looks like this could be hooked up in a relatively straightforward manner now that the owner is known when the barricade is spawned. Unfortunately on the client it would not necessarily allow the owner name to be shown in the kill message because the owner could be offline. I think that might be the reason it did not work that way before. In the future I would like to store some player data (e.g. last known username) on the server by default for purposes like that. Good news yes I am actually starting work on the structure side of the building rewrites today!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
