### ISSUE TITLE
[Feature Request] Add a vehicle interactibility delay

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#2711]
Just like the object interactibility delay ex: Counter_2 (Interactability Binary_State; Interactability_Delay 0.25; Interactability_Reset 60; Interactability_Hint Door; Interactability_Editor Toggle) but for vehicles CTRL button

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
