### ISSUE TITLE
PSA: Some structure changes on preview branch

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#2717]
Everything should be backwards compatible, but it may be worth double-checking with your structure-related plugins.

The naming of some of these old types is bad, but there has been some cleanup to some old problems. `StructureDrop` holds a reference to its paired `StructureData`, so `StructureRegion.structures` is only kept for plugin compatibility. All of the coord+index methods are obsolete so the structures array does not have to exactly match between client and server.

**Comment by DiFFoZ** [comment]
Those changes will be included in the next version?

**Comment by SDGNelson** [comment]
Not this Friday (23rd). Next week I will hopefully get some barricade changes up on the preview branch as well. So maybe August 6th if it seems to be working properly. What broke in your plugins?

**Comment by GazziFX** [comment]
Will there be similar changes for barricades and items?

**Comment by DiFFoZ** [comment]
> What broke in your plugins?

Oh, just some old patches that required me some stuff and are now replaced with game and openmod events.

**Comment by SDGNelson** [comment]
Sorry for my delay. Yes: there will be similar changes elsewhere, I have currently been working on barricades last and this week.

**Comment by SDGNelson** [comment]
Good news! The plugin-affecting barricade changes are now on the preview branch. Just the client-side time slicing changes need to be added there.

**Comment by PandahutMiku** [comment]
> Good news! The plugin-affecting barricade changes are now on the preview branch. Just the client-side time slicing changes need to be added there.

Tested it out a bit and it seems nothing is broken. We've got an open source plugin (Schematics) that saves a configurable distance of structures/barricades around you into a file, and can spawn them all again at any other location, I think that's the most invasive plugin we've got, and it's completely fine without any updates.

Looking forward to the release of this and fixing lag lines for good.

Also, the send chat button looks a bit odd and is unnecessary for the vast majority of players, maybe make it togglable in settings and by default, off?

**Comment by SDGNelson** [comment]
Glad to hear it Miku! 

I still need to add an icon for the send chat button, but will see about making it less intrusive. If hidden behind an option I am not sure if the players for whom it might be useful would discover it - if there is backlash I will hide by default though.

**Comment by PandahutMiku** [comment]
A few minor things that would be nice to have:

Could we get destroyBarricade/destroyStructure methods in BarricadeManager/StructureManager that accept the barricade/structure region as well as x, y, and plant/ragdoll parameters? A lot of the time plugins will go up from the transform of the barricade/structure and get the BarricadeDrop/StructureDrop and the other info already.

It would be nice too if we had damage & repair methods for BarricadeManager and StructureManager that accepted the drop, x, y, region.

Do you plan on implementing new events (OnSalvage, OnDamage, etc) for BarricadeManager/StructureManager that pass just the actual BarricadeDrop instead of x, y + index, and such? It seems you are moving away from methods using the index, and it would be nice if the events didn't force plugins to get the BarricadeDrop / other info manually.


It would be helpful if the spawn barricade/spawn structure stuff returned the Structure/Barricade drop instead of just a transform. Internally it looks like it would be easy to pass up the drop instead of just grabbing the end of the drop list anyway, and a lot less error-prone.


Additionally, it looks like you finished and added the client-side stuff for barricades. I noticed that if you teleport into a region and then teleport far away whilst the region is still loading, some barricades will load in a bit after. I don't know if you just haven't finished with the barricades yet. I couldn't get it to happen with structures though, although maybe I just didn't have enough.

Thanks for your time.

**Comment by SDGNelson** [comment]
Thanks Miku! You are correct that all of the index stuff should be removed. All of the vanilla game indexing into those arrays was removed.

Good point: I will add new versions of those events without the x/y/plant/index.

As you noted, the API sucks a lot right now. In some places it could work to add a "DoThingV2" to change the return type or whatnot, but I am not entirely sure what to do about the "drop" classes whether they should be a component or not. The main thing to clean up first I think should be eliminating the public-facing "region" stuff so none of the tidied up public methods have x/y/plant parameters. Lots of the methods which take transforms have been marked obsolete.

I will check into that barricades spawning after leaving report - it should be cancelled as part of leaving the region... 🤔 

Definitely time-slicing the destruction should/will happen. The purpose of these initial changes is to allow the client to instantiate/destroy barricades and structures without falling out of sync with the server. Then in an update probably a few weeks from now I can add async loading, pooling, and time-sliced destruction.

**Comment by rube200** [comment]
Btw this update broke some patches since u keeped the name with dif parameters.
Another think can u fix those methods that just throw exception like claim stuff?

**Comment by SDGNelson** [comment]
@rube200 Any public methods that needed parameters changed were marked obsolete and got new versions. I cannot guarantee backwards compatibility for patching internal methods, only backwards compatibility for non-patched public methods. What do you mean fix methods which throw exceptions?

**Comment by rube200** [comment]
Public method example
BarricadeManager.ReceiveClaimRequest just vanished.
Old obsolete methods that use index just throw exception.

**Comment by rube200** [comment]
Public method example
BarricadeManager.ReceiveClaimRequest just vanished.
Old obsolete methods that use index just throw exception.

**Comment by rube200** [comment]
It doesn't directly affect me as I update my plugins, but I'm sure it will break many

**Comment by SDGNelson** [comment]
@rube200 `BarricadeManager.ReceiveClaimRequest` is called by the netcode, plugins should not be using it. One of the reasons the `ServerInvocationContext` constructor is private is to help make sure plugins do not call those. If you mean the methods which were marked obsolete back in April, then unfortunately they are fundamentally incompatible with this rewrite (index is not stable between client and server now that client can defer instantiation) which was one of the reasons for the pause between the RPC rewrite and this rewrite.

**Comment by SDGNelson** [comment]
@PandahutMiku the barricades appearing after leaving bug is extremely concerning because it sounds like it could leak or duplicate barricades on the client, but unfortunately I have not been able to replicate it yet. I tried placing [a ton of barricades](https://i.imgur.com/e28ax58.png), limited my client framerate so that I could teleport partway through loading, and then teleported in and out of range so that I left the region while only a few were loaded in. Would you perhaps be willing to share the Barricades.dat and Structures.dat from your server so I could try replicating using your setup please?

**Comment by PandahutMiku** [comment]
> @PandahutMiku the barricades appearing after leaving bug is extremely concerning because it sounds like it could leak or duplicate barricades on the client, but unfortunately I have not been able to replicate it yet. I tried placing [a ton of barricades](https://i.imgur.com/e28ax58.png), limited my client framerate so that I could teleport partway through loading, and then teleported in and out of range so that I left the region while only a few were loaded in. Would you perhaps be willing to share the Barricades.dat and Structures.dat from your server so I could try replicating using your setup please?

Sorry for the confusion, should have probably looked into it more than I originally reported it, but wasn't sure if you were even done with those changes yet.

It looks like the actual root of the error was because of a plugin that had spawned in a sentry and then called BarricadeManager.sendStorageDisplay. From that point on, my game was glitched, and everytime I teleported back and forth to unload/reload the regions, it was just staying in that glitched state where the regions couldn't properly unload.

The actual error it spit client-side was:

```[2021-08-02 19:26:59] Exception invoking SDG.Unturned.InteractableStorage.ReceiveDisplay deferred:
[2021-08-02 19:26:59] Object reference not set to an instance of an object
[2021-08-02 19:26:59]   at SDG.Unturned.InteractableSentry.refreshDisplay () [0x0007f] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.InteractableStorage.setDisplay (System.UInt16 id, System.Byte quality, System.Byte[] state, System.UInt16 skin, System.UInt16 mythic, System.String tags, System.String dynamicProps) [0x0003b] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.InteractableStorage.ReceiveDisplay (System.UInt16 id, System.Byte quality, System.Byte[] state, System.UInt16 skin, System.UInt16 mythic, System.String tags, System.String dynamicProps) [0x00000] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.InteractableStorage_NetMethods.ReceiveDisplay_DeferredRead (System.Object voidNetObj, SDG.Unturned.ClientInvocationContext& context) [0x00068] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.NetInvocationDeferralRegistry.Invoke (System.Object voidNetObj, SDG.Unturned.NetInvocationDeferralRegistry+DeferredInvocation invocation) [0x00035] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
```

And then when I went far enough to unload, it started spamming errors

```[2021-08-02 19:27:42] NullReferenceException
[2021-08-02 19:27:42] UnityEngine.Component.GetComponent[T] () (at <451019b49f1347529b43a32c5de769af>:0)
SDG.Unturned.BarricadeRegion.destroy () (at <18563b3e45d647ceb7e8fe6d3056b174>:0)
SDG.Unturned.BarricadeManager.onRegionUpdated (SDG.Unturned.Player player, System.Byte old_x, System.Byte old_y, System.Byte new_x, System.Byte new_y, System.Byte step, System.Boolean& canIncrementIndex) (at <18563b3e45d647ceb7e8fe6d3056b174>:0)
SDG.Unturned.PlayerMovement.updateRegionAndBound () (at <18563b3e45d647ceb7e8fe6d3056b174>:0)
SDG.Unturned.PlayerMovement.simulate (System.UInt32 simulation, System.Int32 recov, System.Int32 input_x, System.Int32 input_y, System.Single look_x, System.Single look_y, System.Boolean inputJump, System.Boolean inputSprint, UnityEngine.Vector3 clientResultPosition, System.Single delta, System.Boolean clientEnteredTeleporter) (at <18563b3e45d647ceb7e8fe6d3056b174>:0)
SDG.Unturned.PlayerInput.FixedUpdate () (at <18563b3e45d647ceb7e8fe6d3056b174>:0)
```


But at least when I went back in the bugged-out regions, it didn't double spawn the barricades or anything, it already knew they were spawned.

```[2021-08-02 19:31:33] Exception while spawning barricade: 1297
[2021-08-02 19:31:33] An item with the same key has already been added. Key: 0000CE49
[2021-08-02 19:31:33]   at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000c1] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at SDG.Unturned.NetIdRegistry.Assign (SDG.Unturned.NetId key, System.Object value) [0x00000] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.BarricadeDrop.AssignNetId (SDG.Unturned.NetId netId) [0x00007] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
  at SDG.Unturned.BarricadeManager.spawnBarricade (SDG.Unturned.BarricadeRegion region, System.UInt16 id, System.Byte[] state, UnityEngine.Vector3 point, System.Byte angle_x, System.Byte angle_y, System.Byte angle_z, System.Byte hp, System.UInt64 owner, System.UInt64 group, SDG.Unturned.NetId netId) [0x0017f] in <18563b3e45d647ceb7e8fe6d3056b174>:0 
```


[Client.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6920102/Client.log)

The "catch" is that it seems the bug only works if the regions you are around have enough barricades in them to be defer loaded over a few seconds. This only happens with sentries, although using sendStorageDisplay on trophy cases still doesn't visually update what is in them for clients. You might be able to spot the issue right away with it, but if not, I could get it working 100% of the time If I just teleported to Alberton (default PEI) on this map and spawned a barricade using this:

[map.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6920220/map.zip)


```csharp
                    var barricade = new Barricade(1373); // ID of hostile sentry
                barricade.state = Convert.FromBase64String("yeObCgEAEAEAAAAAAAAAAAEAAAAEAAFkEgUAAAAAAAAABgAeAQFkZGRkZAAAAAAAAAA=");// Example eaglefire in sentry
                    var barricadetransform = BarricadeManager.dropNonPlantedBarricade(barricade, YourPosition, new Quaternion(0, 0, 0, 0), YourSteamIdUlong, 0);
                var InteractableStorage = barricadetransform.GetComponent<InteractableStorage>();
                if (InteractableStorage != null) BarricadeManager.sendStorageDisplay(barricadetransform, InteractableStorage.displayItem, InteractableStorage.displaySkin, InteractableStorage.displayMythic, InteractableStorage.displayTags, InteractableStorage.displayDynamicProps);
```

I only post all this because I would imagine that players themselves could do this if they interacted with items at exactly the wrong time.

The reason why plugins use sendStorageDisplay is because when you first spawn a barricade, the interactable's state doesn't get updated/sent to the client. So they see an empty sentry/no gun. Using sendStorageDisplay to update the client's visual display of sentries/trophy cases worked fine before the netcode rewrite. 

Hopefully, this isn't the start of finding more one-off issues with a barricades updating while deferred or anything like that.

Please let me know if you need more details.

**Comment by SDGNelson** [comment]
Thank you @PandahutMiku for all this detailed information! Off the top of my head I am not sure what could be happening here because I did test with sentry guns before the first upload. 🤔 I will give it a try with your example code spawning the hostile eaglefire sentry, and will also check into these other exceptions to protect against similar potential problems sneaking through.

**Comment by SDGNelson** [comment]
Thanks again @PandahutMiku! Your example code was very helpful to replicate and track down the problem. After enabling all of the netcode debug features and some head-scratching the bug was tracked-down and should be fixed in the current preview version. Regarding the three different points:
1. The underlying bug is embarrassing in retrospect. There are more unit / integration tests for the netcode rewrite than the rest of the project combined. But I copy-pasted a typo between all the tests for the new deferral code, so they were passing when they should have failed. I added a bunch more sanity checks, warnings, errors, etc that should be useful regardless, but once I realized the tests were wrong it became apparent there was a buffer offset problem in the new deferral code causing the sentry bug.
2. Since the sentry was in a bad state it was not cleaned up properly when leaving the region which prevented other barricades from being cleaned up, so I have added a catch in some relevant places to ensure the region is empty when re-loaded.
3. Re-assigning a net id should never happen, but now if it does it will log an error and reassign rather than throwing an exception to avoid breaking the game more that it already must be in the state.

Your sentry code should work again in the current preview version! 🤞

**Comment by PandahutMiku** [comment]
> Thanks again @PandahutMiku! Your example code was very helpful to replicate and track down the problem. After enabling all of the netcode debug features and some head-scratching the bug was tracked-down and should be fixed in the current preview version. Regarding the three different points:
> 
> 1. The underlying bug is embarrassing in retrospect. There are more unit / integration tests for the netcode rewrite than the rest of the project combined. But I copy-pasted a typo between all the tests for the new deferral code, so they were passing when they should have failed. I added a bunch more sanity checks, warnings, errors, etc that should be useful regardless, but once I realized the tests were wrong it became apparent there was a buffer offset problem in the new deferral code causing the sentry bug.
> 2. Since the sentry was in a bad state it was not cleaned up properly when leaving the region which prevented other barricades from being cleaned up, so I have added a catch in some relevant places to ensure the region is empty when re-loaded.
> 3. Re-assigning a net id should never happen, but now if it does it will log an error and reassign rather than throwing an exception to avoid breaking the game more that it already must be in the state.
> 
> Your sentry code should work again in the current preview version! 🤞

I'm happy that this was caught before the update went live, it would have been a lot more difficult to track it down then.

I tested and couldn't replicate it again, seems all fixed now.


One other thing that I think is worth mentioning, I think it would help a lot if the region system prioritized loading in the closest regions to the player, and then expanding outward.

For example, on a map pulled from our Roleplay servers, where there are about 5-6k elements in Seattle, it takes about 30 seconds for it to load in the bed/barricades strictly around me. It's a bit more annoying than it looks too, as if you went to leave your apartment/base, you would get lagged back through the door thanks to movement verification, so you're just kind of stuck there for a bit. It's still better than game freezing though.


https://user-images.githubusercontent.com/17209937/128023600-bd0f7893-b30c-41a6-ac8e-e0272bbf4024.mp4

If having the map helps:

[Map.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6924433/Map.zip)

To be fair, this is a lot less noticeable on vanilla servers, as people kind of naturally space out their bases, and even the largest sky bases are only ~1-2k elements and load in about 10 seconds max. I'm not sure how difficult it would be, but it would probably be best if it first loaded the immediate regions around you, and did it more aggressively than loading other further away regions. That way as you move around, if you get too close to a region, it will aggressively load in the region. This would also help any potential issues with fast vehicles, like jets or modded vehicles, where because there's no movement verification for them, people could potentially drive right through bases as they slowly load in. That being said, depending on how difficult it is, it might not be worth it.

**Comment by SDGNelson** [comment]
@PandahutMiku phew! I agree that is annoying. It would make sense to prioritize loading by distance. Thanks for the example map data! I will experiment around with some changes on your map:
- As a placeholder currently 5 barricades, 5 structures, and 10 items are instantiated per frame. But 10-30 seconds to finish is pretty slow. My original inclination was to try budgeting a certain amount of time (e.g. 1ms) to deferred instantiations, but that could still take a while if the time per barricade is too slow. Perhaps min 5 + a percentage (20%?) of the total number per frame would do the job.
- Once we have a better spatial data structure it will be faster to find the X nearest barricades to instantiate, but for the meantime I will test how it would perform to simply sort by distance to the camera.

**Comment by SDGNelson** [comment]
Following up on some of the changes I just uploaded:
- Doing a percentage was awful because the client drops to unplayable FPS for quite a while. Perhaps worse than not time-slicing at all! What I settled on for now is budgeting 1ms per frame for items, barricades, and structures each, but always instantiating at least 5 of each per frame even if it goes over the time budget.
- An interesting complication with sorting the instantiations is the client camera position may be wrong, such as when the server is teleporting the player and sending barricades in the new surroundings. What I settled on is the server sending the distance from the center of a chunk of barricades (applies to items and structures too) so the client inserts all of the items in the chunk into the same spot in the pending list, but for single entries it will calculate client side. This also has the nice benefit that placing a new barricade nearby while still loading is immediately prioritized.

**Comment by PandahutMiku** [comment]
Thanks for making those changes!

Went from ~30s like in the video to around ~5s, a lot better!

Even flying a jet into Seattle on that map is silky smooth. The only thing that causes freezes now is just unloading the region, but even for the ~6k elements in Seattle it's still only a micro-freeze for ~2s. If you need a map to test making unloading deferred when you eventually get around to it, on that same test map heading out of Seattle on Rainbridge towards Kent Raceway, you get a micro-freeze from unloading the regions further back in Seattle. It's still so much better than before though, the freeze you get when leaving is minor.

**Comment by SDGNelson** [comment]
That is exciting to hear! I was intending to add the deferred unloading alongside pooling and async loading in the next-next update, but I am itching to add it - just nervous of more potential problems. Will see about it tomorrow / how straightforward it would be to do.

**Comment by SDGNelson** [comment]
Deferred unloading is up on the preview branch! I did see an exception related to barricade + electricity when disconnecting which I need to track down, but not sure whether it was related to this change yet.

**Comment by PandahutMiku** [comment]
Lag lines are completely gone, flying a jet in and out of Seattle is smooth sailing besides a few minor fps drops. However, there's a few bad edge-case bugs.

The first is a strange bug with barricades not being properly unloading and persisting to even the main menu
![image](https://user-images.githubusercontent.com/17209937/128296128-1e370d36-4185-4ab7-96bb-c148d5e1f95c.png)
[Client-copy.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6936130/Client-copy.log)

This bug is really hard to track down to replicate. I tried for 3 hours and really still don't know much about it. I tried with 30k barricades right next to me and entering and leaving quickly, waiting to load and leaving, fresh map placing stuff, and tons of other silly things and none of them could get it to happen repeatedly. The only thing is that as far as I remember it never happened once without me having to place down something first like a metal plate, and then it would sometimes happen, maybe once per 4-5 tries. The logs indicate that on rejoining the game properly knew the barricades were still there and didn't spawn them again, so maybe it's not worth trying to hunt down much more, but just really odd. Something refusing to clean properly, everytime it happened it was accompanied with the generator error.

The second bug is a lot more repeatable, just a native exception when you disconnect while there is regions unloading.
```[2021-08-05 01:00:37] Exception destroying barricade 1281 - Wardrobe_Metal:
[2021-08-05 01:00:37] 
[2021-08-05 01:00:37]   at (wrapper managed-to-native) UnityEngine.Component.GetComponentFastPath(UnityEngine.Component,System.Type,intptr)
  at UnityEngine.Component.GetComponent[T] () [0x00021] in <c394b859740447d7b53708bfc9738b1c>:0 
  at SDG.Unturned.BarricadeDrop.CustomDestroy () [0x00006] in <71164b9ab2c94880bf7243f5a60e21f8>:0 
```
[Client_Prev.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/6936150/Client_Prev.log)

I could repeat this easily by using the test washington map above, just going to the middle of seattle to ensure loading of all the seattle regions, and heading towards Kent raceway on the Rainbridge, about when you pass the Washing machine in the road you start to unload the regions, instantly just disconnect. It threw the error everytime as long as I disconnected fast enough. You could probably replicate this anywhere with enough elements or capping your fps.

**Comment by SDGNelson** [comment]
I am surprised (but happy to hear) that the lag lines are gone for you! In my testing on your Washington save I did still experience framerate drops, but certainly expect it to significantly improve further with future work.

The first bug you experienced there is I _hope_ the not-resetting-during-disconnect fix, which I thought I had uploaded but did not - sorry my bad. I will queue the upload now. (patch 251)

Unsure about the second bug though! I have never seen that exception in Unity before. Perhaps related to this month's LTS update? Will investigate. 😕

**Comment by iBowie** [comment]
Well, it probably doesn't matter since this is mostly just for a meme, but i have something to say.

My plugin for Bad Apple is still working on preview, no code-wise changes, and still working. Yet i have to notice that server-wise perfomance is mostly the same, it still can't produce stable 30 fps in 'i-frames' and stutters, client-wise perfomance is... Well, it's working without lags for sure, but there is a catch...

Comparison here:

[How it was before](https://www.youtube.com/watch?v=tIIvySxM3Bg)
[How it is now](https://www.youtube.com/watch?v=vCzX090LJVY)

Again, it's not critical, it's just more of a FYI, that way it is much more clear what exactly was changed.

**Comment by SDGNelson** [comment]
@iBowie interesting to see the original video! This update should not affect server performance either positively or negatively. The main goal of this update is to allow the client to locally manage the buildables without falling out of sync with the server. The next related improvement that would help server performance would probably be when sending barricades can be spread over multiple frames, hysteresis for unloading, and removing the stupid "state" mess in SendRegion.

**Comment by PandahutMiku** [comment]
> I am surprised (but happy to hear) that the lag lines are gone for you! In my testing on your Washington save I did still experience framerate drops, but certainly expect it to significantly improve further with future work.
> 
> The first bug you experienced there is I _hope_ the not-resetting-during-disconnect fix, which I thought I had uploaded but did not - sorry my bad. I will queue the upload now. (patch 251)
> 
> Unsure about the second bug though! I have never seen that exception in Unity before. Perhaps related to this month's LTS update? Will investigate. 😕

I'm not able to replicate the second bug after the update at all. Before it was really easy to do so as I described above, even just teleporting away and disconnecting right away would do it. Now, I tried repeatedly and it seems patched. Probably because you made it abort doing any deferred stuff when the client isn't connected..?

Do you plan on pushing this Friday like you discussed before or waiting for another week and trying to give people more chance to test it out and such?

**Comment by SDGNelson** [comment]
@iBowie On second thought, a suggestion that should work before and after this update: keep a pool of white and black barricades, and rather than destroying them use `BarricadeManager.ServerSetBarricadeTransform` to move them into visibility or below the map. Note only move them vertically below the map, otherwise the client may destroy them if they move out of range horizontally.

@PandahutMiku I think it should be ready to go Friday! Unless anything comes up today. 🎉

**Comment by PandahutMiku** [comment]
> @iBowie On second thought, a suggestion that should work before and after this update: keep a pool of white and black barricades, and rather than destroying them use `BarricadeManager.ServerSetBarricadeTransform` to move them into visibility or below the map. Note only move them vertically below the map, otherwise the client may destroy them if they move out of range horizontally.
> 
> @PandahutMiku I think it should be ready to go Friday! Unless anything comes up today. 🎉

I noticed that the "findStructureByInstanceID" and "findBarricadeByInstanceIDs" methods were marked as dead code. Do you plan on removing Instance IDs completely? We don't use those methods directly so I didn't notice until now, but we do use Instance IDs to identify unique barricades/structures after full restarts, to do things like making a door in a police station open if a police officer punches/points at it.

**Comment by SDGNelson** [comment]
@PandahutMiku do not worry, instance ids are here to stay, and if anything should be added to other systems! The important (but subtle) distinction here is that the deprecated methods return `BarricadeData` and `StructureData`. In the very early versions there was a clear split between the client-side `Drop` and server-side `Data`. Which is why there is the unfortunate drops and data list problem. Back then I viewed the `BarricadeData` class as the actual barricade, and the `BarricadeDrop` was basically a wrapper around the game object. Now it is the opposite however. `BarricadeDrop` contains most of the info, new code refers to it as the Barricade, and `BarricadeData` is partially deprecated. It should hopefully not be too long before `BarricadeData` ONLY exists for backwards compatibility.

**Comment by PandahutMiku** [comment]
> @PandahutMiku do not worry, instance ids are here to stay, and if anything should be added to other systems! The important (but subtle) distinction here is that the deprecated methods return `BarricadeData` and `StructureData`. In the very early versions there was a clear split between the client-side `Drop` and server-side `Data`. Which is why there is the unfortunate drops and data list problem. Back then I viewed the `BarricadeData` class as the actual barricade, and the `BarricadeDrop` was basically a wrapper around the game object. Now it is the opposite however. `BarricadeDrop` contains most of the info, new code refers to it as the Barricade, and `BarricadeData` is partially deprecated. It should hopefully not be too long before `BarricadeData` ONLY exists for backwards compatibility.

Thanks for clarifying! Just wanted to be sure that support for them wasn't being dropped.

One last request:
It would be useful if onDamageBarricadeRequested/OnDamageStructureRequested had a new event that passed the Barricade/Structure drop itself instead of the transform. You did this for Salvage event and one other, and the BarricadeDrop is already known to both methods that call the event, it just doesn't use it. These are some of the most used events.

Thanks for your time, we'll be sure to watch out and report any bugs during the update tomorrow!

**Comment by SDGNelson** [comment]
@PandahutMiku Thanks Miku! Damage requested would perhaps already be a good candidate to fix up, but the reason the salvage and harvest events specifically were updated is that they still had an index parameter. Ideally I want to unify some of the damage code. On the one hand who knows when that will be so maybe slightly-updated events should be added, but on the other hand if it ain't broke (and ain't fully fixed?) then don't fix it. Hmm :/

Fair points about the potential complaints. I will make a note to address in the update notes that this is better-ish, but not perfect yet by any means. Regarding the framerate limit it should hopefully not be too exploitable because it will budget at least 1ms. When the server becomes responsible for telling client to unload that might be useful to configure for PvP. And once these new features are made more generic, i.e., they all share a common instantiate/destroy prioritization, then we could maybe prioritize within the view frustum.

**Comment by iBowie** [comment]
> @iBowie On second thought, a suggestion that should work before and after this update: keep a pool of white and black barricades, and rather than destroying them use `BarricadeManager.ServerSetBarricadeTransform` to move them into visibility or below the map. Note only move them vertically below the map, otherwise the client may destroy them if they move out of range horizontally.

@SDGNelson 
I was able to not only make it stable without any barricades disappearing, i made it... stable 30 fps! And after that, i've gone even further beyond - 60 fps!
You truly are a mad lad!

If you're interested in seeing it - [here it is](https://www.youtube.com/watch?v=Ri17m7bi020)

**Comment by SDGNelson** [comment]
@iBowie Haha that did turn out really well! Now when is the "high-res" version using small plates? 😁

@PandahutMiku thanks again for all your help! Fingers crossed hopefully the average player can fly across Seattle now. ❤️

**Comment by GazziFX** [comment]
@SDGNelson Will there be new buildings damage events to reduce number of FindBarricadeByRootTransform calls?

**Comment by SDGNelson** [comment]
@GazziFX PandahutMiku's earlier question and my response go into more detail on this, but for the meantime the performance from the FindBarricadeByRootTransform should be the same as before because previously plugins were doing the lookup for BarricadeData, and now they are doing the lookup for BarricadeDrop.
