### ISSUE TITLE
[Suggestion to improve game chat]

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#2727]
**Suggestion to improve game chat**

Add the ability to expand and move the chat area on the game screen. This change will improve much of the server where players use in-game chat to communicate, as well as text RPs. It would be great if such a feature appeared in Unturned!

**Comment by Jdance-Media** [comment]
I agree that this feature would help people in Unturned, but for now I personally think preferences.json does the trick just fine.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
