### ISSUE TITLE
Add OnPlayerJumped event

### ISSUE THREAD

**Issue by DiFFoZ** [SmartlyDressedGames/Unturned-3.x-Community#2738]
Some plugins maybe need this event. For example, counting how much player is jumped.

**Comment by Jdance-Media** [comment]
Agreed

**Comment by DiFFoZ** [comment]
If someone needed this event you can check how it is implemented in `OpenMod`: https://github.com/openmod/openmod/pull/636

**Comment by sunnamed434** [comment]
> If someone needed this event you can check how it is implemented in OpenMod: [openmod/openmod#636](https://github.com/openmod/openmod/pull/636)

this event implement so bad, could be nice if there is would be smth like jumpState, but there is no, and this event happens weird, after player jumped, event made not convenient

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
