### ISSUE TITLE
[FEATURE REQUEST] Barricade Condition

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2739]
Requesting to add a condition that you need to be within a set distance of a specified barricade. Given that blueprints support conditions perfectly fine, adding this would effectively allow for custom crafting stations to work without a problem, and greatly expand the crafting that people would be able to do, such as ammo stations, sawmills or other industrial things to diversify crafting.

**Comment by GlockStone** [comment]
This is what Unturned needs... Bro, just imagine more complex crafting. Players could take crafting from basic and mediocre at best to something that has the player actually do something productive. It creates a tier system similar to Starbound, one of my favorite games. In Starbound, the player has to create several different crafting stations to upgrade their gear. They aren't able to just go out and forage the supplies and craft a superweapon in their inventory. Instead, they have to first craft dozens of different workstations. Please, Nelson, I beg you to add this to the game.

**Comment by SDGNelson** [comment]
I agree this would be useful, and is something I have been intending to add. But no ETA.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
