### ISSUE TITLE
[Feature Request] Animation Event Hook

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2740]
Requesting a way to detect what animation a held item is going through and using it as a unity trigger. Would be useful for creating on reload, inspect, aim effects or even for adding in animated parts.

**Comment by SDGNelson** [comment]
There is a plan for this, but no ETA.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
