### ISSUE TITLE
Please Nelson, more barricades/structures working events

### ISSUE THREAD

**Issue by Jtinha2000** [SmartlyDressedGames/Unturned-3.x-Community#2751]
Please Nelson, I beg you... Add more **Barricades/Structures** events

**Comment by rube200** [comment]
Like?

**Comment by SDGNelson** [comment]
Which events do you have in mind?

**Comment by Jtinha2000** [comment]
Well, there are already certain requests that exemplify what I would like to do, such as Pustalorc's at #2539 , but without a doubt I would like events from before the player place the barricade, when he removes it, when it is destroyed by damage among other things, sorry to being so vague, the Pustalorc request already give with details what i want .0.

**Comment by SDGNelson** [comment]
For "before the player place the barricade" you can use onDeployBarricadeRequested, but true there are still gaps missing in what Pustalorc's request asked for.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
