### ISSUE TITLE
suggstion, rain puts out fire zombies

### ISSUE THREAD

**Issue by ddxn78096** [SmartlyDressedGames/Unturned-3.x-Community#2758]
rain puts out fire zombies if they are not in building

**Comment by Jdance-Media** [comment]
You know what, this is actually reasonable. Would add another benefit for having rain.

**Comment by Ongjming** [comment]
Came across this: https://steamcommunity.com/app/304930/discussions/9/5056966106386128741/
RGF was mentioning about the fire zombies underwater.
Thought it is similar and thus posting it here as well.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
