### ISSUE TITLE
[FEATURE REQUEST] Item animation override for the entire body.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2760]
Currently in unturned, you can only animate arms for items. I think this can bring alot more possibilities to item animations.

**Comment by SDGNelson** [comment]
I agree it would be useful of course. Currently the item directly overrides the arm animations, so we would probably need to see about updating to one of the newer Unity animation systems.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
