### ISSUE TITLE
Sync the head position with the Stance

### ISSUE THREAD

**Issue by Jtinha2000** [SmartlyDressedGames/Unturned-3.x-Community#2775]
When the Player updates the stance, the player head position don't updates ;-

**Comment by SDGNelson** [comment]
What do you mean?

**Comment by Jtinha2000** [comment]
When the Player updates he Stance (Crouch/Climb/Prone), his Look doesn't follow correctly, like:
Orange is the player look, ignore the green

In this case, if the player look for his foots, he will see herself:
![unkn1own](https://user-images.githubusercontent.com/77682013/129964175-51969a79-5c3f-43c5-bb59-08081fecac15.png)

Also happens here, but for all the sides, less up
![unknown](https://user-images.githubusercontent.com/77682013/129963854-4b34c9aa-35a7-4ea6-af17-b0754172eee3.png)

(MVP_Wendi#3074 will probably have more information than me, as he helped me fix this in my plugin).

**Comment by SDGNelson** [comment]
It would be nice for the camera position to more closely match the animation position, but there are trade offs. If the camera moved forward to match the head it would leave the collision capsule, and we already have problems with the near clip plane passing into surfaces. Otherwise if the crouching model head stayed in the center of the capsule the legs of the character would be further back poking through walls. Not a big deal / not a priority but might be improved if the animations get a revamp. If I were making a new game I might approach it differently.

**Comment by Jtinha2000** [comment]
I thinks a variable with the correctly camera position already will be good, like Position for parameters in the game code, and CorrectlyPosition for plugins
