### ISSUE TITLE
Battleye kick people for no reason and can't ban people how cheat

### ISSUE THREAD

**Issue by Peubo** [SmartlyDressedGames/Unturned-3.x-Community#2779]
Battleye keep kick people in my server for no reason.
Just 1 people cheat and i don't know him and battleye can't ban him or kick him.
He be vanish and Handcuffs all people in my server.help pls

**Comment by SDGNelson** [comment]
What BattlEye kick reason is logged? Cheaters cannot handcuff players unless they are in the surrender state (verified server side), and cannot go invisible.

**Comment by warren39** [comment]
Sometimes, If the BattlEye of your Unturned server cannot connect to the BattlEye server, Your server will kick all players with reason like 'Query Timeout'.

**Comment by Peubo** [comment]
[2021-08-22 22:04:12] BattlEye Print: Player #21 alpha (78.242.183.143:51979) connected
[2021-08-22 22:04:12] BattlEye Print: Player #21 alpha - BE GUID: 74de282b0a4ffbefd771af398b1d150d
[2021-08-22 22:04:12] Connecting: PlayerID: 76561198806181657 Name: alpha Character: DucLucas Scorp

**Comment by Peubo** [comment]
in my server the cheat unadmin all people

**Comment by Peubo** [comment]
i need help

**Comment by Peubo** [comment]
@ SDGNelson

**Comment by SDGNelson** [comment]
Cheats cannot unadmin people because admin status is entirely server-side. Those messages are regular BattlEye output, not kicks. From what you described perhaps one of your admins is abusing their powers - unadmining others, using vanish, kicking players, etc?

**Comment by nanashi88** [comment]
a lot of default game commands are bugged if you don't type it carefully.

for example: if you or one of the admins wanted to do /admins to get the list of all admins, but he make a typo and do /admin instead, then a random online player will get adminned! though the command was empty without mentioning player name or ID.

same if you do /admin  [player_name]
there are two white space between /admin and [player]
also in this case, a random player will get adminned!

same with some other commands like: /ban  nanashi
won't ban me but will ban some other random player :P (because of the double space)

this bug cause a lot of trouble with staff realizing, including banning innocent players, and giving admin perms to random people!

@SDGNelson sorry for not reporting this bug before, it is very old to the degree I have forget about it!

**Comment by SDGNelson** [comment]
Thanks for the report @nanashi88! I think this might have been fixed recently actually (#2737) I will check into it. The built-in command system does kind of suck and I would like to revamp it at some point.

**Comment by nanashi88** [comment]
@SDGNelson thank you for fixing it 👍 

I just checked /spy /kick /ban /admin
it is not bugged anymore when empty
and not bugged anymore when there is double space

I withdrew my previous statement : "a lot of default game commands are bugged if you don't type it carefully."
for me now all is good :)

**Comment by SDGNelson** [comment]
@nanashi88 phew glad to hear it!
