### ISSUE TITLE
[FeatureRequest] ShowExpreience type in EPluginWidgetFlags.

### ISSUE THREAD

**Issue by Cubody** [SmartlyDressedGames/Unturned-3.x-Community#2782]
Hey. I really want to hide the default UI and replace it with my own, but this is impossible, please add EPluginWidgetFlags.ShowExperience =)

It's better to make all Glazier UI customizable.

**Comment by Sl4vP0weR** [comment]
I think clientside Glazier UI access for serverside will be so usefull for developers/server-owners, also ability to create custom Glazier UI will be useful too.

**Comment by DiFFoZ** [comment]
Custom UI is in ToDo: https://trello.com/c/crkUBc1q/9-custom-ui

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
