### ISSUE TITLE
[Feature Request] Add a camera control system.

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#2796]
Hi, like the title said, I want a camera control system for plugin developers, due right now you only can enable/disable the _option_ to enter in the admin cameras, but it would be nice if, with some code, we can force the player to join into this modes and options to set the camera in specific positions, I also like, not necessary, know the camera position to know what the player are looking at.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
