### ISSUE TITLE
[Feature Request] The ability to spawn animal without adding spawn point

### ISSUE THREAD

**Issue by nanashi88** [SmartlyDressedGames/Unturned-3.x-Community#2814]
Hi,

I wonder why "/animal" command spawns "animal spawn point" along with the spawned animal?!
is this a desired behaviour for some reason?

If it is on purpose, it would be nice to have a method similart to AnimalManager.spawnAnimal but without adding animal spawn point to that location.

This is not an urgent request, I am not even sure if I gonna continue my plugin for buying animals ...

**Comment by SDGNelson** [comment]
As you say, it is not a desired behaviour. Just a side effect of how the animals work. The /animal command was added for conveniently testing new animals, but is not ideal. I think this would be most likely to be addressed if/when the animals are updated to the newer network features.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
