### ISSUE TITLE
[Feature Request] ItemCaliberAsset change gun ballistics

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#2815]
Would be nice to have ballistic drop and travel multipliers for different ammo types

**Comment by FoxDevUnt** [comment]
Yeah this nice idea

**Comment by nanashi88** [comment]
@GazziFX why don't you add nice features like bullet trace ?! if you ask Coopy nicely he might give you some peice of code!
AH, NVM, YOUR undead IS LONG TIME DEAD! BY NOW IT IS ROTTEN AND STINKING!

**Comment by GazziFX** [comment]
> @GazziFX why don't you add nice features like bullet trace ?! if you ask Coopy nicely he might give you some peice of code!
> AH, NVM, YOUR undead IS LONG TIME DEAD! BY NOW IT IS ROTTEN AND STINKING!

Im developing server with a lot of unique features.
For hacks I have 100% undetectable bypass, so if you want another nightmare you'll get it

**Comment by nanashi88** [comment]
I sooo scared! Gazzi's kids gonna be able to cheat again and give me nightmare XD

**Comment by nanashi88** [comment]
anyway @GazziFX , good luck on your new project, and good luck getting rid of your old project (it doesn't need to be gradual, why does it need to be gradual while you can press shift delete?! are you feeling sad to remove your community?! do you really think they respect you ?! or do you think it brings pride to you?! **it is exactly the opposite!** )

note: later on, I will remove this post and the previous one, since it doesn't contribute to this issue topic.

**Comment by GazziFX** [comment]
@nanashi88 I wont remove community, but already closed it, since I don't have time for both projects. And new project is 2 years in dev, and also tried making own games. In future I want to make messenger like Discord but with asymmetric crypt, because I no longer feel safe in social networks

**Comment by nanashi88** [comment]
I guess I got some misleading hope!
if you are not removing your entire community that mean it is like the other times! I aready saw you doing this multiple times by now! then later on after you see a chance you get back into cheats!

shake your head a bit and look above! you are at the bottom!
as long as you stay in cheats, then you don't receive any respect!
as long as you stay in cheats, then your other projects are not trusted!
as long as you stay in cheats, then you are as pathetic as the Eggs and Balls kiddo!

**Comment by nanashi88** [comment]
no need to chat more! let us see acts!

I am removing the older posts, and will remove this soon ( after you read it, so please react with it so I know you read it)

**Comment by rube200** [comment]
@nanashi88 this is not day care.
This github repository is used to report issues or request features for the game.

**Comment by nanashi88** [comment]
@rube200 if there are bugs, then there might be exceptions!
in my opinion, the existance of this guy here is a bug!
I would have said much more harsh words, but I refrain because he is showing little positive signs for positive change!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
