### ISSUE TITLE
Issue with double quotes in a string

### ISSUE THREAD

**Issue by TH3AL3X** [SmartlyDressedGames/Unturned-3.x-Community#2829]
I am trying to put the reason for a ban and it detects it as the format is wrong, before it worked perfectly, I don't know what you did Nelson to make this stop working

`R.Commands.Execute(null, $"ban {unturnedPlayer}/\"Reason hello\"/300");`

For some reason the double quotes have stopped working in the strings, both in the console and in Rocket Execute

**Comment by SDGNelson** [comment]
It looks like the problem is with spaces in vanilla commands, but I am not sure what the cause is yet because nothing related was touched recently. Will check into it.

**Comment by SDGNelson** [comment]
When I tried this today on a local build it seemed to be working fine. Then I tried again with the release server and reproduced the same issue. The difference between the two was Rocket, disabling Rocket meant the commands worked as-expected. It looks like the reason spaces do not work when using vanilla commands in Rocket is that Rocket parses the arguments, and then calls String.Join in `UnturnedVanillaCommand.Execute`. I would recommend calling the ban method rather than relying on the command inputs.

**Comment by TH3AL3X** [comment]
For some reasons Provider.ban and others do not work for me, besides that I do not know how to implement it to ban a player who is not in-game

> When I tried this today on a local build it seemed to be working fine. Then I tried again with the release server and reproduced the same issue. The difference between the two was Rocket, disabling Rocket meant the commands worked as-expected. It looks like the reason spaces do not work when using vanilla commands in Rocket is that Rocket parses the arguments, and then calls String.Join in `UnturnedVanillaCommand.Execute`. I would recommend calling the ban method rather than relying on the command inputs.
