### ISSUE TITLE
Changing to OnMouseButtonDown instead of Fire()?

### ISSUE THREAD

**Issue by SMDIndomitable** [SmartlyDressedGames/Unturned-3.x-Community#2836]
Dear Nelson,

Is it possible that you change the Useable Gun Event Hook from OnShotFired() to OnMouseButtonDown()? I think this would unlock the potential of making charge-up animations for weapons. For example, there is an option to delay fire using "Fire_Delay_Seconds 1.0", it would be better if the event detect the mouseButtonDown instead of it being fired because if the delay isn't there, the mouseButtonDown does the same thing as Fire. However, if the delay is there, it can only call the OnShotFired() after the delay. What do you think?

Yours Sincerely, 
SMD

**Comment by SDGNelson** [comment]
Cool idea. Rather than specific input events I could add an event specifically for *before* firing that would happen when the delay starts.

**Comment by SMDIndomitable** [comment]
Thank you :D, looking forward to it!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
