### ISSUE TITLE
[Feature Request] Ability to have a single animation for both hammer and reload animations.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2839]
It wouldn't make the full reload look weird for stripper clip bolt action rifles or some rifles with a bit of momentum.

**Comment by SDGNelson** [comment]
To clarify, if I understand correctly you mean that regardless of whether the ammo is zero it would only play one animation? (not both reload + hammer) Would an option to simply disable the rechambering at zero ammo do the trick?

**Comment by DerEnte** [comment]
By full reloads I mean the character reloads and chambers the gun in 1 go instead of doing the reload and then chambering it.

**Comment by SDGNelson** [comment]
Ah, yes that would definitely look much nicer and smoother.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
