### ISSUE TITLE
[Feature Request] Road hole volume.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2840]
Same as the terrain hole volume just for roads. This would be useful to make 3d potholes or just road cutoffs.

**Comment by Ongjming** [comment]
#2722 I feel it might be similar to this.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
