### ISSUE TITLE
[Feature Request] Key combos as plugin hotkeys

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#2844]
Ctrl + 1-10 would be really nice to have, maybe something similar and **easy to use** (unlike current defaults)

Why specifically _alt_:
- _shift_ is used for sprint, so it's not the best option
- _alt_ is used for voice chat, so ain't great either
- ctrl doesn't seem to be interfering with anything

Note that this would need to not trigger the press of 1-10 (that switches weapons/equipment)

**Comment by surv0013** [comment]
I use [Ctrl] to сrouch.

I still believe that we should not look for an alternative, but give the developers all the keys, there is no reason to limit this possibility.

Someone started a rumor that then it would be possible to steal passwords, but this is not so, because the **keys are sent only when the game window is open and selected**, otherwise the keys are not registered by game.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
