### ISSUE TITLE
[Feature Request] Vanilla NPC override

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#2846]
Example would be like, being able to change the vanilla NPC's looks and what they say and vendor. For override mods catering to singleplayer experiences on vanilla maps or servers using vanilla maps. The NPCs would still be stationed at wherever they are placed at, just that their conversation is changed/added upon.

Not sure if this can be done kinda like how Spawn tables can be tagged onto existing tables as an append or completely override the existing table's values.

Just a feature request, not an issue. Started this new topic since I could find none via a quick search.
Thanks!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
