### ISSUE TITLE
[Feature Request] Item Deletion Volume

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#2847]
A volume that removes items similar to how the kill volume kills players on contact, can be used with kill volumes to destroy items that go into inaccessible areas to reduce lag for players in cases where up to hundreds of items have been dropped and haven't yet despawned.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
