### ISSUE TITLE
[Feature Request] Custom attachment slots and more config arguments for attachments.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2864]
Self explanatory and more config argurments such as:
Laser and Light at the same time
Different animations when equiped, aimed etc.
Laser color
Light color
Space take up
Foldable/Unfoldable (Custom attachment slot feature)
Sight mode
I could go on more and more, but I don't want to bore myself.
Also allow every attachment argument be applicable to every attachment type

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
