### ISSUE TITLE
[Feature Request] The ability to fill vanilla magazine from custom magazine

### ISSUE THREAD

**Issue by Ghosticollis** [SmartlyDressedGames/Unturned-3.x-Community#2875]
Hello

It would be nice if it were possible to add crafting recipes to fill vanilla magazines using custom magazines.

If adding something like the following to any asset (not necessary the magazine asset) were possible:
```
Blueprint_0_Type Ammo
Blueprint_0_Supplies 1
Blueprint_0_Supply_0_ID 119
Blueprint_0_Product 6
Blueprint_0_Build 30
```
then this will open the door for a lot of abilities like filling vanilla mags from custom ones, filling custom mags using other custom mags from another mod by third party that is using the two mods, filling custom mags from vanilla ones if the mod does't supply this feature ..

Greetings

--------------
update: for now I have "bundle override" the custom mags, and made it accepting getting filled from vanilla ammo.
that wasn't the best thing to do, but this is fine in my case.
what left is to make vanilla mags getting filled from the custom mags.
but after all it is not big deal. if it happens, that would be nice,
if did not, then it is fine.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
