### ISSUE TITLE
Startup Args for Hosting Companies

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#2876]
Good Evening, @SDGNelson,

Hope all has been well with you since the last time I spoke to you!

Since the latest major update you pushed to the public branch, I've noticed seeing under the _vanilla server.log_ 

_[2021-10-31 01:15:00] Executing 3 potential game command(s) from the command-line:
[2021-10-31 01:15:00] Did not match "nographics" with any commands
[2021-10-31 01:15:00] Did not match "batchmode" with any commands
[2021-10-31 01:15:00] Did not match "LogAssemblyResolve" with any commands_

Should we continue to use these args regardless of the above or should we change/remove them from the services we rent out?

Is there, or will there be a section within the hosting wiki that states what we should and shouldn't be using for startup args?

Thank you!

**Comment by GazziFX** [comment]
nograpghics and batchmode is default args for server, you can find what they mean https://docs.unity3d.com/Manual/CommandLineArguments.html in `Unity Standalone Player command line arguments` section

**Comment by SDGNelson** [comment]
Thanks, hope you are well too!

Yes, you should continue to use -nographics and -batchmode, but -LogAssemblyResolve is optional if you find it useful. Those are logged to maybe help debug command-line commands not working as expected because the game does not know which system (e.g. third party plugin) might be handling those.
