### ISSUE TITLE
[Feature Request] No LOD Hotkey

### ISSUE THREAD

**Issue by RoxyLikesTea** [SmartlyDressedGames/Unturned-3.x-Community#2879]
A keybind for removing all LODS around the map would be amazing for screenshots, it always seems like something is just out of your range and could be by default not binded to stop someone from accidentally clicking it and killing their fps. Having it as a keybind means you cant get stuck in the settings menu with 3fps too.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
