### ISSUE TITLE
ArgumentException: You have already claimed the path with that object (Zombie (AIPath)). Are you claiming the path with the same object twice?

### ISSUE THREAD

**Issue by Rattle189** [SmartlyDressedGames/Unturned-3.x-Community#2884]
Server running Russia on 3.21.30.0 sometimes prints out this error:
`ArgumentException: You have already claimed the path with that object (Zombie (AIPath)). Are you claiming the path with the same object twice?
  at Pathfinding.Path.Claim (System.Object o) [0x00036] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at AIPath.OnPathComplete (Pathfinding.Path _p) [0x0001c] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at Seeker.OnPathComplete (Pathfinding.Path p, System.Boolean runModifiers, System.Boolean sendCallbacks) [0x00097] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at Seeker.OnPathComplete (Pathfinding.Path p) [0x00000] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at Pathfinding.Path.ReturnPath () [0x00008] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at AstarPath.ReturnPaths (System.Boolean timeSlice) [0x0005c] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
  at AstarPath.Update () [0x0005a] in <bed8fa266020479eb7cabbd1b8c540c0>:0 
 
(Filename: <bed8fa266020479eb7cabbd1b8c540c0> Line: 0)
`

**Comment by aviadmini** [comment]
Having the same thing on other maps (pei, washington), linux server
Doesn't seem to hurt anything though

**Comment by SDGNelson** [comment]
Unfortunately this has been around for a long time, but I am nervous to update the A*PFP plugin. Eventually™ there should be an update that overhauls the pathfinding in Unturned. If it ain't broke don't fix it ¯\_(ツ)_/¯

**Comment by GazziFX** [comment]
> Unfortunately this has been around for a long time, but I am nervous to update the A*PFP plugin. Eventually™ there should be an update that overhauls the pathfinding in Unturned. If it ain't broke don't fix it ¯_(ツ)_/¯

I use A* Path in plugins will there be any breaking changes?

**Comment by SDGNelson** [comment]
If A*PFP is replaced then any manual uses of pathfinding would need updating, but if A*PFP is updated it would probably not break manual uses.

**Comment by Rattle189** [comment]
I believe this issue may also be related to horde beacons in Russia, sometimes there are horde beacons with phantom zombies that somehow drop out of the map like in the airport and Silo 22, but the one in Silo 22 can be fixed by going down the bottom of the rocket and running to the gate where the zombies that fell there will clip through the floor and attack you. Other than that, there are no severe issues - and yes the server was running on Linux.

**Comment by DiFFoZ** [comment]
I have investigated this issue, and maybe I know the potential fix for this.

I published the patcher module to GitHub for anyone to test it https://github.com/DiFFoZ/AStarPatcher
**Check the readme info on how to install it.**
Right now, 3 server networks (including mine) are trying to catch this issue with my patcher.

###### some technical notes
When zombie dies or player is out of bounds of pathfinding zone, the code calls [`Zombie.stop()`](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/b727e04d191e2e3661c1042a0a7b0d98e67ddde5/Assembly-CSharp/SDG.Unturned/Zombie.cs#L1094) and then `seeker.stop()`. The `seeker.stop()` looks like this:
```cs
// AstarPathfindingProject.dll -- Seeker.cs
public void stop()
{
     this.path = null;
}
```

This code just sets the current path for moving to null. But there is a catch, that a path was not released by our seeker component! This causes `AstarPathfindingProject` to not be able to pool this path again because it thinks that there is still some reference to this path. But, with some timings, it can actually return to the pool with the claimed reference that then causes this exception:
```
ArgumentException: You have already claimed the path with that object (Zombie (AIPath)). Are you claiming the path with the same object twice?
```

**Comment by SDGNelson** [comment]
Thanks for sharing @DiFFoZ! I'll see about patching that in vanilla just in case.

**Comment by SDGNelson** [comment]
Closing because I think this has actually finally been resolved thanks to DiFFoZ's patch!

**Comment by GazziFX** [comment]
@ImperialKn What is `SDG.Unturned.Zombie.SDG.Unturned.Zombie.tick_Patch2` in your stacktrace?
