### ISSUE TITLE
Mistakes of the players

### ISSUE THREAD

**Issue by strongunturned** [SmartlyDressedGames/Unturned-3.x-Community#2897]
Good afternoon Nelson, after the update, many players have various bugs from mods (screenshot). I have already installed mods in different ways both through the WorkshopID and through Conten, but still some players still have these errors. What should I d
![wi03mn-kfGY](https://user-images.githubusercontent.com/48184311/142765584-eb3fd288-972b-4336-b14a-994801f2ea8f.jpg)
o?

Whatever I do, no matter how I install mods, through a folder or through the WorkshopID file, players kicks because of the check

**Comment by strongunturned** [comment]
Do I need to add Bypass_Hash_Verification to every garment?

**Comment by GazziFX** [comment]
For some reasons mods not updating on client and you always should verify Unturned files to update it

**Comment by SDGNelson** [comment]
Have you modified the clothing files on your server? If not, you can validate files to ensure everything is using the latest version. If you have modified them then I would recommend making custom copies in order to avoid future issues, but enabling Bypass_Hash_Verification does work as a temporary workaround if only server-side properties like storage size and armor have been modified.
