### ISSUE TITLE
New issue with some barricade

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#2903]
What could be the issue here:
![image](https://user-images.githubusercontent.com/14231707/143598570-e56d3667-6fd9-416c-81d6-a8ab0864ce49.png)

Not sure if its an actual barricade or could be map object as well?

**Comment by SDGNelson** [comment]
It's the same as the old missing barricade asset error, except now with guids rather than 16-bit ids. Come to think of it maybe it would be good to change those errors so the client reports the missing asset to the server, and then the server can include the asset name in the kick message.

**Comment by baranmod** [comment]
Well, I tried to look through all wrokshop files on both: server and client files, couldn't find that guid anywhere

**Comment by ArtemD7265** [comment]
yes! checked all the server mods! there is no this GUID

**Comment by ArtemD7265** [comment]
I don't understand! The GUID looks like this:
GUID 4ac471773d4d4547b7e3fc263d9b0404

And in error I get this:
c9accae5-d911-4a0f-a2c5-5774e39893f1
it's not a GUID!?

**Comment by baranmod** [comment]
Is there any chance to get a hotfix, so we are able to find what the name of the barricade? Because it seems like its showing some nonsense GUID which doesn't exist anywhere. Tried to remove dashes, tried with dashes. Did a search on whole server in all dat files, same on my PC. It just won't find the GUID shown in this error message.

**Comment by ArtemD7265** [comment]
I'm experiencing exactly what you just described!

**Comment by SDGNelson** [comment]
Sure, I can move that error to a server kick in a patch today, but I will hold off for a bit in case there are other issues.

Do you have any plugins which modify the barricade and structure methods? Especially Avi for example. Those would need to be updated for today's changes.

**Comment by baranmod** [comment]
No, I don't use Avi plugins

**Comment by ArtemD7265** [comment]
I removed all the mods from the server and installed them again, I also did it with plugins! Now I can log in to the server without an error. But this is a test server...

**Comment by ArtemD7265** [comment]
Reinstalling helped! But all the server buildings have been removed(((

**Comment by ArtemD7265** [comment]
FlexRust players say hello to you Nelson)

**Comment by ArtemD7265** [comment]
Reinstalling mods solves the problem one-time. At the next restart, everything is new.... Waiting for a fix!

**Comment by benvalkin** [comment]
Is there by any chance an ETA on the hotfix? My server has been having a similar issue with a missing barricade since the update, and I don't think I'll be able to find the problem without knowing the GUID or Short ID

**Comment by SDGNelson** [comment]
@benvalkin to clarify: the ID currently shown in the kick message is the GUID, but with default formatting rather than 32 characters which is why it looks different than usual (oops). Unfortunately (or fortunately depending how you look at it) nothing has come up to fix, so I will put up a patch with the more useful kick message proposed in probably 40-50 minutes from now.

**Comment by DanielWillett** [comment]
Also having this problem, I think its beyond just not showing the ushort id. Just scanned through all the mods on the server and no asset has the GUID all our players and I are getting (it's always the same: `09abe147-95c8-9810-0000-000000800810`). I have no other mods installed.

**Comment by DanielWillett** [comment]
(I should probably note I did account for the missing dashes in asset files when scanning)

**Comment by benvalkin** [comment]
@SDGNelson thanks so much, sorry I misread what you originally said about what the kick message currently shows

**Comment by DanielWillett** [comment]
I figured out what was wrong with our non-existent GUID, our plugin patches BM.SendRegion() and was the message was misaligned with the WriteGUID change. Nevermind.

**Comment by SDGNelson** [comment]
@DanielWillett glad to hear you tracked it down!

Is anyone else here patching SendRegion or related methods?

Copying the explanation from the patch:

Improved "missing barricade/structure (guid here)" kick message for hosts experiencing the error frequently after this update. Previously the client could not show the name of the missing asset because, well, the asset is missing/unknown. After the .1 patch the client will notify the server of the missing asset, and from there the server can kick for one of two reasons:

1. Guid read/write error. This happens if the missing asset reported by the client does not exist on the server either, indicating a packet was corrupted somewhere. (because the asset had to exist on the server originally) The most likely reason for getting this error is if a plugin is patching/modifying the netcode for sending barricades and structures to the client.

2. Missing critical asset. Here the server can display both the guid and file name to help track down which asset packs are not installed on the client.

**Comment by DanielWillett** [comment]
Sounds good

**Comment by SDGNelson** [comment]
Following up, @baranmod @ArtemD7265 @benvalkin if you got the chance to upgrade yet did you get a more useful error to narrow it down, or did you get a "guid read/write" error?

**Comment by baranmod** [comment]
ohh, I found the issue before the patch, looked for duplicated rows in all modpacks and couple barricades had the same GUID (mistakes from past)

**Comment by benvalkin** [comment]
@SDGNelson I'm running the same server as @DanielWillett so since we managed to fix our problem that was caused by a harmony patch no longer working, we'll have to check the new kick message another time

**Comment by benvalkin** [comment]
@SDGNelson here is the new missing barricade kick message that someone had. Looks like it works as intended
![image](https://user-images.githubusercontent.com/69928007/143684393-de9a0b42-7286-43f9-b536-a9c4505d6b39.png)

**Comment by Ongjming** [comment]
Just to add on: https://steamcommunity.com/sharedfiles/filedetails/?id=709486342
I have a building with this mod on some server and the floors of this mod turned into window walls.
![image](https://user-images.githubusercontent.com/28900564/143720815-89798296-3f09-4095-8755-5939d420e7ce.png)

Stuff from vanilla and another mod https://steamcommunity.com/sharedfiles/filedetails/?id=1232252658 were not affected.

So from this, the hypothesis I can come up with is that the new update is not compatible with the unity version used in 2019 for mod making but is ok for those 2020 onwards.
Is this somehow also related to long GUID thingy?

**Comment by DanielWillett** [comment]
It's likely they have conflicting GUIDs, maybe have the mod author check that out...

**Comment by SDGNelson** [comment]
Glad to hear you all got it sorted out! Sorry for the hassle. In the long term this will hopefully be useful as it means theoretically you can have a much higher number of custom barricade/structure type items without issue. (though the inventory stuff needs to be updated to guids as well)
