### ISSUE TITLE
[Feature Request] Reload and Hammer animation into one animation.

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#2908]
Now, I have requested this already bunch of times (3rd time, I think). Now basically what this basically means is a smoother transition to the hammer animation or in some situations, even a more realistic reload. Now sure, unturned isn't the most realistic game and I get that, but we, the viewmodel animation enjoyers enjoy these kind of things. All I am asking if there was some sort of .dat argument that would allow for the gun when fully empty play the alternative animation with the reload and the hammer in one action.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
