### ISSUE TITLE
GUID Collision

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2957]
If you use default structure GUID in mod, then instead of default structure, there will be custom. Problem is that this allows you to make a mod where you can replace default structures with such, but transparent or without colliders.

It was supposed to be a metal wall, but...
![image](https://user-images.githubusercontent.com/17459138/146772872-81949e29-e48a-4c6b-a50b-e6acb6b17cea.png)
![image](https://user-images.githubusercontent.com/17459138/146773014-81881bff-829c-474d-9303-007c4121ebab.png)
![image](https://user-images.githubusercontent.com/17459138/146773030-4619808e-1f1c-47d9-8c05-e1ab5bd22430.png)

**Comment by nanashi88** [comment]
there are cool mods at workshop that sadly has this issue, for example this mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1441131424
has this issue for a lot or maybe all structures
apparently mod designer copy paste vanilla dat files and didn't change GUIDs :/

**Comment by surv0013** [comment]
It might be worth abandoning manual GUID and making the game generate WUID* by itself based on workshop ID and item/vehicle/animal/effect ID.

**For example:**
%Content_ID%-%Type_Index%-%Item_ID% = "193301-1-18392"

**Type Indexes:**
Item = 1
Animal = 2
Vehicle = 3
Effect = 4
Object = 5
Resource = 6
Weather = 7

*WUID – Workshop Unique Identificator

**Comment by SDGNelson** [comment]
If the .dat file does not have a GUID then the game will assign one, so the easiest way is to remove the GUID line and a new one will be added when the file is loaded. When a GUID is specified and a duplicate is found then the game has no way to determine which is the original and which is the duplicate, so it cannot be automatically reassigned without breaking files.

Integrity checks have gradually been added to more asset types, but barricades and structures are not yet checked because there are so many of them loaded at once. I do have a plan for this however. Overriding structures like that is not a huge issue anymore because players cannot walk through them (authoritative movement) and the server will reject shots through them.
