### ISSUE TITLE
[Feature Request] Individual Gun Stats per Fire mode

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2964]
The ability to change gun stats like firerate, recoil, spread e.t.c depending on fire mode selected (Auto, Semi, Burst). Would be quite helpful and add more use for Semi and especially Burst modes.

While Semi mode is quite useful when you dont want to spray out several rounds with just one mouse click, burst mode seems a bit useless right now, because you could just use the Auto mode and fire in short bursts, and nothing would change. If we could set special stats for Burst mode, like less recoil (the entire point of burst mode is usually to land several shots before the recoil sways your aim), perhaps bigger firerate. Overall this would make opportunities for more unique and interesting guns for future mods or curated maps.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
