### ISSUE TITLE
[Feature Request] Allow modders to choose semi shot cooldown

### ISSUE THREAD

**Issue by RoxyLikesTea** [SmartlyDressedGames/Unturned-3.x-Community#2966]
There's an awkward balance right now with maps such as Arid, where the creators obviously wanted to make Semi more viable due to the high recoil but the guns being ridiculously slow to shoot, what I hope could be added is allowing the modders to choose how long they want for the gun to wait before shooting again after shooting with semi. This would allow for "click speed semi" which is good in other games such as Rising Storm 2 (see attached). This will hopefully allow for semi to be more viable in mods to come and i'm not asking for vanilla guns to all be modified to this but just for it to be an option. Thanks! [https://cdn.discordapp.com/attachments/324229387295653889/925447049942556813/2021-12-28_17-55-03.mp4](url)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
