### ISSUE TITLE
[Feature Request] Allow Helmets to hide masks/optics

### ISSUE THREAD

**Issue by Dumfoozler** [SmartlyDressedGames/Unturned-3.x-Community#2975]
For helmets that cover the entire head, it would be useful to be able to make the mask/optics disappear exactly the same as how the hair and beard disappear to prevent issues with clipping.

I can picture this working exactly as how the "Hair" and "Beard" lines work, except have something like "Mask" and "Optic" to hide those as well. This will allow for more compatibility with vanilla things as helmets that fit snug to the head won't look goofy with things like that would clip out such as gasmasks or nightvision.

Thanks
- Dumfoozle

**Comment by SDGNelson** [comment]
FWIW, my eventual plan is to allow items to "tag" which clothing slots they occupy, and then you can be more fine-grained with this and which slots are compatible / hidden.

**Comment by Dumfoozler** [comment]
I'm not asking for a feature to directly block them, just to hide the visual items so they do not clip through the helmet.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
