### ISSUE TITLE
[UI] Description does not fit / Adaptive Item Information Window

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2976]
We have the ability to wrap the text on a new line when writing a description for an item, but it often happens that because of this it does not fit into that little window in the inventory. Can you make the window adaptive?

P.S.
I decided to write a description that would list the unique properties of the item:
```
%Some_Text%
%Some_Text%
%Some_Text%
Characteristics:
Fire Protection: 15%
Bullet Protection: 25%
Explosion Protection: 5%
Acid Protection: 10%
Radiation Protection: 20%
```

**Comment by SDGNelson** [comment]
I agree it would be good if the description window resized to fit the text, but the game does not yet have a good way to do that. My intent is to update several of the menus with resizing after we can update everyone to UIToolkit.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
