### ISSUE TITLE
[Feature Request]Useful Clock

### ISSUE THREAD

**Issue by sam9612** [SmartlyDressedGames/Unturned-3.x-Community#2980]
Clock added to game was great but I feel clocks are just for 'decoration' not something for useful item.  It would be great clock functions are work as item so that people can carry them and look at time anywhere such as underground. Or display clock UI on screen like compass would be great when in player inventory.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
