### ISSUE TITLE
[BUG] Inventory Gesture

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2981]
When the player closes the inventory, information about this is sent to the server, and when he opens it, if he has something in his hands, he is lying or is in the vehicle, then no.

I propose to send a request for the animation of opening the inventory in any case, and on the server to check it, this will allow us to hide the custom UI when the player opens the inventory. It would be great, of course, to have some kind of separate request notifying the server that the player has opened a vanilla UI, but unfortunately, I may simply not live to see such a request (I don't know many people who have lived to be 100 years), so let's stop at the inventory.

**Comment by SDGNelson** [comment]
> but unfortunately, I may simply not live to see such a request (I don't know many people who have lived to be 100 years)

lol

I think ideally what will happen for exclusive menus like this is allowing plugins to insert a custom panel, and only one of the fullscreen menus either vanilla (inventory, skills, crafting, etc.) or custom fullscreen menus would be open at a time.

**Comment by DerSpeedMann** [comment]
Any update on this?

**Comment by SDGNelson** [comment]
Here we are 1 year later! Your 100 year guess might be accurate.

Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
