### ISSUE TITLE
[Code] Add method to track quest

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#2989]
```CSharp
private static readonly ClientInstanceMethod<ushort> SendTrackQuestFromServer = ClientInstanceMethod<ushort>.Get(typeof (PlayerQuests), "ReceiveTrackQuestFromServer");

[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER)]
public void ReceiveTrackQuestFromServer(ushort id) => this.trackQuest(id);

public void ServerTrackQuest(ushort id)
{
     PlayerQuests.SendTrackQuestFromServer.InvokeAndLoopback(this.GetNetId(), ENetReliability.Reliable, this.channel.GetOwnerTransportConnection(), id);
}
```

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
