### ISSUE TITLE
[Modhook Request] Temperature Hook

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#2998]
We've got Freezing, Cold, Warm, Burning, Covered and Acid temperature statuses that the player can receive from weather conditions, barricades, zombies and other sources. If we could possibly have a temperature hook, that detects these temperature status sources within a certain radius, and respond with events depending on the status type, this would allow to make some barricades, objects and vehicles that work differently depending on the temperature (slowing down the vehicle because of cold, making a frozen/burned model variants for barricades/objects that turn on if Fire or Freeze sources are nearby e.t.c.).

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
