### ISSUE TITLE
[Feature Request] UI Flags

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3004]
```CSharp
public enum EPluginWidgetFlags // Only new options
{
    ShowVoice = 16384, // Voice chat icon
    ShowTrackedQuest = 32768, // Tracked quest
    ShowHotkeys = 65536, // Item hotkeys [3-9]
}
```
I don't understand why there are options that are in the level config but not in the server config...
```CSharp
public class GameplayConfigData // Only new options
{
    public bool Allow_Crafting;
    public bool Allow_Skills;
    public bool Allow_Information;
}
```
How about not writing the word "DISABLED" on the buttons, but just hiding the button so that it is not conspicuous, it still cannot be pressed.

**Comment by DanielWillett** [comment]
Maybe this could be extended to allow the server to specify which life bars are hidden/shown so they don't have to depend on the level config. (mb if this is already a thing but pretty sure it isn't)

**Comment by XanderCodes** [comment]
> Maybe this could be extended to allow the server to specify which life bars are hidden/shown so they don't have to depend on the level config. (mb if this is already a thing but pretty sure it isn't)

This is already a thing with EPluginWidgetFlags that was added semi-recently. Super useful - now we just need to be able to hide the chat so it doesn't cover full-screen UI's.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
