### ISSUE TITLE
[Feature Request] Custom Claim flag radius

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3005]
The title kinda says it all but can we get an option to change the hard-coded 32m claimed radius in the barricade's dat file for modded claim barricades?
Thanks.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
