### ISSUE TITLE
[Feature Request] Ability to manipulate player's camera.

### ISSUE THREAD

**Issue by DrShockz** [SmartlyDressedGames/Unturned-3.x-Community#3007]
Ability to manipulate the player's camera.

I want to be able to set the player's camera position to point at a podium for vehicles.
And I'm sure theres 100 more uses for something like this.

(character creation - like FiveM, spectate etc.)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
