### ISSUE TITLE
[Suggestion]Speed_Run and Speed_Walk EDIT: For Guns/Magazine

### ISSUE THREAD

**Issue by Ongjming** [SmartlyDressedGames/Unturned-3.x-Community#3008]
Currently these are found in animal files.
Wondering if they could be used to modify player's speed in terms of wearing certain item/holding certain weapon or guns.

Applicable usage example:
Wearing heavy armor makes you walk and run slower.
Holding a heavy gun/ gun with heavy ammo makes you walk/run slower.

Since the default running speed varies across Exercise skill levels, and default speed for walking and running are unknown, it would be good if these 2 work as a multiplier instead of how it works in the animal files.

**Comment by MoltonMontro** [comment]
You can already modify player speed via clothing, with **Movement_Speed_Multiplier**.

**Comment by Ongjming** [comment]
Sorry, I wasn't looking through enough. I just realized this as well as of time of this post. Thanks!

**Comment by Ongjming** [comment]
To add to this:
In Arid files for some guns, there is Can_Player_Equip bool.

Was wondering if conditions could be made to be used with that so that player would have to wear certain stuff/full set of stuff to be able to equip certain weapons?
(Instead of the current true/false)

If it could work in this way instead, it would still kinda work to make certain guns to have slower movement speed (Guns equipping tied to the wearing of certain clothes while the Movement speed is also tied to those clothes.)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
