### ISSUE TITLE
[Feature Request] Projectile Override for Projectile Weapons

### ISSUE THREAD

**Issue by Nuhm** [SmartlyDressedGames/Unturned-3.x-Community#3018]
Many of us have been wanting a feature to allow us to change the projectile per magazine for a weapon.
An example of this would be a flare gun; currently in order to change the colour of the flare in the sky you would need a different gun item, it would be much nicer if we were able to determine the projectile type through the magazine used.

A change like this would allow for people having different rocket types for rocket launchers, different round types for tanks and other vehicles. But also different flight paths for projectiles as you be able to set different rigid bodies per magazine, allowing certain rounds to fly faster or slower.

I'm not sure this would be easy to implement as it would require magazines to be reworked in general and likely requiring a new prefab in Unity to configure the projectile. But to allow the guns to know there is a custom projectile for the magazine I would think this could be added through a line in the .dat for the weapon calling upon the magazine's projectile effect if it has one, if not it would revert back to it's standard projectile, this could be something like `Use_Magzine_Projectile`.

This would go nicely with the previous change for the impacts of projectiles being able to have different effects.

_Thanks,_ 
_- Mikey_

**Comment by BroXn** [comment]
i support

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
