### ISSUE TITLE
Game still "stops working" after trying to join a server: The fix was temporary

### ISSUE THREAD

**Issue by BondarCalabria1** [SmartlyDressedGames/Unturned-3.x-Community#3021]
So, i reported this a while ago, and ended up getting a solution for it but said solution was only temporary

Basically you'd have to delete the game and then download it again, and that would let you join the server for liek the whole day, but the day after that the issue remained and you were still unable to join server as the game would pop up the system "program stopped working" and you have to close it or else you'd be stuck there forever

I know you Nelson, told me before to send a file named "Unity Temp" and extract from inside there a "crashes" and send it over tyo you but it doesent let me open the "unity Temp" in any way, a message pops up telling me something about a conection issue or a badly inserted disk? no idea what its talking about

Now i have no idea but this has never happened to me before, and I think i've heard a bunch of people have the same issue, could this be a problem that came with one of the latest updates?

Eitherway i dont know how i can help identify the issue since i dont have acces to the before asked folder so please tell me if there is any other way

**Comment by SDGNelson** [comment]
To clarify: the "Unity Temp" shortcut links to Unity's crashes folder, so if it says it does not exist then Unity is either not crashing or not getting the chance to write the crash files.

Are you able to join other servers? i.e., are there problems only with this particular server?

Does the game crash to desktop on its own, or does it fade white and Windows says "the program has stopped responding" and then you click "close program"?

**Comment by warren39** [comment]
If you delete Unturned and download it again, and then join the server. There will be a progress bar downloading the workshop files. 
But when you restart the game and then join this server again, it will not download the file from the workshop, but read the file from the local cache. This loading will not have any progress bar and will usually freeze the game (If there are a lot of mods, this will take a few minutes). If you click on the window, it will say "the program has stopped responding".
I recommend adding a progress bar when Unturned loads the workshop file locally. Although Unity uses asyn loading files will increase the load time. Because some player will click the "close program" really.

**Comment by BondarCalabria1** [comment]
Aight so it hasnt happened again today since yesterday so i cant test if it happens on other servers or just this one yet

It fades white and windows says the program stopped working, and i click close program, sorry if i thought that was a crash but it didnt work after a while so i tought it was

**Comment by BondarCalabria1** [comment]
Ok it happened again, as its as Warren said, it just takes a while to load but it ends up doing so

**Comment by SDGNelson** [comment]
Glad to hear it is working (eventually)! warren39 is right that I would like to update it to async loading sooner or later.
