### ISSUE TITLE
[Feature Request] Damage Volume

### ISSUE THREAD

**Issue by KikETs** [SmartlyDressedGames/Unturned-3.x-Community#3033]
Damage Volume that can be placed on both Unity and Devkit. Like you can set the damage when players / animals / vehicles collide with  set area. The damage can be once or consistent, and its value can be set. Other options would be similar with KillVolume.

**Comment by Ongjming** [comment]
One workabout I can think of is using ambience volume specifying a custom weather effect with Health_per_second adjustment (https://github.com/SmartlyDressedGames/U3-Docs/blob/master/WeatherAsset.md)
This is only for Players I think, I haven't tried....., and only for consistent damage rather than an one off damage.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
