### ISSUE TITLE
Signs [Feature Request]

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#3038]
Hey Nelson,
Can you add OpenStorageRequestHandler event but for Signs please.

Thanks you!

**Comment by GazziFX** [comment]
As I know signs doesn't have "opened" state and send request to server only while updating text

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
