### ISSUE TITLE
Bug report N3

### ISSUE THREAD

**Issue by Finn39** [SmartlyDressedGames/Unturned-3.x-Community#3061]
In the video you can see that spec ops vest gives armor from MK2 bullet explosive, but if we take clothes they must give additional defense. In true they reduce armor and you take more damage from explosive .
https://drive.google.com/file/d/1XKZ50VLc7J8u3eqYOZWHfTs8af39s1Pv/view?usp=drivesdk

**Comment by Ongjming** [comment]
Video summary:
0:22 With just spec ops vest your health gets reduced to 36%
0:42 With Spec ops vest, Military Helm, Black balaclava, Spec ops Shirt and Spec ops pants, your health gets reduced to 21%

MKII
Ballistic damage to player:
Player_Damage 50
Player_Leg_Multiplier 0.6
Player_Arm_Multiplier 0.6
Player_Spine_Multiplier 0.8
Player_Skull_Multiplier 1.1
(Though it shouldn't hit since you are aiming at the ground)
Explosive damage to player, property from its magazine:
Range 6
Player_Damage 100

At both points in the video you aimed at the same spot right beneath you.

Known information - 
Explosive damage bypasses Armor values. So you should get hit 100% of the damage.
What I don't get either -
How come the damage from explosive have variation? Isn't it suppose to always deal 100 damage to the player and they die instantly?

**Comment by SDGNelson** [comment]
Explosions actually use the *average* of the player's shirt, pants, vest, and hat explosion armor multipliers which is perhaps kind of unintuitive because with only the vest here which has higher explosion protection the damage is lower than with full gear. I will change this for the next update to include "no item" in the average.

**Comment by Ongjming** [comment]
Note to self: (From https://steamcommunity.com/app/304930/discussions/0/1728711392741267543/)
3.26.3.2 Patch Notes
Armor_Explosion multiplier defaults to the Armor value.
Explosives use the average of your shirt, pants, vest and helmet's Explosion_Armor value when dealing damage.
(Sorry, only found out about this after searching the past patch notes)

Just to expand on my understanding of this - 
For the "No item" in the average, would that mean that
Current: Vest - 0.65 = (0.65+0+0+0)/1 = 0.65
Future: Vest - 0.65 = (0.65+1+1+1)/4 = 0.9125 ?

**Comment by SDGNelson** [comment]
In the next update the "no item" slots are treated as armor of 1.0
