### ISSUE TITLE
Editor not able to bake GPS/Satellite 

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#307]
Unturned sometimes does not bake the GPS view for workshop maps, in which case Unturned stops responding. This has happened for quite a while now but seems to only happen on certain maps. I looked through logs and I found this line of code, which may or may not have something to do with it.

`Failed to extract collision data: Submesh 0 uses unsupported primitive type "Quads". Please use either "TriangleStrip" or "Triangles". Please make sure you have unchecked "Keep Quads" on your model's Import Settings. Mesh asset path "" Mesh name "Model"
`

Once again, some maps work just fine. I think it may have to do with a certain model being used within the map. Any resolutions are helpful, otherwise I think this is a bug.

**Comment by SDGNelson** [comment]
Just updated the Germany (most performance-intensive map in the game) satellite image to double-check that it still works.

Most likely you need to click "wait for the program to respond" if that's happening, as rendering the entire map takes a while. It could be improved if it were rendered across multiple frames in smaller tiles and then stitched together, but that's low priority since it works as-is.

**Comment by SDGNelson** [comment]
Do you know of a publicly uploaded workshop map you're having this problem on? I'll see if it's something that can be readily fixed as part of the map capturing code.

**Comment by N1GHTPATROL** [comment]
Yeah, this Florida map. https://steamcommunity.com/sharedfiles/filedetails/?id=1105745826&searchtext=florida

I was not able to make the map, and neither was a friend of mine nor the map dev. Notice there is a lack of a satellite rendering because he/she must have not been able to either.

**Comment by SDGNelson** [comment]
Unfortunately wasn't able to replicate it on that map, but here's my export of the satellite image in case you want to use it:
https://drive.google.com/file/d/104UzOmX2knqp95xXHPm7qplueKezlLOm/view

Any other maps? Note that I didn't get any warnings while exporting the image likely because the map doesn't seem to have any custom content.

**Comment by N1GHTPATROL** [comment]
Hey, thanks for the investigation on this, I appreciate it. It's really interesting because for me, the game just stops responding for me and multiple people, and in process explorer it shows as using almost no CPU (compared to around 50% on my rig):

![image](https://user-images.githubusercontent.com/7349712/41074293-66ac6658-69d5-11e8-8bd4-27a218f8f2a6.png)

This map also doesn't generate the satellite view: https://steamcommunity.com/sharedfiles/filedetails/?id=523012191 . Maybe there's something I should do to my client (besides verifying cache because I've done that many times) that will fix this.

**Comment by SDGNelson** [comment]
No luck, only took a few seconds on my PC:
https://drive.google.com/file/d/104UzOmX2knqp95xXHPm7qplueKezlLOm/view
(accidentally overwrote previous image): https://drive.google.com/file/d/109A2LW_1Q0NKqb0lTNIagjoOejlyg3r-/view

I wonder if it's purely the amount of RAM or something. Maybe if you enable page files it would successfully bake?

**Comment by joeytheadmingamer** [comment]
Even with 32 gigs of ram, like I have, it'll keep my Unturned frozen until I end task and reopen the game that's with me leaving my pc on to bake overnight or for 6+ hours during the day.

**Comment by AthenaDev** [comment]
@joeytheadmingamer definitely brings up a good point; I think it's on Unturned for this performance, not the user's computer. I would rather not do this solution especially because I'm changing my map and I'd like to see how it looks every few changes, but if a bake satellite takes 6 hours..

One thing that Nelson said might be the only chance of fixing this..unfortunately it's low priority:

- "It could be improved if it were rendered across multiple frames in smaller tiles and then stitched together, but that's low priority since it works as-is."

**Comment by aviadmini** [comment]
Had the same problem - Editor froze and byebye
Restarted game and it baked satellite in 2 seconds

**Comment by aviadmini** [comment]
And then there are server owners who work with defcon and sell his plugins
