### ISSUE TITLE
Allow tacticals to optionally slow fire rate

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3075]
Tacticals, like adaptive chambering, is great & all to speed up fire rate. But it would be cool to allow the feature to also slow down fire rate. Nuff said.

**Comment by Ongjming** [comment]
Suggestion: Change it from byte to sbyte so it can read negative value :D

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
