### ISSUE TITLE
[Bug Report] Skill to accelerate recharge

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3079]
The skill to speed up reloading speeds up character animation, but the animation of weapons through the eventhook remains the same. Because of this, if you pump the skill for 100%, the animations will be out of sync

**Comment by SDGNelson** [comment]
Sorry which even happens at the wrong time? OnChamberingStarted?

**Comment by JorelDecker** [comment]
> Sorry which even happens at the wrong time? OnChamberingStarted?

If you pump this skill to 100%, then the animation of the hands will move 50% faster than the animation of the weapon during OnReloading

**Comment by SDGNelson** [comment]
Oh, that is because the game does not have any way to know you are playing an animation on a separate animation component. One change I intend to make as part of merging first+third person models is to check for animation components on the item and play clips with the same name as the character animations if they exist.
