### ISSUE TITLE
(Windows?) Console bug

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3095]
Not sure if this is a problem on Linux but on Windows it's pretty common for the u3ds console to freeze, (especially when alt-tabbing from it or typing in it). Pressing enter unfreezes it.
Not sure if you can do anything about it or if it's a problem with the windows console but it'd be a low-priority bug that could be fixed at some point.

**Comment by SDGNelson** [comment]
Interacting with the console is blocking, but the console is run from another thread so that the server continues operating as normal. Unfortunately as far as I know there is not an easy way to workaround this without either custom input/output handling for the console, or using the win32 API directly rather than System.Console.

**Comment by DanielWillett** [comment]
Alright, thanks for responding.
