### ISSUE TITLE
[Feature Request] EffectManager.SendEffect() doesn't allow you to rotate the effect around it's local Z-Axis

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3096]
Essentially what the title says. It's currently impossible to rotate an effect around it's local Z-Axis. This is essential if you want an Effect to line up with a plane that is rolling for example.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
