### ISSUE TITLE
Car battery

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3105]
How to make the car use a non-vanilla battery. So that when you click Steel Battery, a different ID appears in the inventory, and not the standard one?

**Comment by Gamingtoday093** [comment]
Seems to be hardcoded to the Vanilla Battery, perhaps modify your title to add [Feature Request]
Taken from `InteractableVehicle.cs`
```cs
protected bool giveBatteryItem(Player player)
{
	byte b = (byte)Mathf.FloorToInt((float)this.batteryCharge / 100f);
	if (b == 0)
	{
		return false;
	}
	Item item = new Item(1450, 1, b); // The ID of the new Item is hardcoded to be 1450, The Vanilla Battery ID
        player.inventory.forceAddItem(item, false);
        return true;
}
```

**Comment by SDGNelson** [comment]
Thanks yes @Gamingtoday093 is correct that it is hardcoded (for now), sorry!

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
