### ISSUE TITLE
Healing glitch [Re-opened]

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3108]
Ruby say:
Then it's good.
If all players can see when a barricade is full healed it could be used as a exploit in game.
Example: Raiders will lock for non full health walls

I ask:
What exploit?
On the current healing system i can see, i can distinguish buildings with full health and not.
How does knowing that I repaired the building to the end or not help the raiders in the raid?

This is an underdeveloped mechanic, not a protection against glitches.
Why can I know when I completely repaired a closed car, but I can not know the same about buildings?

**Comment by SDGNelson** [comment]
You can either create an in-game group from Dashboard > Information > Groups and invite your friend, or both join the same Steam clan. When you do this you will both be able to see the base health.

Health is only replicated to base members, otherwise cheaters would be able to see which part of the base is at lowest health and target it specifically.

**Comment by QERT2002** [comment]
Okey, thanks for reply, 
I didn't think about cheaters, sorry.
