### ISSUE TITLE
you can stuck!

### ISSUE THREAD

**Issue by fishingsman** [SmartlyDressedGames/Unturned-3.x-Community#3111]
you can stuck at vladimir farm (sorry for innaporpative language)
![image](https://user-images.githubusercontent.com/102311071/161403154-3d3ad21a-9584-434c-a66e-b29416cb82a6.png)
![image](https://user-images.githubusercontent.com/102311071/161403163-0b35e858-8c34-479c-9169-86c6f3e96a48.png)
![image](https://user-images.githubusercontent.com/102311071/161403167-21c2b548-5e49-4fe2-9606-286b5dd50d03.png)
![image](https://user-images.githubusercontent.com/102311071/161403177-c3813d57-8935-4602-87a9-11141706b923.png)
I tried to proning and crouching but it didn't work out.

**Comment by SDGNelson** [comment]
Thanks for the report! I will label this "next update" so that I remember to check it out.

**Comment by SDGNelson** [comment]
Unfortunately the spacing here is slightly too short, so the character ends up overlapping the hay and the ceiling which prevents them from moving. For the next update as a placeholder fix I have made crouch and prone more forgiving so that it is escapeable. Once vehicles are hopefully made authoritative there will be a proper fix for character movement.
