### ISSUE TITLE
[Feature Request] FallDamageMultiplier

### ISSUE THREAD

**Issue by WhiteBlaaack** [SmartlyDressedGames/Unturned-3.x-Community#3122]
I think it would work for some servers to add an FallDamageMultiplier in the config.json so owners can choose

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
