### ISSUE TITLE
Possibility of AI creation via open-source assets?

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3124]
As title says, it would be awesome to allow the workshop community to create their own AI. ATM, what we have is being able to create all sorts of animals. But what would be very interesting to see is creators try out scripting all sorts of AI behavior. This will open up new ideas for what AI can be in Unturned if we are given all the resources of how AI's function so it's a nice opportunity to allow us to get this feature.

**Comment by SDGNelson** [comment]
Ideally the zombies+animals will be merged into a more modular system *eventually*, but no idea when that will happen sorry.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
