### ISSUE TITLE
[Feature Request] Vendor categories of items

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3125]
I often see server developers split vendors to categorize items by dialogs. It would be nice if when trading with NPCs, there would be category buttons of items on top. For example: weapons, clothes, food and water. Ideally, be able to set the category of items yourself.

**Comment by surv0013** [comment]
![image](https://user-images.githubusercontent.com/17459138/164537311-623f48f1-7c44-4add-8b13-024ea7427c1a.png)

**Comment by sunnamed434** [comment]
![image](https://user-images.githubusercontent.com/65300126/165780035-cc4ccd48-411d-4782-baab-8e938475ac5a.png)

**Comment by fahrettinenes** [comment]
> ![image](https://user-images.githubusercontent.com/17459138/164537311-623f48f1-7c44-4add-8b13-024ea7427c1a.png)

meh, you should get used to it

**Comment by GazziFX** [comment]
![previewfile_2099705885.jpg](https://user-images.githubusercontent.com/43498426/165870942-80bee9a7-d3f4-4781-98b9-691968b9380a.jpg)
Picture with sound

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
