### ISSUE TITLE
[Feature Request] Animation, Sound and Effect overrides for Zombies

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3131]
Add more customizability to Zombies by making it possible to change their run and attack animations, sounds, and effects. This would allow for making some interesting, non-zombie enemies such as bandit NPCs, or base guards.

A way it could be done would be by making an Asset V2 file that contains all customizable data (i.e.: Attack_0, Attack_1, Run, Grunt_0, Grunt_1, Blood, etc) and using masterbundle pointers to guide the game to the custom animations, then adding it's GUID to a Zombie spawn table's settings in the editor. In-game, it would apply the settings to the zombies when spawning them in or as the level loads up.

Currently the only workaround to this would be making a custom animal, similar to Elver's cultists.

**Comment by SDGNelson** [comment]
Eventually I would like to merge the zombies and animals into one base enemy type that is more modular and customizable.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
