### ISSUE TITLE
Flag tag for NPCs text

### ISSUE THREAD

**Issue by iBowie** [SmartlyDressedGames/Unturned-3.x-Community#3133]
Allow users to put <flag=12345> for displaying flag value in NPC text (something like <name_char>)

This would allow to display value in NPC messages.

Example: "you have killed 35 wolves so far"
In asset: "you have killed <flag=45> wolves so far" where 45 is flag ID that is used by "Kill Animals" condition.

Right now only workaround is not to display it at all, or create separate messages for each flag value.

To implement this Regex could be used.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
