### ISSUE TITLE
[Feature Request] Add confirmation for quit to desktop

### ISSUE THREAD

**Issue by MAGICAL-SPACE-DUCK** [SmartlyDressedGames/Unturned-3.x-Community#3135]
I love that we have quit to desktop now but unfortunately I am a little silly and keep clicking on it when I mean to leave a server 

could we potentially get a confirmation for quit to desk top just like we have for the suicide button?

**Comment by SDGNelson** [comment]
Agreed that it would be helpful. I want to add modal dialogs for things like this as part of revamping the screen transitions for gamepad support.

**Comment by JJacKWW** [comment]
or make it a toggle for the quit button in the settings @SDGNelson

**Comment by danielstankw** [comment]
+1 to suggestion

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
