### ISSUE TITLE
Nelson, can you take sourse Door_Chamber

### ISSUE THREAD

**Issue by JorelDecker** [SmartlyDressedGames/Unturned-3.x-Community#3141]
It is not in the official sources, could you give it separately?

**Comment by SDGNelson** [comment]
Sure. It cannot be included directly because it references components in the Project package, but I shared it on another GitHub issue recently as well The meshes are missing but the component setup will match if you have the source packages imported.
[Anastasia Door.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8556409/Anastasia.Door.zip)
.
