### ISSUE TITLE
Problem with obsolete DamageTool.playerDamaged event 

### ISSUE THREAD

**Issue by RestoreMonarchy** [SmartlyDressedGames/Unturned-3.x-Community#3146]
Hi,
I got the reports from someone that one of my plugins causes another old plugin to not work. 
I found out that when my plugin subscribes to `DamageTool.onPlayerDamaged` event then a method invoked in his old plugin by RocketMod `UnturnedEvents.OnPlayerDamaged` event is not triggered, but when my plugins unsubscribes from DamageTool event the old plugin works for him again.

The problem is that if `playerDamageRequested` is not null it doesn't call the obsolete `playerDamaged` anymore. I guess the `else if` was accidentally used instead of just `if` statement for `playerDamaged` null check.
![image](https://user-images.githubusercontent.com/35507241/165375441-2882a17f-16cc-4bd8-a243-00f60826f9b5.png)

I think it's a big issue for all of the plugins that still use RocketMod events.

PS. I think that `playerDamaged` shouldn't be obsolete and should be called after the `flag` is checked that's set in the `playerDamageRequested` event by plugins that use this event. Then the `playerDamaged` will only be called when actual damage is done.

**Comment by SDGNelson** [comment]
I think the `else if` was intentional to indicate the newer method really should be used instead, but for compatibility I suppose calling both is better. `playerDamaged` was confusingly named because there are still reasons the damage might be cancelled, so it is not a good indicator whether actual damage was done.
