### ISSUE TITLE
[FEATURE REQUEST] ScriptableObject alternative to .assets

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3158]
I've been toying around with Unity's SO's in my personal projects and have been amazed by how convenient and easy to use they are. It may be overkill/too difficult to implement this with some features, but it would be nice if certain .assets like Material Palettes, Airdrops or Weather could optionally be SO's for ease of development within Unity (of course the asset v2 system should be kept for compatibility).

:)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
