### ISSUE TITLE
Adding Automatic Hill Baking

### ISSUE THREAD

**Issue by FylRon** [SmartlyDressedGames/Unturned-3.x-Community#3160]
Hi, cool feature for editor could be Automatic Hill/Environment Baking, basically editor would make whole Hilly map for you by setting just Noise and Material. That can save Developers a lot of time doing whole Environment.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
