### ISSUE TITLE
[Feature Request] PlayerLook control server-side

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#3177]
Hi Nelson, would be cool have some server-side methods to control player camera like:
- Freezing player camera
- Force player to look a certain point (*this is already possible teleporting the player again to their position and just parsing the yaw required but would be cool have a custom method to this and maybe possibility of change the pitch too*)
- Recoil server-side method, so we can move the player camera smoothly and don't need to teleport their view.
- A method to change the player perspective or at least a option for servers so every time that a player join would be in a specific perspective.

I hope this can be added soon so new cool plugins can be made ^^

**Comment by GazziFX** [comment]
I think we need method to smoothly move player to given position instead of teleporting it.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
