### ISSUE TITLE
Option to default empty slot [Feature Request]

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3186]
Explanation:

So you know when you have an empty primary slot and a filled secondary slot? But when you press 1 nothing appears. It would be useful to have an option to default to the slot that is filled when you press either 1 or 2.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
