### ISSUE TITLE
Foliage.blob huge file size after update

### ISSUE THREAD

**Issue by warren39** [SmartlyDressedGames/Unturned-3.x-Community#3188]
The Foliage.blob file was automatically generated after Foliage Bake, and it was large (453MB), so my map increased from 16.9MB to 499MB. The map content looks the same as before, but I think the Foliage.blob is really too big. Is there any way to reduce this file size?

**Comment by GazziFX** [comment]
I looked into code and found that foliage saving in tiles and also same objects grouped by GUID to reduce usage, but I dont understand why each object saving Matrix4x4 instead of 3 Vector3 or Matrix3x3 (position, euler angles, scale). And I found that tiles loading read FileStream synchronously in Update. I think it can be replaced with async Task, or in separated thread which will be synced with lock while adding to matrix list

**Comment by GazziFX** [comment]
And also filesize can be reduced even more if it will be compressed with GZip and decompressed to temp file when loading map

**Comment by warren39** [comment]
Oh, It seems like the file size can be reduced by reducing the number of foliage. But I didn't know how to adjust the foliage density.

**Comment by SDGNelson** [comment]
As a point of reference: Russia's Foliage.blob file is 515 MB, so your file size is about average.

For baking foliage if you do want to customize: you can create a custom foliage "collection" (see Bundles/Assets/Landscapes/Foliage/Grass/PEI/PEI_Grass_00_Collection.asset) which is linked from a material, and then the collection lists foliage assets which have baking properties like density, scale, rotation, surface alignment, etc.

Performance wise yes currently one tile is read per frame on the main thread and I do intend to move that to another thread eventually.
