### ISSUE TITLE
[Feature Request] "Shield" item type

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3190]
Name is self-explanatory, it'd work like Minecraft's shield: you hold it in your arm, and left-clicking makes you defend yourself from incoming bullets/attacks. If possible, could be equippable as a secondary weapon and working as a dual-wield (somehow? Probably wouldn't work well with aiming on guns and secondary attacks)

A boolean "Pierce" variable would allow/disallow incoming attacks from melee weapons (i.e. swords, axes) or high-caliber bullets from piercing through the shield when durability is low (lower = higher chances of the attacks going through the shield).

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
