### ISSUE TITLE
[Feature Request] Make it possible to change the damage of Bayonets/Melee Tactical Attachments

### ISSUE THREAD

**Issue by Gamingtoday093** [SmartlyDressedGames/Unturned-3.x-Community#3206]
Taking a peek at the `UseableGun.cs` file it becomes evident that Melee Tactical Attachment Damage amount is completely hard coded to the `DAMAGE_PLAYER_MULTIPLIER` making it impossible to change the damage of the jab. Ideally, a revamped system would include `Melee_Damage_Multiplier` and the ability to specify damage multipliers per Melee Tactical Attachment. This is essential if you want a different damage scaling for your bayonets or simply to allow for multiple unique bayonets with their own damage amounts.

**Comment by SDGNelson** [comment]
I think what will end up happening as part of revamping attachments in general is new properties for each special attachment sub-type like full damage config for bayonet or projectile config for underbarrel grenade launcher.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
