### ISSUE TITLE
ServerModifyOxygen

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3211]
Hello Nelson, I hope you are okay! If you can add "ServerModifyOxygen" method for the server-side edit player oxygen, that would be great! I'm creating a RocketMod plugin and I can't see any server-side method for modify oxygen :)

**Comment by fahrettinenes** [comment]
```cs
public void ServerModifyOxygen(byte newOxygen)
{
                ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>? SendLifeStats = typeof(PlayerLife).GetField("SendLifeStats", BindingFlags.NonPublic | BindingFlags.Static).GetValue(player.life) as ClientInstanceMethod<byte, byte, byte, byte, byte, bool, bool>;
                FieldInfo field = playerLife.GetType().GetField("_oxygen", BindingFlags.NonPublic | BindingFlags.Instance);
                if (SendLifeStats is not null && field is not null)
                {
                    field.SetValue(player.life, newOxygen);
                    SendLifeStats.Invoke(player.life.GetNetId(), ENetReliability.Reliable, player.channel.owner.transportConnection, player.life.health, player.life.food, player.life.water, player.life.virus, player.life.oxygen, player.life.isBleeding, player.life.isBroken);
                }
}

```

Also, with this code that's possible but a method would be good.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by sunnamed434** [comment]
#3955
