### ISSUE TITLE
"Size Overflow in allocator"

### ISSUE THREAD

**Issue by LiamW07** [SmartlyDressedGames/Unturned-3.x-Community#3215]
Hello, i recently updated my materials to be masterbundled, however 2 out of the 5 cause my game to crash when applying to any tile with the last error in my playerlog being “Size overflow in allocator”.  Any support on how to fix this would be great.

**Comment by SDGNelson** [comment]
Sorry about the crash! When you apply 3 of the materials it does not crash, but 2 specific materials cause crashes? Could you zip and attach the relevant .asset, .masterbundle, and MasterBundle.dat files please? I will try loading it up and see if I can reproduce the crash because I might be able to get more details in a debug version.

**Comment by LiamW07** [comment]
> 
[yeuah.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/8750353/yeuah.zip)
Sorry for the late reply, heres my relevant files.

**Comment by SDGNelson** [comment]
Thanks for the files! The crash message says the asset bundle is corrupted, but further back it mentions the file not being readable, so maybe the "CPU Readable" option is not enabled in Unity? Otherwise it might be worth re-exporting from Unity in case it is corrupted somehow. Also, which version of Unity did you use? 2019.4.38f1 is the current version used by Unturned.
