### ISSUE TITLE
[Feature Request] Escape (ESC) Input Event

### ISSUE THREAD

**Issue by BarehSolok** [SmartlyDressedGames/Unturned-3.x-Community#3225]
There are many UI plugins using their own Window/Modal, most player are used to close Window/Modal with ESC key, so it would be better if there is an input event for ESC key

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
