### ISSUE TITLE
[Feature Request] Lock special items to restrict it in crafting menu

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3226]
I know that in Unturned we have already button to disable crafting of item, imagine situation when you need to restrict a craft of a special item(s) which you would choose.

For example, i have a binoculars that i have already bind to my hotkey, lets that thats is key (3), and i want to do some crafting, i forgot that i have 3 binoculars in my inventory and i clicking to salvage item in crafting menu + pressed hotkey "CTLR" and i lost them all.

Or, i salvage 2 binoculars of 3 then i need to rebind my binocular to the hotkey (3) again.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
