### ISSUE TITLE
Creating an audio streaming function by URL

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3229]
Nelson, hello. We need to make a function that will add the ability to create a specific place where the sound will be played from a direct URL.

**Comment by GazziFX** [comment]
As I remember its possible with built-in Unity components

**Comment by surv0013** [comment]
> As I remember its possible with built-in Unity components

Yes, but scripts in mods are not available.

**Comment by Spebby** [comment]
Built in components =/= scripts. I'm not sure which components the previous reply is referring to.

**Comment by GazziFX** [comment]
> Built in components =/= scripts. I'm not sure which components the previous reply is referring to.

I don't remember which component but it work in Unturned, maybe its not available in some versions, or it needs to change properties mode to show more features

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
