### ISSUE TITLE
[Feature Request] Storage Addition

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3239]
Would it be possible to have it so a player can access and put an item into another players storage but only the owner can remove items from the storage. Useful for things such as mail boxes.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
