### ISSUE TITLE
QoL Suggestion: Allow other attachment locations to be caliber-based & barrels to change muzzle effects

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3240]
It would be nice to make the location of other attachment types on the gun item to be caliber-based so they can have specific areas to go to, which is exactly what's used on the Nightraider, Augewehr, & Fusilaut when using ranger or military magazines.

And muzzle effect change depending on the barrel attached to guns is small but flairs them too. It can work like how magazines override the tracer effects. It'll do cool things like making a barrel that gives a laser muzzle effect or a smoke effect.

**Comment by SDGNelson** [comment]
As in the model position changes depending on caliber?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
