### ISSUE TITLE
QoL Suggestion Snap to Plane on F6 Editor

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3242]
Placing buildables down in game can be really crooked, would it be possible to have a button in the F6 editor that allowed a player to snap the objects rotation to a perfect 90 degree plane whether on the ground or on a vehicle.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
