### ISSUE TITLE
QoL Suggestion: Input fields for scale and rotation

### ISSUE THREAD

**Issue by surv0013** [SmartlyDressedGames/Unturned-3.x-Community#3244]
It would be nice to be able to set the rotation and scale of objects manually using input fields in the default editor, as you can do in the Unity inspector.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
