### ISSUE TITLE
[Feature Request] Cancel last action

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3246]
Add canceling of the last action (healing, reloading, animation, change something in hands (weapon or something like that))

This is would be very helpful feature, this is will increase the level of gameplay in Unturned. This feature will get rid of misclicks.

Example: Press button "X" to cancel reloading or building and etc

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
