### ISSUE TITLE
(Suggestion) Add a feature where you can change the volume of specific things

### ISSUE THREAD

**Issue by johnnysinhghu** [SmartlyDressedGames/Unturned-3.x-Community#3248]
Such as Lowering the noise for guns,footsteps,vehicles etc specifically instead of all of it being into one section.
Good example is minecraft

**Comment by surv0013** [comment]
I think this can give an advantage on PvP servers, what can really be displayed in a separate slider is the sound of the radio, sometimes streamers complain that music with copyright is playing on the radio, which leads to monetization on YouTube being disabled.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
