### ISSUE TITLE
Add Walking NPCs with animations

### ISSUE THREAD

**Issue by Chief-Ahmed** [SmartlyDressedGames/Unturned-3.x-Community#3249]
You can implement this by having a NPC path editor, and have it similar to the road editor

**Comment by Spebby** [comment]
Unfortunately unlikely to appear in 3.x any time soon (if ever?), would be really cool though.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
