### ISSUE TITLE
[Feature Request] Shirt rendering.

### ISSUE THREAD

**Issue by Ditmas1** [SmartlyDressedGames/Unturned-3.x-Community#3252]
Would it be possible to make a feature where you can choose what clothing piece renders first? (Shirt or pants) This would allow for features such as shirts with capes to have the cape apply to a piece of pants as long as the cape is on the texture of the shirt. Currently if you did something like this you would need it to be a item in pants ( but have only the texture of shirt + cape), and in first person mode it does not show the shirt texture, also does not give protection status for the arms.

**Comment by Ditmas1** [comment]
![image](https://user-images.githubusercontent.com/107338452/173216850-458e4281-0909-41b1-bd56-80120dc7093e.png)
![image](https://user-images.githubusercontent.com/107338452/173216855-e4b66a6b-8943-4c68-8b8d-837dc59d5020.png)
![image](https://user-images.githubusercontent.com/107338452/173216858-bd6a8857-8f43-40d4-b149-0471295a25d7.png)
As you can see in the pictures provided it works only when the shirt is labeled as a pant in the item menu
![image](https://user-images.githubusercontent.com/107338452/173217029-e8aaeaa9-9591-4d8e-8f33-1379e7d94cb5.png)

**Comment by MoltonMontro** [comment]
This has been requested in the past (1+ years ago?). I believe we're hesitant to due this because some mods (and cosmetic items) are already relying on pants being layered after shirts. Adding a parameter that switches them would just be another hacky workaround.

@SDGNelson has long wanted to [revamp how clothing and clothing slots](https://trello.com/c/cUi1cLCA/43-clothing-slots) works to better support things like this. I believe a proper revamp is currently more likely than any sort of workaround.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
