### ISSUE TITLE
[Feature Request] Movement_Speed_Modifier for Items & Food/Medicine

### ISSUE THREAD

**Issue by EnderDerSchaender** [SmartlyDressedGames/Unturned-3.x-Community#3253]
I love the option of giving clothes a unique movement speed, but what about Items and Food/Medicine? Some guns are heavier than others, so it would only make sense, that for example a minigun has less movement speed than a pistol. Also concering the food/medicine in the title, making something like a consumable energy bar, which grants a speed modifier for * seconds, could also be very handy! I'm thinking of making some pills, which act like berries (giving you drug effect) but also giving you a speed boost, so it pays off using it.

**Comment by educatalan02** [comment]
This could be done with plugins ^^

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
