### ISSUE TITLE
[Feature Request] Config.json

### ISSUE THREAD

**Issue by danielstankw** [SmartlyDressedGames/Unturned-3.x-Community#3255]
I would like to suggest adding ability to define the chance of ground/ water/ air vehicles to spawn in the `config.json`.
Currently we can only define the max instances of ALL the vehicles, but players often complaint that its very rare to see air vehicles.
It would be very cool to define the max instances like now, but than have ability to define the chance of vehicle type to spawn.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
