### ISSUE TITLE
Add element to user interface

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3258]
Conditionally I have a list of items in the UI. Is there a function that can duplicate one of the items in this list.

**Comment by Dolphinchik** [comment]
Support for creating and removing duplicates of already existing elements in the scene would be quite a useful addition.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
