### ISSUE TITLE
[Feature request] Echo player voices in caves

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3260]
Adds an echo to player voices similar to effects -> no lighting in the editor.

**Comment by SDGNelson** [comment]
Technically if you really want this might be possible by placing a prefab with reverb zones. (for the meantime)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
