### ISSUE TITLE
[Feature Request] Dedicated Weather Mask and Music volumes

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3265]
Currently, when implementing non-diegetic music or adding a weather mask, an Ambience Volume is required. Usually this is fine, but there can be issues if a map either has very detailed weather zones, or there's a cave with a dark zone within a Weather Mask. The game doesn't like it when there's an ambience volume inside of an ambience volume and gets confused about which to prioritize (From testing priority appears to go to the older volume). In some cases, if an Ambience Volume has audio attached to it (like music or cave ambience) it can play globally if it's within a larger ambience volume.

I think it would be good if the Weather Mask functionality was split into its own volume in order to reduce errors with Ambience Volume priority. ~~I'd also like to request a dedicated Music Volume in order to further avoid issues with Ambience Volume priority, and also incase a dedicated "Music Volume" slider is added at some point, which seems more likely considering the recent addition of loading screen music to PEI.~~ (This has been added)

**Comment by DMJaxun** [comment]
Adding on to this, a generator volume that provides infinite power to items in the zone.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
