### ISSUE TITLE
[Bug or Feature] Megazombies

### ISSUE THREAD

**Issue by FireRain4** [SmartlyDressedGames/Unturned-3.x-Community#3267]
Hello Nelson

I just tried to put several megazombies on one navigation. Eventually only one will spawn. Please help me fix this!

**Comment by gargTop12** [comment]
I have the same problem

**Comment by SDGNelson** [comment]
Sorry, the limit for natural spawns is one mega zombie per navmesh.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
