### ISSUE TITLE
Add cvar to edit network update time

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3269]
I want to change Provider.UPDATE_TIME and Provider.UPDATE_DELAY on my arena server for best synchronization.
Please add this function, its very simple and very cool feature.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
