### ISSUE TITLE
Add control animation hook

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3270]
I want to change parameters in Animator, but standart UnityEvents cannot pass more than 1 parameter.
I think you can add simple script to change Float Bool And Int parameters.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
