### ISSUE TITLE
[Feature Request] Purge Unsubscribed Mods Button

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3275]
Add a button to the in-game Manage Files menu to purge the workshop folder of workshop mods that have been downloaded when joining a server that aren't subscribed to by the player. Makes it more easier to remove unwanted content than doing it manually in the files.

**Comment by GazziFX** [comment]
I think unloading of unsubscribed content when joining to the other server is better

**Comment by surv0013** [comment]
Maybe make it possible to disable certain assets in the menu, as is done in Garry's Mod.

**Comment by SDGNelson** [comment]
Adjusting the list of ID->Asset lookups when changing servers is on my to-do list, but this request is unlikely because it would be modifying Steam's install folders in unintended ways. (SteamUGC does not directly expose a function to uninstall)

**Comment by QERT2002** [comment]
> Adjusting the list of ID->Asset lookups when changing servers is on my to-do list, but this request is unlikely because it would be modifying Steam's install folders in unintended ways. (SteamUGC does not directly expose a function to uninstall)

Why delete mods from the folder if it is enough to upload the assets of already loaded mods from the game so that there is no mixing of IDs and other things, also after each update of the modification in the workshop you have to restart the game in order to update the files, otherwise your check does not see the updated modification when reconnecting to the server that it uses

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
