### ISSUE TITLE
[Feature Request] Custom per-map Skillsets overrides

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3287]
Skillsets aren't a super notable feature in Unturned, so this is a pretty minor suggestion. For maps like Elver and Arid-- which have no vanilla item content --it may be confusing to a player why they can't use the cloth they're finding with the cloth they've gotten from scrapping their starter clothing. This is a relatively minor issue, but it would be nice to allow for starter clothing to be customisable per map, to allow for the vanilla clothing items to be overridden with the map's equivalent. I imagine this could be done with an Asset V2 file that is referenced by a JSON.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
