### ISSUE TITLE
Timers and stopwatches for UI.

### ISSUE THREAD

**Issue by Sl4vP0weR** [SmartlyDressedGames/Unturned-3.x-Community#3298]
Creating timers or stopwatches in UI is painful, to update time in text elements we should to send new formatted text each second to client.
Too many RPC calls may cause ping troubles.
Maybe we can do something about it?
As solution, I guess we could add some RPCs with formatting of text which will update elements on client-side each second.

Example of usage:
```csharp
EffectManager.sendUIEffectStopwatchText(key, connection, reliable, name, format: "{time:mm':'ss} passed.", timeFrom); // time = DateTime.Now - timeFrom
EffectManager.sendUIEffectTimerText(key, connection, reliable, name, format: "{time:mm':'ss} left.", timeTo); // time = timeTo - DateTime.Now
```

**Comment by Sl4vP0weR** [comment]
@SDGNelson

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
