### ISSUE TITLE
[Feature Request] Custom Death Music

### ISSUE THREAD

**Issue by EnderDerSchaender** [SmartlyDressedGames/Unturned-3.x-Community#3304]
We all know the iconic Unturned Theme that plays, when you die in Unturned. But what if you could customize it, just like the loading screen music that was added a few updates prior? I'd imagine it gives maps a certain uniqueness when you die on them.

**Comment by Spebby** [comment]
While interesting, I would still like to hear the classics theme instead. If this is added a toggle would be appreciated.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
