### ISSUE TITLE
server attack problem

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#3310]
My server was attacked by a Steam login packet with a fake IP.
The number of links is only about 7K, and the server cannot be searched. Is there any way to improve the carrying capacity of the server?

**Comment by SDGNelson** [comment]
What do you mean by Steam login packet? And by the number of links?

**Comment by CatzMR** [comment]
The Steam query packet I am talking about is the data packet sent by the client to the server when the player searches for the server. This data packet can be used to attack the server. At present, my server has been attacked, and the number of links is as much as 40W. But the server did not answer the data packet, it seems that the carrying capacity is exceeded, so that players cannot search for the server, and cannot enter directly. My server has enough bandwidth, and I hope to improve the carrying capacity of the server.

**Comment by SDGNelson** [comment]
I think all of the protections mentioned in this post are now active by default which is why your server would not be responding to the spam packets: https://steamcommunity.com/discussions/forum/14/2974028351344359625/

This is outside of what is configurable by the game however, sorry. I think part of the intention behind Steam's newer fake IP system is to help mitigate this by making the game server no longer directly responsible for the query response.
