### ISSUE TITLE
Grow speed multipler

### ISSUE THREAD

**Issue by GazziFX** [SmartlyDressedGames/Unturned-3.x-Community#3314]
Not found any settings for plants in ModeConfigData, I think can be useful to change grow speed globally.

**Comment by Darkmega18** [comment]
I'd probably appreciate growth speed config also.
unless it's mixed into the resource replenishment timer multiplier? 
but in that case, it's also bad, cause while I'd want rocks and trees to not come back so quickly as to sprout in my face at places I've logged/mined before I'm done collecting. Having it nuke growth speed of crops that the only reliable way to grow is to mass plant and wait for rain or log off and have it grown later is kinda oof.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
