### ISSUE TITLE
Hello! Is there any way to control the slider or the fill amount of image

### ISSUE THREAD

**Issue by wrdkj** [SmartlyDressedGames/Unturned-3.x-Community#3315]
I want to realize the blood bar function of zombies in the game! But I don't know how to control the progress value of the slider, because the UI doesn't support packaged scripts

**Comment by wrdkj** [comment]
I see that other plug-in authors have implemented this function, but he doesn't want to tell us

**Comment by wrdkj** [comment]
> 
Can you talk about it in detail

**Comment by wrdkj** [comment]
> 

Can you talk about it in detail

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
