### ISSUE TITLE
[Feature Request] Interactability options for barricades

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3317]
Could we possibly get the abiltiy to add Interactability actions to barricades? Like Droppers, fuel and water sources, so that its possible to make custom well barricades, sinks that actually serve as water sources, or maybe some machinery that produces new items (just a dropper same as vending machines).
Also it would be nice if it was possible to add item conditions to droppers, so it would be possible to make crafting stations (you loose the required items, but get the dropped item). Right now the only way of somehow doing this is using the Plant barricades, but they have way too many disadvantages with such application (they break when you harvest all of the crops, the amount of drops is dependent on Agriculture skill and you cant disable it) and overall its not the use they're intended for, yet still the demand for such barricades exists.
Crafting system being limited to just inventory crafting, using tools and skills, is a big limitation for mods that revolve around crafting progression and adding these features allows to remove this limitation without rewriting the crafting code.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
