### ISSUE TITLE
[FEATURE REQUEST] Projectile Override per Magazine

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3326]
Allow magazines to have custom "Projectile" prefabs that would override an weapon's projectile prefab when loaded. Would allow for more ammo variety for projectile weapons.

**Comment by Spebby** [comment]
> I remembered seeing this idea and there are also a few related topic to this, though they are all quite a few months/year back. #3018 #1221 #2303

good to know it's widely requested.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
