### ISSUE TITLE
Server get client binded plugin key name

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#3327]
It would be cool and useful, to get the name of the key which client is bind.

It could be more understandable and useful for UI and players.

**Suggestion:**
Real example with UI: Press Plugin Key 1 to do smth and here is misunderstanding, player dont understand what is that key, player need to open settings and look to settings and find "Plugin Key 1", not all players will do this, they just will start click to every key on their keyboard.

**The result:**
UI: Press Comma to do smth

I`d like to hear your thoughts about that.

![image](https://user-images.githubusercontent.com/65300126/179754148-5f840417-c714-4bf2-8813-596963d6e55a.png)

**Comment by DiFFoZ** [comment]
It's already possible to do that by: `<plugin_{0}/>`

**Comment by GazziFX** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2882

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
