### ISSUE TITLE
[Feature Request] Option Components for Crafting

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3338]
It'd be interesting if we could craft an item from X amount of a group of items, eg. a trash bundle from different varieties of trash.

**Comment by GazziFX** [comment]
It think it wont happen in near future, based on these comments:
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2972#issuecomment-1003205583
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2990#issuecomment-1013532588
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3219#issuecomment-1135861536

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
