### ISSUE TITLE
Workshop mods mixing

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#334]
Spotted this a while ago. Its probably due to same ids. For example, if player connects to some modded server and then without relaunching game he connects to another then he see some items completely different as it should be on that server. 

I am pretty sure that this issue appears because of same ids used for different items. Even if both servers use different workshops

I believe it shouldn't be like that?

**Comment by SDGNelson** [comment]
Related to some recent changes to how mods from servers are handled - new content from the server is allowed to completely override files / ids the client knew about before joining which currently isn't reversed when leaving the server.

It's a trade-off due to some bad decisions from 2014, the idea being that at least this way if you have a ton of workshop content installed you can still properly join servers that have different workshop content. (Previously you would get kicked for having mistmaching files.)
