### ISSUE TITLE
Equipped Item condition

### ISSUE THREAD

**Issue by Tiway-Paper-Guy** [SmartlyDressedGames/Unturned-3.x-Community#3342]
Hello!

It would be very cool if a line added to an Item condition would consider equipped items, the conditions should not take these item into acount by default though, because player may loose item they prefer to use.

Something like this :

> Condition_0_Type Item
> Condition_0_ID 4
> Condition_0_Amount 1
> Condition_0_Count_Equipped_Item

(Not sure if the line I chose makes the most sense)

Thanks!

**Comment by DrDallas1** [comment]
+1 to this suggestion. 

Example on how useful this would be:
You could make backpacks that have specific gear, like carrying a stack of planks on your back. Could be used with the new movement speed multiplier, such as having a quest to carry planks across a yard, and they would be too big to fit in your inventory, hence why you should be able to turn it in directly.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
