### ISSUE TITLE
[Feature Request] Allow plants to require power/fuel to grow 

### ISSUE THREAD

**Issue by SaturnnDragon** [SmartlyDressedGames/Unturned-3.x-Community#3353]
Been trying to make a industrial mod for awhile and was wondering if you could pretty please make an option in unity mod creator where a plant will require generator power to grow.

**Comment by Gorge420** [comment]
Good idea

**Comment by Gorge420** [comment]
This would be better added in the .dat files options

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
