### ISSUE TITLE
Feature Request: Health condition mod hooks for buildables, objects, & vehicles

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3354]
It'll be creative & interesting if there are mod hooks that set health conditions for buildables, objects & vehicles. It can allow many things  to occur to your liking such as build states & vehicle physics changes.

**Comment by SDGNelson** [comment]
Like changing out the model as it gets closer to destruction? That would be neat.

**Comment by OneManOperative** [comment]
Exactly that. Optionally, do you mind having a mod hook variant that works on item & clothing durability?

**Comment by SDGNelson** [comment]
Mod hook component for the Item prefab? Currently it would not have a good way to get the item details, but I am aiming to start the inventory rewrites after the volume rewrites.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
