### ISSUE TITLE
[Bug Report] Prison Swing Doors

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#3362]
Prison Swing Doors don't seem to be working on Multiplayer since the last update, players can't walk through them while they're open. 
Prison Slide Doors are working correctly, and swing doors are working on Singleplayer. 

Not sure if this is a universal issue or just on my server/custom map

https://user-images.githubusercontent.com/71527679/184508241-fa2b0c9c-2798-47ad-8b02-d6490ad4850a.mp4

**Comment by SDGNelson** [comment]
Sorry about this! It looks like they are configured identically, will investigate.

**Comment by MoltonMontro** [comment]
Contrary to OP's post, this issue seems to affect _all_ interactable objects—including both prison slide doors and prison swing doors. But also things like silo doors, boom barriers, and car lifts.

It's just that the specific symptoms differ slightly. For most objects, there is at least still a very subtle rubberbanding. But some will allow you to walk through anyways (and even walk through while the object is closed). For example, the silo doors and prison slide doors.

Surely this is a side-effect from Clip.prefabs no longer being necessary for interactable objects? Perhaps the automatic clip prefab doesn't work as expected for objects with multiple states?

**Comment by SDGNelson** [comment]
Should be fixed in the .2 patch this morning! Sorry this went unfixed longer than it should have. In case anyone is curious the reason is that the Clip.prefab manually had the Animation culling type set to Animate Always.
