### ISSUE TITLE
Flags in Effects

### ISSUE THREAD

**Issue by felipedual** [SmartlyDressedGames/Unturned-3.x-Community#3363]
Hello. I would like to know if effects work with flags (to appear and disappear like objects). If this is not possible I would like to know if it is possible to transform the effects into objects so that I can use the flags.

**Comment by GazziFX** [comment]
Why not check flags at plugin side when you sending effect?

**Comment by felipedual** [comment]
> Why not check flags at plugin side when you sending effect?

Because I'm trying to do this on my map so it doesn't have any plugin.

**Comment by DerpyHoowes** [comment]
What are you trying to make with it?
Maybe we can figure out a better solution

**Comment by Ongjming** [comment]
> Hello. I would like to know if effects work with flags (to appear and disappear like objects). If this is not possible I would like to know if it is possible to transform the effects into objects so that I can use the flags.

Do you also mean if conditions like this:
![image](https://user-images.githubusercontent.com/28900564/185236304-9176bf55-5944-4857-9ec2-4afbb5279f68.png)
Can be used in the effects .dat files?
![image](https://user-images.githubusercontent.com/28900564/185236394-6016e6da-d5cd-4534-af3c-a5a58b68050b.png)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
