### ISSUE TITLE
Feature Request: Usage Language.dat

### ISSUE THREAD

**Issue by V1nDeer** [SmartlyDressedGames/Unturned-3.x-Community#3371]
Hello. I would like to ask you. You can add language changes in the game settings. What if our mods have English.dat or Russian.dat, then the player who chose one of the languages in the game settings used the translation. If the mods do not have the desired language that the player has chosen, then English.dat was used by default. I know you want to add this feature after the game is translated. But I want to ask that this be added with the next update so that those people who want to translate their mods can take advantage of this in the next update and not wait for the official translation. This would be very helpful for many developers. Well, or add a function that would allow using the plugin, for example, to use other translations on NPCs, mods, maps, etc.

**Comment by SDGNelson** [comment]
This should be how it currently works - if Russian.dat exists it will use that, but if it does not exist then it uses English.dat as a fallback.

**Comment by V1nDeer** [comment]
Why doesn't this work on our servers? We did this several times and nothing worked. What conditions are needed for this to work?

**Comment by V1nDeer** [comment]
I don't want to use Russifier. I want this setting to be official in the game.

**Comment by V1nDeer** [comment]
Please explain. What should I do that Russian.dat, English.dat, Ukrainian.dat worked for me. What should I do for this?

**Comment by V1nDeer** [comment]
![image](https://user-images.githubusercontent.com/54030822/185702951-b155c7d0-ede4-473c-8508-0109ad922a03.png)
![image](https://user-images.githubusercontent.com/54030822/185703162-037bd334-bd7d-4c3b-b75d-9da488683a3d.png)

Here I made 3 languages. But the game uses only Russian. If I remove Russian, then Ukrainian is used. And I want to be able to choose through the game which language I should use. Even if the Localization does not have the language that I chose.

**Comment by SDGNelson** [comment]
Oh you want to specify which language is used during startup? Currently that can be done with the -Lang=XYZ argument. For example:
1. Right-click Unturned in your Steam Library
2. Select Properties... > General
3. Find the Launch Options field
4. Type "-Lang=Ukrainian" without quotes

**Comment by surv0013** [comment]
I think he wants to be able to change the language right in the game. As I understand it, now the game is not developed for this, translations are loaded at the time of its launch. It would be nice to be able to change the language during the play. This would allow creating thematic localizations for the server.

By the way, how about making only one file with the extension ".lang" instead of folders? This would make it easier to load the localization. For translations of items, you can make the fields "ITEM_NAME_%ITEM_GUID%".

**Comment by DiFFoZ** [comment]
> Oh you want to specify which language is used during startup? Currently that can be done with the -Lang=XYZ argument.

Maybe also use Steam API to get preferred language [ISteamUtils::GetSteamUILanguage](https://partner.steamgames.com/doc/api/ISteamUtils#GetSteamUILanguage)?

**Comment by SDGNelson** [comment]
Based on V1nDeer upvoting surv0013's comment I assume that is what he meant: an in-game option to override the language setting might be added at some point, but not without restarting the game unfortunately because the entire codebase assumes the language does not change while running. (which does greatly simplify some things)

@DiFFoZ Unturned does default to GetSteamUILanguage if not otherwise specified.

**Comment by V1nDeer** [comment]
![image](https://user-images.githubusercontent.com/54030822/185764766-cd8937d4-747a-4bbf-b1e8-530a78df97f3.png)
The Steam API only works if the player has a Russian or Ukrainian folder in Localization

**Comment by surv0013** [comment]
> The Steam API only works if the player has a Russian or Ukrainian folder in Localization
Yes it is. Unfortunately, the game loads only those localizations that are in the "Steam\steamapps\common\Unturned\Localization" folder, it would be nice if the game also checked those localizations that are in the "Steam\steamapps\workshop\content\304930" folder.

**Comment by surv0013** [comment]
> because the entire codebase assumes the language does not change while running

I understand this, I made games myself, but nevertheless, maybe then at least add a setting to the game options so that you can select the language from those available in the "Steam\steamapps\workshop\content\304930" folder, just sign below that: "For changing the language you need to restart the game", as you did with the tree models. It’s just that few people want to transfer folders from the workshop to the game folder for localization to work, and then also set an argument to launch the application, it takes too much time, and you know what kind community of game you have (children).
