### ISSUE TITLE
Zombie damage with shotgun

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#3386]
There is a bug that when a zombie is killed with a shotgun `DamageTool.damageZombieRequested` is triggered multiple times even after zombie died this should be fixed.
`DamageTool.damageZombie` should just check if zombie is dead and ignore it, since it trigger events and do some calculation in vain(Image bellow).

![image](https://user-images.githubusercontent.com/20555316/186267290-95d5c9f8-47bf-48ae-8615-de3ac189537f.png)
`Zombie.askDamage` seems to have an unecessary duplication check. (prob. a typo)

**Comment by surv0013** [comment]
My friend, I've been digging into this code since 2015, and so, there are a huge number of such duplicates. Double check is still nonsense, in some places there are fields that simply refer to other same fields. And then there are variables that are never used. Some variables are equated to the same value 2-3 times. :D

**Comment by rube200** [comment]
The real issue is not the mem code but the miss checks

**Comment by rube200** [comment]
@SDGNelson anything?

**Comment by SDGNelson** [comment]
Oh right, will put on to-do I suppose

**Comment by SDGNelson** [comment]
Player, zombie, and animal methods in that class will ignore the request if dead in the next update
