### ISSUE TITLE
Small Requests: Flag to only shoot when aiming & movement speed multiplier to equipped items

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3390]
An optional but welcome addition to add options to make gun items only shoot when aimed, which already exists via Actions Minigun & String, but it would be nice to have it as a flag. & have the movement speed multipliers be an option for equipped items so that creators can make items that have speed debuffs. A little fun thing that is welcome too is an option for multipliers to apply if the item is in your inventory as well.

**Comment by SDGNelson** [comment]
Ideally yes all of the stuff linked to "Action" should be their own separate options.

**Comment by OneManOperative** [comment]
Yep, unfortunately the minigun action doesn't allow you to aim down sights & string ejects magazines. I hope to see a feature to make a workaround that issue so that it can be used for making a gun balanced around only shooting if aimed down sights while not ejecting ammo.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
