### ISSUE TITLE
[Feature Request] Ability to change the attack rate of continuous melee weapons

### ISSUE THREAD

**Issue by GreatHeroJ** [SmartlyDressedGames/Unturned-3.x-Community#3410]
Title feels fairly self-explanatory.

This would open up interesting avenues regarding melees, such as permitting someone to mimic an auto-swing feature for melee weapons that would otherwise not be continuous (by making the attack rate very slow).

**Comment by GazziFX** [comment]
Try to set `Weak 0.1` in dat file

**Comment by SDGNelson** [comment]
Melee really needs some love in general. Currently it is hardcoded to 10 times per second but I should make this configurable.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
