### ISSUE TITLE
[Feature Request] Unique id for Items

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3417]
Hello! Please add unique id to Item class. That would be really great. Please do that :D

**Comment by rube200** [comment]
Why? What is the point of that?

**Comment by GazziFX** [comment]
> Hello! Please add unique id to Item class. That would be really great. Please do that :D

InstanceID is more relevant name

**Comment by GazziFX** [comment]
> Why? What is the point of that?

Custom server-side data for items, but Nelson already mentioned that https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3352#issuecomment-1212179281

**Comment by fahrettinenes** [comment]
> InstanceID is more relevant name

You're right

**Comment by fahrettinenes** [comment]
> > Why? What is the point of that?
> 
> Custom server-side data for items, but Nelson already mentioned that [#3352 (comment)](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3352#issuecomment-1212179281)

I didn't see that, thanks I hope he can do that asap

**Comment by fahrettinenes** [comment]
> Why? What is the point of that?

Imagine you have a roleplay server and everyone opening lockers and doors with custom key items :D

**Comment by Gamingtoday093** [comment]
This. It'd be great to easily be able to keep track of an item after it's dropped

**Comment by rube200** [comment]
I mean this should be for items and not itemjar

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
