### ISSUE TITLE
[Feature Request] Adjustable effect for the airdrop

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3426]
Currently when the carepackage lands, the game always spawns the red smoke effect. Could we get the ability to spawn our own effects on carepackage landing or not to spawn any at all?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
