### ISSUE TITLE
[Feature Request] Load Vehicle Ammunition from Vehicle Storage

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3427]
Allow vehicles with turrets the option to load ammunition from the vehicle storage as opposed to a players inventory. Eg to simulate loading ammunition from a ready rack inside a vehicle like a tank.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
