### ISSUE TITLE
Issues with Client & Server communication following mods.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#3436]
Hello, I am opening this issue in part with a few large community based servers.

As we have come to the issue where people are having trouble connecting to servers whenever a mod updates and changes the .dat files, due to a desync happening between the client side .dat files, and server side .dat files.

We thought it would me a major advantage for the modding community to be able to give versions for their mod, so if an updated / outdated version of the mod on the client attempts to join the server, the server can notify the client that there is a version mismatch between the mods, instead of eg:
`Modified or corrupted asset: "Aero x Ducci Aero Industries Seven Month Sparrow" File: "Aero x Ducci Seven Month Sparrow" Id: fb3b68e97a7746bfa92c6c2e73fcd92e Client: 2C12CA77CA4C53D426E7ACFE1DE065F5A8D9258F Server: E0448A830663422193AA5CC45F1CEA46B65BD8B1`

Which would offer a more readable solution for users who are less tech-savvy, and would reduce my overall time and effort into helping all users not subscribed to a mod and thus also encountering this issue.

An "Easy" implementation or solution for this "Issue" could be as simple as letting mod developers add a version name or number for their mod, which when the server sees that the versions of each mod mismatch, that it can notify the user that they have outdated or that the server has outdated mods, and if possible update it itself.

This in turn would make it a lot more user friendly as most of the Unturned community are kids with little to no tech experience.

This is just an observation based on previous encounters whenever my, or anyone else's mod gets updated and the client & server have a desynchronized .dat file.

Thank you for reading this all, I know it is a large amount of text, but if you did end up finding the time to read this all it'd be great.

**Comment by Bradler26** [comment]
I'm don't have a great grasp of how workshop mods work but from what I have been told this error is common with mods that update often since it changes the MD5. I understand that this is of course used to stop people editing game files to get unfair advantages but could there be some server-client cross check that runs before the user gets into the server? Even if it makes the loading time a tad longer for the client it would solve a lot of headaches if the server could pass all the mod's info to the client and then the client checks it with the files on the local PC. if any files are outdated then the client should redownload the mod to the latest version.

Another suggest (not sure if this is allowed with steam or anything) would be to force subscribe the user to the mod via steam as I believe steam handles keeping the users mods fully updated when they boot their game. I think the problem here is because users aren't subscribed and rather just have the files downloaded onto their machine which results in them having outdated versions. 

Like @Axodouble suggested maybe a version number in the files would be great. That way the server and client can cross compare and if the client has a lower version the mod will be redownloaded whereas if the server has the lower version then a message can be shown to the client that the server owner needs to update the mods.

**Comment by DiFFoZ** [comment]
If you're buiding a mod with `Multi-Platform` option it will create a `.hash` file, so server will check the hash and kick him if hash is wrong with a reason `asset bundle MASTERBUNDLE_NAME version mismatch`.

Also, steam doesn't not force check/update subscribed workshop items on game startup.

**Comment by SDGNelson** [comment]
There is definitely a lot of room for improvement with asset desync between client and server. One of the next related improvements on my to-do list is to include the workshop file ID with the error so that different messages can be shown for example "asset with same guid in two different workshop files: X and Y"

**Comment by Axodouble** [comment]
> There is definitely a lot of room for improvement with asset desync between client and server. One of the next related improvements on my to-do list is to include the workshop file ID with the error so that different messages can be shown for example "asset with same guid in two different workshop files: X and Y"

Would it not be easier to let a mod owner put a version string for EG: the mod itself? So the server and the client could still see a mismatch but the more likely issue still being that there is a desync because of an update.
