### ISSUE TITLE
Feature Request: Launch Option for default masterbundle.

### ISSUE THREAD

**Issue by ksdsksd** [SmartlyDressedGames/Unturned-3.x-Community#3458]
I'm proposing a '-force-default-masterbundle' for the following reasons:

- The problem with using Linux is some map makers don't update/export the masterbundle for linux(I assume it's the same for Mac).
- On these maps, textures and items may be, and generally are missing, which can, and sometimes do make quests impossible to complete.
- In single player a  workaround is to remove " *_linux.masterbundle" and corresponding "manifest" files.  However you are then unable to connect to a server with these files removed.
- Generally, when contacting the map creator, they'll argue that it needs to be reinstalled to fix the problem.

**Comment by SDGNelson** [comment]
It sounds like you are asking for an option to force use of the Windows asset bundle? Unfortunately if the Linux hash is present then the server will expect the client to be using the Linux version of the file. Hmm not sure if there would be a downside to allowing joining with different platform's asset bundle. Nowadays if the mod creator updates the asset bundle without enabling multi-platform it will delete the Mac and Linux asset bundles + hash, but it depends whether they are using the most recent version of the tools.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
