### ISSUE TITLE
Feature Request: A client side only artificial horizon hud for aircraft.

### ISSUE THREAD

**Issue by ksdsksd** [SmartlyDressedGames/Unturned-3.x-Community#3459]
Having an artificial horizon would be nice to have during dust/rain/sand/snow storms.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
