### ISSUE TITLE
[Feature Request] Refill sound for Canteen (Type Refill) items

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#3462]
Currently refill items have Use and Refill animations, yet only the Use action can have an audio file, which makes it a bit inconsistent. Would be nice to see the ability to add refill sound to the item.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
