### ISSUE TITLE
[Feature Request] Can_Decay line for VehicleAsset.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3464]
It would be quite useful to have a `Can_Decay` line for vehicle assets. Might be used on admin vehicles, in custom gamemodes, etc.

**Comment by Jdance-Media** [comment]
Another good addition alongside this would be a `Battery_ID` line, similar to the `Tire_ID` line.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
