### ISSUE TITLE
[FEATURE REQUEST] Oxygen Volume tick rate

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3474]
Currently the oxygen volume applies its effect quite quick, it would be nice if this could be adjusted to different rates per volume, so map makers can create a more fine-tuned experience. Currently I'm working on a few areas that take advantage of the oxygen volume, and at the moment the oxygen volume suffocates a player with max skills quicker then they can explore the area.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
