### ISSUE TITLE
[FEATURE REQUEST] Holiday Lighting Override

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3476]
Been working on a full Halloween makeover for a project by making use of good ol' holiday redirects. I'd like the ability to override the map's lighting during holidays as well, since sticking with the regular lighting while sporting a barren landscape in the vein of Halloween PEI just looks off.

**Comment by Spebby** [comment]
Also would be nice to bring back Halloween PEI 😄

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
