### ISSUE TITLE
[BUG] God mode fails when damage overflows

### ISSUE THREAD

**Issue by makeloffve** [SmartlyDressedGames/Unturned-3.x-Community#3485]
The damage value of explosives in some workshop mod overflowed(more than 100), in this case, god mode and Friendly_fire setting false failed. Can this case be fixed in the internal mechanism?

**Comment by SDGNelson** [comment]
Explosives do not actually check for friendly fire because I did not want it to be safe to throw a grenade in while a teammate rushes with a shotgun. There is not yet a built-in god mode, so it depends where the plugin is blocking the damage. For explosives it would work to bind the `damagePlayerRequested` event.
