### ISSUE TITLE
[Feature Request] Aiming_Traverse_Speed_Multiplier

### ISSUE THREAD

**Issue by ComradePixel** [SmartlyDressedGames/Unturned-3.x-Community#3489]
Seeing how there are implementations on how guns and movement go together (such as Aiming_Movement_Speed_Multiplier and Aiming_Recoil_Multiplier) I think it would be nice to have an option to choose the aiming traverse speed for guns. 
Could be named Aiming_Traverse_Speed_Multiplier for consistency. It would simply multiply how fast you can traverse the gun in your hand, if I recall it's somewhat hardcoded into some elements but giving modmakers this possibility would enhance gun combat in many, many areas.

Thank you for your consideration.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
