### ISSUE TITLE
[Feature Request] Vehicle teleport volumes.

### ISSUE THREAD

**Issue by DrDallas1** [SmartlyDressedGames/Unturned-3.x-Community#3495]
Suggestion: Vehicle teleport volumes!
Why? Vehicle teleport volumes open a lot of possibilities with modded maps, such as allowing for pluginless off map garage parks, seamless sequences to have different parts of the map (two maps accessible via a tunnel, teleporting the player to the other side + their vehicle). 
Specifications I think would work very well with the system:
RequiresPlayerInVehicle: bool    (requires a player to teleport the vehicle. Minimizes griefing)

**Comment by Bar0nline** [comment]
good idea

**Comment by LocoCZ** [comment]
Sounds like a good idea to me.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
