### ISSUE TITLE
Thermal imager

### ISSUE THREAD

**Issue by PARTOVIY** [SmartlyDressedGames/Unturned-3.x-Community#3497]
Nelson, hi =)
Please add thermal imagers in the form of glasses and sights to the game.

**Comment by GazziFX** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2267030216

**Comment by GazziFX** [comment]
Can be done with `Projector` component and some shaders

**Comment by MoltonMontro** [comment]
Hey PARTOVIY,

Game suggestions (e.g., new items) are out-of-scope for what this GitHub repository is for. Consider using one of our other community platforms instead, such as our [official forums](https://forum.smartlydressedgames.com/).

**Comment by billdeck** [comment]
> Can be done with `Projector` component and some shaders

How? cant see

**Comment by GazziFX** [comment]
> How? cant see

Tried but it looks weird, needs custom shader

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.

**Comment by HETROW** [comment]
Good evening to all of me on a servet portirba technique with thermal imagers maybe someone knows how to do it write to me in Discord there and discuss the price neptyn4.5.2
