### ISSUE TITLE
[Feature Request] Editor lock Objects

### ISSUE THREAD

**Issue by JD550** [SmartlyDressedGames/Unturned-3.x-Community#3500]
seeing as it is really annoying accidentally selecting and possibly moving/changing an objects rotation/translation/scale there should be an anchor button for locking objects in place. This will prevent accidentally messing up things such as road networks by moving them accidentally

**Comment by Vanilla-Mix** [comment]
yesss, this would be soooooo useful, it would honestly be a game changer, pleaseeee NELSON ADD IT!!!!!!!!!!! DO IT NOW!!!!!!!!!!

**Comment by SDGNelson** [comment]
I could definitely see this being useful. Also would like to improve undo/redo at some point.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
