### ISSUE TITLE
[Feature Request] Editor prefab line for objects

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#3503]
Currently, if I want the "Editor" gameobject of my object to be only displayed in the map editor, I have to put these lines in the .dat file:
```
Rubble Destroy
Rubble_Reset 60
Rubble_Health 50
Rubble_Effect 72
Rubble_Editor Dead
```
The object I used this on isn't meant to be destructible, and it doesn't have any the gameobjects required to make it destructible. The game doesn't give me any errors for not including the needed gameobjects, but it seems quite unnecessary to use rubble lines. Perhaps it might be a good idea to have a proper `Has_Editor_Gameobject` line?

**Comment by SDGNelson** [comment]
So you have an Editor-only variant of the object? Out of curiosity what differentiates it?

**Comment by Jdance-Media** [comment]
For me I use the "Editor" gameobject to add a speaker icon so people can easily see and move sound effects.

**Comment by SDGNelson** [comment]
Ah interesting, that is clever.

**Comment by Spebby** [comment]
I would greatly appreciate this as well. I've tried doing this same thing for tumbleweed object "spawners" and sound objects

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
