### ISSUE TITLE
[Feature Request] vehicle / ship / planes / helicopters physics

### ISSUE THREAD

**Issue by fahrettinenes** [SmartlyDressedGames/Unturned-3.x-Community#3508]
Hello Nelson, As far as you know, players are not able to walk inside ships, vehicles, planes, or helicopters while someone is driving them. If you can fix (or add, idk) this, we can make really good mods and plugins with this feature.

**Comment by GazziFX** [comment]
I think it was already on trello, but cant find it

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
