### ISSUE TITLE
[Feature Request] Kill Volumes for Barricades, Structures, Traps, and Weapon Projectiles

### ISSUE THREAD

**Issue by Nuhm** [SmartlyDressedGames/Unturned-3.x-Community#3516]
Currently Kill Volumes allow for Players, Zombies, Animals, and Vehicles. But it would be cool to allow areas to auto destroy certain barricades or other instances. My request for this is mostly because I would like to stop projectiles from entering certain zones.

**Comment by UsernameIsUnavailible** [comment]
Could use a safezone or some model/asset that stops projectilles but can be walked/driven though? I am no modder but this seems do-able

**Comment by DrDallas1** [comment]
You could always use other scripts to force destroy all of those other things.

**Comment by Nuhm** [comment]
You cannot destroy barricades with the pre-provided scripts.

**Comment by DrDallas1** [comment]
You can. Contact me on discord if you want an explanation on how. DrDallas#7087.

**Comment by GazziFX** [comment]
> You cannot destroy barricades with the pre-provided scripts.

Grenade or Rocket

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
