### ISSUE TITLE
Local bundles not loading on client when joining to server

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#3523]
Hello Nelson.
This was done to save PC resources but how can I now test my mods on server without uploading them to workshop?

Can you add option Always_Load_On_Client to MasterBundle.dat or something like this?

**Comment by SDGNelson** [comment]
Interesting question 🤔 
The easiest option right now would probably be to test them as part of a map e.g. your local files in /Maps/MyTestMap/Bundles because it will use the local copy of the map. I will think about this because there needs to be / should be a straightforward way to test non-map assets in multiplayer.

**Comment by Wyvernaed** [comment]
Understood, it was necessary to set "MyTestMap" as map on server(before it was a PEI and mods loading only on server from test map) but it would be better make solution for testing mods on different maps without difficulty.
Thanks for answer :D
