### ISSUE TITLE
Feature Request: Dark Flashbangs setting

### ISSUE THREAD

**Issue by JD550** [SmartlyDressedGames/Unturned-3.x-Community#3527]
Taking a feature from the new battlefield game where theres a setting to make flashbangs flash black instead of white, would help for those who are sensitive to bright/flashing lights.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
