### ISSUE TITLE
Feature Request: Multiplayer Map Editing

### ISSUE THREAD

**Issue by UsernameIsUnavailible** [SmartlyDressedGames/Unturned-3.x-Community#3530]
I'm quite unsure if this has been suggested many, MANY times. But can map makers get some love in the part of making maps with multiple people, Sending over files is such a pain especially due to you can't copy over, But you have to override files. (meaning you can't edit terrain, Roads, Assets at the same time).

**Comment by Spebby** [comment]
been veto'd in the past

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
