### ISSUE TITLE
[Feature Request] Make animals compatible with NPC Condition/Rewards system

### ISSUE THREAD

**Issue by FlodotelitoKifo** [SmartlyDressedGames/Unturned-3.x-Community#3533]
I talked about this with Molton last night, where I mentioned the possibility of animals giving negative rep on death. As he pointed out however, "It'd probably make more sense for us to add support for animals using NPC Rewards (which includes granting rep)—rather than just granting/removing reputation"

Figured doing so would allow for, as an example, boss animals who can grant achievements, reputation and flags to a player, without necessarily needing a quest for it.

also, I'm not sure if this is already possible but maybe a way to 100% guarantee an animal's spawn? like with boss mega zombies in a navmesh, or through spawnpoints.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
