### ISSUE TITLE
[QOL] Single Click Visibility Option for Volumes

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3537]
While it's nice that each volume has an individual visibility checklist, it's quite tedious to disable all of them when not working with volumes. It would be nice to get an ol' reliable toggle like Decals, World Borders, Items and Zombies have. (Also please give Decals a keyboard toggle).
Ideally this and Decals would be higher in the hierarchy since they're likely to be toggled more. Perhaps f4 for volumes and f5 for decals?

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
