### ISSUE TITLE
[Feature Request]Throwable's recyclable options

### ISSUE THREAD

**Issue by prank0079** [SmartlyDressedGames/Unturned-3.x-Community#3553]
Similarly, after a bow and arrow is shot, it can pick up the shot arrow at the hit position. I hope Throwable can also pick up and recycle it at the explosion position.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
