### ISSUE TITLE
Feature Request - Increase magazine ammo capacity instead of capping it to 255

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3557]
I forgot the reason why ammo was capped to said amount, but it would be nice to have the max ammo way higher. I know there's an option to make ammo infinite. But as an example, if people wanted to make jet cannons that have max ammo that exceed the current max ammo amount to like 940 shots, it'll be great to have that in the game.

**Comment by Jdance-Media** [comment]
The ammo was capped to that amount because the numerical type used was a byte. Bytes are capped at 255.

**Comment by GazziFX** [comment]
It maybe possible in future https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/2990#issuecomment-1013532588

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
