### ISSUE TITLE
[Feature Request] Rising & Falling tides

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#3560]
Hello,

this seems like something that would be both easy to implement, and harmless to implement. Simply let map editor designate the level or area for a high tide and a low tide, and let the map transition between the two as the time goes by.

Low tide could reveal new areas or objects, high tides could help you access new areas. Maybe you build something that can only be clearly seen at low tide but is partially hidden underneath the water at high tide. Or you know, screw practical use and just add it because its a fun little idea.

**Comment by Romelete** [comment]
This would be super cool for underwater caves
maybe even adding in a hook for mods to check if it's high tide or low tide would be cool as well

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
