### ISSUE TITLE
[Feature Request] Editor lighting values RGB are not enough, add Saturation

### ISSUE THREAD

**Issue by RainOfPain125** [SmartlyDressedGames/Unturned-3.x-Community#3561]
Hello,

In real life, our eyes have two different recepters. One can measure colors, but requires a lot of light to function. The other simply measures the presence and absence of light, and requires much less light to function. And so at night time, you may have never realized that we don't particularly see things in color, only in black and white.

I would like this in the game, but as it stands the values for map lighting can only be RGB values. Of course having 0,0,0 will give you darkness, and any value will give you a specific color.

My suggestion is to add a fourth value of saturation. That way we can tweak the RGB values of how we want light to "bounce" off certain objects of certain colors so to speak, and then we can desaturate the colors into black and white at midnight.

To me it sounds easy and harmless to implement. Only upsides! :)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
