### ISSUE TITLE
Comments regarding the monetization change

### ISSUE THREAD

**Issue by KodakDolph** [SmartlyDressedGames/Unturned-3.x-Community#3568]
Hello Nelson, I hope this message finds you well.

I'm sure you may have expected a post like this sooner or later, this is focused on the change you made in today's update in hiding unspecified monetization from the server list.  I see to the reasons behind the change. It's probably best to circumvent new players away from crazily modded, 100x servers with loads of plugins that might make no sense to them, leading them to question whether or not they downloaded the same game they saw in the Steam store.  However, myself, and many other server owners, feel a bit of frustration towards this change as I expect it to largely impact my servers playerbase, as new players make up a large fraction of the player counts daily.  This may seem like an overreaction, but **players joining from the server list remain the main source of players for my servers (and I think it's fair to assume many others as well.)**

It's especially frustrating for servers such as mine (Kodak SemiVanilla), which remain close to the base game concept, and have strived to find a balance between fairness for free players and benefits for those who wish to support server costs.  Additionally, this will harm other markets such as ImperialPlugins and UnturnedStore from having customers, as well as fan-favorite modded servers like Unturned Blackout and Warzone.

I understand this post might be rash, given that it is posted just moments after the update's release and we haven't truly seen the change in action, but I have already noticed that my server's counts are especially low right after they were updated.  I hope that you see this perspective and perhaps we can find some sort of cooperative effort that will satisfy both efforts.

**Comment by Vanilla-Mix** [comment]
100% agree with this, without no new players coming in it's gonna kill pretty much any server even if it has a huge playerbase already.

**Comment by Trojaner** [comment]
How about an alternative approach: A P2W filter that defaults to No P2W?

**Comment by GazziFX** [comment]
Guys, I think we need custom version of Unturned with P2W and modding features 😀

**Comment by andkon144** [comment]
i agree with roejanner, theres so many alternative ways to deal with the problem of p2w, hopefully this is reverted back to original

**Comment by SDGNelson** [comment]
If it does seem to be a big issue then I did include a feature to rollback the change without a client update. There could perhaps be some room to revise what is considered "non-gameplay", for example Minecraft's guidelines allows gameplay purchases that do not provide a competitive advantage and do not adversely affect others.

**Comment by JD550** [comment]
I feel like there needs to be a search category for a server which has/doesnt have a donation store so that ppl who are looking for a no donations experience can still do so

**Comment by PARTOVIY** [comment]
If the GSLS token is conditionally blocked for using other people's modifications, then it will not work to connect to the server?

**Comment by KodakDolph** [comment]
> If it does seem to be a big issue then I did include a feature to rollback the change without a client update. There could perhaps be some room to revise what is considered "non-gameplay", for example Minecraft's guidelines allows gameplay purchases that do not provide a competitive advantage and do not adversely affect others.

In my opinion, it might be fair to revert the change and take some time to come up with some other way to achieve these goals. This way server owners have time to prepare for any changes that might happen, be it changing their store items, or adding new non-monetized servers.

![image](https://user-images.githubusercontent.com/105953666/206777637-7862d47c-52db-49f5-9d34-5bae325a6a73.png)
 P9nda suggested perhaps adding a "Non-monetization" category here.

**Comment by JD550** [comment]
> i agree with trojaner, theres so many alternative ways to deal with the problem of p2w, hopefully this is reverted back to original

Yea cuz there can still be donation store to purchase packages but it can still be non p2w so its just puting servers like those out to die off

**Comment by Buldozeris** [comment]
Servers are already abusing and marking their servers as non p2w, while selling kits etc. What will happen to these servers? "non-gameplay" - so only cosmetics, chat tags?

**Comment by GazziFX** [comment]
If Nelson add skins for modded items, that would be a way for non-gameplay monetization

**Comment by JD550** [comment]
> Servers are already abusing and marking their servers as non p2w, while selling kits etc. What will happen to these servers? "non-gameplay" - so only cosmetics, chat tags?

But i mean you can still sell kits/permanent items while also making them obtainable for free 

Or would ppl still consider it p2w?

**Comment by Buldozeris** [comment]
> 

according to your logic, nothing is p2w :D. Do you get advantage when buying kits? yes you do, so it is p2w.

**Comment by JD550** [comment]
> > 
> 
> according to your logic, nothing is p2w :D. Do you get advantage when buying kits? yes you do, so it is p2w.

But what if you have an option to get them for free? That would just make paying for it an option

**Comment by Buldozeris** [comment]
> 

What does it change? Nothing, you buy kit or whatever, you get advantage over others, who will have to waste time or something in order to get same thing. Everything except, cosmetics and things like "chat color" gives you advantage.

**Comment by P9ndx** [comment]
I think a better approach is to make non-monetized servers more visible for new players instead of just hiding 90% of the high-quality servers that have tons of work, effort, and money being invested in. I feel like setting the default filter to "Not-Monetized" would be the better approach as Trojaner mentioned before. There are a crazy amount of Players we have to explain how filters work in the Network every day, simply from those not finding our server through name or IP. I don't want to know how many players there are not ever paying attention to those in the first place. All the big networks that carried Unturned for years are now just being thrown in the shade, which I find not fair at all. Making non-p2w more visible is good, but making p2w basically invisible is not the right approach.

**Comment by ItsRodrigoAl** [comment]
I could say almost all the new players who plays the game and join a server for the first time won't even look to the server filters or even understand it at all

What about the rest of servers which basically keep the game alive including new stuff or different ways of experience the game? Those server need a lot of work and of course, nobody do things like that for free so selling things in a store to support the owners is completely fair, but then this new filter option just kills all those servers? So basically what, everyone will need to play only vanilla servers because everyone will just see those servers? Def that's not the way to make this

**Comment by Buldozeris** [comment]
Thing is game is still alive because of community servers. Would like to see how it goes if this update is not rolled back.

**Comment by Bradler26** [comment]
Honestly I don't understand why this is even being discussed still. The way I see it is things should just be left as is. Players will always find a way to play the server they enjoy the most. All this update has done in my opinion has made a lot of server owners no longer want to invest and create revolutionary servers because they can't even monetize it without being thrown off the internet list.

Also as a side note, from what I understand all of this has stemmed from P9nda's servers being monetized which is pretty much the only way we are ever going to see servers as advanced and impressive as blackout is. Nobody is going to make that for free, thats the reality of it. And in a way P9 and other youtubers are lucky, because they have their platform to promote their servers which most networks don't have. 

I agree with what @P9ndx and @Trojaner have said about making non-monetized the default if that is the only solution but from my perspective I think if changes like this continue there will be a large drop in creative servers and content being made

**Comment by sunnamed434** [comment]
> Guys, I think we need custom version of Unturned with P2W and modding features 😀

Haha, go on

**Comment by GreatHeroJ** [comment]
While historically I've held a personal stance against heavily monetized servers, I have to agree with the others here in that the change to monetized server visibility goes a bit too far. I understand the rationale that went into enacting this change (protecting oblivious players from predatory micro-transactions or P2W), but I also believe the player should be given as much agency in their choice as possible.

Utilizing the filter for non-monetized servers as previously suggested would be an ideal compromise here, since it would both promote the non-monetized servers, while still allowing players who voluntarily choose to view monetized servers to easily find what they are looking for.

**Comment by SDGNelson** [comment]
Definitely open to disabling this change if necessary. Surprised GHJ is pro-disabling - that is a big point in favor of disabling.

When any of us is looking for a game to play on Steam: would you actually even consider a game with P2W elements? I do not feel that any of the games I personally play are P2W. It seems in everyones' best interests to promote non-P2W over P2W.

That being said, there is more of a grey area with servers that are not P2W (e.g. OP Kodak) but do not currently fall into non-gameplay monetization. Does anyone have a proposal of how to distinguish better between P2W vs non-P2W?

**Comment by GreatHeroJ** [comment]
> When any of us is looking for a game to play on Steam: would you actually even consider a game with P2W elements? I do not feel that any of the games I personally play are P2W. It seems in everyones' best interests to promote non-P2W over P2W.

Most of the games I play are also non-P2W so I share this viewpoint - but I feel like there's an incredibly fine balance to be struck here, since some servers labelled as P2W bring a lot of new content to the community. Unturned's identity is strongly shaped by community content, so regardless of what becomes of the changes today, I think a longer-term solution is needed (though this will be difficult to come up with, since the community's interests are so diverse).

Also, are "unspecified" and "monetized" servers differentiated from each other here? It makes a lot more sense to me that the unspecified ones would be hidden, but I've been receiving conflicting reports that specified "monetized" servers are also hidden.

**Comment by P9ndx** [comment]
"P2W" servers have always been played much more than "non P2W" even though these were never invisible or hidden in any way from the server browser simply because people enjoy them more. It should be up to every player what they want to play on and therefore be a free choice. Less compensation and therefore incentive for future server owners means fewer players creating new and innovative servers & therefore it will become more and more repetitive. Larger Networks generally also have better infrastructure and plugins to moderate their servers better, allowing players generally a better time on a server with fewer troublemakers or help with questions or problems possibly new players will face.

**Comment by monoblur44** [comment]
I think the biggest problem here is Nelson point of view.
Even if he rolls back the changes, the question is when will the next attempt take place to kill high-quality and well-moderated servers.
We spend a lot of time each day maintaining and developing our servers, and from time to time Nelson tries to kill our servers in small steps.

There is a p2w shop on our servers for a reason. Lack of other opportunities to earn enough money to maintain the server (including adequate remuneration for the time spent for the entire team).
I host servers as a hobby and some extra income for my main job. Every day after work I spent many hours maintaining the server. If I had to do it for free, I'd rather not do it at all and if I just leave the servers running unattended they will die quickly.

I suggest adding more No-P2W options to the game that server owners could sell to increase their earnings and then start thinking about reducing P2W on servers.

**Comment by negrifelipe** [comment]
I think that all the servers should be shown in the server list without labeling them as p2w or not, the user should have the freedom to choose what he wants to play and all the servers should be shown in the internet list without privileges.

**Comment by SDGNelson** [comment]
> If curated devs can get paid, server hosters have the same right

I agree. I am perfectly fine with server hosts getting paid for their work! The difference is only whether what is getting sold is P2W or not.

> Even if he rolls back the changes, the question is when will the next attempt take place to kill high-quality and well-moderated servers.

I do not want to kill high-quality and well-moderated servers. High-quality and well-moderated servers are great for everyone! I want to discourage P2W though - Unturned is not a P2W game.

> I suggest adding more No-P2W options to the game that server owners could sell to increase their earnings and then start thinking about reducing P2W on servers.

Do you have any suggestions in mind?

> Also, are "unspecified" and "monetized" servers differentiated from each other here?

There is not currently a tag for "monetized" because I doubt many hosts would want to specifically tag their server as "p2w".

**Comment by Buldozeris** [comment]
What about servers that use "non monetized" tag while selling all kinds of stuff on their servers?

**Comment by GazziFX** [comment]
When we will be allowed to join the LAN servers?
![image](https://user-images.githubusercontent.com/43498426/206798438-19fe2618-6162-44d0-83d3-1209583cfeeb.png)

**Comment by KarmaWSYD** [comment]
As someone specifically hosting servers that fall under the "None" category this update has been quite interesting. For one, I saw a relatively significant increase of players, roughly ~1.8-2x as many compared to prior weeks. Hiding servers with pay-to-win aspects certainly did a lot to increase the population of at least my servers and the servers of others I talked with whose servers also fall under this category. 

So, obviously, this update wasn't well received among the people working on servers with paid monetization aspects (at least apart from those who chose to break the rules instead and use the NonGameplay or None tag for fully monetized servers). I do believe there are some valid reasons for that, particularly as it came essentially out of nowhere. Nonetheless, the majority of the servers affected certainly weren't ones one would call high-effort content but rather servers that don't have much reason to exist other than to make cash from kids.

As was mentioned, other monetization methods such as cosmetics or chat colours do exist. These are essentially unheard of as there's simply been no reason for anyone to attempt monetization with just them while far more lucrative alternatives exist. I do believe that some servers may very well sustain themselves with just these (Or potentially some new) options, particularly as costs for most servers, and particularly server networks, really aren't as high as many seem to imply. Obviously, the major exception to this is servers requiring large amounts of custom content and I frankly don't have a solid answer for that. Servers with large player counts might still be profitable enough to justify this but there are no such examples currently (Nor can those exist without these rules being around for a while).

In the end, while these changes may have been extreme, the update certainly has promoted servers that don't have pay-to-win aspects and I don't believe that it'd have happened without them being applied exactly as they were. Some rules could potentially be adjusted to not be quite as harsh as they are but re-enabling monetized servers to be a part of the internet list would absolutely destroy any benefit gained by these changes in the first place.

**Comment by KarmaWSYD** [comment]
> > Also, are "unspecified" and "monetized" servers differentiated from each other here?
> 
> There is not currently a tag for "monetized" because I doubt many hosts would want to specifically tag their server as "p2w".

The lack of a monetized tag has actually caused a decent amount of confusion since it's been added, at least among the people who populate the server hosting section of the community discord, and a tag specifying that it's for monetized servers would certainly lessen that confusion to great extent.

**Comment by GreatHeroJ** [comment]
> There is not currently a tag for "monetized" because I doubt many hosts would want to specifically tag their server as "p2w".
> I am perfectly fine with server hosts getting paid for their work! The difference is only whether what is getting sold is P2W or not.
> Some rules could potentially be adjusted to not be quite as harsh as they are but re-enabling monetized servers to be a part of the internet list would absolutely destroy any benefit gained by these changes in the first place.

Not sure how difficult this would be to implement, but a more drastic idea I've had would be splitting up the monetization filter into a toggle list of four categories, which can be adjusted further as the need arises:

- non-monetized
- monetized (non-gameplay)
- monetized (gameplay)
- unspecified

The player can toggle on or off multiple of these categories at once or "show all", with default values hiding the unspecified servers. By hiding unspecified servers you would encourage compliance and players still have total control over what they want to see, while still providing protection for players who don't want to stumble across a P2W server.

A more detailed warning can be provided to the player when joining a monetized (gameplay) server. I don't remember but I could have sworn Nelson added something along the lines of that last part sometime in the past.

**Comment by PandosGallan** [comment]
> > There is not currently a tag for "monetized" because I doubt many hosts would want to specifically tag their server as "p2w".
> 
> > I am perfectly fine with server hosts getting paid for their work! The difference is only whether what is getting sold is P2W or not.
> 
> > Some rules could potentially be adjusted to not be quite as harsh as they are but re-enabling monetized servers to be a part of the internet list would absolutely destroy any benefit gained by these changes in the first place.
> 
> Not sure how difficult this would be to implement, but a more drastic idea I've had would be splitting up the monetization filter into a toggle list of four categories, which can be adjusted further as the need arises:
> 
> * non-monetized
> * monetized (non-gameplay)
> * monetized (gameplay)
> * unspecified
> 
> The player can toggle on or off multiple of these categories at once or "show all", with default values hiding the unspecified servers. By hiding unspecified servers you would encourage compliance, and players still have total control over what they want to see which provides protection for players who don't want to stumble across a P2W server.
> 
> A more detailed warning can be provided to the player when joining a monetized (gameplay) server. I don't remember but I could have sworn Nelson added something along the lines of that last part sometime in the past.

In my opinion, this is a very good idea.

**Comment by P9ndx** [comment]
Might as well disable every server that lets players have a free choice of in-game skin color then since greenskins are also P2W. Same with not showing any servers that allow multiple characters. I'm not trying to relativize P2W but my point is, everything can be seen as P2W if you really break it down but it doesn't mean that it ruins the server/game. Greenskins have been annoying always yes, but players don't play on said servers because of that. If you don't sell some sort of advantage in 99% of the cases you don't sell anything. 99% of the players spending money, in general, would not spend money on a chat color - and creating gun skins for a server or other custom cosmetic content also costs money which they wouldn't make back

**Comment by SDGNelson** [comment]
@GazziFX what is your LAN server's IP?

**Comment by KarmaWSYD** [comment]
> The player can toggle on or off multiple of these categories at once or "show all", with default values hiding the unspecified servers. By hiding unspecified servers you would encourage compliance and players still have total control over what they want to see, while still providing protection for players who don't want to stumble across a P2W server.
> 
> A more detailed warning can be provided to the player when joining a monetized (gameplay) server. I don't remember but I could have sworn Nelson added something along the lines of that last part sometime in the past.

While this would certainly promote compliance among certain hosts most players will simply choose to ignore any monetization filter and/or warning and enable all servers to be visible, which will, in effect, result in the changes of this update becoming non-existent. The key issue seems to be promoting non-pay-to-win servers, not player agency. Hence I don't believe the key to solving it is in promoting player agency.

**Comment by rube200** [comment]
> @GazziFX what is your LAN server's IP?

https://en.m.wikipedia.org/wiki/Private_network
Should be the allowed ips

**Comment by GazziFX** [comment]
@SDGNelson Steam browser shows it as 26.156.242.148:27015, but i can also connect via 127.0.0.1

**Comment by Buldozeris** [comment]
> Might as well disable every server that lets players have a free choice of in-game skin color then since greenskins are also P2W. Same with not showing any servers that allow multiple characters. I'm not trying to relativize P2W but my point is, everything can be seen as P2W if you really break it down but it doesn't mean that it ruins the server/game. Greenskins have been annoying always yes, but players don't play on said servers because of that. If you don't sell some sort of advantage in 99% of the cases you don't sell anything. 99% of the players spending money, in general, would not spend money on a chat color - and creating gun skins for a server or other custom cosmetic content also costs money which they wouldn't make back

Agree, depends on perspective. You can say that everything besides chat color is p2w. So there shouldnt be "grey" area in this topic. Thing is, everyone will talk from their own perspective, which is understandable.

**Comment by GreatHeroJ** [comment]
> my point is, everything can be seen as P2W if you really break it down but it doesn't mean that it ruins the server/game.

I've been careful to avoid the use of the term "P2W" regarding the filter since it's highly subjective at times.

Through the filter being defined specifically by monetization type rather than P2W interpretation as I mentioned above, it allows server owners to be honest about how they monetize their servers while not being penalized or branded "P2W", and players also fully know what they're getting into.

The warning could really be something as simple as "This server has monetized features purchaseable with real currency that can affect gameplay".

> The key issue seems to be promoting non-pay-to-win servers, not player agency. Hence I don't believe the key to solving it is in promoting player agency.

As mentioned before, if someone wants to play on a server they will find a way, agency or not. Might as well make it equally accessible to those who want it, while informing them properly. At least through the filter system, nservers without gameplay monetization are still the most promoted.

**Comment by ItsRodrigoAl** [comment]
> 

1. Adding the 'monetized' and 'any monetization' options. When a new player plays multiplayer for the first time, it should use as default filter 'any monetization', so it will make sure all servers owners should specify what do their servers offers and also their servers will appear for new players. If the server owner leave it as 'unspecified' on the config, then it shouldn't be shown on server list. Therebefore, players may decide if they want to only see 'Not monetized, Non-gameplay monetized, Monetized or Any monetization' servers. Now 'unspecified' should be deleted maybe (?)
2. Maybe adding an alert under the Details server, just like the alert when a server a server is breaking the rules, or when it doesn't have the GSLT token, explaining the server monetization the server has, just to give a clear and "last warning" to the players before joining a server
![image](https://user-images.githubusercontent.com/57012631/206799767-5204516d-b3e5-41a7-b171-7188522acd08.png)

**Comment by KodakDolph** [comment]
> > 
> 
> 1. Adding the 'monetized' and 'any monetization' options. When a new player plays multiplayer for the first time, it should use as default filter 'any monetization', so it will make sure all servers owners should specify what do their servers offers and also their servers will appear for new players. If the server owner leave it as 'unspecified' on the config, then it shouldn't be shown on server list. Therebefore, players may decide if they want to only see 'Not monetized, Non-gameplay monetized, Monetized or Any monetization' servers. Now 'unspecified' should be deleted maybe (?)
> 2. Maybe adding an alert under the Details server, just like the alert when a server a server is breaking the rules, or when it doesn't have the GSLT token, explaining the server monetization the server has, just to give a clear and "last warning" to the players before joining a server
>    ![image](https://user-images.githubusercontent.com/57012631/206799767-5204516d-b3e5-41a7-b171-7188522acd08.png)

I agree with this suggestion.

**Comment by SDGNelson** [comment]
The subnets the game considers as LAN address are:
127.0.0.0/8
10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
169.254.0.0/16

**Comment by SDGNelson** [comment]
The server list change has been rolled back. Even Molt messaged me that it was an overstep.

Some of the things I will review:
- Adding a designation for servers that are monetized rather than Unspecified
- Expanding on the monetization disclosure shown on the server lobby screen as discussed here
- Improving the documentation for requirements to get server listed
- Adding better messaging for that documentation during server startup, specifically *after* all loading is finished rather than when the related feature is initialized
- Clarify warnings about misleading discounts

I was happy to hear @KarmaWSYD your server got more players! Sorry that there is more delay in better promoting non-monetized servers.

**Comment by KodakDolph** [comment]
Thank you Nelson for hearing us out on this, hopefully, we can reach a crossroads to satisfy everyone's goals.

**Comment by P9ndx** [comment]
I am glad you are taking the time to rethink your decision and refine the whole idea a bit more. Something that could be thought about is differentiating between "Pay2Progress" and "Pay2Win" in certain scenarios. It could help incentivize "P2W" servers to make it fairer for the players, a fair compromise I think.

**Comment by KarmaWSYD** [comment]
> Adding the 'monetized' and 'any monetization' options. When a new player plays multiplayer for the first time, it should use as default filter 'any monetization', so 

I'd like to highlight that Any Monetization has been a filter (Maybe even the default one?) ever since the filters were initially added and it clearly hasn't done much so far.

> I was happy to hear @KarmaWSYD your server got more players! Sorry that there is more delay in better promoting non-monetized servers.

Thanks, although to clarify this has been a considerable jump in players on 10 of the 17 unturned servers I currently host and a jump in players on all 17. Additionally the other servers in my sample total ~20 for a total of 35+ servers. Unless this was an anomaly specifically caused by server owners not having adjusted to the changes I'd imagine we'd more likely than not see this as a trend for the future if these changes are kept. Of course, until there's more data (and thus, statistics), nothing can be said for certain.

I'd like to also point out that some parts of the hosting guidelines could use some updating: for example, the currency pack limits aren't specified in the documentation so many don't know about the limit at all.

**Comment by Jdance-Media** [comment]
Many server owners who stick with the base game concept have a hard time making money without selling stuff that provides the players with a slight advantage. Perhaps it would be wise to open an issue on here or a post on the forum that helps to brainstorm ideas for making game features that help support server owners?

**Comment by MoltonMontro** [comment]
> Many server owners who stick with the base game concept have a hard time making money without selling stuff that provides the players with a slight advantage. Perhaps it would be wise to open an issue on here or a post on the forum that helps to brainstorm ideas for making game features that help support server owners?

Discussion/feedback regarding this has been crossposted to the Forum here: https://forum.smartlydressedgames.com/t/feedback-on-hiding-p2w-servers/21753/

**Comment by DanielWillett** [comment]
#3276 could be an idea

**Comment by M10327** [comment]
At the very least it would be much appreciated if we could be let know about these changes a week or so in advance.

**Comment by Ankumo** [comment]
> Guys, I think we need custom version of Unturned with P2W and modding features 😀

Totally agreed. The ability to gather new players by being listed is the only thing that was stopping us from considering making our own custom Unturned client and launcher

As our RP project lived for 5 years, we have a definite confidence that there's tons of players who will be much more likely to play with an ability to buy some "time-consuming to obtain" things than without it (i.e. luxury vehicle). I mean, they WILL NOT play on our server if this option will be disabled

<details>
<summary>off-topic, kinda</summary>
We have a lot of giveaways of store coins and in-game events where you can also win it, so even new players can buy things from there. This is also helping us to make those in-game events interesting which really boosts players interaction with each-other resulting in gameplay fun. And much more other things involving monetization and good things about it. So imo: forget it, don't be a killjoy. We've already removed a feature to hijack vehicles and it killed one of the funniest content for Police fraction. There's just A LOT of servers with too much variety of how it's being played and monetized
</details>

New players are basically don't give a sh*t about server list filters. Especially when they're looking like I'm gonna land a plane or hack a Pentagon using them

> If Nelson add skins for modded items, that would be a way for non-gameplay monetization

Then what? I'll need to buy skins on all servers I play? :D Hold my beer

**Comment by Ankumo** [comment]
> Guys, I think we need custom version of Unturned with P2W and modding features 😀

Totally agreed. The ability to gather new players by being listed is the only thing that was stopping us from considering making our own custom Unturned client and launcher

As our RP project lived for 5 years, we have a definite confidence that there's tons of players who will be much more likely to play with an ability to buy some "time-consuming to obtain" things than without it (i.e. luxury vehicle). I mean, they WILL NOT play on our server if this option will be disabled

<details>
<summary>off-topic, kinda</summary>
We have a lot of giveaways of store coins and in-game events where you can also win it, so even new players can buy things from there. This is also helping us to make those in-game events interesting which really boosts players interaction with each-other resulting in gameplay fun. And much more other things involving monetization and good things about it. So imo: forget it, don't be a killjoy. We've already removed a feature to hijack vehicles and it killed one of the funniest content for Police fraction. There's just A LOT of servers with too much variety of how it's being played and monetized
</details>

New players are basically don't give a damn thing about server list filters. Especially when they're looking like I'm gonna land a plane or hack something using them

**Comment by Ankumo** [comment]
Uhm. What?
![image](https://user-images.githubusercontent.com/19735171/206824684-29549d6d-0433-4ee1-a651-66198a83b53d.png)

**Comment by DanielWillett** [comment]
Going to copy this from the forum because I feel like more people are discussing here

I think a good way to help discourage ‘p2w’ is to give more ways for server owners to make money. This has also been brought up here, but there just aren’t that many good options for making money from hosting servers that aren’t classified as p2w. Allowing workshop skins via plugins could possibly open up some options (selling skins, a battle pass type system, etc). Realistically not many people will put 1k+ hours into making a server (or pay people to) for little to no return.

Another thought I had (although it would take quite a bit of effort to implement) is a kind of server reputation system linked to the GSLT key, so players could decide whether a server’s paid content was ‘p2w’. Servers with low reputations would be harder to find on the list or would show up under a separate monetization category. You would probably want to make sure servers can’t see who has voted so they can’t ‘buy’ people’s votes.

I personally dislike most extremely pay-to-win servers, but after co-creating and owning a server for a while and seeing how much time and effort goes into creating and running one, taking any server that tries to make a little return on investment seems a bit harsh. As mentioned on GitHub some kind of warning when joining like Minecraft now has when you join a non-realms server could be a better option until there are more ways to make money without being considered ‘monetized’.

**Comment by GazziFX** [comment]
> Then what? I'll need to buy skins on all servers I play? :D Hold my beer

This is just example of replacement P2W kits and ranks. You can unlock skins progressively for played time or unlock all permanently

**Comment by SmallBerry** [comment]
(copy of a post from blog post)
Hi,
First of all thank you for listening to the community and rolling back the update regarding monetization. I think we all (server owners) agree that that would a destructive change.

I personally do not seem to understand why people consider “p2w” as a problem. There are more players playing the game then ever before. And there is hundreds of server options to chose from. If a server which monetizes the game is popular enough to be on the top of the server list, why to punish it for that. If players enjoy the server then I do not understand why would such server be punished in any way, by restricting its reach in any way or form.
Thanks to the ease of opening server there is plentiful of option for everyone to chose from. One can find server that do sell perks, and also ones that do not. I am a believer of giving players a choice, to decide what to play instead of hiding some option from them.
If standard vanilla server doesn’t get enough attention, it is for a reason. Maybe the “standard” way to play Unturned is not amusing enough for most players.

Removing or restricting server that sell perks and ranks in my opinion is counter productive, as it will result in inability to fund servers, mods, plugins etc for most of the servers and thus an overall decrease of server count.
I think that the current state in which thee are many servers, and large competition created environment of healthy competition. Each network strives to be better in some way than another, to attract players in unique way and constantly grow and develop to bring players in. This healthy competition is what made Unturned what it is today. Without it, most of the plugin would never be created, as so do mods or custom game mods like Unturnov or most recent example being Blackout.
I think that exactly that healthy competition is what allows game to grow and expand beyond the initial boundaries. And changing it will damage the game and community.

I think that healthier approach to the “p2w problem”, which I personally do not see to be a problem. Is more of a topic of transparency. If that’s something that is important to players and community, servers that sell perks could have a $ sign added somewhere in the server list, so that players joining will be aware that server does monetize the game.

I believe educating players in what is available and transparency is more productive than blocking/ restricting.

**Comment by Bradler26** [comment]
Totally agree with with what SmallBerry has said here. 

To add to 
> If standard vanilla server doesn’t get enough attention, it is for a reason. Maybe the “standard” way to play Unturned is not amusing enough for most players.

I believe content updates with new items/vehicles/maps would likely push players into vanilla servers. This can clearly be seen when curated maps are released and hundreds of players flock onto pure vanilla servers just to try out the new maps and items. I think the reason people play heavily modded (and servers with monetization are often the more heavily modified ones) servers currently is because those servers have new modded items, new plugins and new stuff in general. 

I even have a PvP server which has pretty basic plugins, no mods and no ranks for sale and the times there have been the most players is when there has been a large change in unturned or new content added. As I see it the more "pure" servers are never going to be as popular as modified and monetized servers unless unturned has content added consistently that will draw people into those servers to play around with it
