### ISSUE TITLE
Config.json question

### ISSUE THREAD

**Issue by chenyicheng311** [SmartlyDressedGames/Unturned-3.x-Community#3571]
@SDGNelson 
Excuse me, what is their explanation, or perhaps their meaning?
pls tell me！
very thanks！
    "Rate_Limit_Kick_Threshold": 10,
    "Fake_Lag_Threshold_Seconds": 3.0,
    "Fake_Lag_Log_Warnings": false,
    "Fake_Lag_Damage_Penalty_Multiplier": 0.1,

      "Melee_Repair_Multiplier": 1.0,

      "Melee_Repair_Multiplier": 1.0

**Comment by GazziFX** [comment]
Rate limit iirc is how many packets client can send before it gets kicked

**Comment by SDGNelson** [comment]
Copying some of the code comments:
```
/// <summary>
/// If a rate-limited method is called this many times within cooldown window the client will be kicked.
/// For example a value of 1 means the client will be kicked the first time they call the method off-cooldown. (not recommended)
/// </summary>
public int Rate_Limit_Kick_Threshold;

/// <summary>
/// Ordinarily the server should be receiving multiple input packets per second from a client. If more than this
/// amount of time passes between input packets we flag the client as potentially using a lag switch, and modify
/// their stats (e.g. reduce player damage) for a corresponding duration.
/// Minimum value is PlayerInput.MIN_FAKE_LAG_THRESHOLD_SECONDS.
/// </summary>
public float Fake_Lag_Threshold_Seconds;

/// <summary>
/// Whether fake lag detection should log to command output. False positives are relatively likely when client
/// framerate hitches (e.g. loading dense region), so this is best used for tuning threshold rather than bans.
/// </summary>
public bool Fake_Lag_Log_Warnings;

/// <summary>
/// PvP damage multiplier while under fake lag penalty.
/// </summary>
public float Fake_Lag_Damage_Penalty_Multiplier;
```
Melee_Repair_Multiplier is the multiplier for blowtorches repairing items/vehicles.

**Comment by sunnamed434** [comment]
> Copying some of the code comments:
> 
> ```
> /// <summary>
> /// If a rate-limited method is called this many times within cooldown window the client will be kicked.
> /// For example a value of 1 means the client will be kicked the first time they call the method off-cooldown. (not recommended)
> /// </summary>
> public int Rate_Limit_Kick_Threshold;
> 
> /// <summary>
> /// Ordinarily the server should be receiving multiple input packets per second from a client. If more than this
> /// amount of time passes between input packets we flag the client as potentially using a lag switch, and modify
> /// their stats (e.g. reduce player damage) for a corresponding duration.
> /// Minimum value is PlayerInput.MIN_FAKE_LAG_THRESHOLD_SECONDS.
> /// </summary>
> public float Fake_Lag_Threshold_Seconds;
> 
> /// <summary>
> /// Whether fake lag detection should log to command output. False positives are relatively likely when client
> /// framerate hitches (e.g. loading dense region), so this is best used for tuning threshold rather than bans.
> /// </summary>
> public bool Fake_Lag_Log_Warnings;
> 
> /// <summary>
> /// PvP damage multiplier while under fake lag penalty.
> /// </summary>
> public float Fake_Lag_Damage_Penalty_Multiplier;
> ```
> 
> Melee_Repair_Multiplier is the multiplier for blowtorches repairing items/vehicles.

As I understand these summaries in your IDE, what do you think about installing these .XML files in Unturned?

**Comment by SDGNelson** [comment]
@sunnamed434 Ideally yes, but I would need to review there is no sensitive info in those comments, and last time I checked there was no easy automatable way to export them. Are you aware of one?

**Comment by sunnamed434** [comment]
> 

## My one recommendation 
and not advice is not to care about writing these summaries professionally and well just simply and readable because summaries have huge rules on how to write them properly, etc. Because Unturned is waiting for big changes and these summaries are not infinite and probably will be removed in the future (because code will be updated a lot). The goal is just to give small code documentation and this is enough. The main goal is to make these summaries not take more time than the development of Unturned - if this happens this is very bad. Btw existing summaries in your IDE are enough at the moment.

## Automating export of .XML docs
Uhm... I never had experience with publishing games on steam, but, so this doesn't matter probably, you can try to do the same as I do in the screenshot, visually it can look differently and locate in other places, in the screenshot I'm using .NET 6.0 with a changed project to .NET Framework 472, and so that gives me many helpful things i.e new IDE design and more control.

Just put there your path to production after that deploy it as you do it by default.
Create a new file somewhere, for example, let's say Magic.xml then put the path to your file, and done!
![image](https://user-images.githubusercontent.com/65300126/206937655-c0c2e1ea-72e1-4055-8833-d5325cba740a.png)

**Comment by SDGNelson** [comment]
Unfortunately that is not an option AFAIK because the Unity solution/project files are auto generated.
