### ISSUE TITLE
[Feature Request] Gun QOL Requests

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3574]
Some requests to make guns more detailed/more fun to play with.

- Sounds when trying to shoot an empty gun
- Animations when trying to shoot an empty gun (Gun Event hook or animation)
- Colored weapon lasers (Could use headshot hitmarker color?)
- Last Shot Fired event for Gun Event Hook 
- Separate animation clip for reloading an empty gun (**Reload_Empty**, Fallback to Reload animation)
- Toggle for only playing hammer after shooting a bolt action rifle (**Shoot_Only_Hammer** bool, default to false) and not when reloading an empty gun (so does not conflict with the empty reload animation clip)

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
