### ISSUE TITLE
[Feature Request] Weights for Individual clothing items on Zombies

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#3581]
Been adding some rare clothing items for zombies only. Unfortunately I've realised that I cannot adjust the weight of specific clothing items. So these silly clothing items appear far more frequently than intended. 
![image](https://user-images.githubusercontent.com/47935791/207121261-2137fa61-480b-43d3-ac60-70ba0b4c6448.png)
The above clothing item is only supposed to appear 2% of the time, otherwise it's supposed to be a regular farmer's hat. currently I've opted for creating "zany" zombie types and placing them sparingly, but it's a pretty hacky solution.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
