### ISSUE TITLE
 Unturned support proxy-protocol?

### ISSUE THREAD

**Issue by lootoos** [SmartlyDressedGames/Unturned-3.x-Community#3583]
this thing is needed to support haproxy
https://rustrepo.com/repo/b23r0-udppp

**Comment by GazziFX** [comment]
> this thing is needed to support haproxy https://rustrepo.com/repo/b23r0-udppp

Why you need this? Whats wrong with Steam Datagram Relay?

**Comment by lootoos** [comment]
need to be able to log in to the server via haproxy with the proxy-protocol function,to do this, the game must support proxy-protocol

**Comment by lootoos** [comment]
I use vpn wireguard, I installed wg server in vds, wg client in home pc, on the wg server I forwarded the port to 10.228.228.2 which is located on the home pc, the game server is hosted on this ip, if you add proxy-protocol support then I will be able to get the correct IP of players on the server instead of 10.228.228.1 for all gamse players server

**Comment by lootoos** [comment]
Proxy Protocol to send user’s real IP to local services.

**Comment by GazziFX** [comment]
Shouldn't you get real IP by default?

**Comment by GazziFX** [comment]
You just forwarded ports trough VPN, but your clients isnt connected to VPN, they use VDS IP

**Comment by lootoos** [comment]
yes

**Comment by educatalan02** [comment]
It seems like un-useful features🤣

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
