### ISSUE TITLE
[Feature Request] Electricity Volumes / Weather effect that provides electricity

### ISSUE THREAD

**Issue by Romelete** [SmartlyDressedGames/Unturned-3.x-Community#3588]
Volumes that power any objects/barricades that require power within them.  Would be useful for maps that are set during the apocalypse or RP maps.  Could also have an option to set it so that when a generator is powered within the volume, the whole volume has power, which would be useful for things like powering a whole building with one generator.  
Another suggestion is storms that provide power to the map i.e. Aurora in The Long Dark.

**Comment by GazziFX** [comment]
I hope Nelson will rewrite electricity system a lot

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
