### ISSUE TITLE
[Feature Request] Biome Volumes

### ISSUE THREAD

**Issue by Romelete** [SmartlyDressedGames/Unturned-3.x-Community#3592]
At the moment, if you want to have different ambience in a volume, you can only have one sound effect constantly playing.  A Biome Volume would allow you to make many changes to different ambient effects; for example a plains biome should have a different sound to the middle of the woods.  With a Biome Volume, you would be able to override all of the ambience that's stored in the map to use different clips.  This would allow for night time in different biomes to have more unique sounds and mesh better with the rest of the map.  For example, a forest at night could have the sound of trees swaying or creaking, while a swamp biome would have bullfrogs and other spooky noises. Maybe even an option for full moon for even spookier sounds.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
