### ISSUE TITLE
[Feature Request] Food Spoil

### ISSUE THREAD

**Issue by sLmpgn** [SmartlyDressedGames/Unturned-3.x-Community#3596]
simple modding capability to make food spoil after so and so ticks. or maybe a server config option? 

please :(?

**Comment by Spebby** [comment]
maybe instead it would happen at low percentages of food? Food would turn into a "spoiled" item that was defined in the item's .dat 

I could see a few uses like potions, wine or cheese that age.

**Comment by sLmpgn** [comment]
Expanding on what Spebby said, this could be useful for non food items as well. ex. you have little bits of diamond in your pocket for long enough you get lint in them :), or you don't repair your armor and it starts to get rusty, etc. 

very useful, doesn't have to be applied to the entire game (that could be a bit of a community twister idk) just a modding capability outside of plugins.

**Comment by sLmpgn** [comment]
> maybe instead it would happen at low percentages of food? Food would turn into a "spoiled" item that was defined in the item's .dat
> 
> I could see a few uses like potions, wine or cheese that age.

I like your idea of items turning into something else after awhile, I think it needs the decay system to function properly though. food storage is the big thing for me personally, but there is a lot of utility in something like this.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
