### ISSUE TITLE
[Feature Request] EffectUIManager

### ISSUE THREAD

**Issue by FANYPLAYRU** [SmartlyDressedGames/Unturned-3.x-Community#3599]
It would be nice if it had those capabilities:
1. Give the object not only on and off, but also set the color of the image
2. Ability to set the photo not only by URL link, but also RAW photo

**Comment by GazziFX** [comment]
2. Not good for game netcode to send large images, it doesn`t support streaming large files, and lack of cache reduce performance. Thats why spy has so poor quality

**Comment by FANYPLAYRU** [comment]
What if you make a method in the game with which RocketMod can send item GUID, and the game will display the icon from the loaded assets

**Comment by FANYPLAYRU** [comment]
3. send Animator.Play (string) animation request to the object.

**Comment by GazziFX** [comment]
> What if you make a method in the game with which RocketMod can send item GUID, and the game will display the icon from the loaded assets

yeah, that is nice, but Nelson wont do that, you can find answer here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3010

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
