### ISSUE TITLE
[Feature Request] Devkit XYZ/Scale for volumes

### ISSUE THREAD

**Issue by DMJaxun** [SmartlyDressedGames/Unturned-3.x-Community#3600]
With the merger of devkit and normal editor, we lost the ability to set the position and scale of volumes manually with precise numbers.
It'd be nice to have it added into the normal editor again.

**Comment by Spebby** [comment]
agreed

**Comment by SDGNelson** [comment]
At some point I do intend to return "inspector" style functionality to the editor.

Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
