### ISSUE TITLE
[Feature Request] Disable player storing specific item in any storage system

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#3601]
**Hello**
Sorry if this option already exsist but i couldn't find it, if it doesn't exist then.
I would like to see a option for any item in the .dat file to disable storing this specific item

For example i have a magical fireball attack and i dont want it be stored in any storage system, So it can't be gifted or intentionally giving to another player through storing, I hope you understand my issue here.
This options could be a flag or a bool

**Can_Be_Stored** _bool_
**Disable_Storing** _flag_

thanks for acknowledging the issue.

**Comment by QERT2002** [comment]
You can do it by plugin, just check if player try to store your item block this action.

**Comment by BREEZEXPVP** [comment]
@QERT2002 
I understand that you can create a plugin to check the action but what if i'm not a programmer or have any understanding of c#.
Can sir @SDGNelson just add a flag to make it even more easier to modders instead of using external options like plugins.

Just close this issue if it's too much code for this request.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
