### ISSUE TITLE
[Feature Request] Crops have a second drop variable and Farming skill drop can be disabled

### ISSUE THREAD

**Issue by ComradePixel** [SmartlyDressedGames/Unturned-3.x-Community#3616]
Content creators are using the crop system to create other types of "processing" or "aging" elements, such as wine fermentation or leather drying. The Farming skill seems to ruin the process in a way that when there are multiple steps towards the final product it will be multiplied by 2 each time you place the "crop". I would like to ask for a bool for crops that disables the Farming skill multiplying the produce.

Secondly, would it be possible to add a second variable for the drop? In a similar manner as "Range2" and "Explosion2", it could simply be "Grow2". 
This would help when you for example have a separate item for the process and you want the crop to drop the produce and the empty version of that item.

This would open up new possibilities for a lot of new ideas for all types of servers in Unturned.

**Comment by iBowie** [comment]
or, you could expand it by adding ``Grow_Rewards`` instead, future-proofing this

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
