### ISSUE TITLE
[Feature request(s)] A collection of small UI/modding related requests over time

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#3636]
@SDGNelson I understand you're hesitant to work on UI stuff pending the UI rework, and I'm not trying to sound rude, but do you have an ETA for the rework? I feel like adding some of these features wouldn't really take that long and would expand modding so much in the meantime...

+ Sending Item icons to UI Images (with state, skin, etc) #3010
+ Playing animations by name for UIs, barricades, structures, vehicles, maybe even Useables (#3599, #3625)
+ Setting UI element color and transform (pos, rot, scale)
+ Clearing 3d effects by some kind of instance id or key.
+ Skins for workshop items #3276
+ if moving UI effects gets added, clearing them by key as well, as lists will be doable by sending more than one of the same one.
+ ModHooks for different types #3421 (see GazziFX's comment)
+ Setting images from Bundles (perhaps a new asset type to set as an image source, or just being able to send a path to an image component) so we don't have to rely on sites like imgur.
+ Branch ModHook (Give it a gameObject reference, when you call its method it will call one event if the gameobject is active, another if it's not), would act as 1 bit of memory for animations, etc.
+ Support for more UI components, Toggle, Dropdowns, and Sliders.
+ Method to destroy one item so we don't have to reflect ItemManager.SendDestroyItem

(this would actually take a while but could be something to think about in the future for modders)
+ Getting a library for running an interpreted language like python, js, lua, etc and allowing client-side scripting, you can limit what APIs and functions the scripts have access to and the only malicious code you'd have to worry about would just be crashing the game which really isn't a big deal.

**Comment by Akulation** [comment]
i agree

**Comment by blazethrower320** [comment]
I would personally love seeing alot of these features added to the Game. It would really extend the possibilities that can be done with a Plugin and a UI. I love all the features, however the main ones I would truely love to see would be, Sending Item Icons to UI Images, Sending a Animation and Support for more UI Components. Exepecally a Slider. Using a Slider can be used for multiple things. One thing in particular is a Hud. Instead of having 100 images and or, Block of Text, You can just set the Slider Value.

Please look into these suggestions, It would really mean alot.

**Comment by negrifelipe** [comment]
I would like to have a way to extend the game ui instead of having to create an ui using unity

**Comment by fahrettinenes** [comment]
I hope he wont ignore lol, but I agree

**Comment by flash1o** [comment]
**Please**, we need it.

**Comment by Jdance-Media** [comment]
I too personally think many of these changes are needed. Mainly the image slider change, as I feel as if having hundred different images is unoptimized and frustrating for many.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
