### ISSUE TITLE
Splash damage on buildings is broken

### ISSUE THREAD

**Issue by sigataros** [SmartlyDressedGames/Unturned-3.x-Community#3672]
Splash damage goes through most triangle honeycomb, making base building really difficult
![base examples](https://user-images.githubusercontent.com/96797819/215342960-673870b6-cf8a-4923-9eab-4d693489da39.jpg)
exploding at the pillar at the 2 examples on the right splashes the walls in the square floor so the splash damage goes through the walls
but the example on the far left, exploding at the middle corner does not splash to the other 2 walls on the other side

it's because you don't need a pillar to make it work, the walls themselves perfectly block the splash damage because they are at an 90* angle, the problem could be that pillars don't stop splash damage at all, so if it gets fixed the game would be much more enjoyable to play, 80% of players don't know about this issue and wonder why they get raided so easily

**Comment by SDGNelson** [comment]
Sorry, I'm not sure I understand your example image because the description references a few situations.

To clarify a few points about splash damage:

- Explosions only do a line of sight test if the hit point is more than 0.5m away.

- Explosions deal damage based on the nearest point on the overlapping object, so even if the pillar/wall blocks line of sight there might be a closer position on the other item near the center of the explosion.

- Rocket launchers also have an option `Projectile_Penetrate_Buildables` which causes explosive damage to ignore base walls.

**Comment by sigataros** [comment]
I used demolition charges on the corner of the 2 walls or on the pillar and i'm no expert on the coding or mechanics behind this but i just want to have walls or pillars stop explosion damage from going any further so it only splashes the surface of the base that you are raiding, and there has to be an issue since objects behind a wall getting exploded stay fine but on the triangle examples it goes through

**Comment by SDGNelson** [comment]
I'm still not 100% sure I understand. I thought you were suggesting there is a gap between walls at triangle corners, but it seems like if anything it would be the opposite because walls at square corners don't have any overlap. (remnant from when collision checks were used for pillar placement unfortunately)

Could you share an example screenshot of a case where damage is going through a wall that you don't think it should go through please?

![image](https://user-images.githubusercontent.com/12567645/215924106-b7aef145-42cf-4145-ace7-175c46fb1b2c.png)

**Comment by sigataros** [comment]
Here's a quick video I made with 2 examples where i think splash damage wrongly went through the wall, the walls i hit are the ones i think it shouldn't have splashed

https://www.youtube.com/watch?v=5bDLar8qc_g

**Comment by SDGNelson** [comment]
Thanks for the example video! My apologies for all the hassle with this post.

In my opinion it makes sense those walls get damaged. i.e., I think this is more a subjective balance issue than a bug. I am open to changing balance based on feedback though. My suggestion would be to make a post on the forum with your video, starting a discussion about the splash damage: https://forum.smartlydressedgames.com/

If you decide to do this I will be curious to see the thoughts - there is a lot of back and forth about base raiding balance.
