### ISSUE TITLE
High CPU Usage Fix at Game Loading Phases

### ISSUE THREAD

**Issue by aerodak2** [SmartlyDressedGames/Unturned-3.x-Community#3825]
CPU Usage increases as there is no FPS restriction while the game is loading. And for this reason, it can take an average of 15-20 minutes to open the game for many players using **old CPUs**. _V-SYNC_ can be kept active or _FPS limit_ can be applied only during the loading phases of the game. I noticed that the loading speed increased when the Game FPS Value was set at 60 FPS while the game in loading phase.
This issue usually occurs when the game is launched because the FPS settings are not applied when the game is Loading Phase
 ( _first loading screen when game is launched_ )

**Comment by SDGNelson** [comment]
You're right that it looks like when framerate limit and vsync is applied was changed so that they aren't being applied immediately during startup, so that should probably be changed.

That being said, high FPS during the non-asset-bundle-loading period of loading screen shouldn't be an issue because the game loads a certain number of assets per frame. During asset bundle loading (e.g. "mounting asset bundle x...") high FPS would be a problem though.

P.S. to readers: aerodak2 is a cheat developer. 😞

**Comment by sunnamed434** [comment]
> P.S. to readers: aerodak2 is a cheat developer. 😞

What's the actual matter that aerodak2's a cheat dev? Does it change smth?

**Comment by ItsRodrigoAl** [comment]
> > P.S. to readers: aerodak2 is a cheat developer. 😞
> 
> What's the actual matter that aerodak2's a cheat dev? Does it change smth? On the other hand, if aerodak2's a cheat dev, this guy suggests you improve the game experience I think it's forgivable and not so important in this case

he just said it in a joke way I guess. still, is bad that someone makes cheats for a game

**Comment by ItsRodrigoAl** [comment]
@SDGNelson I want to add that also the game loads really slow on the first launch after starting the PC, between only 3 and 8 frames (of course this depend on the PC specs) but then if you close and launch the game again, it will load fast at a higher framerate between 20-40 (as it should be)

Mouse movement also seems to be affecting the load speed and frames, but it's really weird since on the video I show how the CPU or GPU aren't stressed at all and still the game seems to have a frame drop loading the game only because I drag the mouse a little bit.

And I want to remark that this was not happening on previous versions, this has been happening to me since maybe the last 2-3 game versions? Before those, the game always loaded fast for me (as it were the second launch)

[https://streamable.com/8fgy4k](https://streamable.com/8fgy4k)

**Comment by sunnamed434** [comment]
> > > P.S. to readers: aerodak2 is a cheat developer. 😞
> > 
> > 
> > What's the actual matter that aerodak2's a cheat dev? Does it change smth? On the other hand, if aerodak2's a cheat dev, this guy suggests you improve the game experience I think it's forgivable and not so important in this case
> 
> he just said it in a joke way I guess. still, is bad that someone makes cheats for a game

ah, ok

**Comment by iBowie** [comment]
> @SDGNelson I want to add that also the game loads really slow on the first launch after starting the PC, between only 3 and 8 frames (of course this depend on the PC specs) but then if you close and launch the game again, it will load fast at a higher framerate between 20-40 (as it should be)
> 
> Mouse movement also seems to be affecting the load speed and frames, but it's really weird since on the video I show how the CPU or GPU aren't stressed at all and still the game seems to have a frame drop loading the game only because I drag the mouse a little bit.
> 
> And I want to remark that this was not happening on previous versions, this has been happening to me since maybe the last 2-3 game versions? Before those, the game always loaded fast for me (as it were the second launch)
> 
> https://streamable.com/8fgy4k

It has to do with System file cache, when on the second and next reads file is read from system cache, rather than from a disk.
https://learn.microsoft.com/en-us/windows/win32/fileio/file-caching

Still, weird that you say it wasn't the case in previous versions.

**Comment by aerodak2** [comment]
> > > > P.S. to readers: aerodak2 is a cheat developer. 😞
> > > 
> > > 
> > > What's the actual matter that aerodak2's a cheat dev? Does it change smth? On the other hand, if aerodak2's a cheat dev, this guy suggests you improve the game experience I think it's forgivable and not so important in this case
> > 
> > 
> > he just said it in a joke way I guess. still, is bad that someone makes cheats for a game
> 
> ah, ok

calm down bro.

[Video Link (streamable.com)](https://streamable.com/xqddfw)

As you can see at video my CPU is overloaded at Mounting Phase.
I realized when CPU is not overloaded Mounting Phase is loading much _Faster_
CPU overloading to produce FPS. Background processes in the game slow down due to excessive CPU usage

**Comment by Coopyy** [comment]
> You're right that it looks like when framerate limit and vsync is applied was changed so that they aren't being applied immediately during startup, so that should probably be changed.
> 
> That being said, high FPS during the non-asset-bundle-loading period of loading screen shouldn't be an issue because the game loads a certain number of assets per frame. During asset bundle loading (e.g. "mounting asset bundle x...") high FPS would be a problem though.
> 
> P.S. to readers: aerodak2 is a cheat developer. 😞

developer is a strong word
