### ISSUE TITLE
Bug: Impact grenades not despawning

### ISSUE THREAD

**Issue by OneManOperative** [SmartlyDressedGames/Unturned-3.x-Community#3834]
Impact grenades don't despawn if fuse length is long/infinite.

Example:
![image](https://user-images.githubusercontent.com/48363842/235359923-23957434-c14f-4a34-9718-b24ea2902cb9.png)

**Comment by SDGNelson** [comment]
Thanks for the report! Will investigate.

**Comment by SDGNelson** [comment]
It looks like this is because only the server handles the projectile impact, and the game doesn't currently have a way to notify clients about changes in projectiles after they have been launched. This will be properly resolved when I rewrite projectiles (https://trello.com/c/Rx3KI6md/45-projectiles-rewrite)
