### ISSUE TITLE
Gamebreaking Exploits

### ISSUE THREAD

**Issue by thosedambandits** [SmartlyDressedGames/Unturned-3.x-Community#3848]
![noocean](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/133050070/c612a99f-c2e0-43ea-8571-c8c14331990d)
![noflinch](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/133050070/3ba1b88b-b1ac-4b4e-822c-becccecda0f0)
![lagswitching](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/133050070/2b7c30c2-cf66-4b87-8c5a-4b6039c1fe32)
PEX has youtube videos online that show ocean and flinch has been removed, lagswitch scripts still work on unturned aswell, cheaters usually get banned by anticheat or admins but these exploiters never get punished, it would be appreciated if you could fix these issues

**Comment by SDGNelson** [comment]
It depends what they're doing. I looked up this video and it appears to be an external program removing the water because it happens while the game is running. If they release their cheat then BattlEye will be quick to add a detection. Any simple *exploit* without an external program should be fixed if reported.
