### ISSUE TITLE
Workshops not loading

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#3877]
After todays update, workshops stopped loading on server launch. Maybe need to change something?

**Comment by SDGNelson** [comment]
Could you elaborate please? As part of my pre-release testing I loaded up a PEI server with More Farming and it was working properly (could use More Farming items).

**Comment by SDGNelson** [comment]
By default the game won't load items if the asset is missing, so unless the virtual storage is loading differently it sounds like the server should have those assets. Could you attach the server's log file please?

**Comment by baranmod** [comment]
Tried to take items by ID, didn't give anything. On server lobby it shows that mods are there. When I load into server it shows that mods are loading, though not sure why

Here is the log: 
[Server_WarzoneZ.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11578162/Server_WarzoneZ.log)

**Comment by SDGNelson** [comment]
It looks like there are a bunch of folders with workshop file IDs inside:
`/Servers/WarzoneZ/Workshop/Content`
Which the game isn't correctly searching. I'll get that fixed, but why do you have workshop files installed in there? And if so, why instead of using the workshop auto download? The game warns about this on startup.

**Comment by baranmod** [comment]
Tried to use auto downloader in the past but there were some issues with it (workshops weren't updating properly) so just kept uploading/updating manually instead
