### ISSUE TITLE
Repair recipes for items do not appear unless you search for them - and other issues.

### ISSUE THREAD

**Issue by Renaxon** [SmartlyDressedGames/Unturned-3.x-Community#3881]
The title of the post explains everything, likely a byproduct of this addition?

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67073622/262247ed-7344-4cbc-b9ea-7909321f8e07)

**Comment by Renaxon** [comment]
After searching for the recipe, it's hard to find it because there is all the other recipes that have 'top' in the way, making it unable to see what you actually need to repair the top, unless you search for the specific name of it, fairly annoying.

Instead of making a second post I will mention this here: searching for crafting recipes shows recipes from all the items available from other maps. This setting should likely be enabled per-map.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67073622/f3f9ce88-224a-40ce-af5f-e30b3fb4fd5a

**Comment by SDGNelson** [comment]
Thanks! When looking into a different bug I tidied up some of the crafting code, and it looks like a typo of `>` rather than `>=` messed up repair blueprints. :(

As for the entire list: singleplayer has the problem of not knowing which assets should be used by which map, so it uses all of them. This allows your installed mods to be used on all maps and for example modify spawn tables to add other items.

**Comment by Renaxon** [comment]
What I'm suggesting is for the new setting, the one that shows all the available recipes when you search for them, to be enabled only if the map specifies so. I don't believe this setting to be desirable on all the maps, I am already receiving reports about this setting myself as it's showing unobtainable recipes and generally messing with people's muscle memory.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67073622/1a6c9867-8b79-4f95-a21a-ab5f166b0a17)

**Comment by SDGNelson** [comment]
I'm not sure I understand about the muscle memory since the results that would have been returned before are still shown at the top. Is it specifically with the repair bug?

As for the option: how about a per-item or per-blueprint option to hide? Then items like "Debug" there could opt-out, but recipes from mods would be visible.

**Comment by Renaxon** [comment]
Per-blueprint option to hide them from search results sounds like a good solution.

**Comment by SDGNelson** [comment]
Awesome, I'll open a new issue to remind myself to add that
