### ISSUE TITLE
Revise how asset's closest masterbundle is found

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#3885]
If you have two or more folders with similar names, game load bundles from first folder by alphabet, fix it please
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/67b43e4d-9455-4873-af65-55b8d330964b)
Folder with red line not loading .unity3d files.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/39222548/2489bca2-1684-4dc5-a744-87cc60698e54)

**Comment by SDGNelson** [comment]
Interesting issue! Previously the game tracked which masterbundle was closest while descending the hierarchy, but as part of moving that to the other thread the game now finds it per-asset. There's a bug with this though because it's going by string length which won't work when those two folders have the same prefix. In the meantime if you rename to something like NoBundle_BatSun_Mods it will work, and for the next update I'll maybe move tracking the masterbundle to the other thread.
