### ISSUE TITLE
Steam network internal error

### ISSUE THREAD

**Issue by zevordex** [SmartlyDressedGames/Unturned-3.x-Community#3904]
When i connecting to server i have this error "(5002) Reliable message size X too large for remaining space in message queue."
How can i fix this?

**Comment by surv0013** [comment]
I also noticed that some players have this problem. Moreover, it is solved by itself, but then it occurs again with the same players. It seems like deleting mods from the folder and then verifying of the game files can temporarily solve this problem.

**Comment by SDGNelson** [comment]
There seem to have been an increasing number of reports of this starting sometime partway through May. There's currently an open issue about it in the GameNetworkingSockets repository. Apparently it's ending the connection when it receives too much data for the receiving buffer rather than dropping the packet. I'm unsure why this started happening between updates. If I understand correctly Valve intends to fix to drop the packet rather than ending the connection. There's also an option to increase the buffer size which I will probably do, but didn't in this past Friday update because the version of the API used by the game doesn't have that option. (might just hack it in)

**Comment by DanielWillett** [comment]
If you do end up changing the buffer size is it possible to make the buffer size a launch option? I'm working on a project that would benefit from a larger buffer size, the 65535 byte limit has actually been one of my biggest hurdles.

**Comment by SDGNelson** [comment]
Oh, to clarify: this is the buffer Steam Networking Sockets is keeping not-yet-handled messages in. Where are you running into size limits with the game's network buffer?

**Comment by DanielWillett** [comment]
If I try to send more than around 65 kb within a short amount of time (not necessarily the same message or frame, more like I have to space them out like 0.25-0.5 seconds), it just stops sending (even when connected locally). I know the net packer class has that 65kb buffer size but even on different messages it still cuts off, which I just assumed was a steam buffer issue.

**Comment by DanielWillett** [comment]
I'm working on a multiplayer module for the map editor, and sending larger stuff (like rendered GPS pngs), etc to the server takes a pretty long time because of how much I have to space out packets. I'm not asking you to go out of your way or anything for this but if you're already going to mess with the buffer size, an option would be nice.

Here's a dev-progress video from a few days ago if you're interested https://youtu.be/lbulwEYijRU, repo is in the desc.

**Comment by SDGNelson** [comment]
Wow, that's quite remarkable, nice work!

Considering you are already patching a lot of code, one option might be to modify Block.BUFFER_SIZE or Block.buffer (write) and Provider.buffer (read) early during startup. It sounds like you might run into the same issues though if the limiting factor is the transport implementation. Maybe tuning the transport config will resolve it.

**Comment by DanielWillett** [comment]
I'll look into it, thank you.

**Comment by GazziFX** [comment]
Client has following messages
```
[2023-06-15 06:06:10] Accepted by server
[2023-06-15 06:06:10] Loading BattlEye client library from: D:\SteamLibrary\steamapps\common\Unturned/BattlEye/BEClient_x64.dll
[2023-06-15 06:06:10] BattlEye client message: Initialized (v1.249)
[2023-06-15 06:06:11] Client connection problem detected locally (5002) "Reliable message size 7 too large for remaining space in message queue."
[2023-06-15 06:06:11] Disconnecting: Client transport failure: "Steam network internal error."
```
Has this problem not been fixed yet?

**Comment by sunnamed434** [comment]
Getting reports by some people about the same issue

```console
Removing player steamid:76561199137350310 due to transport failure (ClosedByPeer Reason: 5002 Message: "Reliable message size 6 too large for remaining space in message queue.")
```

**Comment by Mondopna** [comment]
Yes, the problem is real.
[2023-06-15 20:39:25] Removing player steamid:76561199446623243 due to transport failure (ClosedByPeer Reason: 5002 Message: "Reliable message size 49 too large for remaining space in message queue.")

**Comment by SDGNelson** [comment]
Valve commented on the issue in the GNS repo saying they will put up the fix soon. 🤞

**Comment by DiFFoZ** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/48765566/1079b623-8b6a-4452-a4e5-100f1736820c)
Looks like fix is already on Steam Client Beta

**Comment by SDGNelson** [comment]
Has anyone run into this again recently?

**Comment by surv0013** [comment]
> Has anyone run into this again recently?

No, the issue has been resolved.

**Comment by SDGNelson** [comment]
Thanks surv0013, that's reassuring to hear. I haven't gotten any support tickets about this recently either. I'll keep it open for a few more days just in case.
