### ISSUE TITLE
Mods i'm not subscribed too continue to be downloaded.

### ISSUE THREAD

**Issue by ApexFresh** [SmartlyDressedGames/Unturned-3.x-Community#3907]
I've uninstalled these mods on the workshop multiple times, and deleted the workshop folder contents yet they keep reappearing whenever I launch my game. I don't know how to stop them from downloading. I cannot work on my map or play most servers because of these mods.

**Comment by DanielWillett** [comment]
Can confirm, even deleting the `C:\Program Files (x86)\Steam\steamapps\workshop\appworkshop_304930.acf` file doesn't fix it. You can test this by deleting them all and verifying your game.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/79c96133-5ad3-4472-b47c-574ab6994820)

after verifying:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/46cbcedd-b7b7-4633-9b1f-748845bb7d9c)
appworkshop_304930.acf file (renamed to .txt so I can upload it)
[appworkshop_304930.txt](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/11594003/appworkshop_304930.txt)


On a related note, mod loading in general feels like it could be reworked some.

Since all assets in all enabled mods are loaded on startup, asset conflicts are very common. Mods (except localization mods) could be loaded when you join a server.

For singleplayer a more reliable way to select which mods load would be good. Since assets can be loaded at runtime (which we see when you join a server and download the mod for the first time), I don't really see any problems with doing this.

If possible, mods should be unloaded when you leave the server/singleplayer/editor.

A possible way to deal with singleplayer is just a list of all installed mods with checkmarks, per-save, so you can enable and disable mods and it's linked to the save. A missing mod shouldn't be removed from the list, but downloaded when you launch singleplayer instead, since sometimes you have to clear your mod folder (assuming you're connected to the internet). I know this page already sort of exists but it only shows subscribed mods, not installed, and it only takes effect over a restart. It also seems inconsistent sometimes, for example, sometimes I have to join a server that has the mod, to load it properly, before I can edit the map. This page would need to double for the editor as well, so you can select mods to load when you load the editor for a map, per-map.

**Comment by SDGNelson** [comment]
Do they show up in Menu > Workshop > Manage Subscriptions? The Steam workshop API mentions that unsubscribing might not delete them right away, but they shouldn't be getting loaded by the game if they aren't subscribed. If you click the Unsubscribe button in that menu do they reappear in-game again? I use the Manage Subscriptions menu practically daily so I'm confident it's working.

**Comment by ApexFresh** [comment]
> Do they show up in Menu > Workshop > Manage Subscriptions? The Steam workshop API mentions that unsubscribing might not delete them right away, but they shouldn't be getting loaded by the game if they aren't subscribed. If you click the Unsubscribe button in that menu do they reappear in-game again? I use the Manage Subscriptions menu practically daily so I'm confident it's working.

In the "Manage Subscription tabs", only the mods I am subscribed too show. However, there are mods in the workshop folder not listed in this tab. I did not acquire these by joining a server.

**Comment by DanielWillett** [comment]
Yeah, same here. If that's a Steam issue I understand not much you can do but it's not that it doesn't delete them right away, it just never deletes them, and if you try to clear them, it puts them back. It seems I was wrong about the subscriptions tab I just did some testing and it seems to work as intended, I just misunderstood how it worked.

Is it possible to unload mods when you stop using them if they're not enabled in the subscription manager? Going from one modded server to another sometimes requires a restart if there are conflicts.

**Comment by DanielWillett** [comment]
And to add on to that I think auto-enabling subscribed mods confuses a lot of players, the most common error I see by far is people asking about asset conflicts between mods.

**Comment by Jdance-Media** [comment]
> And to add on to that I think auto-enabling newly subscribed mods confuses a lot of players, the most common error I see by far is people asking about asset conflicts between mods.

I'd like to add on that Cities: Skylines has players enable newly subscribed mods in-game in order to prevent confusion. Not sure if this is the best idea for Unturned, but it might promote awareness of the workshop management tab, as there are still many players out there that have no idea about it.

**Comment by SDGNelson** [comment]
Where did they come from then? (i.e., they aren't just completely random workshop file ids - they were subscribed or installed at some point?) I think Steam keeps them installed for some amount of time in case they are used by DownloadItem or re-subscribed.

Also, are you sure the folders aren't just empty? If I look in my workshop/content/304930 folder there are 98 subfolders, but many of them are empty.

Ideally yes I would like to add options for which workshop mods are enabled when playing singleplayer or using the editor per-map at some point.

Regarding problems switching servers: that should no longer be an issue after the update last year which puts together the "asset mapping" per-server. Have you still run into this recently?

**Comment by ejspinn** [comment]
I have also been having the same issue.  Mostly noticed it since the last update on friday.  

84 folders keep reappearing in the workshop>content>304930 folder.  It amounts to 8.5 gigs worth of mods.  After unsubscribing from the only two mods i had selected (Arid and A6 Polaris) and deleting the contents of the workshop folder, then it auto verifys game to amount in excess of 5 gigs of downloads. 

So when i try to play a multiplayer server it takes 30 minutes to download im assuming the 84 folders of mods again.  Then i end up getting kicked from the server saying i dont have that map.

i thought it may have been like preloading mods and assets from servers in my favorites list because alot of mods were from an Unturnov game i was playing.  I cleared my server favorites list and shutdown steam , clear folder again. 

it still loads 84 folders and 8.5 gigs of mods i dont want.  I was given this link from the discord support from JDance he said there were a few others having similar issues.

**Comment by SDGNelson** [comment]
@ejspinn the 8.5 GB mods are likely the ones from that server yes. If you are manually deleting them from the drive then Steam may be re-installing them thinking they were accidentally lost / need updating. If they don't get used for a while Steam should delete the contents but it sounds like the empty folders will remain. Is your concern mainly the disk space usage? They shouldn't be occupying any game processing/loading time because they aren't loaded until subscribed or used by a server.

**Comment by ejspinn** [comment]
I was trying to work on a vanilla map in the editor using only the original assets.  I didnt want to mix in some other mods and assets so I would clear that workshop>content>304930 folder.  I typically dont subscribe to many mods just like the most recent maps Arid and A6. 

The new map I was trying to play was Gadsden and it has in its workshop box, in the server list, 13 assets/mods mostly from other curated maps.  Hmm 13 must be the  max amount of Mods listed on the server workshop list screen.  As both the Gadsden server and Pandahut Unturnov server have that many listed in that description box.  Is there a way to find out all required assets from the server?  

Another thing I noticed just now, in that Workshop Mod list is the ones from Pandahut's Unturnov only one has a "-" side beside the workshop mod. It the Hawaii Assets, the other 12 listed workshop mods have a "+" beside them and has a tool tip to subscribe to it in the workshop.  I will try to attach a screenshot showing this.  

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81039292/d6a10284-f02a-477c-a408-3c71e32a28bf)
On the Gadsden server its showing a few more as being Subscribed such as Greece assets, Hawaii assets again, and finally Carpat.  Ill try to post a screen shot.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/81039292/a849bf48-70ce-4b8e-af69-d685042792e8)

The main concern was the loading in time, it was close to 30 minutes downloading a 84 mods. I know my network isnt the fastest its the  middle package, and there was others on the network at the time.  But ive never had to wait 30 minutes to play this game.  Just struck me as odd.  Which made me investigate into why all these folders were coming from?

**Comment by SDGNelson** [comment]
@ejspinn Currently when you load up the editor it will only use your subscribed workshop files, though if you have joined a server it will have loaded those as well. (so currently the safest option would be to restart the game after playing if you are going to edit) It *won't* load all of the files in the content folder in the editor.

There *shouldn't* be a limit on the number of mods shown. I think I've seen some servers with dozens of mods listed.

**Comment by GazziFX** [comment]
When you join any modded server installed mods won't show in subscriptions, but they will update because they listed in appworkshop.acf. If you want delete these mods you should close Steam delete appworkshop.acf and folder with game appid

**Comment by SDGNelson** [comment]
As far as I know this has been covered / addressed, but if there are any further concerns or if my response was incorrect please feel free to comment and I will re-open.
