### ISSUE TITLE
When finding a duplicate masterbundle redirect to existing copy

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#3927]
Will provide some compatibility for mods that are having issues with re-uploaded masterbundles. (please don't do this though)

**Comment by P9ndx** [comment]
please 🙏

**Comment by GazziFX** [comment]
> please 🙏 

Just reference original mod instead of re-upload

**Comment by DerpyHoowes** [comment]
Could we have an update that would make the game always pick the MasterBundle from workshop over any other versions of it stored on client's PC?
The way it currently works is very uncomfortable for me, as whenever Im often making new content for my mods, and keep the update MasterBundle version in Sandbox folder. And so whenever I made some change, but didnt release it as an update to the workshop and try to join a server with this mod, it kicks me, with the error message saying that MasterBundle versions dont match. And every time this happens, I have to remove the mod files from Sandbox folder to other place on my PC, restart the game. join the server again and so on.
Rather than just kicking the player, saying that MasterBundle versions dont match, it would be better if the game just loaded the MasterBundle from workshop, replacing the local one in RAM, so that the player can join the server without going through all that hustle.

**Comment by SDGNelson** [comment]
The reason duplicates were skipped: Unity fails to load asset bundles if the contents are identical.

On the preview branch now it will try to load all master bundles, and if it fails it will try to find a fallback with the same name hopefully indicating that the contents are identical. I tested using some vanilla assets and it seems to be working okay, but if you get the chance to try a situation that isn't working currently with the preview branch version I would appreciate it!

**Comment by GazziFX** [comment]
Maybe find by hash, and use name if not found?
