### ISSUE TITLE
Game doesnt clear RAM after pageuping

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#3928]
You didnt completely fix what i mentioned in #3841 because now it fills up RAM and paging file afterwards
![10040 MB of RAM used](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/113861259/851d4565-e579-46fd-8833-5eb9e7ba1e7f)

**Comment by SDGNelson** [comment]
Perhaps I misunderstood your original question: the issue I thought you were referring to was that Page Up could be pressed multiple times in short succession to cause multiple reloads to happen at the same time. (this was fixed)

Previously the game ran garbage collection and unloaded assets periodically during loading, but it looks like now it's *only* running that when leaving the level unless the **-AggressiveGC** command-line argument is enabled.

It's also quite possible that the game is leaking memory during asset reload because it doesn't `Object.Destroy` any of the previously loaded Unity objects.

If you run the game with **-AggressiveGC** does it help mitigate the problem?

**Comment by CyberAndrii** [comment]
Tried **-AggressiveGC** yesterday and it seems to have become significantly slower after the update. When enabled, it takes around 30 minutes to join a modded server with 13k assets, whereas only 3 min when disabled. Previously, `CleanupMemory()` was invoked every 25 loaded assets, but now it's every 3rd-ish for me. This also could be the reason of https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3907#issuecomment-1571194279

**Comment by Wyvernaed** [comment]
The main issue im trying to point out is that game doesnt clean up memory after each assets reload. Before update, game garbaging something on C drive and cause BSOD because i have small free space on this drive, now it garbaging RAM and paging file afterwards, which is also annoying in some ways.

**-AggressiveGC** fix the problem but it takes much longer time to load game.

**Comment by GazziFX** [comment]
> Before update, game garbaging something on C drive

Probably swap file
