### ISSUE TITLE
Unturned crashes 

### ISSUE THREAD

**Issue by Miguel0hara** [SmartlyDressedGames/Unturned-3.x-Community#3936]
Needed help when I open unturned everything is fine but when the resources are finished loading it crashes and I can't enter the game that's been happening to me since yesterday when the game crashed suddenly and i can't play

**Comment by SDGNelson** [comment]
It may be worth checking out the [reducing memory (RAM) usage](https://support.smartlydressedgames.com/hc/en-us/articles/12112637453076) article because that is the most common cause of crashes.

Otherwise if you can please submit a crash report following the steps from this article I can investigate: https://support.smartlydressedgames.com/hc/en-us/articles/12144393042324-Reporting-a-crash
