### ISSUE TITLE
bug when downloading workshop then the server got shutdown

### ISSUE THREAD

**Issue by kezaspr** [SmartlyDressedGames/Unturned-3.x-Community#3965]
Hello,

I was downloading a workshop for an server, then the server got shutdown. Let me explain what's happening in the video. So after the shutdown, it still continues the update. It also loads the workshop, but when it's done loading the workshop, it shows me the "Lost connection to host or Steam network." (first it was the server was shutdown, but i didn't clip that, then i rejoined the server now it's doing that thing). Well, it did download the workshop that i needed for the server, but it doesn't load to the server instead the game trying to load it in singleplayer mode (CMIIW), and it won't load to the map thingy and just stays at 100%.

Well the only thing i know to fix this is just reload the game and rejoin the server.
Thanks.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109429480/54a4ad2b-b268-4748-8e46-eb4fe794d29e
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109429480/ae947d28-f641-439a-b39b-70a2af0ffdc3

**Comment by SDGNelson** [comment]
Thanks for the report. It should eventually lose connection if the server shuts down while loading the map, but the timeout is longer because the server doesn't consider the client "connected" until they finish loading.

**Comment by SDGNelson** [comment]
I think what happened here is the OnClientTransportFailure callback is happening at a point when disconnection isn't handled properly, namely when workshop is downloading/installing/loading and/or the level is loading. Ordinarily the game ignores timeouts during these - in part because there can be long hitches - but the underlying Steam Networking Sockets library can still disconnect in the meantime. Interrupting loading will/would be a nightmare right now, so for the next update I've changed it to defer the failure handling until the current uninterruptible state completes.
