### ISSUE TITLE
bug with items

### ISSUE THREAD

**Issue by waddleswaddles** [SmartlyDressedGames/Unturned-3.x-Community#3998]
so if you have a locker high up and you destroy it, items stay up there instead of dropping down to the ground (some occassions they fall down and you can pick them up, sometimes you can't pick them up) 
this also happens with players dying in helicopters, in the air, etc.

**Comment by SDGNelson** [comment]
The game will try to find ground for the items within 512 meters when they fall. If no ground is found they appear at the original position. There is a limit on how far the physical version can fall though because the item physics are client only. If item physics are eventually made server-sided this can be properly fixed to always fall infinite distance.
