### ISSUE TITLE
Missing A2S_RULES packet (missing details/links/workshop mods on server connect screen)

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4003]
Roughly ~90% of the time or more, on my server, it won't show any of the details, links, workshop mods, or plugins on the server connect screen. For other servers, it works almost all of the time. I've included screenshots from my server and another server that seems to work. I've also included the IP & port for the server if it's needed for debugging.

The server seems to be dropping the A2S_RULES packet, which I can see in Wireshark (it begins with 0xffffffff45).

Screenshot from my server (top Unturned server):

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72173894/b3d4ce21-8314-4896-9504-b9b220e71491)

IP: 144.217.87.134:28015 (horizonrp.life:28015)

Screenshot from inferior competitor's server:

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/72173894/d72c2059-113e-49c7-a08f-e322a0ce5238)

IP: 104.129.132.73:27095

Any help or guidance is appreciated, have a nice day.

**Comment by SDGNelson** [comment]
Unfortunately I'm not sure either. I've noticed that when using a VPN the rules query almost never goes through. As far as I know it's outside the game's control, but I'll leave this open for now in case anyone else reading this has an idea.

**Comment by ItsRodrigoAl** [comment]
It gets fixed by just changing one minimal thing from any of the Browser configs (for example, just change something anywhere, so it will need to get 'refreshed' on your client because it have a new change and you'll see now the server details)

I know this because I also manage Unturned servers with a friend, and we've noticed this weird bug since time ago, where my friend can see the server details but I can't, or vice versa. Luckily I found a "solution" for this just doing the thing I just said.

Example: lets say the server descriptions says something like "best vanilla server" then just change it to "best vanilla server!!!" or "hehe temporal change" or "abc" (just random changes), restart the server and this will make it be visible again for you, and then just change it back to "best vanilla server"

The curious thing about this bug is that is just a client-side problem. I mean, while you can't see the server details, others can (I tried with your server and I can actually see your server detail).

**Comment by asineth0** [comment]
>when using a VPN the rules query almost never goes through

This is what I needed. I know almost no one else will probably be affected by this, but my MTU inside of the container that Unturned was running in was 1500, while the external interface's MTU was 1420 (WireGuard).

**Comment by SDGNelson** [comment]
@asineth0 Wow really? That's so interesting! So the server outbound traffic was going through a VPN and the lower MTU caused the A2S_RULES packet to be dropped? I guess maybe this is a bug in Steam that the packet is too big - most network code I've seen assumes an MTU of 1,000 to 1,200 bytes. I'll have to see if I can raise the MTU in my VPN.

**Comment by asineth0** [comment]
> @asineth0 Wow really? That's so interesting! So the server outbound traffic was going through a VPN and the lower MTU caused the A2S_RULES packet to be dropped? I guess maybe this is a bug in Steam that the packet is too big - most network code I've seen assumes an MTU of 1,000 to 1,200 bytes. I'll have to see if I can raise the MTU in my VPN.

Yeah, that's my setup. I have a WireGuard tunnel set up so people connect to the server through a VPS that's hosted somewhere. I use Pterodactyl as a server panel, which runs the servers in Docker containers, and it set the default MTU inside the container to 1500. There's a way to override that to 1420, and when I did that it started working. To be clear I'm not talking about the MTU of the WireGuard VPN, but of the MTU inside the container for the Docker network bridge.

So, I think it was just an issue with my uncommon setup and not Unturned/Steam.

**Comment by Balicon01** [comment]
As I've noticed, this is all due to a large number of configuration changes. If I change 10 items, nothing happens, but if I change 110, this error appears. I might be wrong, but I noticed this through experimentation.

**Comment by GazziFX** [comment]
To avoid it in the meantime we could compress data, for ex replace names with IDs, use binary format, encode gzip. This would break server monitorings

**Comment by Balicon01** [comment]
It's worth adding the ability to toggle the display of all changes with a single action. This will simplify management and make the interface cleaner. In my opinion, players don't need to see every single server configuration detail.
