### ISSUE TITLE
Material GUID / Index not working as expected on some objects

### ISSUE THREAD

**Issue by AdamDN** [SmartlyDressedGames/Unturned-3.x-Community#4025]
Presumably objects that have custom shaders?
Not a big issue - but it works as you would expect in the Editor, and just doesn't appear properly in-game.

(shown below, Grass 1, Grass 2, Russia Grass 3, Lava 1, Peaks Boulder 03)
Editor: 
<img width="1091" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/69d86658-193b-4fa5-84c9-62e1b2bb6960">

In-game: 
<img width="1001" alt="image" src="https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/71527679/a3640ecd-d1e8-43e4-8026-dfff049fb860">

**Comment by SDGNelson** [comment]
It looks like it might be from applying the level atlas, will investigate

**Comment by SDGNelson** [comment]
With `-ValidateLevelBatchingUVs` and the material palette override these are logged as having UVs outside the 0-1 range. Ordinarily this isn't a problem because they use triplanar materials so don't use texture atlassing. If your material palette also uses triplanar mapping it should work properly, but I don't think these objects are an issue because there's no reason to use the regular old texture palettes on them.
