### ISSUE TITLE
Consider reverting boulder kill volume changes or tweaking them.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4033]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/ecdbe454-163a-432f-a493-4b8988830dfe)
^ This was taken from apocalypse roleplay server.

There may be too many unintended consequences that come with the change.

**Comment by SSGamingServers** [comment]
Yes this must be patched. everyone is getting killed @SDGNelson

**Comment by SDGNelson** [comment]
Sorry about this, it's been reverted now in the .1 patch. The problem was that some of the volumes in the boulders were spheres and capsules which can't be non-uniformly scaled. Unfortunately this didn't come up in testing because on vanilla maps the boulders were always uniformly scaled, whereas on many custom maps boulders are scaled on a single axis to better fit a surface or for visual variety. (which is perfectly reasonable, my bad for not thinking about this side effect)
