### ISSUE TITLE
Add_Kill_Triggers

### ISSUE THREAD

**Issue by HathHub** [SmartlyDressedGames/Unturned-3.x-Community#4034]
Latest unturned update for boulder objects containing **Add_Kill_Triggers true**, specially on scaled boulders, makes the killer volume extend past the actual object. This is most commonly seen on community servers using boulders from Boulder_00 to Boulder_11.

Note how this only happens on the scaled up version of Boulder_01 on the video attached:
https://cdn.discordapp.com/attachments/1104802402244239522/1134592049082028083/Unturned_2023.07.28_-_18.00.16.02.mp4

**Comment by SDGNelson** [comment]
Sorry about this, it's been reverted now in the .1 patch. The problem was that some of the volumes in the boulders were spheres and capsules which can't be non-uniformly scaled. Unfortunately this didn't come up in testing because on vanilla maps the boulders were always uniformly scaled, whereas on many custom maps boulders are scaled on a single axis to better fit a surface or for visual variety. (which is perfectly reasonable, my bad for not thinking about this side effect)
