### ISSUE TITLE
Offroaders and Rovers (SUV) use "SqrDelta" instead of "Valid_Horizontal_Speed"

### ISSUE THREAD

**Issue by MoltonMontro** [SmartlyDressedGames/Unturned-3.x-Community#4057]
These vehicles (offroaders, rovers) have a property in their .dat files included as ``SqrDelta 1.6``.

It appears that SqrDelta _is_ implemented, but not as its own property. Instead, it looks like it's part of the formula for calculating the actual `Valid_Horizontal_Speed` used for sanity checks.

Reporting this as a bug, just in case the intention was for those vehicles to have ``Valid_Horizontal_Speed 1.6`` instead. Although that value seems very small, so maybe it's something else (e.g. just leftovers from testing years ago), and isn't actually a bug?

**Comment by GazziFX** [comment]
SqrDelta is calculated with following code
```csharp
float x = data.ParseFloat("Valid_Speed_Horizontal") * PlayerInput.RATE; 
_sqrDelta = MathfEx.Square(x);
```

so `Valid_Speed_Horizontal` should be 15.8 in this case
```csharp
Mathf.Sqrt(1.6f) / PlayerInput.RATE
```

**Comment by SDGNelson** [comment]
Oof for bad variable naming. `sqrDelta` is very old but would more correctly be named something like "max valid horizontal squared distance per move input". I think earlier on it could be specified in the file but was replaced by `Valid_Speed_Horizontal` and `Valid_Speed_Up` / `Valid_Speed_Down`. It should probably be removed but for the meantime shouldn't have any ill effect because it uses the speed as a default.
