### ISSUE TITLE
On attachment update aim animation speed scales between Aim_In_Duration value and original animation duration

### ISSUE THREAD

**Issue by Wyvernaed** [SmartlyDressedGames/Unturned-3.x-Community#4063]
https://youtu.be/48P3IShTfLU

When i update attachment in video, aim animation speed scales between 0.2(deafult Aim_In_Duration) seconds and 1 second(original animation duration) but aim speed stays 0.2 sec.

**Comment by SDGNelson** [comment]
Thanks for the report! I think what's happening here is when the game updates the animation speed it's currently using the scaled length of the animation rather than the default (unscaled) length. If that's the case it should be correct after re-equipping your item. Does it work as-expected after re-equipping?

**Comment by Wyvernaed** [comment]
Yes, it working as-expected after re-equipping.

**Comment by SDGNelson** [comment]
Thanks for the confirmation, will fix for the next update!
