### ISSUE TITLE
Can Master_Bundle_Override be used in servers to customize a mod from the Steam Workshop

### ISSUE THREAD

**Issue by MooRic** [SmartlyDressedGames/Unturned-3.x-Community#4076]
In single-player mode, it is possible to customize and modify a specific mod without making any changes to its original files, by creating a "Master_Bundle_Override" file. This allows for localized modifications or changes to the data, while largely avoiding copyright infringement. However, although the resulting "Master_Bundle_Override" file can be uploaded to the workshop, it cannot be used on servers. So, I would like to inquire whether there are any plans regarding this issue or what the reasons for its infeasibility are.

**Comment by NotOfficeChair** [comment]
I believe this is currently broken, I have been trying to modify a workshop mod called "The Sock Mod" using master bundle overrides to change 2 Item ID's to make compatible with another mod, however it seems to randomly work and not work, i believe it's due to how the game loads bundles and it's sometimes overriding my mod and sometimes not, i'd love if this could be looked into because i'm sure this doesn't only affect me

**Comment by MooRic** [comment]
> 我相信这目前被打破了，我一直在尝试使用主捆绑包覆盖来修改一个名为“袜子模组”的创意坊模组，以更改 2 个物品 ID 以使其与另一个模组兼容，但它似乎是随机工作的，而不是工作，我相信这是由于游戏加载捆绑包的方式，它有时会覆盖我的模组，有时不会， 如果可以对此进行调查，我会很高兴，因为我相信这不仅会影响我
> 
> 我可能还应该注意，在研讨会中，我将袜子模组设置为我的模组的依赖项，它不包含任何重新上传的捆绑包，只包含我要更改的项目的.dat文件

"Master_Bundle_Override" can only be used when there are no conflicting IDs. When there is a conflict, it can only be used for the one that can still be accessed.

**Comment by MooRic** [comment]
> I believe this is currently broken, I have been trying to modify a workshop mod called "The Sock Mod" using master bundle overrides to change 2 Item ID's to make compatible with another mod, however it seems to randomly work and not work, i believe it's due to how the game loads bundles and it's sometimes overriding my mod and sometimes not, i'd love if this could be looked into because i'm sure this doesn't only affect me
> 
> I should probably also note that in the workshop i have the sock mod set as a dependancy for my mod, it does not include any reuploaded bundles and just contains the .dat files of the items i wish to change

"Master_Bundle_Override" can only be used when there are no conflicting IDs. When there is a conflict, it can only be used for the one that can still be accessed.

**Comment by NotOfficeChair** [comment]
What would be the best way to change ID's for compatibilities? i was under the assumption that's one of the uses for master bundle overrides?

**Comment by MooRic** [comment]
If there is a conflict with IDs, there is no other solution but to modify the original mod and re-upload it, or simply choose not to use that particular mod.

**Comment by SDGNelson** [comment]
Unfortunately, Master_Bundle_Override is limited at the moment. It is only 100% supported when used with the core masterbundle or other masterbundles in your mod. During startup, all masterbundles are loaded first, which is why it works in singleplayer. In multiplayer, they are loaded as they are installed, so the target masterbundle might still need to be installed. Ideally, the game would track which masterbundles are dependencies of each mod in the future.

**Comment by KorMalek** [comment]
Can masterbundles still be used for multiplayer?
