### ISSUE TITLE
Disconnect while dying in vehicle with many items in inventory

### ISSUE THREAD

**Issue by lvlbgn** [SmartlyDressedGames/Unturned-3.x-Community#408]
Short of long story, there is an "old" bug which causes you to crash from server if you have 30 or more items in your inventory and die in a vehicle.
To understand better, we recorded this video for you.
https://www.youtube.com/watch?v=eI2kkm1jmYg&feature=youtu.be

PS.: The test was made on a full fresh wiped server which doesn't using any plugins or workshop items.

**Comment by SDGNelson** [comment]
Having never been able to replicate this before I was really curious how it could be related to items. After giving it a test I got lucky replicating it on my client, and it seems the problem is actually if you exit or die in a vehicle between the start and end of the input packet preparation step (because the vehicle is null at the end). I patched this for the next update and wasn't able to replicate it again after crashing another 10 jets.
