### ISSUE TITLE
BattleEye issue.

### ISSUE THREAD

**Issue by Lion4K** [SmartlyDressedGames/Unturned-3.x-Community#4083]
![image-2.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/10391955/b0aafc9c-170f-4e4c-a143-95d53557cfb7)

Says it can't load a driver (like what? What driver? I need a driver for a hardware, no?)

![image-1.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/10391955/5fb3620a-e917-42b2-935c-37bca4fe9a32)

Then Windows itself says this, that this alleged "driver" cannot be loaded because my security is too high (heck yeah it's high), that if I want it loaded then I need to lower my security, again, WTF?

![Screenshot_20230826-141602-008.png](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/10391955/22b32a39-76c0-43ea-875c-b70901c6ca05)

English translation of the image above.

**Comment by SDGNelson** [comment]
Sorry! Somehow I didn't see this until it just got pushed up into the first page of issues. It's been three months since then (oof) so I imagine you found the solution in the meantime, but for anyone who comes across this post in the future: Quoting from the BattlEye FAQ:

When launching the game I get a “Failed to initialize BattlEye Service: Driver Load Error (1275).” error and Windows displays a popup reporting that BEDaisy.sys cannot be loaded on this device due to a security feature called “Hardware-enforced Stack Protection”.

Recently Microsoft has started to ask Windows 11 users to enable this security feature and if they do so it will cause the BE driver to be unable to load. Due to the complexities involved in security software unfortunately many kernel-level anti-cheats, including BE, are not compatible with this feature yet. While we are working on finding a solution and are also in contact with Microsoft regarding this issue, unfortunately there is no easy or immediate fix for it.

Update: Recently we have fixed this incompatibility, however, currently the latest Windows 11 is still blocking any version of our driver whenever this feature is enabled. We are currently waiting for Microsoft to release a Windows update to unblock the latest versions of our driver to solve this.

Therefore, for the time being, users will have to revert enabling this security feature using one of the following ways. Please note that by doing so you will not lower the security of your device or expose it to greater risks compared to previously, as this is a new security feature that wasn’t enabled on devices before.

- Click the “Disable” button in the Windows popup and reboot your system.
- Open the Start menu and enter “Core isolation” in the search bar to open the related Windows Defender settings. In the “Windows Security” window switch the option called “Kernel-mode Hardware-enforced Stack Protection” to “Off”, then reboot your system.

Afterwards you should be able to play BE-protected games again.

**Comment by Lion4K** [comment]
Yeah, since then I've reinstalled Windows 11 and that issue didn't happen again ever since.
Perhaps the newer build of Windows I've installed didn't had this or something, idk.
But thanks for replying.
