### ISSUE TITLE
The server crashes after few hours or few days of operation

### ISSUE THREAD

**Issue by TespyQQ** [SmartlyDressedGames/Unturned-3.x-Community#4098]
No errors in the logs before the crash. The server just shuts down. At one point, I managed to log on to the machine at the moment when the server crashed and take a screenshot of the console. Photo from below

I also attach a file dump

Crashes occur only on the most populated server out of 6. Can you help?

![65d7DtrVMY8](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/144448533/ef3ba0d5-c1af-4b62-b0cb-3e1c16ef8207)
[crash.zip](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/12559076/crash.zip)

**Comment by SDGNelson** [comment]
Sorry about the crash. Here is the call stack:
>	UnityPlayer.dll!JobQueue::ScheduleDependencies(JobGroupID & depend, JobInfo * first, JobInfo * last, bool zeroJobWorkersMode) Line 352	C++
 	UnityPlayer.dll!JobQueue::ScheduleJobMultipleDependencies(void(*)(void *) func, void * userData, JobGroupID * dependencies, int dependenciesCount, MemLabelId dependenciesAllocator) Line 1520	C++
 	UnityPlayer.dll!SyncFences(JobFence * fences, unsigned __int64 fenceCount) Line 51	C++
 	UnityPlayer.dll!TransformChangeDispatch::GetAndClearChangedAsBatchedJobs_Internal(unsigned __int64 systemMask, void(*)(void *, unsigned int, const TransformAccessReadOnly *, const unsigned __int64 *, unsigned int) batchJobFunc, void * userData, profiling::Marker * profiler) Line 201	C++
 	[Inline Frame] UnityPlayer.dll!TransformChangeDispatch::GetAndClearChangedAsBatchedJobs(unsigned __int64) Line 130	C++
 	UnityPlayer.dll!TransformChangeDispatch::CheckAndClearChangedForMultipleSystems(unsigned __int64 systemMask, profiling::Marker * profiler) Line 216	C++
 	[Inline Frame] UnityPlayer.dll!PhysicsManager::ClearTransformChanges() Line 1805	C++
 	UnityPlayer.dll!PhysicsManager::Simulate(int sceneHandle, float dt) Line 938	C++
 	[Inline Frame] UnityPlayer.dll!PhysicsManager::FixedUpdate() Line 724	C++
 	UnityPlayer.dll!`PhysicsManager::InitializeClass'::`2'::FixedUpdatePhysicsFixedUpdateRegistrator::Forward() Line 434	C++
 	UnityPlayer.dll!ExecutePlayerLoop(NativePlayerLoopSystem * system) Line 384	C++
 	UnityPlayer.dll!ExecutePlayerLoop(NativePlayerLoopSystem * system) Line 408	C++
 	UnityPlayer.dll!PlayerLoop() Line 514	C++
 	UnityPlayer.dll!PerformMainLoop() Line 324	C++
 	UnityPlayer.dll!MainMessageLoop() Line 1206	C++
 	UnityPlayer.dll!UnityMainImpl(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, wchar_t * szCmdLine, int nCmdShow) Line 1707	C++
 	UnityPlayer.dll!UnityMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, wchar_t * szCmdLine, int nCmdShow) Line 1762	C++

Considering it's in the Unity job system I think it's likely out our control and out of plugins' control. The next update is on Unity 2021 LTS, so it might have been fixed in the changes between engine versions. Sorry not to have a more useful answer. 😞

**Comment by GazziFX** [comment]
I've been waiting preview of 2021 for months
