### ISSUE TITLE
Preview branch update 2023-10-09

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#4116]
It's been a while! The preview branch is now updated with quite a few fixes and some QoL improvements.

The pending changelog is posted here: https://support.smartlydressedgames.com/hc/en-us/articles/12462494977172

If you check out the new version and run into any issues, please let me know! 🙂

**Comment by DanielWillett** [comment]
New update looking great so far... any chance you could revert this change though while the update isn't final (or use a non-constant)?  I'm working on a multiplayer map editor module and since Dedicator.IsDedicatedServer is a constant value it completely removes the method's contents on the server build so I can't transpile it out either. If not i guess i can copy it over but worth asking.

`Landscape.linkNeighbors`

(client build)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/f0fa12ac-7d71-446c-ada7-390012de97c5)

(server build)
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/77f00ccd-d99b-4088-9d9d-cfa9024b3ae0)

**Comment by GazziFX** [comment]
> I'm working on a multiplayer map editor module and since Dedicator.IsDedicatedServer is a constant value it completely removes the method's contents on the server build so I can't transpile it out either. If not i guess i can copy it over but worth asking.

Isnt it client-side module only?

**Comment by DanielWillett** [comment]
> Isnt it client-side module only?

No it's hosted from a dedicated server.

**Comment by SDGNelson** [comment]
@DanielWillett why does the server need it? IIRC it's removed there in part because it's unnecessary and in part because of a Unity warning/error when updating that in headless builds.

**Comment by DanielWillett** [comment]
Ok, if it causes warnings I can copy it over manually. Thanks
