### ISSUE TITLE
Current Rocket been compile with highest version of NET Framework

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4154]
Many plugins use net framework 4.6.1 and 4.7.2
And if you not change the plugin framework version to 4.8 you can't compile it.

If it's not so hard please recompile it with 4.5-4.6 version of net framework

**Comment by sunnamed434** [comment]
I agree. I don't understand why we use 4.8 version in RocketMod when most of the plugins and OpenMod use 461 and netstandard2.1/2.0 (For Unturned 2.0), there are no reasons that require us to use higher than 461 version in Unturned right now, only higher NuGet Packages/Libraries versions but we can't use it while most of plugins use outdated and sometimes deprecated libraries, such as Microsoft.* 3.1.32, etc

But I guess we will gonna need to move on 4.8 and major versions of packages to fix most of the problems, yeah probably most of us don't want to do that (due to most of the plugins will die), but in the meantime anyway we will gonna need to do that, just a question of time

If we move on 4.8 then everyone need to do that, make a global post for everyone, and perhaps make a docs post which Libraries is should be used as a gold standard, for example, OpenMod as a example of stable packages can be used

**Comment by Trojaner** [comment]
> And if you not change the plugin framework version to 4.8 you can't compile it.
... and what exactly prevents you from upgrading to .NET Framework 4.8?

>  OpenMod use 461 and netstandard2.1/2.0 (For Unturned netstandard 2.0)
OpenMod uses .NET Standard 2.1 for Unturned

I'm not 100% sure but eExisting plugins shouldn't break with an upgrade to .NET Framework 4.8

**Comment by QERT2002** [comment]
> > And if you not change the plugin framework version to 4.8 you can't compile it.
> 
> ... and what exactly prevents you from upgrading to .NET Framework 4.8?
> 
> > OpenMod use 461 and netstandard2.1/2.0 (For Unturned netstandard 2.0)
> 
> OpenMod uses .NET Standard 2.1 for Unturned
> 
> I'm not 100% sure but existing plugins shouldn't break with an upgrade to .NET Framework 4.8

More than 200 my plugins use old framework and with update source code i need to upgrade every plugin to net 4.8 it's not so comfortable, but your right: aldready compiled plugins working normally.
