### ISSUE TITLE
Continuation of server issue. Cannot connect via direct connection, can connect via LAN.

### ISSUE THREAD

**Issue by Axodouble** [SmartlyDressedGames/Unturned-3.x-Community#4169]
A day or so ago I had created an issue about this same issue.

The main issue of the server being an older version in a direct connection has been fixed, however if I try joining after the bugfix being released the server still will not let me join and still lacks some information.

Ref #4167, still same port forwarding settings.

Server still does not show all information; 
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/63e75d5d-f729-4770-8305-e7382cde8fc5)

And does not show the settings or the workshop information, now kicks me for the following:
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/7b8a4a68-1134-4292-b6c9-072a1e1ab3d6)

Here is what the server looks like in the LAN tab.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/53979495/72b1ef86-da8a-475c-abee-ad845ee5e343)

**Comment by ItsRodrigoAl** [comment]
some similar is happening to me with my internet servers. they won't show the lobby, config, links, plugins, nothing.

I have no idea how it is working right now with workshop because I don't use them, but you can't join because it is not showing it on the lobby, which means the server will request you to have it but won't make it you download it and somehow won't have a way to check if you have the required workshop (time ago I had a lobby modifier plugin for a modded server and I tried to hide the workshop, and even if you have it the server won't let you join it , is basically happening the same)

**Comment by sunnamed434** [comment]
Sometimes it happens with my server when I enter it too early (earlier that level is loaded), after 5-10s problem is gone

**Comment by Axodouble** [comment]
> Sometimes it happens with my server when I enter it too early (earlier that level is loaded), after 5-10s problem is gone

That is not the issue here, as this happens regardless of how long the server has been online.

**Comment by SDGNelson** [comment]
Regarding the workshop kick:

If the game does not receive any "rules" response from the server then the workshop file list cannot be shown on the lobby screen. In that case, the client will not disconnect for workshop files mismatch. If the rules data has been received then it will disconnect if the workshop files do not match. Since at least some of the rules are coming through (the description) it thinks the server is not advertising the used workshop files.

For the meantime I'd recommend just joining directly by the LAN address.

At some point I would like to replace some of the dependency on the Steam server advertisement because that's the main IPv4 dependency before you could join servers by IPv6 address.
