### ISSUE TITLE
Bugged random spots and spots you cant get out or get stuck 

### ISSUE THREAD

**Issue by Kubusiek3** [SmartlyDressedGames/Unturned-3.x-Community#4195]
![p1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/22146a71-f254-4338-ae74-38d2932338dc)
![p2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/fedfacd4-c0eb-436b-93f3-58d54dd09a5f)
![y1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/aa63f8c6-1634-4d2a-97cf-229e1e85b9bb)
![y2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/9bb79d18-cfd0-472d-bea2-4ef2f2b0f384)

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/a5b14086-269b-4a1b-97b0-2ceafe296504

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/eb32ae48-37b2-47bd-84ba-ec80f08158a2

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/3244902f-10d0-47ec-928a-7845bb07603d

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/141286023/5474e9fd-b10a-422e-b60f-bf03403d3b8f

Can i get white beret or faster updates to help solve bugs please?  https://steamcommunity.com/profiles/76561198222086980/ for all these bugs and glitches

**Comment by rube200** [comment]
White hat are for security issues

**Comment by ItsRodrigoAl** [comment]
Hey @SDGNelson can you just ban this guy from here? He's just reporting "obvious" things and mechanics from the game just trying so hard to get any beret, he is even claiming to get "faster updates" (lol?)

**Comment by Kubusiek3** [comment]
> Hey @SDGNelson can you just ban this guy from here? He's just reporting "obvious" things and mechanics from the game just trying so hard to get any beret, he is even claiming to get "faster updates" (lol?)

i have purple one like 2 years

**Comment by SDGNelson** [comment]
I haven't looked through them all yet, and I'm sure you're well intentioned, but as ItsRodrigoAl pointed out these seem to be minor/known issues posted with the intent of getting the white beret. Please don't spam the issues tracker as some people may choose to receive notifications for every new issue.

The White Hat (white beret) refers to [white hat hackers](https://en.wikipedia.org/wiki/White_hat_(computer_security)). These hackers find an exploit, but rather than abusing it, they report the bug to the developer — specifically bugs in the code. For example, they could find a way for a custom cheat client to crash the server and report so that it can be fixed. Reporting in-game bugs like an out-of-map exploit is more so what the [Debugger's Beret](http://support.smartlydressedgames.com/hc/en-us/articles/12266602743188) was intended for, but that became a problem of its own.

While all bug reports are appreciated, I'd recommend against specifically looking to find problems. I'd prefer that you focus on having fun playing the game! I'm happy to fix genuine issues that arise through normal gameplay, but I don't think there will ever be a shortage of minor problems for players that try to find these problems.

**Comment by SDGNelson** [comment]
For the next update I've slightly moved the crate in the PEI hangar, but as far as I can tell the one in the Yukon is possible to walk out from beside there. As for some of the glitching into object issues, unfortunately they all fall into this category for now: https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds
