### ISSUE TITLE
FPS limitation

### ISSUE THREAD

**Issue by nikiternak5269** [SmartlyDressedGames/Unturned-3.x-Community#4202]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123768100/e7e770ec-fa29-4c2a-91d7-2d46c4e2538c)
Greetings, is it possible to make an fps limiter from 30 in the next update, you will ask why I am asking about this?
I answer: Because players deliberately lower their FPS to view other people's houses and rooms that have objects and barricades from other people. This is done by logging in to the server, or by teleporting to the player. This interferes with the gameplay as a whole. Because anyone who does this can safely find out where your boxes are
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/123768100/850e7706-6e6b-4b54-8739-766113795752)

**Comment by ItsRodrigoAl** [comment]
Its something nelson needs to fix about giving priority to loading first structures instead of barricades (lets say is just an old code from young nelson XD). If I'm not wrong he's planning to make an overall recode of how builds are loaded player-side, like to have even less performance impact if there are a lot of builds loaded at same time, or this issue about being able to build barricades inside of structure, and maybe that's why he have not fixed this yet, so instead of fixing this would be better to recode it all

So yeah making a "minimum FPS limit" is not the correct way to handle this, but this is a serious issue too. Time ago I even asked to a dev to make a plugin to ban players if they were trying to reconnect a lot of times in short time x.x

**Comment by DanielWillett** [comment]
Perhaps buildable loading could happen instantly after a teleport but happen over frames for normal movement? I think the frame drop would be quite a bit less noticeable during a teleport.

**Comment by SDGNelson** [comment]
Unfortunately, as ItsRodrigoAl mentioned, this is a long-term issue: #3011
Whenever it gets prioritized, the approach I will likely take is for the server to prioritize streaming the relevant structures to clients, and afterwards to stream the smaller barricades.
