### ISSUE TITLE
Structure manager optimisation

### ISSUE THREAD

**Issue by archie426** [SmartlyDressedGames/Unturned-3.x-Community#4209]
RegionList blocks for 2.6seconds when loading into a server. This is because it instantiates 512 * 512 lists (a two dimensional array) TWICE for `grid`. Creating 512 lists would be fine, however doing this 524,288 times when loading allocates tons of memory, repeats many instructions and unnecessarily so. A recommendation I could give instead is instatiating the lists on a needs basis, when `RegionList::Add`, `RegionList::RemoveItemFast` or `RegionList::GetList` are used. Whilst this conceivably could use the same amount of processing power over time, it is unlikely to and instantiating one list every now and then is far faster than instantiating 524,288 all at once, especially in such a critical context. I believe that most of the methods are only used when linking structures, so some regions may be instantiated on load but certainly not all 524,288 of them lol.

Either way, the point of this issue is to draw your attention to this clear bottleneck. My solution is probably not the fastest, but it's certainly a quick fix for a glaring problem.

**Comment by ItsRodrigoAl** [comment]
The answer you're looking for this is probably here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3011 and here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4202. However ideas about how these could be fixed/reduced are well received 🐱

**Comment by DanielWillett** [comment]
This could safely be extended to some of the legacy 'region lists' in other manager classes by using a single 'empty list' instance for everything, then checking if `list.Count == 0` and making a new list for the region when adding if it does, although there is some saving grace here since lists with a capacity of zero all use the same empty array instance.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/372d11e6-79d5-42ff-88fa-d4368d355528)

With that said across all the different region lists it is quite a lot of memory.
Just counting the fields in List<> it totals to 22 bytes on a 64-bit machine, and with a 512x512 array that takes up roughly 11.5 MB. This doesn't count overhead but if we round up to 32 bytes it takes up almost 16.8 MB. (times two since there's two RegionLists in StructureManager).

While I'm at it, world regions (64x64) total about 32 x 4096 = 132 KB which isn't as bad but could definitely be better.

Note that these calculations are taking into account using a singleton instance of the empty list like the default List does.

**Comment by archie426** [comment]
@ItsRodrigoAl Although related to structure lag, the issues you mentioned don't seem to be related to this specific problem: the almost 3seconds of blocking takes place when one loads into the server because of the two region lists (and seemingly ones which @DanielWillett mentioned) being allocated/instantiated all at once). This is a specific easy fix issue which does not need an answer per se.

**Comment by SDGNelson** [comment]
I didn't yet check the performance of that allocation, but it does seem reasonable to change this. I think the region size *was* equivalent to the older ones and then changed to be smaller without thinking about the number of allocations. I think what I'll do is add a pool of lists so it can create them in batches. i.e., rather than allocating one list each time it's needed it can allocate ~1000 as-needed.

**Comment by archie426** [comment]
> I didn't yet check the performance of that allocation, but it does seem reasonable to change this. I think the region size _was_ equivalent to the older ones and then changed to be smaller without thinking about the number of allocations. I think what I'll do is add a pool of lists so it can create them in batches. i.e., rather than allocating one list each time it's needed it can allocate ~1000 as-needed.

Admittedly this time was produced on a subaverage 3.0GHz, 4 core processor, so realistically for those with PCs with high CPU power it shouldn't be as bad. Nevertheless, out of all of the processing time it to load the game (full vanilla assets) and join a server, 160 seconds, it took up 0.7% which is pretty significant. This obviously also doesn't include the memory issues caused by this as mentioned by Daniel. 
![aaaa](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/13406648/732f9962-05e2-407d-aaf1-a89bb2e467d6)

The pool idea sounds good and in line with the design of similar Unturned entity-management systems.
