### ISSUE TITLE
Steam groups surpass the in-game group limit

### ISSUE THREAD

**Issue by Senior-S** [SmartlyDressedGames/Unturned-3.x-Community#4221]
As the title says, steam groups can surpass the `Max_Group_Members` config option

I know that I can set `Allow_Static_Groups` to false so players need to use in-game groups, but I still want to let players use steam groups.

A possible solution could be a kick, notifying the player that they have exceeded the maximum group members, and if they join again, they will be removed from the group (similar to pressing 'leave' in the menu).

This way, players don't need to manually leave their Steam group, but the maximum group members limit is still respected.

**Comment by SnSKarma** [comment]
This would very greatly improve the ease of moderation of Steam group sizes. They being allowed to be limitless allows for pretty gnarly zerging incidents and an easy bypass of the established player group limits. 

I personally would however completely remove the ability for more members of the group to join if they have the Steam group selected as their group in the menu, for it to be not as easy as simply creating an in-game group soon after you join and instead having to change or unselect the group in the menu.

**Comment by ItsRodrigoAl** [comment]
This plugin exist for that https://github.com/ShimmyMySherbet/SteamGroupLimiter

However this should be by the default and not by a plugin. The solution of the plugin is also good, it just kicks you from the group if you try to join the server and the group is already full

**Comment by SDGNelson** [comment]
It looks like the way @ItsRodrigoAl that plugin works is only by limiting the number of players in the same Steam group on the server at a time, whereas the game's group member limit option limits the total number of members in the group. Unfortunately as far as I'm aware there isn't a good way to check the total number of players in a Steam clan/group which is why there isn't an equivalent option built-in.
