### ISSUE TITLE
[Feature request] New RPC - EffectManager.sendUIEffectImageItem

### ISSUE THREAD

**Issue by fsocoptt** [SmartlyDressedGames/Unturned-3.x-Community#4228]
@SDGNelson, code for you to add into EffectManager class, should work just fine.
I know that a lot of people still does need this for a long time.
Let me know if you want me to change or add something.

Used sendUIEffectImageURL as a reference.
```CSharp
public static void sendUIEffectImageItem(short key, ITransportConnection transportConnection, bool reliable, string childName, ushort assetId, byte[] state)
{
	ThreadUtil.assertIsGameThread();
	ENetReliability enetReliability = (reliable ? ENetReliability.Reliable : ENetReliability.Unreliable);
	EffectManager.SendUIEffectImageItem.Invoke(enetReliability, transportConnection, key, childName, assetId, state);
}
```
```CSharp
private static readonly ClientStaticMethod<short, string, ushort, byte[]> SendUIEffectImageItem = ClientStaticMethod<short, string, ushort, byte[]>.Get(EffectManager.ReceiveUIEffectImageItem);
```
```CSharp
[SteamCall(ESteamCallValidation.ONLY_FROM_SERVER, legacyName = "tellUIEffectImageItem")]
public static void ReceiveUIEffectImageItem(short key, string childName, ushort id, byte[] state)
{
	GameObject gameObject;
	if (!EffectManager.indexedUIEffects.TryGetValue(key, out gameObject))
	{
		UnturnedLog.info("tellUIEffectImageItem: key {0} not found (childName {1} id {2})", new object[] { key, childName, id });
		return;
	}
	if (gameObject == null)
	{
		UnturnedLog.info("tellUIEffectImageItem: key {0} was destroyed (childName {1} id {2})", new object[] { key, childName, id });
		return;
	}
	Transform transform = gameObject.transform.FindChildRecursive(childName);
	if (transform == null)
	{
		UnturnedLog.info("tellUIEffectImageItem: childName '{0}' not found (key {1} id {2})", new object[] { childName, key, id });
		return;
	}
	Image component = transform.GetComponent<Image>();
	if (component == null)
	{
		UnturnedLog.info("tellUIEffectImageItem: '{0}' does not have an image component (key {1} id {2})", new object[] { childName, key, id });
		return;
	}
	ItemTool.getIcon(id, 100, state, texture => { 
		// Copied from WebImage class.
		component.sprite = Sprite.Create(texture, new Rect(0f, 0f, (float)texture.width, (float)texture.height), new Vector2(0.5f, 0.5f), 100f);
	});
}
```

**Comment by surv0013** [comment]
This was already suggested, but unfortunately it was never added, although such a method is indeed very necessary. By the way, in addition to the ID, metadata is also needed so that the attachments on the weapon can be seen.

**Comment by DanielWillett** [comment]
> This was already suggested

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/3010


Would love this feature ngl (also please add item state and skin).

I know you're hesitant to touch UI until Glazier comes to plugins but small stuff like this really goes a long way, even if it's temporary.

If you want it to be more 'future-proof' take an `Item` instance and skin ID instead of taking state directly so it's easier to change out the byte array state in the future.

**Comment by SDGNelson** [comment]
Sorry but this isn't currently planned and the issues tracker isn't intended for feature requests.

**Comment by DanielWillett** [comment]
He has some points but I think the general complaint with UI stuff is that if you're not going to consider adding any new UI features, then a prioritization of the Glazier implementation for plugins would be nice. Realistically most of the UI stuff we request wouldn't take more than 15 minutes to add and test, but if it's something like it straying too far from vanilla, doing the glazier implementation would definitely bring things back to the vanilla style.
(Also brought up here https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions/3745, although I feel like React is a bit overboard).

Currently, the control we have over UI consists of 3 methods and 2 events... which is not great for doing complicated stuff.
I'm not sure how much testing you've done with plugins/making modded UIs but I think everyone would agree it's by far the most unenjoyable part about Unturned development.

I can't imagine a new UI system would actually be too difficult, just being able to send a set of properties, values, and event hooks for each sleek element. Since I imagine you don't really do much with plugin UI we mostly need the following features:
* Being able to send a default UI all at once.
* Being able to create and delete elements on the fly (like for lists).
* Being able to call pretty much any method and set all properties on the sleek interface of the element.
  * Maybe you could just create new a new `Remote` IGlazier set.
  * Values will stay updated by hooking to the event handlers (like `OnTextSubmitted`) of each element, which plugin devs can also hook to.
* Being able to use any of the sleek wrappers that already exist.


This is kind of how I imagined it would end up looking like based on the vanilla UIs.
```cs
public class KitUI : ReplicatedSleekWindow
{
   private ISleekLabel testLabel;
   private ISleekButton testButton;

   // the constructor would build the initial UI and be sent all at once for performance purposes.
   public KitUI() : base()
   {
      this.Container.PositionOffset_X = 10f;
      this.Container.PositionOffset_Y = 10f;
      this.Container.SizeOffset_X = -20f;
      this.Container.SizeOffset_Y = -20f;
      this.Container.SizeScale_X = 1f;
      this.Container.SizeScale_Y = 1f;

      // each UI would have an IGlazier instance linked to it's object instance, which would also be given a NetId, along with each element.
      testLabel = this.Glazier.CreateLabel();
      testLabel.whatever = whatever;

      this.Container.AddChild(testLabel);

      testButton = this.Glazier.CreateButton();
      testButton.whatever = whatever;

      testButton.OnClicked += OnButtonClicked;

      this.Container.AddChild(testButton);
   }

   private void OnButtonClicked(ISleekElement button)
   {
       // property edits should be flushed every frame so multiple simultaneous edits don't cause extra traffic.
       button.PositionOffset_X += 3f;
       button.PositionOffset_Y += 3f;
   }
}

// later

KitUI uiInstance = new KitUI();

EffectManager.CreateSleekUI(Provider.GatherRemoteConnections(), uiInstance);
```

Would love to know your thoughts and how you plan to do it.

Also, do you have some tool for making Vanilla UIs from Unity or do you just keep changing it until it looks good?
