### ISSUE TITLE
Expanding the map size of the game

### ISSUE THREAD

**Issue by Blackwolf0726** [SmartlyDressedGames/Unturned-3.x-Community#4232]
The currently supported map sizes for Unturned are small, medium, and large.

Also, there is an unofficial map of insane size. Are there any plans to officially support maps of this size?
If you're not going to support insanely sized maps, I'd like to know why.

**Comment by DanielWillett** [comment]
Just use terrain tiles and cartography volumes to make the map bigger. Anything up to insane size (8x8 with a 1 tile wide border) is 'supported'. Note that performance is not great and rendering charts takes like 5 minutes which is probably why it was removed.

If you want the map to actually be 'insane' you have to use a hex editor to set the 10th byte to `0x04` in Level.dat.

**Comment by WW-TC** [comment]
you can also just disable the Borders in the Config.json and set ur own using the player volume. Like Arid does.

**Comment by SDGNelson** [comment]
Thanks @DanielWillett and @WW-TC for your helpful answers. As they mentioned, there are ways to expand your map, but only up to a certain limit. Even at those sizes you'll start experiencing floating point precision issues. Unreal and Godot both support 64-bit float coordinates now, so in the longer term I think the larger map sizes might be resolved for us simply by brute force rather than origin shifting.
