### ISSUE TITLE
RuntimeGizmos not captured in screenshots.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4235]
I recently added a /debugregion command to one of my modules so that I could view the bounds of each region. I wanted to share this progress, but unfortunately it wasn't captured in my screenshot.

Looking back at several of my past screenshots, most gizmos are not visible in screenshots for whatever reason.

![2023-07-30_21-03-12](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/67397422/ce06b8d4-f489-463a-9d88-04985d9d4fe5)

**Comment by SDGNelson** [comment]
Unturned uses `ScreenCapture.CaptureScreenshotAsTexture`, so unfortunately if those aren't showing up it would likely require a fair bit of effort to properly handle them. If you add the `-FallbackGizmos` command-line option they should become visible because those use regular Line Renderers. Maybe that mode should become the default. 🤔
