### ISSUE TITLE
Masterbundle not refreshing assets after doing /reload

### ISSUE THREAD

**Issue by realtrollman2319** [SmartlyDressedGames/Unturned-3.x-Community#4238]
# Problem:
Masterbundle dosen't reload its actual assets even id it's replaced, only the .dat files do.

# How to reproduce:
1. Make a masterbundle, apply some changes, put it at the `Sandbox` folder.
2. Reload the masterbundle using `/reload Sandbox/MyBundle`.
3. You can see that the masterbundle stayed the same before you added some changes.

Reloading all assets (PageUp key) currently works, but I don't want to reload every single masterbundle when I'm just working on one. Maybe you could fix the `/reload` command and unload and load the targeted bundle?

**Comment by SDGNelson** [comment]
Off the top of my head it's likely because it has the same name and there are a variety of troubles with asset bundles with duplicate names. Two options for the meantime could be to use individual asset bundles for content you're actively working on, or to rename the masterbundle between reloads. When you do a full reload it clears all loaded asset bundles.
