### ISSUE TITLE
Change method of reload sound pitch randomization

### ISSUE THREAD

**Issue by DerpyHoowes** [SmartlyDressedGames/Unturned-3.x-Community#4249]
I dont know all that much about sound design so I dont know the proper terminology, but from what I noticed the sound pitch randomization in Unturned works by simply shrinking or stretching audio file, resulting in pitch change, instead of just changing the file's pitch directly, like you can do in Audacity for example. But it leads to very prominent desync of actions and sounds when it comes to some complex animations of player armature or objects. Especially for complicated reload animations. I tried adding Static flag to item's asset, but still it gets affected (and I assume it works only for effects or something). Please either change the method used to randomize sounds pitch, or make Static flag work on all sounds that can be affected by this method, It was good enough for simplistic vanilla animations, but we've obviously went beyond that in modding and curated content already.

Here's in example of what I described. While the animation start has action and sound matching most of the time, the longer animation gets, the bigger desync there will be towards its end, as shown here with the slide cover closing. Sometimes it matches the action completely, sometimes its way too late.

https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/59206749/ec53a619-3193-474a-972c-9e55d9d1e49c

**Comment by SDGNelson** [comment]
As far as I'm aware, all the big game engines approximate pitch changes by adjusting how fast the audio is played because changing pitch without changing speed is computationally expensive.

Nowadays I would play individual sounds from the animation rather than one sound for the entire length of the animation. This approach handles game speed changes better, too.

I may as well turn off the pitch randomization for the reload and hammer sounds because they do tend to get out of sync.
