### ISSUE TITLE
Barricades appear faster than structures.[Very old bug]

### ISSUE THREAD

**Issue by QERT2002** [SmartlyDressedGames/Unturned-3.x-Community#4255]
There has long been a bug with the fact that you can view other people's bases due to the faster appearance of structures.
I suggest checking the full loading of the structures and loading the barricades after that, this will solve the main problem of “base clearance”.

You can send a packet from the client stating that all structures in the region are loaded and then send the region with barricades from server.
This is not a complete solution to this problem, but I think for most it will be enough.😊

**Comment by SDGNelson** [comment]
This became an issue after barricade and structures received some improvements to time-slice instantiation rather than creating everything in a single frame. More than just barricades, there's also the problem of seeing players inside bases outside the relevant distance. As part of #3011 I intend to load structures at a greater distance than barricades, and prioritize structures ahead of barricades.
