### ISSUE TITLE
Modifing Workshop Map's Config.json rejects players with "This server is using a modified version of the map"

### ISSUE THREAD

**Issue by staridiot** [SmartlyDressedGames/Unturned-3.x-Community#4272]
Some maps contain a Config.json file which overrides setting set in the server's Config.json. I wish to change these settings, but when I do so the server begins rejecting players stating the server is running a modified version of the map.

**Comment by SDGNelson** [comment]
This is intentional, albeit usually to prevent clients from modifying the level rather than the other way around. If the server config has been changed from the default then the level overrides do not apply. One shortcoming of this, however, is for the boolean (true/false) options which I should really add some way to specify the server wants to keep.

The server config system in the first place is not ideal and continued expanding past the point it needs a rework. At some point I intend to get rid of the separate difficulty sections and probably make it so you only need to specify the key/values you want. Then this won't be an issue anymore.
