### ISSUE TITLE
I keep getting a new error message

### ISSUE THREAD

**Issue by Lmgleader** [SmartlyDressedGames/Unturned-3.x-Community#4279]
Client and server disagree on asset "PEI Stone 00" configuration. (File: "PEI_Stone_00_Material" ID: 50acf0bddd844f93addd0097f7d95d95)
Usually this means the files are different versions in which case updating the client and server might fix it.
Alternatively the file may have been corrupted, locally modified, or modified on the server.
Client hash is 25FF4BEEAE84A29B876D33C726AB87B9AB24BBE3, whereas server hash is 84262219BA130A0B0C56B761CCF05E57A2D73ED4.
Client and server agree this asset is from Vanilla Built-in Assets.

or i keep getting

Client and server disagree on asset "Yukon Dirt 00" configuration. (File: "Yukon_Dirt_00_Material" ID: e52b20e26b7c47c89aa5a350938f8f42)
Usually this means the files are different versions in which case updating the client and server might fix it.
Alternatively the file may have been corrupted, locally modified, or modified on the server.
Client hash is E81673F49D71F48A4D12C8D8AD17CA13E97C7DF1, whereas server hash is F52151B60312E195C10699854706AC8DE8AD84A0.
Client and server agree this asset is from Vanilla Built-in Assets.

**Comment by SDGNelson** [comment]
Sorry about this! I've been investigating it this afternoon. This issue is quite odd, especially since it's different for players with very similar setups. The asset hash for my files matches the one reported by the server in your log, so I wonder why the hash calculated by your client is different.

There was a change to how hashes are calculated in this update: It takes into consideration the asset's path relative to the asset bundle to prevent some exploits. If you are willing, I would be very curious to know the file path of the PEI Stone 00 file on your PC so that I can test whether it would somehow be getting a different result for the hash:
 
1. Right-click Unturned in your Steam Library
2. Select Properties...
3. Hover over Manage
4. Click Browse local files
5. Search for "PEI_Stone_00_Material.asset"
6. Hold shift and right-click the PEI_Stone_00_Material.asset file
7. Click "Copy as path"
8. Paste the path into your comment. For example, on my PC it is: "D:\Steam\steamapps\common\Unturned\Bundles\Assets\Landscapes\Materials\PEI\PEI_Stone_00_Material.asset"

**Comment by Pootwich** [comment]
Changing my Windows Display Language from Turkish -> English resolved the issue. I can also confirm that changing it to Turkish brings back the issue.

Further investigation shows that when the language is set to Turkish, the player can only join Turkish servers, and when it is set to English, they can join any server except for Turkish ones.

**Comment by SDGNelson** [comment]
Thanks @Pootwich, great find! It looks like this must all have been because the path included in the hash used ToLower rather than ToLowerInvariant. D:

I was on completely the wrong track. Thanks to your report it should be an easy fix today!

**Comment by SDGNelson** [comment]
This should be fixed in the .2 update now!
