### ISSUE TITLE
Precision charge not doing damage from sides to a floor.

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4286]
Hello, an user in UO Discord server reported that the precision charge does not damage floors from the side. Watch this [video](https://cdn.discordapp.com/attachments/324229387295653889/1188449358350385172/1.mp4?ex=659a90b7&is=65881bb7&hm=dcffbd61c8ba76771e0ead4658b006b04e65cd49b7ebe6a010817172b8871781&) recorded by kirichau.

Credit to "kirichau" for this bug report.

**Comment by SDGNelson** [comment]
This is due to the unfortunate way explosions work. In ye olden day to avoid physics query allocations the explosions manually gather nearby entities based on their pivot point and then use the nearest position to calculate damage. This doesn't work if the pivot point is outside the range of the explosive - the case with the charge on the side of the floor. I would like to update explosions to use Physics.OverlapSphereNonAlloc at some point.
