### ISSUE TITLE
Server Code on dedicated servers

### ISSUE THREAD

**Issue by kulkaGM** [SmartlyDressedGames/Unturned-3.x-Community#4292]
Server Code can be usefull in dedicated servers, but if someone has a dedicated server they probably have already port forwaded or have hosting, the feature should not previously have been made for Dedicated but should have been for Unturned client with "host World / Server" feature (that would mean more coding for the game client I know) otherwise there could be ServerCode config option.

Also Dedicated Server Code generated upon server startup should be displayed with less text with only the Server Code, the full text is not needed for people who already have hosted server.

**Comment by SDGNelson** [comment]
Hosting a server within the client would require listen server support which the current version isn't really built with in mind, unfortunately. Although yes that would certainly be ideal, having server codes for hosts who might not otherwise take the step of port forwarding (or even be able to) is at least moving in a more accessible direction.
