### ISSUE TITLE
Communication between server and client via module

### ISSUE THREAD

**Issue by Maximjetfs1305** [SmartlyDressedGames/Unturned-3.x-Community#4297]
Hello, I had this idea to make a module for client and server. I need to be able to call some methods from my module on the client side.
I understand that this can be organized with the help of "SteamChannel". but it didn't work out well for me(((.
Perhaps someone has already done this and can share examples of work?) I would be very grateful.

**Comment by GazziFX** [comment]
`SDG.Unturned.NetReflection` class is very flexible, you need to load your module before `.cctor` is called and it will automatically register all your stuff which marked with `NetInvokableGeneratedClass` and `NetInvokableGeneratedMethod`

**Comment by DanielWillett** [comment]
Also see https://github.com/SmartlyDressedGames/Unturned-3.x-Community/discussions/4176

**Comment by Maximjetfs1305** [comment]
> Also see #4176

Hi, watched your code really professionally done) Could you help me with this? As my programming level doesn't allow me to use your code or fully understand how it works. I would be very happy if you could help me to make a module or give me a small example of a module with work between client and server. Because I am just learning to program and it is very difficult for me. I will be glad if you contact me by e-mail hldmcsscs@gmail.com.

**Comment by DanielWillett** [comment]
In that case, maybe try @GazziFX's way. I think @Jdance-Media had success doing it gazzi's way, maybe he'd be willing to show how he did it. The only reason I went with my way instead of just patching is because I already had a lot of that code written beforehand otherwise I would've probably used the ingame system.

And btw it looks like the line number in the link there is a bit out of date now it starts at around [line 131](https://github.com/DanielWillett/DevkitServer/blob/a9645f4c28c3b1c9aefa3e1ef20c902f7b5a516f/Multiplayer/Networking/NetFactory.cs#L131)
