### ISSUE TITLE
Minor: text in menu needs some padding

### ISSUE THREAD

**Issue by TeemoCell** [SmartlyDressedGames/Unturned-3.x-Community#4299]
Same as in https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4261, just with the text.

![Rqe8p0U7u](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/11705513/4ff45ba0-21af-498c-887c-1ec5639133b6)

**Comment by DanielWillett** [comment]
Sort of related, been seeing this in my client log the past few days with one of the currently featured mods even though the mod page itself looks okay at first glance. https://steamcommunity.com/sharedfiles/filedetails/?id=3093069128

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/6079bbb0-3ceb-480d-81de-0b9cc79353e5)

**Comment by SDGNelson** [comment]
Closing as this is the same issue as #4261 (that the vertical layout currently has no option to control content padding)

@DanielWillett it's pretty common for most workshop files to run into that. It's because my hacked together bbcode to rich text conversion is poorly implemented - it expects everything to be formatted a certain way, and doesn't support several features - so the game just expects it to throw an exception otherwise.
