### ISSUE TITLE
Tile_Dither doesn't seem to work for Instanced meshes.

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4302]
If I'm understanding this feature correctly it's supposed to thin foliage out as it gets closer to the tile border but it doesn't really seem to work.

Examples:
Grass Quality Ultra
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/a75d30d5-3ea2-4cba-b6bc-0bf03f7b82d2)

Grass Quality Low
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/79f88b19-86f3-450b-b909-05d1b6b104ad)

(yes that asset has tile dither turned on)

A little less obvious on Washington but if you look from below you can see it more clearly.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/b5f07f52-12af-426d-a390-50be94e4e323)

**Comment by SDGNelson** [comment]
It looks like I (temporarily?) disabled it in April 2022 when reworking some foliage stuff. I don't think it ever looked very good and didn't really improve performance. The better solution would be to fade in the foliage at the far end in the foliage shader rather than across the entire tile - too jarring.
