### ISSUE TITLE
Minor (but very annoying) issue with the object editor and workzone (Global space transform copying)

### ISSUE THREAD

**Issue by DanielWillett** [SmartlyDressedGames/Unturned-3.x-Community#4304]
When you use Ctrl + B / Ctrl + N to copy a transform of one object, the rotation isn't retained in `GLOBAL` space. I assume it's supposed to keep the rotation even in global space? if not it should at least compensate for the 90° rotation all objects have and rotate it accordingly so it's not sideways like below.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/79b5899c-3dd0-4147-b4fd-e482e45ef829)

I think all that needs to be changed is to use
```cs
dragCoordinate == GLOBAL ? selection[0].transform.rotation : handles.GetPivotRotation()
```
in EditorObjects.Update instead of getting it from the handle when in global mode, since in global mode the pivot rotation is set to Quaternion.identity in `calculateHandleOffsets`.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/c1e0bc01-981d-43d3-b10c-573fce2daa4c)

The in-game workzone also has the exact same bug.

**Comment by SDGNelson** [comment]
Hmm that sounds right. Thanks for the report. 🤔

**Comment by SDGNelson** [comment]
I agree the current behavior is bad. I think there are a few options:

1. Copy the first object's rotation, as proposed. I think this could easily be confusing, however, as the transform handle would still be aligned with the global axes.
2. Reset to (-90, 0, 0). I think this could be useful in some cases, and the vast majority of object surely are designed with that (annoying... 😬) default rotation.
3. Copy only the position, not the rotation. i.e., move the pivot to the copied position without affecting rotation.

For the meantime I've made the 3rd change because of all of them I think it might be the most potentially useful and intuitive. Do you think that's reasonable?

**Comment by DanielWillett** [comment]
Yeah that's a good way to do it I think.

iirc the world/local space setting doesn't save on restarts, so that could also help some as usually you have to switch over to copy transform either way.

Could definitely see benefits to the second option too if you wanted to 'reset' an object's rotation or something like that.
