### ISSUE TITLE
The gap between the door and the wall on the floor below the door

### ISSUE THREAD

**Issue by kelllmonakil** [SmartlyDressedGames/Unturned-3.x-Community#4329]
![2image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/157976200/67b5e9d7-a913-4460-ad38-29d518bef32f)
![1image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/157976200/16d56e86-dab0-4a68-8098-70568b7a0dee)
![5image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/157976200/5b8c279f-896a-4b35-8ae3-41148c2769b7)
![4image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/157976200/0df3eefc-5b37-4b02-984d-f20dbc9d7554)
![3image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/157976200/9c4900c6-3a87-4315-8f6a-c0e699eb7ca2)
The gap is not bullet penetration, but does not leave any traces of hits

**Comment by SDGNelson** [comment]
Thanks for the report. I'll double-check the collider size on the door.

**Comment by SDGNelson** [comment]
Ah, what I didn't realize earlier is there is no floor there, just a door on top of a wall. What's the reason for doing this?

**Comment by MoltonMontro** [comment]
> Ah, what I didn't realize earlier is there is no floor there, just a door on top of a wall. What's the reason for doing this?

My assumption is that it's just an example scenario for the bug report, but some possibilities could be:
- Doorway is being used instead of a window to make leaving easier / shooting easier (I know some players dislike using shutters/windows for this).
- This is an airlock leading into another staircase (although I don't think the structure pieces would let you place them like that – I think the door would count as "obstructing" the stairs).
- Door leads to a loot room with an immediate drop instead of a hole/roof (to make entering / accessing loot / walking easier).

**Comment by SDGNelson** [comment]
I adjusted the collider size on the vanilla doors before realizing this was actually intentional: All of the openable vanilla buildables have a bigger collider that completely fills the door slot when closed so that they are airtight. If I recall correctly, this was to help ensure doors of different sizes are plugged and players can't shoot through tiny gaps in the trim. It is confusing though that there's no indication of a hit, so for the next update I've applied physics materials matching the door material so it appears the bullet hit the wood.
