### ISSUE TITLE
Hitmarker still visible when fully immune to damage

### ISSUE THREAD

**Issue by Semidvista** [SmartlyDressedGames/Unturned-3.x-Community#4337]
When the "gun lowcal damage multiplier" and "melee damage multiplier" parameters in config.json are set to 0, the hitmarker is still visible when hit by low caliber weapons and when hit by melee weapons
This is very confusing for players because they see the hitmarker and think that damage is being dealt, but in fact it is not.
I tested this on cars, but I think this applies to all durability parameters in the game.
The solution would be to remove the hitmarker at durability parameters ​​of 0
This problem exists in single and multiplayer
![Screenshot_1367](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/130897671/a790c4f0-4731-4ba1-9559-ed0666c75dd0)

**Comment by SDGNelson** [comment]
Currently, hitmarkers are instigated by the client rather than in response to a notification of damage from the server, and the hit effects are spawned by the server. This is maybe backwards from how others games do it. Even if the client knew all the vanilla damage multipliers plugins could still cancel the damage. Sorry, I think this is a "won't fix" for now.
