### ISSUE TITLE
[Preview Branch] IOBS Update breaks exotic use case

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4345]
I give a more complete description and demonstration in the video linked below, but I'll summarise it, so others can more easily comment on it.

https://youtu.be/O0OtvVAl2ME?si=yqLhtQoWDcuUG6G4 (this has just been uploaded, so the quality isn't going to be great, sorry!)

Essentially: Spyjack found a method to trigger Interactability_Reward from Unity using the IOBS hook. He used it a few times in Tales Of Terror's Jester sections. I use it quite a lot on a project for quest conditions and one-time teleports (as opposed to the volume added a few years ago). This is an exotic use case that was probably never intended for IOBS hook, and I completely understand if this isn't supported in the future. While the IOBS hook can't (and probably shouldn't) be modified continually to support unintended uses, but ideally this functionality would be supported in some way, possibly a new mod hook, would be greatly appreciated.

**Comment by Gamingtoday093** [comment]
This seems to be an actual bug with `ToggleState()` introduced in the preview version. Nelson must've accidentally removed the `!` from `interactable.isUsed`. The reason it doesn't work anymore is because the IOBS doesn't let you update its state to it's current state as you can see [Here](https://github.com/Unturned-Datamining/Unturned-Datamining/blob/linux-client-preview/Assembly-CSharp/SDG.Unturned/InteractableObjectBinaryState.cs#L250). (Which is what `ToggleState()` is trying to do)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/70017362/ee3e0810-ac11-409a-9b16-ba5400c9f9ba)

### *Nelson Please Fix*

**Comment by SDGNelson** [comment]
Thanks @Gamingtoday093! Not sure how I managed to remove that `!` considering the method would have been renamed by F2 and the parameter added was *after* the existing one. 😕

**Comment by Spebby** [comment]
Thanks for taking a look at the code @Gamingtoday093 ❤️

**Comment by SDGNelson** [comment]
Does it seem to be working again in the 3.24.1.0 update? I restored the `!` as a last-minute addition.

**Comment by Gamingtoday093** [comment]
I just checked and it seems to be working again! I should have the same setup as @Spebby so it should be working for him as well.

**Comment by Spebby** [comment]
yep, working again!

**Comment by DrDallas1** [comment]
This doesn't make any sense... isn't this usecase of IOBS (applying interactability rewards to players using IOBS hook) completely broken in multiplayer? How did you manage to use this outside of singleplayer? I originally suggested "Server Listen Host Mode" as a way to combat this, with "OverrideState" bringing multiplayer behavior to singleplayer.

**Comment by Spebby** [comment]
> How did you manage to use this outside of singleplayer?

The server would sometimes apply the rewards. If a player quit and rejoined it would usually give the rewards. Not tested since the update launched so it may be consistent now the IOBS hook behaves consistently in mp and sp.
