### ISSUE TITLE
Problems with furniture render distance including new barriers on Volk Military Base

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4349]
Here is example of me watching through new barriers and furniture
https://youtu.be/TXiLifoXeFg
And here some more examples of furniture disappearing on other location 
https://youtu.be/58uU0VAMIRU

**Comment by SDGNelson** [comment]
Awesome trick jumping on the zombie's head to get over the low wall at the end of the airstrip!

Unfortunately, the camera through the small barrier trick predates the wall replacement. If anything it's a little better now that most of the walls are using the larger objects which block the camera. This is a limitation of Unity's current physics system: Each collider can only be assigned one physics layer, so on a per-physics-layer basis we have to decide whether they should block the camera. In other engines like Unreal or Godot we would be able to assign on a per-object basis whether the camera can pass through using layer masks. My hope long-term is that with Unity's eventual physics engine update we can do something like that.

Hiding objects inside buildings is a tradeoff between performance and gameplay as you highlighted. When rewriting the "culling volumes" I did consider using the on-screen size so that they would appear when scoped in, but this would enable an order of magnitude more objects when scoped in requiring e.g. frustum culling for the volumes, and still be exploitable without aggressive hysteresis - I didn't feel it was worth it.
