### ISSUE TITLE
OnTellVirus inconsistent

### ISSUE THREAD

**Issue by rube200** [SmartlyDressedGames/Unturned-3.x-Community#4373]
Atm there is to events for virus change: `onVirusUpdated` and `OnTellVirus_Global`
But the problem is `onVirusUpdated` is almost always client-side except for `AskRadiate` but that method doesn't emit `OnTellVirus_Global`.

So current game implementation:
`askDisinfect` and `askInfect` -> `OnTellVirus_Global`, `OnVirusUpdated` (but this last one in client side only)
`AskRadiate` -> `OnVirusUpdated`

**Comment by SDGNelson** [comment]
Thanks for pointing this out. I'll take a look at what's going on.

**Comment by SDGNelson** [comment]
`onVirusUpdated` is the original old client-side event for notifying the UI to change. `askRadiate` is called on both client and server while standing in a deadzone - and is only used for that one case - which is questionable but that's why it doesn't call the RPC.

For the next update I've changed `askRadiate` to also call `OnTellVirus_Global` 👍
