### ISSUE TITLE
Impossible to launch without Battleye on Linux

### ISSUE THREAD

**Issue by ai-kana** [SmartlyDressedGames/Unturned-3.x-Community#4403]
It is currently impossible to launch Unturned without battleye on Linux and Mac platforms

Makes it impossible to test client side modules. I tried the work around of deleting BE libs, it doesn't show the menu element which grabs the BE status from provider so the game still thinks its loaded aka won't load modules; You're still unable to join servers.

No binary for launching without BE, option also unavailable in Steam launch options.

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/109441902/49c0d3cc-09fe-4862-8516-afaa9d7423a0)

**Comment by SDGNelson** [comment]
`Unturned_BE.exe` adds `-BattlEye` to the launch command-line to indicate it was launched through BattlEye. This is used to decide whether to load modules and whether to show the "BattlEye disabled" banner on the menu. It looks like that banner is removed from the Mac and Linux versions because they don't receive that `-BattlEye` flag, i.e., they don't think they are running with BattlEye until joining the server. This means it *should* be loading modules regardless. Can you attach the Client.log file, please? Your modules should be getting loaded.

**Comment by ai-kana** [comment]
I see that now was able to load a module just fine sorry for the trouble.
