### ISSUE TITLE
Parse input IP as address before using DNS lookup

### ISSUE THREAD

**Issue by sunnamed434** [SmartlyDressedGames/Unturned-3.x-Community#4413]
The video below shows the problem, sometimes Unturned is just laggy but a few times it lead me to the whole game crash. Idk what causes this crash, IP: 156.236.84.205​:27070
https://streamable.com/y82oph

**Comment by sunnamed434** [comment]
IP from the discord server where I copied this IP, seems like I copied the `─` also, but it doesn't show in the menu IP/Port inputfield
🪨[ P9nda's Unturned KOTH [Rust] (Wiped)](https://discord.gg/WzzcyuEEt5)
IP: 156.236.84.205​ ​ ─ ​ ​Port: 27070​ ​ ─ ​ ​Players: 3

**Comment by SDGNelson** [comment]
On my PC resolving that address is immediate, but the underlying issue is that the game calls `Dns.GetHostAddresses` on the main thread and it blocks until it gets a result. It should probably try parsing as IPv4 *before* calling GetHostAddresses instead of just afterward. I suspect the reason the game closed is if the Windows "application is not responding" popup appears and gets clicked to close instead of waiting - looks like the timeout was around 11 seconds in your case.

As a solution for the meantime, I would suggest investigating why your DNS response was so slow.

**Comment by sunnamed434** [comment]
After I copied IP again all went just fine, without lags, but I guess the problem is in invalid character inputted into the ip/port

**Comment by CyberAndrii** [comment]
Uhh I don't think you know what DNS is... It is used to resolve IP addresses from domain names. If you make the game to parse as IPv4 before calling GetHostAddresses, then calling it will make no sense because you already have the IP address. But in that case it won't be possible to connect via domain names anymore because it won't be able to parse the IPv4 address from the domain.

> On my PC resolving that address is immediate

That's likely because you copied a valid IP address so it doesn't need to resolve anything. In sunnamed's case there's \u200b (zero-width space) character at the end. You can copy it from the logs by selecting both the IP and `"` after the IP then remove the `"`.

**Comment by SDGNelson** [comment]
> Uhh I don't think you know what DNS is... It is used to resolve IP addresses from domain names. If you make the game to parse as IPv4 before calling GetHostAddresses, then calling it will make no sense because you already have the IP address. But in that case it won't be possible to connect via domain names anymore because it won't be able to parse the IPv4 address from the domain.

Currently, the game checks whether the "Connect Address" text input is a server code or "localhost", and if not it proceeds to call `Dns.GetHostAddresses`. While some players do connect by domain name, a lot of the time this could be skipped by calling `IPv4Address.TryParse` first. If it IS a valid IPv4 address then it can proceed with that, and if not it can try resolving the name. I am well familiar with what DNS is.

> That's likely because you copied a valid IP address so it doesn't need to resolve anything. In sunnamed's case there's \u200b (zero-width space) character at the end. You can copy it from the logs by selecting both the IP and `"` after the IP then remove the `"`.

Good catch about the zero-width character. I copied it without the quotation mark so I didn't get the space. The game does call `string.Trim` before parsing, but unfortunately doesn't remove that. It seems like an unlikely/infrequent case that players would be pasting IPs with zero-width characters, so maybe this post is a non-issue. The reason I mentioned that it was immediate in my case was to clarify that `Dns.GetHostAddresses` wasn't stalling for 10 seconds on my end the way it was on OP's, and I wondered if internally Windows was forwarding the perfectly valid address to the DNS server rather than parsing it - which is why I proposed bypassing it when the input is already valid.
