### ISSUE TITLE
Console error.

### ISSUE THREAD

**Issue by CatzMR** [SmartlyDressedGames/Unturned-3.x-Community#4426]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/62692767/98b2af4a-7204-45ce-a570-49f9ffd5d3a1)
After the server starts, this error will pop up crazily on the console.
How to solve this?

**Comment by SDGNelson** [comment]
It looks like Unity is writing that to standard output because it's trying to play a video on headless mode. Vanilla doesn't use the video player, so this must be from a mod. Unfortunately, the error message is outside of our control. If you know or can figure out which mod it's from the best option would be to prevent the video player from being instantiated on the dedicated server.
