### ISSUE TITLE
I can't see a multiplayer server (my server)

### ISSUE THREAD

**Issue by arrow12312** [SmartlyDressedGames/Unturned-3.x-Community#4432]
I can log in via IP but I want others to see my server too?

**Comment by GazziFX** [comment]
Do you host on your own computer or on dedicated server? Do you forwarded configured ports (default 27015) and +1 port (27016)?

**Comment by arrow12312** [comment]
only 27015

**Comment by arrow12312** [comment]
i change port its work thank u<3

**Comment by MoltonMontro** [comment]
> i change port its work thank u<3

I'm glad you were able to resolve this issue with the help of @GazziFX (feel free to close the topic since the issue is solved).

In the future – please note that this GitHub is intended for bug reports. I recommend posting troubleshooting-related stuff (like server setup issues) on [our forum](https://forum.smartlydressedgames.com/) or Discord server instead!
