### ISSUE TITLE
Cannot use scroll wheel to go faster/slower in editor

### ISSUE THREAD

**Issue by SpylessNyah** [SmartlyDressedGames/Unturned-3.x-Community#4433]
It works for me using admin cam (F1), but not in the editor, i've reinstalled unturned and it didn't fix it, any fix?

**Comment by SDGNelson** [comment]
The code for it is essentially identical between freecam and the level editor. :confused: I trust you are holding right mouse button while trying to use it in the editor?

**Comment by SpylessNyah** [comment]
I am yes, this was never an issue up until about the start of this month.

**Comment by SDGNelson** [comment]
I'm sorry to say I have no idea why it isn't working for you. As far as I'm aware it's working for other players (including on my end), and there isn't really anything to troubleshoot here.

While writing, one idea is maybe you have the Glazier option overridden (if so, would recommend removing): https://docs.smartlydressedgames.com/en/stable/servers/glazier.html

Otherwise, sorry not to have a useful answer.
