### ISSUE TITLE
UI cannot control objects on the server

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4437]
I have placed ActivationEventHook on the UI to enable Object, which will take effect in single player mode and not on the server
![@1%%JRNM4GWJU3ZGC$S}NNL](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/beef94cf-9f4d-4b66-b3ef-77acb59f142d)
![Q17J$8LRD%~I7{N@NR3 DC2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/b257ed57-73f0-40be-9bda-6bc748972f83)

I want UI to send NpcGlobalEventMessenger, but UI cannot send events on the server
![TK178YUW`WKFL4Q_$8)0%BK](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/92e1af07-e492-4508-bb5e-4be9e99851db)

**Comment by DanielWillett** [comment]
UIs do not get spawned server-side if that's what you mean.

**Comment by DanielWillett** [comment]
Are you trying to control a projectile with a UI? That's not really possible with the way projectiles are replicated. You could use plugins to simulate a projectile using effects.

**Comment by SDGNelson** [comment]
`NpcGlobalEventMessenger` can only instigate events when running on the server-side, sorry. Since the UI only exists on the client, not the server, it cannot rely on that component existing in the UI on the server.

That said, it sounds/appears this is more-so about the particular setup, whereas this repository is intended for bugs/crashes/issues/etc in the game rather than modding assistance, sorry.
