### ISSUE TITLE
Missing Curated Maps

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4458]
In the single-player curated tab, a few curated maps are missing. The early Danaby maps and Ireland are missing. Ireland's omission is very strange, especially considering that there is an achievement tied to the map. Obviously Carpat and Belgium are missing since they are currently broken, but the old Danaby maps still work. If the idea is that they aren't played enough to justify taking up menu space (especially since they are arena), then maybe adding a spot for them in misc would be good? Would also give a good place to link to PEI and Washington Arena from in-game.

**Comment by SDGNelson** [comment]
Unfortunately, I don't recall off the top of my head about Ireland. I found the change in the commit history but I didn't list the reasoning. It might have been related to drama surrounding the team who updated the map. As for the arena maps, I think it was because it didn't make sense to recommend them for Singleplayer.

**Comment by Spebby** [comment]
> Unfortunately, I don't recall off the top of my head about Ireland. I found the change in the commit history but I didn't list the reasoning. It might have been related to drama surrounding the team who updated the map. As for the arena maps, I think it was because it didn't make sense to recommend them for Singleplayer.

For wiki purposes, what were the dates on the removals? As far as I'm aware, it's not public information
