### ISSUE TITLE
NPC Questions

### ISSUE THREAD

**Issue by Mark15612** [SmartlyDressedGames/Unturned-3.x-Community#4464]
Reward_#_GrantDelaySeconds float: If set, the reward will be queued for the specified number of seconds before being granted to the player. When the player dies any pending rewards are cancelled. Defaults to -1.
How do I cancel the reset bonus CD after death? 
because I want to make an NPC similar to the daily bonus, but once the player dies this bonus expires.

**Comment by SDGNelson** [comment]
I'm sorry to say there isn't currently an option to prevent it from being cancelled on death/leaving. For a more complex daily bonus system a plugin might be required. I would like to expand the reward delay feature in the future, perhaps at least with an option to apply on death/leave rather than canceling.
