### ISSUE TITLE
The queue doesn't work

### ISSUE THREAD

**Issue by Zombs-R-Cute** [SmartlyDressedGames/Unturned-3.x-Community#4472]
Map Loads, states in Queue Position 1, then immediately kicks back to server list and queue now full.
How can it be full when in the 1 queue position?
Shouldn't it wait until a spot opens up?  And when another joins they are added to position 2, also waiting, ect...
Then the Cancel button then would have a reason to exist, to forfeit the position in the queue.

**Comment by SDGNelson** [comment]
That's odd. What reason did it give when kicking you back to the server list?

**Comment by Zombs-R-Cute** [comment]
![Screenshot_20240526_161538](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/52ebf3b5-4e55-430b-9723-36f224d7f49a)

**Comment by Zombs-R-Cute** [comment]
[untitled.webm](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/161528800/7500aca7-8b05-4ff6-a812-94ffb7571a9d)

**Comment by SDGNelson** [comment]
Purchased some server parts a couple weeks ago and put together a proxmox virtualization server last week. Very slow IT department here haha but finally a good way to run multiple servers and test things like this with more clients.

As far as I can tell in testing to reproduce this the queue is working properly in vanilla. I did a variety of scenarios and it correctly put the players in the queue, showed the queue positions, advanced queue position when the player ahead got into the server, etc.

I know that there are some plugins which accept multiple players at a time which isn't supported. The server might be using such a plugin. I think that might be happening because you got the server full kick after being notified of position #1 in the queue, which happens when `ServerMessageHandler_Authenticate` double-checks that server has open space.

For anyone reading, for what it's worth, please don't use plugins that do the "verify" step for multiple players simultaneously.

If you are able to reproduce such an issue in vanilla I can reinvestigate!
