### ISSUE TITLE
Cutom map with assets from diffrent curated maps on a dedicated server.

### ISSUE THREAD

**Issue by HELPMEPLEASE222** [SmartlyDressedGames/Unturned-3.x-Community#4483]
so i tried to put my custom map to a dedicated server. i used assets from greece , hawaii , france, elver, kuwait, polaris, buak and escalation so i putted all the maps ids into workshop download so okay it downlaod then i try to join the server everything works fine for 5 seconds and after 5 seconds its just kicking me out i tried to fix it for literally 5 hours but everytime when i try to fix it its says that missng asset or wrong asset or wrong directory a lot of problems how to fix this pls

**Comment by SDGNelson** [comment]
Closing as the issue tracker is intended for bug reports, not troubleshooting, sorry. That said, I'd recommend adding all of your subscribed workshop files to the list of dependencies on your map's workshop file page so that your client and the server will both have all of the same assets. (It's possible you accidentally used files from more workshop pages than you realized.)
