### ISSUE TITLE
Battle Eye Obstructs Players from Entering the Server

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4491]
I am the owner of a server with 2 years of experience. After the latest game update, most players were frequently kicked out by WarEye and reported errors as shown in the following image.
Most players don't know the solution, so I hope the game developers can solve this problem

**Comment by hyjhkt** [comment]
![99d11a10cb4721047b0557b2a41f36ab](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/761f56c7-8679-4adc-b632-e309ef9b3868)

**Comment by DanielWillett** [comment]
Now that you mention it I've seen a lot more recently on my server as well, no one has complained yet. It definitely doesn't happen to everyone.

![Untitled-1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/12886600/6776866e-26e9-4d23-88f4-b6892dc18b31)

**Comment by sunnamed434** [comment]
I saw the same issue but it's not on my servers but on one of the plugin users, its 651 logs made by `Bad Service Version`

The most interesting thing is that it happens once or twice per random player or even more (I don't think it cheater specific)

![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/65300126/60aecf1e-5e33-41f3-8b45-6859c460e320)

**Comment by hyjhkt** [comment]
The most serious impact is that if a player is kicked out of the server and this error pops up, it becomes difficult for them to enter the server again. Restarting the game and computer is a common solution for players, and trying multiple times is useless. Reinstalling Battle Eye is something that some players will operate, with a 50% chance of success. Some players will change the "host".
But this is still only a skill that some players know

**Comment by SDGNelson** [comment]
Sorry for the trouble. I think they may have released an update recently (they can update the service without a game update nowadays). If the FAQ entry doesn't help then I'd advise players to [contact BattlEye support](https://www.battleye.com/contact/). According to BattlEye FAQ:

### I am getting kicked for the following violation(s). I don’t use hacks, so what can I do to resolve this? (Bad Service Version)

For some reason the BattlEye Service is outdated or not operating properly. Please make sure your BE Launcher is not reporting any update failures when launching the game. Due to external factors in some cases the BE Service may have problems operating, which can also lead to this error. In that case please try to close all unnecessary programs while playing the game. If that still doesn’t help we would suggest a full repair reinstallation of Windows as a definite solution.
