### ISSUE TITLE
how to get permamently stuck inside of a bookshelf 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4495]
https://youtu.be/ZbEwjmq1Tds

**Comment by SDGNelson** [comment]
Sorry about that and thanks for the report. Unfortunately, the underlying cause is this known issue: https://support.smartlydressedgames.com/hc/en-us/articles/12801674391188-Wiggling-out-of-bounds

If it happens genuinely then a player can log out and log back in and it should teleport to a non-stuck spot.
