### ISSUE TITLE
Reinforced Storefront needs a Reinforced Storefront to be crafted. On Escalation

### ISSUE THREAD

**Issue by DustyOwO** [SmartlyDressedGames/Unturned-3.x-Community#4512]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/97802758/555e1170-5ed5-4a32-8bfd-251ba4d808b8)

**Comment by Jdance-Media** [comment]
Hi, Escalation is a curated map, which means that it was created by the community rather than the actual game developer. If you wish to report any problems with Escalation, it would be better to do so in its discussion page on [Steam](https://steamcommunity.com/workshop/filedetails/?id=3251926587).

From what I'm aware, this issue tracker is mainly focused on the base game, rather than any content that is installed separately through the workshop.

**Comment by SDGNelson** [comment]
Thanks Jdance! Yes, in some cases - for example, exploits that are best kept private - I message reports directly to the map teams. For a general issue like this, however, I'd ask that you post it in the discussion here so that other players can see which bugs have already been reported and are being fixed.
