### ISSUE TITLE
[Preview Branch] Audio Menu related issues

### ISSUE THREAD

**Issue by elsultaan** [SmartlyDressedGames/Unturned-3.x-Community#4531]
UI Elements are off-center
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/f6ee016d-e41a-485d-abe1-59754c1f2395)

'Volume While Alt-Tabbing' has duplicated % symbol
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/d7232833-4f70-4990-b93c-b3425d72de78)

'Loading Screen Music Volume' could be referred to as 'Music Volume' instead? - Is_Music bool on effects is influenced by loading screen volume percentage, the term might be outdated.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/c86a95e8-aed7-4a18-b7f7-7f7f1391c208)

**Comment by Spebby** [comment]
Do you have any UI scale? Could be affecting scales.

**Comment by elsultaan** [comment]
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/156057376/d383f42e-1e49-4540-871d-8ffbd90b505b)
Nope

**Comment by SDGNelson** [comment]
Funnily enough it was more off-center a few days ago. It has space for 500 pixels while only being 400 pixels wide at the moment - I forget what I was making room for. 😕 

Thanks for pointing out the double percentages!

On my to-do list I intend to add separate sliders for "music" effects and the ambience and main menu music which is why there isn't anything for those yet.
