### ISSUE TITLE
structure snapping is locked to 45 degrees

### ISSUE THREAD

**Issue by diddlyono** [SmartlyDressedGames/Unturned-3.x-Community#4532]
https://youtu.be/V1lhYJUPbuM

structures dont rotate properly in snapping, mainly affects walls and floors.
seems to be 45 degrees offset from the world. happens with and without the housing planner.

**Comment by Senior-S** [comment]
Probably related to #4530 https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/4530

**Comment by SDGNelson** [comment]
Thanks for the reports! This does seem like the two must be related. 🤔

**Comment by SDGNelson** [comment]
Two annoying issues:

- The 27 bit quaternions are not as consistent as I thought they were, compared to rounding euler angles to the nearest 2nd degree. It might work OK to specialize structure and barricade writing for the most common case of only rotated around the yaw axis, and use quaternions for unusual transforms. Need to experiment further.

- Structure connections were using the eulerAngles property to extract rotation around the Y axis, but when replicated as a quaternion the resulting euler angles can be very different while still representing the same rotation. I think this is a straightforward fix but we'll see.

**Comment by SDGNelson** [comment]
Thank you both for catching this! It should be resolved in the next preview version (104), and in particular the usual case of structures rotated around the Y axis is more precise than before: In 3.24.3.0 it could be rotated in 1/128th increments, whereas after this 104 patch it is 1/8388608 with no additional bandwidth. 😄 (1 bit flag for Y-axis-only or not, and figured since the old rotation was 24 bits we may as well allocate 23 to Y rotation)
