### ISSUE TITLE
[Preview Branch] /give /vehicle parity with Rocket

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4539]
This isn't a bug, but I think it will be a common complaint. When using /i or /v in rocket you put quotes around entities if they have a space in them, where as /give and /vehicle use underscores. It would probably be good to support the quote format, since a lot of players will likely be used to how rocket handles things.

**Comment by Jdance-Media** [comment]
> This isn't a bug, but I think it will be a common complaint. When using /i or /v in rocket you put quotes around entities if they have a space in them, where as /give and /vehicle use underscores. It would probably be good to support the quote format, since a lot of players will likely be used to how rocket handles things.

Yeah, agreed. This is the case for almost all server commands. Players will instinctively use quotes.

**Comment by SDGNelson** [comment]
The built-in command parsing would certainly benefit from a rewrite, but you don't actually need to use underscores. The vanilla /give and /vehicle commands match in this order:
1. Exact match with file name (these typically contain underscores which is why your underscores would match)
2. Exact match wth display name
3. File name contains input
4. Display name contains input

**Comment by Spebby** [comment]
I see, definitely long term then.

It may be good as a precaution to have the game ignore quotes so players who instinctively try quotes aren't confused on why nothing happened. Perhaps though this would be too messy.

**Comment by Jdance-Media** [comment]
Ah okay, that makes better sense. Thank you!
