### ISSUE TITLE
Wheels missing materials when vehicle explodes

### ISSUE THREAD

**Issue by Big-Raider** [SmartlyDressedGames/Unturned-3.x-Community#4550]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174275952/b8dda596-7c6d-488c-b8bf-110a30a176f3

when the vehicle explodes and the main model despawn the wheels material also dissapears, this only happens on vehicles on which the wheels can also be painted

**Comment by SDGNelson** [comment]
Whoops! Thank you for the report. I'll take care of this on tomorrow.

**Comment by SDGNelson** [comment]
Ah, this was simpler than I feared: It's because the wheels are now moved out of the vehicle hierarchy, so if the vehicle despawn timer is shorter than the wheel despawn timer it could destroy the material before the wheels. As a fix I've changed it to also destroy the wheels when the vehicle is destroyed.
