### ISSUE TITLE
[Urgent assistance]If "Yut. AdvancedRegionModule" is not changed, will the functions related to this plugin in the server be able to be used normally, and can "Save" be saved properly? Will archiving be affected

### ISSUE THREAD

**Issue by hyjhkt** [SmartlyDressedGames/Unturned-3.x-Community#4561]
![0551627beaace36ac7dd230ee0c83e0f](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/82864808/db8aff7e-9cc2-4231-834a-f4493a84a0a9)

If "Yut. AdvancedRegionModule" is not changed, will the functions related to this plugin in the server be able to be used normally, and can "/Save" be saved properly? Will archiving be affected

**Comment by hyjhkt** [comment]
I'm sorry, my friend's server is experiencing this issue now. He needs to urgently repair the server in the middle of the night

**Comment by GazziFX** [comment]
Just remove it from plugins

**Comment by SDGNelson** [comment]
I'm not personally familiar with Yut.AdvancedRegionModule so I'm not sure whether it's directly modifying the contents of the Barricades.dat and Structures.dat files. If you remove it for the meantime then that error will go away, but you may need to save a backup and delete Barricades.dat and Structures.dat until the plugin developer is able to update it. This is because if the plugin *is* modifying those files the game won't be able to load them by default, so it's best to have a backup for when the plugin is restored.
