### ISSUE TITLE
Unturned Vehicle Update Bug

### ISSUE THREAD

**Issue by thraxsh255** [SmartlyDressedGames/Unturned-3.x-Community#4565]
Just in case my e-mail doesn't go through, ive discovered a glitch with the new vehicle physics, ill provide images below.
![1](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174660256/9b08199b-8bb3-4b46-bd1b-70e076e71de2)
![2](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174660256/dc6d4b20-78eb-42cd-9b6a-511a50a54a09)
![3](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174660256/b4061be2-5eb2-4d1d-ac64-98ffc98bcdb9)
![4](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174660256/6855a7ab-c4f6-46ef-bb6c-026fb0a7ae22)
![5](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/174660256/166f1232-4949-42e3-a926-488047a36d3e)

**Comment by SDGNelson** [comment]
Closed the support ticket since you posted this here as well. Did you just spawn two vehicles at the same time?

**Comment by thraxsh255** [comment]
> Closed the support ticket since you posted this here as well. Did you just spawn two vehicles at the same time?

Basically me and my friend ran 2 vehicles into eachother, so you need 2 players for testing, just let the vehicles collide with eachother, and you have to go as fast as the vehicle can go i believe.

**Comment by SDGNelson** [comment]
Ah, thanks for the report by the way. Unfortunately, this would be because the physics are simulated by the driver, so on each of your clients the game thought it could continue driving forward, and only once you were both overlapping on the server did they realize what had happened. The ideal solution would be for vehicle physics to be fully server authoritative similar to walking movement, but there isn't a good way to roll back the simulation so the you would need to wait for the server's response to inputs which is practically unusable. 😞
