### ISSUE TITLE
The problem of cheaters.

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#457]
Hello world =)
I would like to talk to you about cheaters.
I think this is the biggest problem unturned 3.0
I created a simple neural network that checks for player cheats, she is still in development,
 **But the problem is that there are cheats that will turn off when the server sends the player a message about  /spy**
I would also like to set limits on the player’s watch in the game. Because the game is free, and many cheaters when they get banned create new accounts and play in again.
I'm afraid here to talk about my neural network and how it will work, although I would love to tell you.
I also have worker cheat files, and if you need to, I can send them to you.
**I want to say that many players leave the game because of cheaters.**

**Comment by Trojaner** [comment]
1. **You can not prevent /spy getting patched by cheats.** Simple problem when relying on client side stuff. Some countermeasures are chcking if the image is static (might be cheat or AFK player) or if the image does not show up at all (in this case, kick the player). Don't forget that advanced cheats use stuff like second camera to render screenshots without their UI layer. Another approach is to disable the cheat when a screenshot gets taken and re enable it afterwards. Both are impossible to detect.

2. Like Rocket Observatory, you can use Steam API to check how old a players account is and reject them if they are too new or do not have any other games.

3. Neural Networks require a lot of power which your average Unturned Server does not have. They especially need professional Nvidia GPU's which are not present on most dedicated servers. Using the CPU requires even more resources which makes it not feasible.

3. Unturned doesn't have a as big cheater problem as you have described. Since battleye, the amount of cheaters is relatively low.

Conclusion:
Close-Request, there is nothing to do on Unturneds side.

**Comment by VitaxaRusModding** [comment]
1You are joking? 50 players are banned every day ...
Half of them take and new accounts create.
Many players have an opinion that the developer himself does the cheats, although I do not agree with them, but not a few of them think so.
2 I don’t know for sure, but I watched STEAM API and didn’t find how to get a player’s watch. There you can get a watch per week in the game ...
3 I know what a neural network is and I understand
what loads will be.

**Comment by VitaxaRusModding** [comment]
Yes, I often heard that.

**Comment by VitaxaRusModding** [comment]
even stream youtube with cheats. =(

**Comment by aviadmini** [comment]
1. **You cannot detect cheats with any of currently useable methods as of I know**
I personally know 2 different working approaches to overcome any of that BattlEye or /spy nonsense. I'm quite sure I could find more if I bothered to.
Like Trojaner said - it's possible [and easy] to make those undetectable. Or make it send memes when you spy on somebody

2. As Trojaner said there's this Rocket observatory etc but I don't see much point in it as it might be easily abused. He also said that it's possible to get steam profile **but** it won't work unless it's private. Either it's useless or you reject too many innocents along with a small bunch of actual whoresons

3. _"Neural Networks require a lot of power which your average Unturned Server does not have. They especially need professional Nvidia GPU's"_ is one of the most stupid things I've ever read from Trojaner.
Still, it's nonsense because you have no technologies to detect cheats (see 1.). Which means that you neither have a working algorithm nor samples of data for training the net. 

4. I wonder who still thinks that BattlEye does a great job (see 1.)

So now that I spilled shit on everything said so far I should suggest something right?
Well, I can't really 😲 The problem exists, it's negatively impacting the whole community, server owners in particular. Those also lead to game dying and having less and less players playing (steam stats pl0x)

Let's see what Nelson has to say

**Comment by SDGNelson** [comment]
Which cheats are you seeing? Recently there was one cheat being actively developed, but they quit and released the source code.

While I think it goes without stating, obviously I'm not developing cheats. Not to mention I doubt the revenue from cheats would even come close to breaking even with the cost of BattlEye.

**Comment by aviadmini** [comment]
I have no idea what's it called but people use stuff that allows you to watch thru walls, highlight enemies (thanks HighlightTool), remove recoil, aim bots etc. Dunno the exact tools, but those exist

And okay, contrary with my previous post you totally could check no-recoil and serverside. Not that it's a big help agains aim bot with simulated aiming (whatever you call moving not instantly)

**Comment by baranmod** [comment]
not really to the "topic" but aren't there any chances to incorporate some spectating feature to unturned 3? I believe it would help to fight cheaters much more effectively.

**Comment by Trojaner** [comment]
> "Neural Networks require a lot of power which your average Unturned Server does not have. They especially need professional Nvidia GPU's" is one of the most stupid things I've ever read from Trojaner.
Run Tensorflow with CUDA and then without CUDA, tell me the differences.

**Comment by SDGNelson** [comment]
Again are you aware of any available cheat programs though? I have not seen any online recently.

**Comment by Johnanater** [comment]
"MetallicCheats" is a cheat that's been going around recently. It originally came out this June, but it's been re-released. I've seen a few people use it on my servers sadly.

**Comment by SDGNelson** [comment]
Thanks Johnanater, and actually a few people anonymously emailed me that cheat in response to my comment as well.

I had sent that cheat in to BattlEye a little over a month ago so I was surprised. Today I followed up asking about it again and apparently it will now be banned.

In the future if any of you learn of any functional public cheats feel free to send them over (e.g. to nelson@smartlydressedgames.com) and I'll get them to BattlEye ASAP.
