### ISSUE TITLE
Escalation building recipe issue.

### ISSUE THREAD

**Issue by Anormalpotato** [SmartlyDressedGames/Unturned-3.x-Community#4578]
In escalation you can turn walls into center walls, windows into center windows etc. if you have a complex building book. But you can not turn metal center window into metal window because recipe does not give you anything.
![image](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/assets/175015934/8b7c66ff-a227-4c13-8756-2ce795e11f77)

**Comment by Jdance-Media** [comment]
Hi, this is probably not the best place to post issues regarding Escalation. It is a curated map and therefore it is not developed by SDG for the most part. Consider using the discussions on the workshop item for Escalation.

**Comment by SDGNelson** [comment]
Thank you for the report, and thanks Jdance for the reply. In some cases - for example, exploits that are best kept private - I message reports directly to the map teams. For a general issue like this, however, I'd ask that you post it in the discussion here so that other players can see which bugs have already been reported and are being fixed: [Escalation Bug Reports](https://steamcommunity.com/workshop/filedetails/discussion/3251926587/4326348922703778470/).
