### ISSUE TITLE
Gearbox Doesn't Support Engine_Additive

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4584]
Easter Island used Engine_Additive on the Hornet (Bombardier in files) to make it feel more rugged. I verified that my setup is the same as the vanilla Cargo Train, whose Engine_Addative does work as intended.

**Comment by SDGNelson** [comment]
It depends on the `EngineSound_Type` property. The `EngineRPMSimple` type only controls the engine audio source volume and pitch. The pre-existing behavior of `Engine_Additive` for the default engine sound was maintained, but at some point I intend to add some separate options for it because it's not really configurable at the moment.
