### ISSUE TITLE
Servers caching workshop mods.

### ISSUE THREAD

**Issue by AngelAbov3** [SmartlyDressedGames/Unturned-3.x-Community#4594]
I know barely anything about server hosting but I'm pretty sure this should work different.

Upon start servers download and cache a version of the workshop mod they start up with.

In the event that a workshop mod is updated and a player attempts to join the server instead of being kicked with the reason of  
`"Server is running a older version of (X) workshop mod".`
The mod would be pulled from the servers cache instead of steam, making the player able to join instead of waiting for a server restart to manually update the workshop mods on the server.

In theory if this worked this should solve a range of different workshop related issues issues but it doesn't work.

I also noticed this in WorkshopDownloadConfig.Json and it doesn't seem to have any effect either.
  `"Use_Cached_Downloads": true,`

**Comment by SDGNelson** [comment]
During startup the server queries the list of requested workshop file IDs. Since the server doesn't have subscriptions per se it might need to download all of them, but when the cache option is enabled it will look for a local copy and skip downloading if the local copy seems to be up to date.

i.e., the download cache in that case is referring to whether the server will download the files, not whether clients will download from the game server.

I agree it would be useful for clients to be able to download files directly from the game server. This would be a relatively big update, however, and open a whole other can of worms.
