### ISSUE TITLE
Preview branch version 3.24.5.101 - Snowmobile glitching

### ISSUE THREAD

**Issue by GatoAgus** [SmartlyDressedGames/Unturned-3.x-Community#4624]
Name: Gato Agus
Bug: If your snowmobile goes fast, it glitches thru the terrain.
![imagen_2024-08-07_143203677](https://github.com/user-attachments/assets/852b3e58-b965-4a74-8d5d-93470b09514a)

https://github.com/user-attachments/assets/1dc26d5b-24a2-43b7-aebe-2390ed35a3b5

**Comment by Kubusiek3** [comment]
i think its just hix textures xd

**Comment by SDGNelson** [comment]
Since there've been a few bits of feedback about these I'm adjusting them in the .102 preview version. Ideally, they would sit flush with the snow surface, but clients don't know the ground normal - only the suspension height - so as a compromise fix it will use the steering angle and adjust the pitch to aim at where the invisible wheel is. It's far from perfect but nicer than in .101.
