### ISSUE TITLE
Some resources don't seems to getting applied the Respawn Time?

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4630]
I wanted to add some kind of economy to my server, however I noticed I can't control how much time needs to take to get another currency from these ones? Like, no matter how much time I set on the Binary State Reset Time or Resource Respawn Time, I'll be able to get money from these ones like every minute or less, which will easily break the economy of my server because on any city there may be a lot of them, and the time it requires to loot each of time will consume the same time it requires to give to you another one currency, so you can stay looting money forever instead of, like a tree or ore, which requires a lot of time to respawn and you can actually control their respawn times

![2024-08-09_08-24-13](https://github.com/user-attachments/assets/46d1c7a2-bd30-4fdf-94b5-6afe905bb631)

**Comment by SDGNelson** [comment]
It's a fair point, but currently these aren't affected by any gameplay config, sorry. The relevant parameter is `Interactability_Delay` which is how often they can be used. To avoid any issues like this the best option might be to use a currency from a curated map or a new custom currency rather than the vanilla one.
