### ISSUE TITLE
Kicks with disconnect codes in "Client.log"

### ISSUE THREAD

**Issue by RBMKBlaze** [SmartlyDressedGames/Unturned-3.x-Community#4665]
After the recent update, a few players are getting kicked (including me) for no kick message in the client UI, straight to the lobby. The logfile shows messages with random codes:
`Disconnecting: 195`
`Disconnecting: 55`
`Disconnecting: 96`
`Disconnecting: 208`
`Disconnecting: 247`
`Disconnecting: 109`... etc, in the discord people have said its a `BattlEye` issue, but I didn't believe after some fixes people have mentioned not working it so I created a fresh `U3DS` server with `steamcmd`, disabled `VAC`,`BattlEye` in the `Config.json` of my server ID, launched Unturned without the battleye sc running, yet the kicks still happen. Im not the only one who this happens to and this happens globally on multiplayer I'm not entirely sure how to replicate it as it doesn't happen to everyone.

**Comment by ymo-4** [comment]
+1. Short video demonstrating it with client.log in the end: https://youtu.be/Wf-FaeLhevU

No matter playing with anticheats or without, nothing changes. Here's some info about my system just in case:
```
[2024-09-07 22:13:48] Game version: 3.24.5.1 Engine version: 2021.3.29f1
[2024-09-07 22:13:48] Requesting promo item grant
[2024-09-07 22:13:48] Found Steam language 'english' in root Localization directory
[2024-09-07 22:13:48] Platform: LinuxPlayer
[2024-09-07 22:13:48] Operating System: Linux 6.6 NixOS 24.05 64bit
[2024-09-07 22:13:48] System Memory: 15939MB
[2024-09-07 22:13:48] Graphics Device Name: AMD Radeon RX 580 Series (radeonsi, polaris10, LLVM 17.0.6, DRM 3.54, 6.6.47)
[2024-09-07 22:13:48] Graphics Device Type: OpenGLCore
[2024-09-07 22:13:48] Graphics Memory: 7185MB
[2024-09-07 22:13:48] Graphics Multi-Threaded: True
[2024-09-07 22:13:48] Render Threading Mode: MultiThreaded
[2024-09-07 22:13:48] Supports Audio: True
[2024-09-07 22:13:48] Supports Instancing: True
[2024-09-07 22:13:48] Supports Motion Vectors: True
[2024-09-07 22:13:48] Supports Ray Tracing: False
```
Player.log also mostly quiet: a lot `[S_API FAIL] Standard callback dispatch cannot be used; manual dispatch has already been selected` (i have that two freezes after some time joined to the server) and right after that:
```
Unloading 5 Unused Serialized files (Serialized files now loaded: 19)
Could not terminate pathfinding thread[4] in 50ms, trying Thread.Abort
SynchronizationLockException: Object synchronization method was called from an unsynchronized block of code.
  at (wrapper managed-to-native) System.Threading.Monitor.Exit(object)
  at Pathfinding.ThreadControlQueue.Pop () [0x0013c] in <644d941eb45b46f89507fc3a06fe7dce>:0 
  at AstarPath.CalculatePathsThreaded (System.Object _threadInfo) [0x00075] in <644d941eb45b46f89507fc3a06fe7dce>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
AstarPath:CalculatePathsThreaded(Object)
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart(Object)

Unhandled exception during pathfinding. Terminating.
UnloadTime: 920.937590 ms
Unloading 1923 unused Assets to reduce memory usage. Loaded Objects now: 118832.
Total: 159.673110 ms (FindLiveObjects: 8.663090 ms CreateObjectMapping: 7.639820 ms MarkObjects: 108.715080 ms  DeleteObjects: 34.653770 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 19)
Unloading 1 unused Assets to reduce memory usage. Loaded Objects now: 118848.
Total: 130.298900 ms (FindLiveObjects: 8.627050 ms CreateObjectMapping: 8.289470 ms MarkObjects: 113.042310 ms  DeleteObjects: 0.338730 ms)

Unloading 0 Unused Serialized files (Serialized files now loaded: 19)
Unloading 0 unused Assets to reduce memory usage. Loaded Objects now: 118848.
Total: 127.599220 ms (FindLiveObjects: 8.450930 ms CreateObjectMapping: 7.898400 ms MarkObjects: 110.957520 ms  DeleteObjects: 0.291230 ms)
```
Which is also not an issue as said in #2801. Will test on the other distro and windows soon.

**Comment by ymo-4** [comment]
Have tested it on windows result is exactly the same. But fedora worked well, no that weird "kicks" at all. After some time of trying to figure what is different on fedora. I thought this may be the issue with settings so i copied `~/.config/unity3d/Smartly Dressed Games/Unturned/prefs` from fedora to my nixos install. And it seems like this worked, now unturned on my nixos runs well too. `perfs` looks like this now:
```
<unity_prefs version_major="1" version_minor="1">
	<pref name="CloudStorageHash" type="string"><censored></pref>
	<pref name="Screenmanager Fullscreen mode" type="int">1</pref>
	<pref name="Screenmanager Fullscreen mode Default" type="int">1</pref>
	<pref name="Screenmanager Resolution Height" type="int">1080</pref>
	<pref name="Screenmanager Resolution Height Default" type="int">768</pref>
	<pref name="Screenmanager Resolution Use Native" type="int">0</pref>
	<pref name="Screenmanager Resolution Use Native Default" type="int">1</pref>
	<pref name="Screenmanager Resolution Width" type="int">1920</pref>
	<pref name="Screenmanager Resolution Width Default" type="int">1024</pref>
	<pref name="Screenmanager Window Position X" type="int">0</pref>
	<pref name="Screenmanager Window Position Y" type="int">0</pref>
	<pref name="UnityGraphicsQuality" type="int">1</pref>
	<pref name="UnitySelectMonitor" type="int">0</pref>
	<pref name="unity.player_session_count" type="string">MTYx</pref>
	<pref name="unity.player_session_restoreflags" type="int">195</pref>
	<pref name="unity.player_sessionid" type="string"><censored></pref>
</unity_prefs>
```
Only 5 values has been changed: `unity.player_sessionid`, `CloudStorageHash`, `unity.player_session_count`, `Screenmanager Resolution Use Native` from `1` to `0`, and `unity.player_session_restoreflags` from `21` to `195`. Only the last one looks to me like something sensible.

P.S. `~/.config/unity3d/Smartly Dressed Games/Unturned/prefs` used like a "windows registry" when you trying to access it from .net on linux.

@RBMKBlaze can you test this and reply back if its work? But i honestly don't know exactly where is unturned storing this in real the windows registry. Probably something would be here `HKEY_USERS\S-1-5-21-3728725473-1881688733-3596223992-1001\SOFTWARE\Smartly Dressed Games\Unturned`. You will probably need to find directory like this `S-1-5-21-3728725473-1881688733-3596223992-1001` manualy since it seems unique.
@SDGNelson sorry for ping but you haven't answered in 3 weeks while answering on other issues. Now when we have a little bit more info - any thoughts/comments? Also i wanted to copy unturned settings (like graphics etc) from fedora to nixos but haven't found corresponding file. Can you tell me please where unturned settings is stored? Maybe you can also give an advice to @RBMKBlaze how to find these prefs in the windows registry.

**Comment by RBMKBlaze** [comment]
@ymo-4 I in the end solved it a day after I posted the issue. And Unity Player prefs are found at `HCKU\SOFTWARE\Smartly Dressed Games\Unturned` at `%USERPROFILE%\ntuser.dat`

**Comment by downj05** [comment]
Can confirm the `unity.player_session_restoreflags` value is what causes this. Am in the process of helping a friend troubleshoot, my Windows 10 system does not have the issue but I was able to temporarily give myself the kicking problem by setting my `unity.player_session_restoreflags` to `21` as detailed by @ymo-4 . Reverting it to the old value I had (`146`) fixed it for me. It seems you can even change this live while in the main menu to enable/disable this bug. Interestingly my friend could not fix it for him trying different numbers. It seems these numbers may be unique per player, perhaps tied to the `unity.player_sessionid`, not sure. Unity doesn't have much documentation on what these values do from what I can find but for all affected this seems to have become prevalent after the online safety and vehicle physics update.

**Comment by GazziFX** [comment]
> It seems these numbers may be unique per player, perhaps tied to the `unity.player_sessionid`, not sure. Unity doesn't have much documentation on what these values do from what I can find but for all affected this seems to have become prevalent after the online safety and vehicle physics update.

Just delete it and you will be fine, also this is not unity value, but Unturned specific, it was made to confuse someone )

**Comment by downj05** [comment]
> > It seems these numbers may be unique per player, perhaps tied to the `unity.player_sessionid`, not sure. Unity doesn't have much documentation on what these values do from what I can find but for all affected this seems to have become prevalent after the online safety and vehicle physics update.
> 
> Just delete it and you will be fine, also this is not unity value, but Unturned specific, it was made to confuse someone )

In the case of my friends issue, deleting the registry values and letting them be re-populated replaced them with the same, broken values. Even reinstalling Windows for this user had the same issue. It seems some mechanism (perhaps tied to their steam user? More testing to be done here) is deciding what these numbers should be - and is setting them wrong for some users after the aforementioned online safety & vehicle physics update.

Trying random `player_session_restoreflags` values doesn't seem to fix it, I suspect there is some relationship between this value and `player_sessionid`  that needs to be correct for the bug to not happen.

In @ymo-4 's testing they managed to fix it by trying a different Linux distribution, which seemed to repopulate these values with completely new ones instead of carrying over the old ones. These newly generated values were confirmed to work on their older distribution after copying them over. Perhaps @SDGNelson could weigh in and provide some clarity on what the relationship between these values are and how to forcefully repopulate them with new ones? That seems to be the only known fix.
