### ISSUE TITLE
I just attached a video where you can see a way to penetrate through any ceilings (you can also use textures).

### ISSUE THREAD

**Issue by Firegames666** [SmartlyDressedGames/Unturned-3.x-Community#4673]
https://youtu.be/JoibB4qMzFQ

**Comment by SDGNelson** [comment]
Thank you for the report! Despite some of the adjustments to floor snapping in the .1 patch I think several bugs are still worse because you can get closer to these slopes now. I'm going to experiment with a few approaches. Closing your issue for the meantime because it's along the same lines as #4667.
