### ISSUE TITLE
Volume properties are not being saved unless volume is transformed.

### ISSUE THREAD

**Issue by Jdance-Media** [SmartlyDressedGames/Unturned-3.x-Community#4686]
I place a deadzone volume, save the map, it shows up in the savedata (Level.hierarchy). I change it to full suit, save the map, and it doesn't change the savedata. You have to transform the volume to get the changes to apply. This happens with all of the available properties.

Brought to my attention by user Pappa, I then went ahead and tested + recorded.

**Comment by Jdance-Media** [comment]
https://github.com/user-attachments/assets/55eb4f93-388c-442b-a9c6-8556a80bdfec

**Comment by SDGNelson** [comment]
Fair point. Admittedly I've just added and removed a volume quickly if I need to force it to re-save. It's the way it is at the moment because the automatic reflection-based inspector was removed when merging into the regular editor so the per-volume-type editors would need to mark it as needing re-save.
