### ISSUE TITLE
Air drop teleports form touch down spot

### ISSUE THREAD

**Issue by Zombs-R-Cute** [SmartlyDressedGames/Unturned-3.x-Community#4690]
The airdrop landing location is off, sometimes by a lot more than a couple of meters, crushing nearby players.  

[Airdrop offset.webm](https://github.com/user-attachments/assets/2cb097af-354d-4e1b-ba32-4fbef23186e1)

**Comment by Jdance-Media** [comment]
This might be specific to Arid, but I'm not too sure. If it does happen to be specific to Arid, you'll want to report this in the discussions for the workshop item rather than here.

**Comment by Zombs-R-Cute** [comment]
It's not just arid.
[Airdrop offset PEI.webm](https://github.com/user-attachments/assets/0a568cc1-9b2b-4052-b314-3cf0b87c7c5e)

**Comment by SDGNelson** [comment]
Sorry about this! A proper fix keeps getting pushed back as part of wanting to rewrite how projectiles work, i.e., to merge rockets, grenades, zombie boulders, airdrops, etc into one "system" that makes them more deterministic rather than each doing their own thing. I made a somewhat related improvement a while ago but there is at least one more thing we can do in the meantime to make it closer.

And my apologies for the delay and thank you for your patience! (I was away the 3rd through the 10th)
