### ISSUE TITLE
Player UV maps are not alligned with corners of pixels

### ISSUE THREAD

**Issue by DerEnte** [SmartlyDressedGames/Unturned-3.x-Community#4704]
![image](https://github.com/user-attachments/assets/0ce7b414-1733-43b8-8d71-7e77c2d06afb)

This is very visible when wearing non-matching colors of clothes, I managed to fix it myself in blender by selecting all of the UVs and scaling them all individually and snapping them to the corners of pixels

https://github.com/user-attachments/assets/ff9ab49c-3f74-47eb-a79f-887b179ebc50

**Comment by SDGNelson** [comment]
Ideally, they should be in the pixel corners, yes. The current version is centered in pixels because there is no margin between UV islands. It could probably be closer to the corners though. A newer version of the character model has symmetrical UVs to make painting easier, snapped to corners of pixels, and automatic expansion of colors into the margin. :P
