### ISSUE TITLE
Chewing Gum doesn't hide explosion stats

### ISSUE THREAD

**Issue by Spebby** [SmartlyDressedGames/Unturned-3.x-Community#4709]
takes away the fun :(

**Comment by SDGNelson** [comment]
Hmm... On the other hand, players won't necessarily look at the description of every item they find. I'm unsure whether we should hide information from item descriptions.

**Comment by Spebby** [comment]
True, though given it's a troll item I think in this specific case it's warrented.

**Comment by MoltonMontro** [comment]
I think consistency is better (reinforcing that players can trust the stats shown on an item / the game isn't unfairly deceptive). The only two vanilla items like this is the Upgrade Cake and Chewing Gum. _Maybe_ raw berries. And then Hawaii has a poisonous Raw Mushroom variant, if we include that map.

I think if we were hiding information from the player, it might be better if players could still figure out its actual stats. E.g., items have all stats hidden until first used (tied to either character savedata on the world, or to the player regardless of character/world?). Or maybe tied to a skill (e.g., Cooking, Engineering, Mechanic, Survival...).

^^ But I wonder if that might be uninteresting as a mechanic.

**Comment by SDGNelson** [comment]
Thanks for your input, Molt! I like the idea of discovering stats rather than knowing them all by default. Kind of like identifying items in the older Diablo games, or inspecting items in Tarkov. Perhaps different item types stat discovery could be tied to different skills. (e.g., gun discovery related to a gunsmithing skill) Will close this issue for the meantime.
