### ISSUE TITLE
Change default rendering mode to Deferred mode

### ISSUE THREAD

**Issue by asineth0** [SmartlyDressedGames/Unturned-3.x-Community#4721]
I noticed that the default render mode in graphics settings is set to "Legacy" instead of Deferred. While this might've been done at one point for compatibility reasons, even my old laptop with an Intel HD 4000 can run the Deferred mode, so I'd guess that almost any consumer hardware is going to be able to run the Deferred mode out-of-the-box.

![image](https://github.com/user-attachments/assets/111cb11b-ba0a-41f9-8c15-6cae42531c8e)

Doing so would help with performance and making sure maps look correct for more players as the map dev intended.

**Comment by SDGNelson** [comment]
For the most part the defaults are tuned to favor performance in case a player with a low-spec machine loads into multiplayer. Especially when there are more lights (e.g., flashlights, vehicle lights, player-placed lights) forward is helpful because it limits the maximum number of lights that can affect rendering. Ideally, at some point I would like to only support one "render mode" because it would simplify quite a few things. Perhaps after the Unity merges the render pipelines. 😄
