### ISSUE TITLE
Voice Chat Volume Slider

### ISSUE THREAD

**Issue by AngelAbov3** [SmartlyDressedGames/Unturned-3.x-Community#4737]
Voice chat volume slider doesn't seem to work

https://github.com/user-attachments/assets/3789f230-fc6d-43d5-adc6-4926c58e9218

**Comment by SDGNelson** [comment]
Thanks for the report! Wonder what I broke here. 🤔

**Comment by SDGNelson** [comment]
To add the new volume categories I converted the game's audio sources to use Unity's new audio mixer, and this required setting the output mix. When testing voice I typically enable local loopback to simplify. Turns out I forgot to change the non-loopback audio source to use the voice output mix. 😅 Will test this properly in multiplayer before the update.

**Comment by SDGNelson** [comment]
Double-checked **properly** tonight that the voice chat volume slider is working now. ;)
