### ISSUE TITLE
Transitions on main menu have lower FPS

### ISSUE THREAD

**Issue by ItsRodrigoAl** [SmartlyDressedGames/Unturned-3.x-Community#4745]
Now when you go from the main menu to any of the options like Play or Settings, there's a noticeable FPS drop compared to the previous version

**Comment by SDGNelson** [comment]
Thanks for the report! I think this might be caused by the particularly long update post being shown/hidden. 😅

**Comment by ItsRodrigoAl** [comment]
> Thanks for the report! I think this might be caused by the particularly long update post being shown/hidden. 😅

Actually this was happening on the branch version without the long update post being published yet, but just recently I remembered to report it after joining the game again because I noticed it again :S

**Comment by SDGNelson** [comment]
In order to support the previewyoutube tag I rewrote how the Steam BB code was tokenized and converted into in-game widgets. Previously, the text typically got broken into separate labels after a header like the "Additions" or "Changelog". Now, it was only broken into giant pieces of text, images, buttons, and youtube links.

I hadn't really thought about this having a performance impact, but if anything I would've assumed that fewer separate labels was better. Turns out: This wasn't the case! Indeed, on my PC it takes about twice as much processing time to move the main news feed on the new version with combined labels. Here's an example of the old breaking points:

![Before update](https://github.com/user-attachments/assets/85073a2f-b693-4e41-a1a5-448694128c7c)

Versus the breaking points in the update:

![After update](https://github.com/user-attachments/assets/d63cbac7-e7e9-428c-bdaa-c72c03746c58)

In response to the issue I've experimented with breaking on every new line vs breaking after certain numbers of characters. Breaking on every new line is worse, and certain number of characters doesn't work because even with no spacing on the vertical layout group it introduces a noticeable gap.

To work around it for the meantime I'm changing it to break lists apart, so all of the list items are a chunk of text separate from the labels before and after. This seems to be approximately the same as the pre-update performance!
