### ISSUE TITLE
I seem to be having issues buying items from the Stockpile

### ISSUE THREAD

**Issue by DenkoMali** [SmartlyDressedGames/Unturned-3.x-Community#4774]
I am unsure if I did something wrong I have tried so far 2 times ingame and 1 time on web wanted to spend a bit more money than usual in light of the discounts but it seems I am not allowed to hope this gets fixed I don't know if finding this issue makes me qualified for the bug Barret id prefer if the bug/issue get's fixed
![Screenshot_10](https://github.com/user-attachments/assets/9b0a391d-1e19-4e71-9ecf-34a4cb837136)
![Screenshot_11](https://github.com/user-attachments/assets/569a6bc2-23eb-4ed5-bfdc-8d4e65cc60a8)
![Screenshot_13](https://github.com/user-attachments/assets/53adf5ea-e27a-4e7c-857e-3ef420b601c0)

**Comment by DenkoMali** [comment]
![image](https://github.com/user-attachments/assets/b3523116-cdaf-417b-8935-b36696e3ef3d)
here is the web version of the cart

**Comment by Jdance-Media** [comment]
https://support.smartlydressedgames.com/hc/en-us/articles/12266602743188-How-can-I-get-the-purple-debugger-s-beret

**Comment by SDGNelson** [comment]
From us and on behalf of the item creators, thank you for your financial support! I think this is one of the largest Unturned in-game purchases I've ever seen. 0_o Sorry for the trouble!

And thanks Jdance, indeed, nowadays, if we know one or two players explicitly reported a bug, we'll include a thank you note crediting them in the changelog. This approach has worked well as a more balanced incentive for helping fix the game.

Technically, this in-game message is shown if Steam doesn't return a call handle when trying to start the purchase process. Considering you're getting a similar issue in the online checkout I think this is something you'll need to contact Steam Support about. Here's their support link: https://help.steampowered.com/

If it turns out they say it's an issue with Unturned though please feel free to comment and I'll re-open! Fingers crossed. 🤞
