### ISSUE TITLE
Vehicle to spawn teleportation exploit/bug

### ISSUE THREAD

**Issue by Hawsdhas** [SmartlyDressedGames/Unturned-3.x-Community#4816]
When getting out of a vehicle, if the player is blocked by a wall, structure or another vehicle, he is teleported to a random spawnpoint.

Attached is a clip of me performing the exploit/bug.

https://github.com/user-attachments/assets/39ecc511-5e08-4c50-a170-89fa70bcaf9d

**Comment by Astrepio** [comment]
Well, I don't really think this is a bug. It is done to prevent going through textures and the borders of the map. If you try to do the same with the Jet you will run into the same issue. I don't know what others will say but I would say that it is good, but why it happened with a metal structures I don't know.

**Comment by SDGNelson** [comment]
Thanks for the report, and thanks Astrepio for the answer! Indeed, this is intentional, albeit not intuitive. If the game is unable to find a reasonable spot to exit the vehicle it uses a spawn point instead. In older versions if the vehicle was completely boxed in it would try to find a nearby spot instead, but this was exploited to, for example, go through walls or teleport upward. The game *could* prevent exiting the vehicle if it's boxed in but this could get you completely stuck if you were unlucky and knocked the vehicle upside down into a narrow gap.

**Comment by Hawsdhas** [comment]
Thank you very much for clearing that up, hopefully in the future there is a way to "fix" this. Have a good day

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
