### ISSUE TITLE
Vehicle Turning

### ISSUE THREAD

**Issue by vduin1233** [SmartlyDressedGames/Unturned-3.x-Community#4823]
Not able to turn vehicles on my server. ( its only with modded vehicles, ive tried from multiple mods)
Vanilla vehicles work fine.

**Comment by vduin1233** [comment]
https://medal.tv/nl/games/unturned/clips/jjHX278frTHBh24m-?invite=cr-MSxtOEcsMjg2Mzc1OTE2LA

**Comment by Aiden9034** [comment]
https://www.youtube.com/watch?v=Gtp-uIIYc1Y

This is a link to a video with some vehicles from different mods that are affected.

**Comment by SDGNelson** [comment]
Thanks for the report! It looks like the issue is with converting vehicles from prior to the "WheelConfigurations" addition and the SteeringAngleMultiplier getting set to zero. Sorry for this trouble. It should be a straightforward patch this afternoon, but I'll wait a bit in case any other reports come up.

**Comment by vduin1233** [comment]
Its fixed, cars turn again!
