### ISSUE TITLE
Changing buttons doesnt cahange the button in the game UI 

### ISSUE THREAD

**Issue by Happy12222** [SmartlyDressedGames/Unturned-3.x-Community#4828]
https://github.com/user-attachments/assets/1fbe378e-1466-4365-86bf-02015b4cf98e

**Comment by SDGNelson** [comment]
Thanks for the report! It _should_ update the next time you load into the world. The way 3 handles input prompts is *not* how I would implement it nowadays - it formats the input name into the translated text on a case-by-case basis, rather than a UI element representing an input binding. If doing a giant input refactoring update this would be overhauled, but otherwise is not going to change in the near term, sorry.

**Comment by Happy12222** [comment]
👍
