### ISSUE TITLE
Couple improvements

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#517]
1. First thing that really confuses me is how sights/aiming is working. You basically need to create external sights for each weapon in order to make it work aesthetically. If you set "sight" object in a right position (so it would look good while aiming without external sight) then if you attach external sight it will hang up in the air or something like that. So my suggestion would be let content creators to insert "aim or something like "sight_1"" object to weapons (example below). Would work like that: if you don't use external sight then aiming will go through aim object and if you attach external sight it will aim through sight object. This would also let to get rid off bunch of iron sight mods and reduce overall size of mod packs. Not really sure if its possible to do but I think that would be a cool addition.
![image](https://user-images.githubusercontent.com/14231707/50539020-15265b00-0b82-11e9-8ebe-841e7166a78a.png)

2. No water volumes doesn't work or I don't know how to properly use it (tried through devkit and simple editor). I believe its supposed to remove water?

3. Removing spawns which are hanging in the air is kinda impossible without building some high object near them. Especially annoying when you add bunch of spawns in some location and change landscape height.

4. Would it be possible to get Hatch example asset?

**Comment by khakers** [comment]
iirc water volumes add water in areas as opposed to removing them.

**Comment by baranmod** [comment]
nah, there are water volumes and no water nodes I believe

**Comment by SDGNelson** [comment]
1. Originally added for the scoped Ace I believe. The sight is always attached to the 'Sight' transform, but if there isn't a sight attachment the viewpoint will use a 'View' transform.

2. Poorly named. The no-water flag for the sound volume was added because the bottom of Silo 22 was too close to the sea level meaning you could hear waves.

3. Agreed it's annoying. Best way is to create a temporary object though. Not sure how I'd handle this in the future since it's not obvious where the depth should be for a 3D brush without a hit.

4.  Here's the hatch from 5.5: https://drive.google.com/file/d/12_DPhL-Fb8ax1R8msJs9ymU_T__HJQsh/view?usp=sharing
