### ISSUE TITLE
.asset file appears after subscribing to mod

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#518]
So problem is pretty obvious: when I subscribe to some mod - .asset file appears for some items (randomly, but usually for same items). And it breaks that item until I delete this .asset file. what could be the reason why this file appears? 

![image](https://user-images.githubusercontent.com/14231707/50544056-b7c9f280-0bf1-11e9-972d-94316d11620f.png)

**Comment by baranmod** [comment]
Also, pretty sure that these files only appears after I update mod. Never faced same problem when I do fresh upload

**Comment by Trojaner** [comment]
Have you got any errors in log when the asset file is there?

**Comment by SDGNelson** [comment]
IIRC there was some partially finished work to support converting the flat .dat files to key-value .asset files, but the only vanilla example was the Ace. Unturned's likely failing to load it due to some flags that weren't supported by the .asset format yet. I wonder if you opened those .dat files with the devkit which may have triggered the automatic conversions?
