### ISSUE TITLE
LTS Issues

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#535]
I'm using Linux, so most of the bugs are probably just a Linux issue.

With the latest update, server icons are really dark, though someone asked if my server network got a new logo, so that must be a global issue.

![image](https://user-images.githubusercontent.com/10360610/51420700-45419800-1b49-11e9-927b-b8d1449b6637.png)

Scroll wheel scrolling seems to be backwards. Scrolling up goes down and down goes up.

Ambient Occlusion still gives you wall hacks (Definitely a Linux issue)...

![wallhax](https://user-images.githubusercontent.com/10360610/51420800-6d7dc680-1b4a-11e9-8db0-b8fdd6b7d09f.png)

Everything else works! Great job with the update Nelson! :D

**Comment by SDGNelson** [comment]
Thanks! Some good news, some bad news.

Looking into the image download it looks like unity wasn't setting the linear color space flag on downloaded images (from webrequest.texture) so now the game creates a texture and uses LoadImageIntoTexture, but interestingly the workshop images using newer unity UI display correctly with gamma space so I'll leave those linear space off. Comparing the server list icons using a color picker to the websites of the server networks icons they look correct with linear space now so that should be fixed!

Bizarrely the AO issue seems fixed for some players and still broken for others. That, and the scrolling issue might be out of my hands for the moment. 😕 On the bright side now that we're on a supported unity version there's a change that they will be patched!
