### ISSUE TITLE
Docs for SDG.Unturned

### ISSUE THREAD

**Issue by BrinzaBezrukoff** [SmartlyDressedGames/Unturned-3.x-Community#566]
Hello!
Where I can find docs for SDG.Unturned libraries?
Because this library is very important in plugin development, but decompiling not very good method to learn this library...

**Comment by SDGNelson** [comment]
In order to distribute c# docs I'd normally enable the .xml documentation export in visual studio, but since Unity regenerates the .sln files any time the project changes those settings are lost.

Could be done by not using UnityVS, but I don't think it's worth it because hardly any of the plugin-facing API is documented. Most of the original code (2014-2016ish) is undocumented, it was only late 2016 or 2017 that I properly got into the good habit of documenting everything.

If you know a command-line script to export the documentation for a VS project I'll happily add it as a build step to automatically include the .xml docs.
