### ISSUE TITLE
Support non-default shaders on platforms other than Windows

### ISSUE THREAD

**Issue by aviadmini** [SmartlyDressedGames/Unturned-3.x-Community#57]
Currently shaders are either swapped to standard shader (`Standard (Decalable)` I suppose, tell me if I'm wrong) or they use `Asset_Bundle_Version 2`. The latter doesn't work on Mac (and supposedly Linux) so it's just producing pink textures textures. 

Example: using `Particle/Blended` shader from Unity works well on Windows and shows pink texture on Mac.

**Comment by SDGNelson** [comment]
I don't think this is on the game's end, rather what platforms the asset bundle supports. Off the top of my head the official asset bundles might work with other shaders because they're explicitly included with the game (Graphics -> Always Included Shaders) while the non-official ones are built for windows. You might need to build the asset bundle for windows, mac and linux in which case it might make sense to add an option to the game to look for {AssetBundleName}_{Platform}.

**Comment by aviadmini** [comment]
Does that mean that there's no way *right now* to use asset bundles with custom shaders on multiple platforms?

**Comment by SDGNelson** [comment]
For the moment you could have a different version of the asset bundle for those other platforms.

**Comment by aviadmini** [comment]
Thanks for answers ;)

And yet I have a more specific one
Realistically using a workshop item with custom shader and making it work properly on multiple platforms is not doable at the moment?

**Comment by SDGNelson** [comment]
Through the workshop no, but I have added it as an issue: SmartlyDressedGames/Unturned-3.x-Community#60
