### ISSUE TITLE
Blimp is glitchy

### ISSUE THREAD

**Issue by evermoreservers** [SmartlyDressedGames/Unturned-3.x-Community#594]
Player report.. As Blimp supposed to stay in the air, it is very annoying to see how glitchy it is, turn down to let you fall off and still stay in the air to not let you Access it anymore.

https://youtu.be/MmZlj6qh5LQ

**Comment by SDGNelson** [comment]
That does look pretty wacky... I'm sorry to say though that being able to stand on simulated vehicles is unlikely to improve (and got worse after the recent update because of) the overlap change which means that when player and vehicle simulation disagree and get slightly inside each other the vehicle has to be the one to try and separate itself (causing the turbulence there). On the bright side: once this prone->standing exploit is patched there shouldn't be any more glitch-into-wall exploits thanks to the overlap change?
