### ISSUE TITLE
"Unofficial Modules Not Supported" Delay

### ISSUE THREAD

**Issue by N1GHTPATROL** [SmartlyDressedGames/Unturned-3.x-Community#630]
When I have a module installed, instead of kicking me immediately off servers it seemingly waits around 4 or so minutes before kicking me. I'm not sure if this is intended but I know how powerful modules can be.

**Comment by Coopyy** [comment]
i agee

**Comment by SDGNelson** [comment]
A BattlEye kick for module not supported? I'm surprised it let you start up the game. Originally I intended to allow clientside modules, but I'll adjust this.

**Comment by Coopyy** [comment]
you should allow clientside modules

**Comment by SDGNelson** [comment]
Double-checked and when BattlEye is enabled it does skip the module loading step, so I suspect it's not loaded and instead BattlEye is kicking because there was something in the modules folder.

I assume the module you had was Rocketmod? Intention I guess is that servers are in a separate install from the game client e.g. through SteamCMD.

**Comment by justboughtmarmalade** [comment]
@NIGHTPATROL just force delete modules while in game simple
