### ISSUE TITLE
add new ModHooks 

### ISSUE THREAD

**Issue by VitaxaRusModding** [SmartlyDressedGames/Unturned-3.x-Community#678]
List mod hook:

1. EventOnTriggerEnter.cs (player(tag))
2. EventOnTriggerExit.cs (player(tag))
3. SDG.Unturned.WebImage.cs (it works)
4. EventOnUseInteractable.cs (open,use class Interactable)
5. SetPlayerParentTransform (Add a player to the parent object (elevator, etc.))

I would like to see Interactable.cs (NPC and light and etc) in this list. Or something similar, I hope you understand what I mean ...

I noticed that some developers use  VehicleEventHook.cs

**Comment by VitaxaRusModding** [comment]
lookat.cs The script for the object to look at the player. For example, a billboard with a message.

**Comment by VitaxaRusModding** [comment]
Effect send client to server button message 
One more necessary thing, I encountered a system that can not be transferred to the player in the message text, for example, I made an ATM and I would like the player to be able to specify the amount he wants to put in the bank.
![image](https://user-images.githubusercontent.com/32962870/54551009-7d9e0f00-49f0-11e9-869d-86a82d31511f.png)

**Comment by SDGNelson** [comment]
For the ATM best current option would be having buttons for different amounts e.g. 20, 50, 100 which is how real ATM works anyway.

In your vehicle request these worked well since they were unity event callbacks for existing code, but parenting to elevators, interactables, lookat would all be new features.

I'll see about adding the player trigger, however #720
