### ISSUE TITLE
Invisible Players while Driving & Duplicated player while walking [BUG]

### ISSUE THREAD

**Issue by educatalan02** [SmartlyDressedGames/Unturned-3.x-Community#693]
![image](https://user-images.githubusercontent.com/34221626/54492438-f6a14780-48c6-11e9-9e7a-6b95f9d7b32e.png)

There's not logged anything in Unturned.log 
That's very suspicius, when a player left a car It makes a copy of him.

**Comment by glxygmng** [comment]
Don't have any screenshots however I had this issue when I banned someone; a relog fixes it however. No idea if this is the same issue.

**Comment by Trojaner** [comment]
Sounds like a desync bug a plugin would cause, to be honest.

**Comment by SDGNelson** [comment]
Looking through the relevant code nothing jumps out to me, and I can't imagine which code would be duplicating the player object without breaking everything 🤔 

Since it's obviously a modded vehicle I'm inclined to think some sort of unexpected setup is changing something. Could you post the output_log.txt please?

**Comment by educatalan02** [comment]
Sincerily I don't have the output_log.txt

**Comment by SDGNelson** [comment]
Will close for the meantime, but anyone feel free to reopen if there are some repro steps
