### ISSUE TITLE
Fatal error in GC

### ISSUE THREAD

**Issue by Johnanater** [SmartlyDressedGames/Unturned-3.x-Community#711]
Sometimes when an Unturned server (on Windows) shutdown, it crashes with the message "Fatal error in GC, SuspendThread failed" The server doesn't actually close completely and the exe is still running in the background, causing chaos with my automatic restart script.

The only log that I can find is a file created in the server root directory called "Unturned.gc.log". I've uploaded it and the error message. 

![gc](https://user-images.githubusercontent.com/10360610/55270187-5568a880-5259-11e9-9a57-2be5c7e2dcc9.png)
[Unturned.gc.log](https://github.com/SmartlyDressedGames/Unturned-3.x-Community/files/3025045/Unturned.gc.log)

**Comment by SDGNelson** [comment]
Looking this error up there seem to be a decade of posts about it, with a lot of responses saying it was related to anti-virus, but I doubt there's anti-virus on a dedicated server
One thing I would suggest however is adding a timeout to your auto-restart so that if the process does not close gracefully after a threshold you terminate it and proceed. This way you're resilient against other shutdown issues if they come up

**Comment by Johnanater** [comment]
Yikes
