### ISSUE TITLE
Invisible airdrop effects

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#740]
Have any changes been made with airdrop effects in the last couple updates? Not sure why but big part of players can't see airdrops (plane and supply crate fall effects) - supply crate is only visible when it lands on the ground.

**Comment by Th3God** [comment]
Afaik this happens on France only - right?

**Comment by baranmod** [comment]
no, custom map

**Comment by SDGNelson** [comment]
No changes to that code recently, and testing on my server it seems to work okay. There aren't any plugin hooks aside for spawning airdrops, so that's out of the picture. Only thing that looks like a potential cause is if the airdrop state isn't sent / received, but that would be a bigger underlying network issue.

Is it that some specific players can't see while others can, or that nobody at all can see sometimes?

**Comment by baranmod** [comment]
I've tested today and it seems like the first player who joins a server sees them while others don't. First airdrop (after server restart) is visible for every player but only first one.

**Comment by SDGNelson** [comment]
Interesting, that's bizarre... after your comment tried a few extra cases and didn't replicate it, but I've two minor changes we'll see if affects it.

**Comment by baranmod** [comment]
tested vanilla airdrops - they seems to work fine. Probably something wrong with a plugin

**Comment by glxygmng** [comment]
I have had this issue too. I believe it was occurring to me when I would teleport.

**Comment by SDGNelson** [comment]
Will close for the moment then. Feel free to re-open!
