### ISSUE TITLE
Add possibility to change vendors currency to items instead of XP

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#784]
Would it be possible to add currency option for vendor NPC? Like currency [item id]? For now its very limiting and XP is not really an option for PVP servers.

**Comment by SDGNelson** [comment]
I sympathize with this, but it would be quite a few changes to revamp the vendor in 3. I'll leave it open to maybe implement in another future update (planning to work on 4 in the coming weeks).

As for 4, I intend to implement bartering for NPCs rather than fixed XP currency. e.g. some NPCs trade for bullets, some for pre-apoc cash, some for items directly

**Comment by SDGNelson** [comment]
This has been added in the next update! Here's the documentation: https://github.com/SmartlyDressedGames/U3-Docs/blob/master/Currency.md
