### ISSUE TITLE
Small bug about Should_drop_on_death

### ISSUE THREAD

**Issue by BREEZEXPVP** [SmartlyDressedGames/Unturned-3.x-Community#831]
_Small bug_ 
**I Was playing with the Should_drop_on_death, but it seems not working**

i put should_drop_on_death false with in my item but not working at all same with true the item drops even if the data is on ; false.
But if you put the config to drop rate only 75%  of your inventory then the option true will not drop some times i'm sure if the drop rate to 0.0% in the Server config then the item will not drop even with should drop true.

**You can see Here my Item Data is on Should_Drop_on_Death false**
![20190611193146_1](https://user-images.githubusercontent.com/40163506/59293498-9892bf00-8c7f-11e9-8a05-ff7bb16c0be8.jpg)

**Thanks**

**Comment by SDGNelson** [comment]
There's been a lot of confusion about this because it's very literal to the option description. When it's enabled the item will not be spawned as an interactable drop, but will also not be retained after respawn. In the future there could maybe be a Should_Keep_After_Death option, but that would be problematic unless all the clothes were kept as well.
