### ISSUE TITLE
PlayerCrafting - onCraftingRequested not static

### ISSUE THREAD

**Issue by pastet0422** [SmartlyDressedGames/Unturned-3.x-Community#847]
All events should be public and static cuz PluginMakers need to use it.
onCraftingRequested - not static
When i tried use new PlayerCrafting().onCraftingRequested +=
Its dont works

**Comment by Trojaner** [comment]
Why does it have to be static?

**Comment by Eatric** [comment]
Understand before offering, ask knowledgeable people. Thanks

**Comment by Eatric** [comment]
Understand before offering, ask knowledgeable people. Thanks

**Comment by pastet0422** [comment]
> Why does it have to be static?

cuz i cant add to event my method(or event just dont works), maybe u have other ideas what can i do in this situation ?

**Comment by Trojaner** [comment]
Maybe you should first research what static means and what instance means and what they are used for.
You need to get the players instance and subscribe to the event from there.

```cs
Player player = ...
player.crafting.onCraftingRequested  += ...
```
something like that.

You can use Provider.clients to do this for everyone and you should also subscribe to join events and do that there.

**Comment by pastet0422** [comment]
Just strange, in args of delegate contains PlayerCrafting,then why do I need this argument?

**Comment by Trojaner** [comment]
Because often you are going to use the same event method for all players, so you need some way to distinguish them and to grab an instance.

**Comment by pastet0422** [comment]
but,i think be right if Nelson give static to this event

**Comment by SDGNelson** [comment]
Trojaner is correct, however I see where you're coming from considering all of the other plugin events are static. It's a lot easier to bind a static event than to keep track of the different player objects.

I'd probably been working on 4 when I added onCraftingRequested since 4's code does not have any static events. Obviously a lesson I learned AFTER developing most of 3's older features.

In tomorrow's update I've marked onCraftingRequested with the obsolete attribute, and added a static onCraftBlueprintRequested event.
