### ISSUE TITLE
PSA: Switch to Dedicated Server App

### ISSUE THREAD

**Issue by SDGNelson** [SmartlyDressedGames/Unturned-3.x-Community#855]
Now the dedicated server is available in a separate steam app which can be downloaded without a login, strips client files e.g. foliage for faster updates, and automatically keeps the steam redistributables up-to-date.

Using SteamCMD you can run the following commands to download it:
login anonymous
app_update 1110390

If there's a reason not to update, please post here! I'm happy to help work out any kinks in the process, and Valve has requested we switch to the dedicated server app.

Edit: To make hosting on Linux easier I'm including a script in the .3 patch called ServerHelper.sh which fixes issues with finding steamclient.so: https://gist.github.com/SDGNelson/9500b9f754cf711a2678f2a0a0f3e02d

**Comment by Kenzim** [comment]
Thanks for this, Nelson. Not only will this hopefully improve stability and performance, but also make server management easier. RIP my twenty plus steam accounts for downloaded with steamcmd.

**Comment by Trojaner** [comment]
Thank you very much, this is really useful.

**Comment by HanaForward** [comment]
Thank you very much, this is really useful.

**Comment by SDGNelson** [comment]
In the .3 patch tonight I'm including a script for the Linux server called ServerHelper.sh which fixes issues with finding steamclient.so: https://gist.github.com/SDGNelson/9500b9f754cf711a2678f2a0a0f3e02d

**Comment by Ascivv1** [comment]
What version of Unity does this build use?

**Comment by SDGNelson** [comment]
The game and dedicated server use the same version: 2017.4.24f1

**Comment by Ascivv1** [comment]
Is that the latest version?

**Comment by SDGNelson** [comment]
Nope, the latest is 29f1.

**Comment by HanaForward** [comment]
@SDGNelson NOT WORKING 
https://gist.github.com/SDGNelson/9500b9f754cf711a2678f2a0a0f3e02d
Can you take a course？

**Comment by SDGNelson** [comment]
> @SDGNelson NOT WORKING
> https://gist.github.com/SDGNelson/9500b9f754cf711a2678f2a0a0f3e02d
> Can you take a course？

For future reference by others reading this thread, it looks like it was sorted out here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/860#issuecomment-505312331

**Comment by Mithallas** [comment]
Are we supposed to put 1110390 in its own folder and run the server from there or are we just force installing 1110390 to the original game files for faster updates?

**Comment by SDGNelson** [comment]
The new app is completely separate, and by default installs to a folder named "U3DS" for short. (quicker from the command prompt than Unturned Dedicated Server)
Intention is that you simply run app_update 1110390 and install to the default location.

**Comment by joemisfit** [comment]
I definitely look forward to rolling out the new update to the few community dedi's I manage within this next week, all I've heard is good news so far, and with the automatic updates that's awesome to hear, rather than worrying about using steamcmd updates each time a update is released. Stripping a bunch of the code for the dedicated clients is probably for the best since most of us tend to stare at the cmd prompts waiting for errors to appear on load while all assets including foliage generate. 

Something definitely useful! Kudos!

**Comment by joemisfit** [comment]
Hey @SDGNelson,

I saw that with the original post that this app will keep the steam distributables updated however in order to get the updates aren't we still supposed to use an updater like steamcmd to pull the update from steams servers for both the distributables and Unturned's App itself?

Thanks!

**Comment by SDGNelson** [comment]
Steam will automatically keep the redistributables up-to-date for the dedicated server app, so the only command you should need is periodically updating 1110390 using steamcmd.

**Comment by Johnanater** [comment]
Kinda late to the party, but I recently switched my servers over to the new dedicated server and have got reports that it runs a lot better! Thank you Nelson!
