### ISSUE TITLE
Duplicated IDs problem

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#878]
This problem existed pretty much always but after recent updates it became even more painful. 

Basically, player joins some modded server and later connects to another server (without relaunching game) - he will see completely different items than they are supposed to be. For example: some rose instead of a door, which actually gives some kind of advantage against other players.

Another thing which came up after recent updates: missing objects even if IDs are the same but different workshops (reuploads). The problem also appears when player is subscribed to some workshop which contains duplicated content. For example, player joins server which is using reuploaded content and later connects to a server which is using original one (or vice versa) - he won't see objects used on the map.

**Comment by TheCubicNoobik** [comment]
Also player can't connect to a server if it connected to another server with a modified map before.

**Comment by baranmod** [comment]
Also, apparently, if workshops duplicated and player doesn't see objects - he can shoot through them. Which ends up in abusing - uploads separate workshop with same objects - profit :D 

Didn't test shooting myself yet, but will do it later and drop an update on this issue

**Comment by SDGNelson** [comment]
Re shooting through objects: on the client they will see hitmarkers, but as long as the server does have the objects loaded their incorrect hits are ignored.

At the time of this issue there were a lot of uploads that contained duplicate assets conflicting with each other, and since I added automatic dependency downloads it became a big problem, but I troubleshooted with quite a few modders and hosts to get that sorted out and going forward new uploads should not be doing that. It will also help that I'm dogfooding those systems with curated maps too. 😄
