### ISSUE TITLE
Make Flashbangs/Grenades not work in safezones

### ISSUE THREAD

**Issue by PandahutMiku** [SmartlyDressedGames/Unturned-3.x-Community#906]
It would be nice if grenades/flashbangs/smokes overall refused to throw in safezones or just did nothing. With the popularity of Unturnov, Safezones are used a lot in them (as well in other gamemodes/maps) and players love to abuse that they are unrestricted and blind people.

**Comment by SDGNelson** [comment]
Will do!

**Comment by pastet0422** [comment]
And players can damage vehicles if player not in safe-zone

**Comment by SDGNelson** [comment]
Fixed in the next update: now item assets have a method "canBeUsedInSafezone" rather than using the isDangerous property. isDangerous is marked obsolete and renamed to shouldFriendlySentryTargetUser, and flashbangs now count as dangerous.

Thanks pastet0422, in the next update vehicles should now ignore all damage in noWeapons safezones.
