### ISSUE TITLE
Custom Items

### ISSUE THREAD

**Issue by JustOneMoreBlock** [SmartlyDressedGames/Unturned-3.x-Community#927]
Hello Nelson,

On December 14th, 2018 you made changed to Unturned changing the game base engine to Unity 2017. Apparently, you did warn us that this would break every mod ever made. Unfortunately, googling for a solution today seems not-existent due to the fact the modding community seems to have disappeared because of changes.

I’m writing to you as I’m pleading for some form a solution to make modding easier in some form of fashion.

Originally, I was able to “Copy” specific “Items” from the game and was able to rename them and provide new IDS for these items. In the “dat files” you were able to customize your changes to your liking and place them within your `Bundles/Items/CustomPack` directory and also place it on your server using `unturned/Bundles/Items/CustomPack`

The first few issues with modifying the information. You don’t know the “Max Data” or if it can be “Inserting” to a specific item. For example, What’s your `Max IDs` Unturned or Unity can support? Because I’ve tried `ID 100000` and it said `Item not found` when trying to spawn it. Lowering the number down to `ID 10000` spawned majority of the items, however, it said `Item not found` on my modified Honeybadger.

The next issue is even if you got “working IDs” you cannot see the pack even though. I left all the `blueprint` settings to use the original ID so that way you wouldn’t need to specify `unity3d file` but appears you still need an image which you no longer supply as it’s with your `mastercorefile`.

Which brings me to a compatibility question. You provide “master core files” for Windows, Linux, and Mac. If you provided individual `unity3d` files would you have to provide different versions for different OSes too? I’m asking because a lot of staff uses Windows or Mac and the server uses Linux. If you make a solution to bring back to the modding community then it needs to be universal if possible.

Proposed Changes:
- Define a Max ID and let everyone know what it is, so we are not guessing OR 
- In “dat files” possibly add “Group” or something and call it “GROUP Unturned” for most of the normal items. If we modify “GROUP Custom” then we can use any ID including `1`. IDs would be spawned like /give g:Unturned/ID or /give g:Custom/ID
- Allow us to use skins from the mastercorefiles OR
- Provide us individual skins in the Extras/ folder to copy and paste that skin. I’m not going to download unity, try to learn it and then give up trying because you made it difficult. There’s no reason why this cannot be resolved. Unity 2017 isn’t the restriction here.

**Comment by RoyIL** [comment]
The max id is 65,535 (ushort)

**Comment by RoyIL** [comment]
However, all the issues you described here have nothing to do with Nelson. 
You say that the whole modding community died but you just described your problems which you're too lazy to solve.

**Comment by WCPistolPete** [comment]
@RoyIL : Cory's not lazy. Nelson changed to Unity2017 and it broke all of the mods for servers. Some maps and items have been upgraded but most have been abandoned. Tutorials on how to upgrade and integrate a few items, namely our admin gun, barrel, magazine and pack, are non-existent. Cory is asking for help in finding a way to update the model and integrate it into the new system. If you can't help, don't reply. Since Nelson made the change to update the platform, he should be very familiar with whatever steps need to be taken to incorporate this item. We're asking for assistance. We're not dumb either. Server operation and moderation are our strong points. Modding skins when the whole system switched over just happens to be a weak point for now.

**Comment by RoyIL** [comment]
Lmao, literally just download unity 2017 and asset bundle your models.

**Comment by khakers** [comment]
There's still the official unturned server and many other modding servers that are all active. I certainly wouldn't say the modding community has disappeared.

**Comment by RoyIL** [comment]
Yeah lol, I just see a server owners and his moderator complaining about bs because they're just too lazy.

**Comment by JustOneMoreBlock** [comment]
It's not about being lazy. I go above and beyond trying to make sure my Unturned is STABLE and at the moment it is. I'm trying to help my staff by providing them a custom pack to assist them, and unfortunately, with Unity 2017 update it made it harder as there is no information "On what to do?"

- I shouldn't have to download Unity to modify a simple pack.
- I shouldn't have to learn how to use Unity when the Editor in Unturned originally was designed to make things easier.
- I'm not a designer either.
- I'm not a game dev.

People who want to make a simple pack shouldn't have to go through all this trouble.

**Comment by RoyIL** [comment]
Lmao what a skid, you're just lazy. 
If you don't wanna do shit then just don't make mods, seems like you can't even understand the difference between unity and the map editor in unturned.

**Comment by RoyIL** [comment]
Now you gonna complain that you have to use blender to make guns lmao

**Comment by UFI8** [comment]
It's not like Nelson has made this harder on purpose, using Masterbundles has a lot of perks which help loading times and many other things.

There is resources out there if you just use google. 

I think people really have to stop bothering nelson about major new game features and such for Unturned 3.0, this game is only hanging on till II launch.




>     * I shouldn't have to download Unity to modify a simple pack.
Downloading unity takes 3 seconds, 
>     * I shouldn't have to learn how to use Unity when the Editor in Unturned originally was designed to make things easier.
Unturned was made to do a lot of things, like good networking, unfortunately nelson coded it when he was just learning unity and a bunch of stuff so it didn't work out well, and building off a bad base isn't exactly smart or efficient.
>     * I'm not a designer either.
>     * I'm not a game dev.
> People who want to make a simple pack shouldn't have to go through all this trouble.
Unturned 3.0 has a good amount of problems and inefficients, get used to it. Hopefully Unturned II will be a lot better, but you should expect things in Unturned 3.0 to be hard.

Saying the modding community is dead just because you can't figure out something isn't very informed, Unturnov is pretty big right now and I know a lot of people are continuing to make cool things for the game.

But yea, excuse my ranting a bit but at this point it's pretty obvious 3.0 is on emergency support only and not major new things, focus on II.

**Comment by JustOneMoreBlock** [comment]
I'm not _skid_ as you say. I'm not lazy. There is NO information on how to make these custom items for Unturned.

I don't know how to use blender either.

Nelson took an easy way and made almost impossible for someone that has no knowledge of Unity and is FORCED to download UNITY and make an item? From Scratch? I don't think so. This isn't knowledge that hardly anyone knows when running Unturned servers.

If you don't have any value to add, please stay off this thread. All you're doing is making yourself look like a troll and it's not wanted.

**Comment by UFI8** [comment]
> Nelson took an easy way and made almost impossible for someone that has no knowledge of Unity and is FORCED to download UNITY and make an item? From Scratch? I don't think so. This isn't knowledge that hardly anyone knows when running Unturned servers.
It's not that he took the easy way, he literally just converted all of his bundles to masterbundles for performance reasons,

There is a few reasons nelson gives inside of unturned's install itself
Default Path: C:\Program Files (x86)\Steam\steamapps\common\Unturned\Bundles\Sources
There's a lot of examples in there that might assist you, however in getting the models themselves, maybe there's some masterbundle extractor otherwise might need to get them from the man yourself if you really want to do this.

**Comment by Kenzim** [comment]
The base game is functional. I don't think Nelson has the time to implement simple in game editors for workshop items either. The workshop is for the community, it's not up to Nelson to maintain mods. If you want to repack mods, you should just ask the author. You probably need permission anyway. If you're so dedicated, go take unity course on yt for a few hours and join a modding community

**Comment by educatalan02** [comment]
There are a lot of guides/tutorials to modding. So don't say that.

**Comment by RoyIL** [comment]
There are literally 100 tutorials around the internet, again you're too lazy to even Google it.

**Comment by JustOneMoreBlock** [comment]
Thread has been trashed by trolls. Closing.

**Comment by QnAisbest** [comment]
Trashed by trolls? No. Just by people who are not lazy and know more than you.

**Comment by archie426** [comment]
What are you on about? All you have to do is look up something along the lines of how to make a mod in unturned. Compared to games like Minecraft, where you actually have to code the items, this is pretty easy, as long as you know how to model.
The editor in Unturned is for making CUSTOM MAPS not items. 

How else do you expect to actually load items into the game with a level of obfuscation so they can’t be stolen? This is how it is with all if not most games, I don’t know what you expect.....

You don’t have to LEARN UNITY to make a mod in Unturned. All you have to do is follow a damn tutorial, what is so hard?

Also how is someone calling you a “skid” being a troll? How is insulting someone trolling lol? Makes no sense. Just because we proved you wrong doesn’t make us trolls... if anything, it feels like you’re trolling xD

**Comment by archie426** [comment]
Also if you wanna say you shouldn’t have to use Blender... get out of here... how else can you expect to model (except using Maya etc.)

**Comment by WCPistolPete** [comment]
We have a model, we just want to convert it from the old unity to 2017. The original dev abandoned it when Nelson made the change to Unity 2017. Many mods, but not all, were abandoned. We know there's a good community out there, but quite a number of mods were abandoned with the change. Ours, unfortunately, was one of them.

We're simply asking if anyone can help us do the conversion, if it's even possible. We're not lazy. I ran modded game servers from 95 to 04, did custom maps for DOOM and DOOM2, skins for cars in NASCAR Heat and skins for planes in IL-2. This is just a system that neither Cory nor I are familiar with. Instead of everyone telling us we're lazy, stupid, or whatever, we're just not familiar with Unity and Blender. Tutorials that I've found all start with an extracted model. It's like starting in the middle of a movie. "Well you have this and click this and done." I can't figure out how to get our existing model loaded and get to the "Well you have this" part. The model exists but Unity wants to treat it as a map, not an asset. That's where I'm having trouble. I'm sure that is someone were to point either of us in the right direction once, we could update our model and all would be good.

It's like walking in at the middle of a Quentin Tarentino film. :P

**Comment by RoyIL** [comment]
I literally wanna cry right now.

**Comment by RoyIL** [comment]
You blame Nelson because you don't know how to do basic shit

**Comment by RoyIL** [comment]
And no you can't extract a model from asset bundle, if that's what you're asking.

**Comment by RoyIL** [comment]
And the part where unity treats it as a map doesn't make any sense lmao, it's not a Wikipedia for starters here. 
Go and ask around modding servers in discord.

**Comment by SDGNelson** [comment]
On a constructive note, regarding one of your original points about having custom .dats using the vanilla models:

The base game uses this in a few places, and quite a few mods as well. You can tell the game in the .dat to use another .unity3d / .masterbundle file with an override like:

Bundle_Override_Path /Objects/Medium/Furniture/Note

**Comment by QnAisbest** [comment]
@JustOneMoreBlock it is not allowed to modify mods somebody made without their permission
