### ISSUE TITLE
[FEATURE REQUEST] Vehicle debris despawn timer

### ISSUE THREAD

**Issue by danaby2** [SmartlyDressedGames/Unturned-3.x-Community#935]
When a vehicle explodes, it leaves behind a flaming wreck for a couple minutes. On regular maps, this is fine and cool but on my tiny map, these destroyed vehicles build up and start to clutter up the map quite a bit. Would it be possible to make an option to change how long these destroyed vehicles stay around for? Or maybe an option to turn them off completely?

**Comment by SDGNelson** [comment]
Cleaned up the related vehicle respawn code and fixed some edge cases, but when it came to the actual option I considered a few like:
- Level config despawn vehicle debris timer multiplier
- Level config immediately destroy vehicle debris
However I think the appropriate option might be to do a level override of the Vehicles.Respawn_Time value since any level config options would essentially be doing that. For an example the Destruction map has several overrides.
