### ISSUE TITLE
Effects with serverside custom data

### ISSUE THREAD

**Issue by Trojaner25** [SmartlyDressedGames/Unturned-3.x-Community#96]
Currently effects can not display any data sent by the server.

My idea is to trigger effects like this:
```cs
[SteamCall]
public void triggerEffect(CSteamID sender, ushort effectId, ..., string[] bindings)
```
(bindings is optional)

bindings would replace {0} in texts with bindings[0], {1} with bindings[1] etc...
(e.g. ```Hello {0}``` would become ```Hello Trojaner``` if bindings is set to {"Trojaner"})

This could use string.Format to implement it.

The reason why I ask for this is to have more dynamic effects possible (e.g. an effect displaying "You killed xxxxx!" on the screen)

Of course these effects with data binding should not be able to get triggered by triggerEffect without bindings or wrong bindings.

Actually I would prefer `object[] bindings` but that seems not possible with the current serialization.

**Comment by VitaxaRusModding** [comment]
Yes, many people dream about this, we had such a problem, either the animation of the effect, or many effects (same type), or chat.

**Comment by N1GHTPATROL** [comment]
This would allow for so much haha

**Comment by SDGNelson** [comment]
How do you propose the game find strings to format with your bindings?

**Comment by RoyIL** [comment]
@SDGNelson Hm?

**Comment by Trojaner25** [comment]
effects are unity prefabs so its a bit hard to have data on them

**Comment by SDGNelson** [comment]
Sorry - this is still on my radar, but not super high priority between balancing 4 and 3 development. I'm thinking the next update will be Christmas related, and then I'll be back to Calgary for the holiday. I promise I'll get at least formatting custom effect strings into [Text.text](https://docs.unity3d.com/ScriptReference/UI.Text-text.html) sometime January!

**Comment by SDGNelson** [comment]
This Friday's update has two new features available in EffectManager.sendUIEffect which should allow some neat stuff:

1. You can optionally provide a 16-bit "key" (or -1 to disable) which will remove an effect with the same key before spawning the new one. My thinking is that this will allow you to update effects rather than repeatedly sending them.

2. You can format up to 4 strings into your effect similar to the original post e.g. {2} will be replaced with arg2.

Closing the issue, but interested to see what you can make with it and further requests.

**Comment by Trojaner25** [comment]
Thanks,
But arent 4 strings a bit limited?
What about having dynamic size array instead?

**Comment by aviadmini** [comment]
Just use chunk buffer packet type with dynamic array of args :)

**Comment by SDGNelson** [comment]
It would be fairly straightforward to add read/write string array to the Block class, but in what cases would you need that many strings?

**Comment by Trankvil** [comment]
`EffectManager.sendUIEffect(3, 11234455, player.CSteamID, true, String.Format("Hello"), String.Format("Man"), String.Format("Man"), String.Format("Man")); `
is dont work

**Comment by aviadmini** [comment]
@Trankvil https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/short Special for you

@SDGNelson ... `sendUIEffect` without steamID parameter methods are booed. You need to call not `tellUIEffect`but overloads with arguments like `tellUIEffect4Args` since you're sending those

Otherwise works fine. Something like [https://youtu.be/ZQbvzb13vFE](https://youtu.be/ZQbvzb13vFE) is doable without pain in the ass

**Comment by Trankvil** [comment]
@aviadmini ```
EffectManager.manager.channel.send("tellUIEffect4Args", steamID, (!reliable) ? ESteamPacket.UPDATE_UNRELIABLE_BUFFER : ESteamPacket.UPDATE_RELIABLE_BUFFER, new object[]
			{
				id,
				key,
				arg0,
				arg1,
				arg2,
				arg3
			});
```
this code?

**Comment by aviadmini** [comment]
@Trankvil You don't need this

Btw @SDGNelson there's no way to remove effect from indexed on client, is there? (key = -1 simply destroys effect)

**Comment by Trankvil** [comment]
@aviadmini stop. i dont understand... me need download mod in workshop?

**Comment by aviadmini** [comment]
If you want it to work - yes 💃 

@SDGNelson Could you also add an option to **update** current effect, not just spawn a new one with new string? I can provide the code

**Comment by Trankvil** [comment]
@aviadmini i have code:

> EffectManager.createAndFormatUIEffect(3, sdd, String.Format("Hello"), String.Format("Man"), String.Format("Man"), String.Format("Man"));
I understand, I need to have a mod with a canvas, where I want to output, right?
