### ISSUE TITLE
Why 'list' is 0

### ISSUE THREAD

**Issue by EveryWhere1337** [SmartlyDressedGames/Unturned-3.x-Community#961]
I'm having a code, where i'm getting barricade in radius via                 BarricadeManager.getBarricadesInRadius(player.Position, 40, list);

Why list.Count is always 0

                var list = new List<Transform>();
                BarricadeManager.getBarricadesInRadius(player.Position, 40, list);
                UnturnedChat.Say(player, list.Count.ToString());

**Comment by RoyIL** [comment]
Are u sure that there are barricades around you?

**Comment by EveryWhere1337** [comment]
> Are u sure that there are barricades around you?

Yes, have been near with locker and others

**Comment by Charterino** [comment]
As I remember this function is created for somethink different. Try to iterate all the barrricades.

**Comment by SDGNelson** [comment]
The overload that takes a list of regions is for iterating world barricades, whereas that overload is for barricades on vehicles. At the moment there isn't a combined helper method because the caller often re-uses a list of regions between multiple queries. For example DamageTool.explode uses Regions.getRegionsInRadius into regionsInRadius and uses that for a few systems.
