### ISSUE TITLE
Server doesn't load objects masterbundle

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#968]
Not really sure whats the problem. It already happened in the past as I recall. Basically - I upload my masterbundles to wokrshop/content. I load a server, join it and other players can't see any objects from that masterbundle. If player press "page up" then all objects are magically visible (same if subscribed to workshop or have same workshop uploaded by himself). What could be a problem?

There are definitely no duplicates as I checked it 10++ times

**Comment by SDGNelson** [comment]
Uploading the item manually to the Workshop/Content folder? Why not use the automatic workshop download feature?

Pressing the "page up" key while in-game on the server is causing the objects to become visible?

**Comment by baranmod** [comment]
Yes, they do become visible after page-up, tried auto downloaded - didn't help

**Comment by SDGNelson** [comment]
To double-check that it works properly I set a test server's map to Hawaii which auto-downloaded the separate Hawaii Assets workshop item. When connecting to the server it downloaded the separate Hawaii Assets item, loaded the hawaii.masterbundle and loaded the objects properly.

If I understand correctly you're saying that while IN the editor or playing on the server you reloaded the assets and they became visible? The game doesn't reload the spawned objects so that doesn't make sense.

**Comment by baranmod** [comment]
Well, I can send you an IP so you could see yourself? It might not make sense - but it happens sadly

**Comment by baranmod** [comment]
149.202.86.215:27015 Password: 86869
We already tested with multiple players - all got the same result

**Comment by SDGNelson** [comment]
Tried that address but didn't find a server. Is it offline now?

**Comment by baranmod** [comment]
yeah, validating files, should be up in couple min

**Comment by baranmod** [comment]
ok, its up. Files validation didn't help either

**Comment by SDGNelson** [comment]
For the future I'd suggest checking out the UnityDebug_Client.log file from the Logs folder when tracking down these issues clientside. It looks like most of the problems are due to duplicate asset bundles, for example workshop item 1748033578 contains greece.masterbundle. Unity prevents loading an asset bundle with the same files twice.

**Comment by baranmod** [comment]
here how it works: https://streamable.com/vdrne

**Comment by SDGNelson** [comment]
Since it's some internal asset bundle thing maybe that explains why the assets become valid, but still odd. It also looks like the onItemInstalled callback is running for those downloads (which it shouldn't) so I'm fixing that up, and I'm making some changes to find the original asset bundle when a duplicate asset bundle is found.

**Comment by baranmod** [comment]
I believe this update helped. At least, didin't get any reports from players. Thanks :)
