### ISSUE TITLE
Optimization!

### ISSUE THREAD

**Issue by Edsparr** [SmartlyDressedGames/Unturned-3.x-Community#98]
At the moment the  optimization for structures and barricades are quite poor, on RP servers if you build too much the client crash which is a major problem which prevent a good RP without someone cleaning out bases 24/7 which almost noone has time to do so what I request is that you just take a day or 2 and fix  the  problems in how theyre done and it would help the wwhole community a ton!

**Comment by Savagethepanda** [comment]
It won't even matter because nelson is optimizing unturned in 4.0

**Comment by Edsparr** [comment]
Well I doubt unturned 4.0 will come out any time soon? So why not make people have a better time meanwhile?

**Comment by N1GHTPATROL** [comment]
This issue is quite pointless. Your problem with Unturned is not something that can be fixed easily, at all. The reason Unturned 3.0 doesn't perform as well as other games is because of the way Unturned was built in unity. Full optimization of Unturned would take an entire rework, which could take many months or more. Nelson understands this, and there'd be no point in doing that if he can just make a new game in a much better game engine. What I'd say is just be patient, it will pay off. Give him time.

**Comment by Edsparr** [comment]
Exactly n1gghtpatrol I fucking know that and why focus on a  4.0 that wil ltake like  forever and until then everyone is so tired of unturned is my guess so noone will even bother going to 4.0 nd because its in c++ no rocket will exist and prob not any other modloader? whats better a game that wont be dead or delayed 4.0?

**Comment by FredMods** [comment]
Huh?

**Comment by SDGNelson** [comment]
Unfortunately at this point there aren't any prime straightforward targets for optimization anymore, but yes profiling saves with large bases has yielded some nice improvements in the past.
