### ISSUE TITLE
Auto Update Linux

### ISSUE THREAD

**Issue by Ascivv1** [SmartlyDressedGames/Unturned-3.x-Community#988]
Could you add an auto-update function to Linux servers where SteamCMD will detect an update, shutdown the server, update the server, and then start the server? This feature would be greatly appreciated.

**Comment by Alekaei** [comment]
not related to the core game, wasting time, get a auto update script its easy

**Comment by LTKWatermelon** [comment]
I feel it could go both ways @Alekaei and @Ascivv1. Most servers do not have an auto-updating script @Alekaei and they may not want to spend the money to get one made. On the other hand, I feel if they did add the script, on both Windows and Linux machines, it would provide a great addition to the servers because all of the servers on the list would be updated.

**Comment by Eatric** [comment]
Why only Linux?

**Comment by Alekaei** [comment]
an auto update script is easy to write no reason to limit it to just windows, i wrote one over the weekend in a little over 1 hour. Its not difficult and there are loads of steamcmd auto updaters online

**Comment by Eatric** [comment]
I agree

**Comment by Ascivv1** [comment]
send me it then

**Comment by Alekaei** [comment]
please close this issue, its a waste of nelsons time

**Comment by LTKWatermelon** [comment]
^

**Comment by Ascivv1** [comment]
no thanks

**Comment by Trojaner** [comment]
I agree with Alekaei this is unrelated to the core game

**Comment by JustOneMoreBlock** [comment]
Since everyone is an ass about everything.

https://github.com/JustOneMoreBlock/unturned-scripts/blob/master/unturned-updater.sh
