### ISSUE TITLE
Official Vanilla Maps for Roleplay Servers?

### ISSUE THREAD

**Issue by joeymisfit** [SmartlyDressedGames/Unturned-3.x-Community#991]
Hey @SDGNelson 
I don't really mean to barge in on bigger issues that we currently have going on right now but I've been thinking for a little bit now, would it be possible to have a few revisions done to perhaps Washington or PEI for all of the RP servers that are out there and consider those official maps as well? Making it so that two versions are available. The reasoning behind that is because most full rp servers have to rely on vanilla maps and end up being too laggy because they have to use custom safezone plugins over towns like Seattle for living and shopping areas and by the time people get settled in, the safezones tend to lag miserably due to the killing of zombies, damage protection, and whatever other flags they have enabled in each region. I probably wouldn't recommend enabling safezones through map editor, however, since you can't really place items unless they are in-game edited in. A con for using workshops is that it doesn't really list publically right as you search via online like most kids do, unless they use the workshop function for maps. I think that if just a revised map were to happen it would please quite a bit of the community. Shucks, I'd even be willing to help with fixing up the towns with the spare time I have.

Let me know, Thanks!

**Comment by SDGNelson** [comment]
For this sort of thing I do think using a workshop custom version of the map would be ideal. I'm not sure what you mean by workshop servers not listing properly however, if there's a bug I should take a look into it?

**Comment by joemisfit** [comment]
Hey Nelson,
Thank you for responding, from what I've ascertained in the past say if I were to name the workshop "Washington" it would still have to be selected on the Directory when searching as a workshop map in order for players to find it rather than a true vanilla map. So as a feature suggestion for Unturned 3 I was thinking maybe you'd consider allowing someone to make a few of the small and/or medium maps as a trial basis to see how the community and server owners would react towards FullRP revamped maps.

**Comment by SDGNelson** [comment]
Sorry for the delay: if the map name is identical there will be issues, but if even slightly different it should work fine. For your case I'd suggest something like RP_Washington so that it's easy to search. If you do decide to make that and run into issues conflicting with the base map I'll get them fixed up, but I'm fairly confident it should be fine!
