### ISSUE TITLE
Option to set the local position of a GameObject for UI Effects

### ISSUE THREAD

**Issue by RoyIL** [SmartlyDressedGames/Unturned-3.x-Community#996]
Can you please add an option to set the local position of an GameObject within a UI? 
Just like SetLocalPosition(string Name, Vector3 Position). 
Thanks!

**Comment by Charterino** [comment]
Yeah. So every dev would make universal UIs that are centered, and we could move them. That would be useful.

**Comment by Greenorine** [comment]
Yeah, I like it too

**Comment by SDGNelson** [comment]
Meant to respond: yes I can definitely see this being useful. SoonTM I'm hoping to start rewriting certain parts of the netcode, and as part of that give more control for custom UIs to do stuff like this, whereas right now the "EffectManager" is getting bloated.

**Comment by SDGNelson** [comment]
Closing because the issues list was not really intended for feature requests. Sorry to close this discussion - I do WANT to fulfill all (most?) requests, but it is a matter of prioritization. Constantly being reminded of all the pending requests when checking issues is stressful. I will keep the request in mind. On GitHub maybe the Ideas section of Discussions would be the best place.
