### ISSUE TITLE
Bug with kills_player condition for quests

### ISSUE THREAD

**Issue by baranmod** [SmartlyDressedGames/Unturned-3.x-Community#997]
When player doing a quest he gets kills when other players kills someone in set nav tab too (or maybe whole map). I guess it shouldn't work like that and instead player should get kills only when he kills someone himself?

**Comment by SDGNelson** [comment]
As-is kills are tracked for players within 300m because unfortunately there weren't/aren't any systems in place keeping track of damageable entities' health history. It might be added in the future, but my thought process was that chances are any players nearby with the same quest are working together, or don't have the quest.

**Comment by baranmod** [comment]
ahh, made a quest on a pvp server in a pvp zone :D
